3단계 구간 추가 기능 리뷰 요청
next-step/atdd-subway-admin pull request #1001
Opened 2022-11-25 12:43 UTC by cylee9409

안녕하세요.
3단계 구간 추가 기능 리뷰 요청드립니다!

저번 리뷰 요청 이후로 오랜 시간이 흘렀네요.
JPA가 처음이라 설계를 하고 관계를 매핑하고 하는데 시간이 꽤 걸렸습니다. 😅😥😥

오랜 시간을 투자해서 코드를 작성했는데 부족한 점이 많아 보여서 아쉽네요.

편하게 혹은 과감하게 피드백 주시면 더 학습하고 보완해서 언제든 수정해서 다시 요청드리겠습니다.

그럼 이번 과제도 잘 부탁드려요! 👍👍
감사합니다~ 🙏🙏

2022-11-26 13:40 UTC, geunhwanlee requested changes
3단계 미션 잘 해주셨어요! 👍🏻

몇가지 고민할만한 포인트가 있어 변경 요청드려요. 🙇🏻‍♂️

확인해보시고 재 리뷰요청 주세요! 🙏

그럼 화이팅하세요! 🔥

2022-11-26 13:40 UTC, geunhwanlee commented on src/main/java/nextstep/subway/domain/Line.java
> +    public Line(String name, String color, int distance) {
`Line`은 최소 1개이상의 구간을 포함해야하는것으로 알고있어요.
`upStation`, `downStation`을 생성자 파라미터로 추가하여 필수가 되도록 하는건 어떨까요?

2022-11-26 13:40 UTC, geunhwanlee commented on src/main/java/nextstep/subway/application/SectionService.java
> +        Sections sections = line.addSection(sectionRequest.toSection(line, upStation, downStation, sectionRequest.getDistance()));
```suggestion
        Sections sections = line.addSection(sectionRequest.toSection(line, upStation, downStation));
```
`distance`는 `sectionRequest`에 포함된 값이니까 파라미터를 생략할수 있지 않을까요?

2022-11-26 13:40 UTC, geunhwanlee commented on src/main/java/nextstep/subway/application/SectionService.java
> +        line.updateDistance(persistSections.stream().mapToInt(section -> section.getDistance()).sum());
`Line`의 전체 길이를 관리할 필요가 있을까요? 🤔

2022-11-26 13:40 UTC, geunhwanlee commented on src/main/java/nextstep/subway/domain/Section.java
> +    }
사용하지 않는 메서드는 제거해주세요!

2022-11-26 13:40 UTC, geunhwanlee commented on src/main/java/nextstep/subway/domain/Sections.java
> +    List<Section> sections = new ArrayList<>();
`Section`은 `Line`에 종속적인 관계일것 같은데 `cascade` 옵션을 고려해보는것도 괜찮을것 같아요! 😀

2022-11-26 13:40 UTC, geunhwanlee commented on src/main/java/nextstep/subway/domain/Sections.java
> +    }
`null - upStation`, `downStation - null` 두개의 구간을 넣으신 이유가 무엇일까요? 🤔

상행종점역과 하행종점역을 표현하기위해 넣으셨다고 생각이 들어요.
하지만 구간은 구간에 대한 관심만을 갖는것이 좋다고 생각합니다. 🙏
null이 포함된 구간을 만들게되면 구간의 변경이 생기는 모든 로직에서 위 구조를 유지하기위해 복잡한 코드를 작성해야할거에요. 😭

2022-11-26 13:40 UTC, geunhwanlee commented on src/main/java/nextstep/subway/domain/Sections.java
> +        }
구현하신 `exitsUpStation`을 보니까
`newSection`의 `upStation`과 등록된 `sections` 중 `upStation`이 같은게 있는지 확인하는 로직이던데
의도와 다르게 동작할것같아요!

`newSection`의 `upStation`이 등록된 `sections`의 `upStation` 또는 `downStation`에 있는지 확인해야할것 같네요. 🤔

2022-11-26 13:40 UTC, geunhwanlee commented on src/main/java/nextstep/subway/domain/Sections.java
> +    }
null이 포함된 구간을 고려해서 로직이 작성된것같아요.

하지만 코드에 그 사실이 드러나지 않아서 읽기가 어려운 문제가 있네요. 😭
null이 포함된 구간을 제거하고 읽을수 있는 코드로 개선해보는건 어떨까요? 🤔

그리고 getter가 많이 사용되고있는데
getter 대신 객체에 메시지만을 던져서 결과를 받아오는 방식으로 개선해보면 좋을것같아요!

2022-11-26 13:40 UTC, geunhwanlee commented on src/main/java/nextstep/subway/dto/LineResponse.java
> +    private List<SectionResponse> sections = new ArrayList<>();
API 명세가 바뀌었네요.
`List<StationResponse>`를 응답하는게 적절할것 같은데 변경하신 이유가 있을까요? 🤔

2022-11-26 13:40 UTC, geunhwanlee commented on src/test/java/nextstep/subway/section/SectionAcceptanceTest.java
> +        );
구간을 등록한후 구간을 조회해서 정상적으로 저장됐는지 검증해보는것도 좋겠네요! 😀

2022-11-28 07:59 UTC, cylee9409 commented on src/main/java/nextstep/subway/application/SectionService.java
> +        line.updateDistance(persistSections.stream().mapToInt(section -> section.getDistance()).sum());
넵! 피드백 반영해서 Line 의 distance 관련 처리 제거했습니다~! 🙏

2022-11-28 07:59 UTC, cylee9409 commented on src/main/java/nextstep/subway/domain/Section.java
> +    }
넵 제거했습니다!!😃

2022-11-28 08:00 UTC, cylee9409 commented on src/main/java/nextstep/subway/domain/Sections.java
> +    List<Section> sections = new ArrayList<>();
넵! `Sections` 에 `CascaseType.ALL` 로 옵션 추가했습니다 👍👍🙇‍♂️🙇‍♂️

2022-11-28 08:03 UTC, cylee9409 commented on src/main/java/nextstep/subway/domain/Sections.java
> +    }
이번 과제가 사실 이 항목 때문에 엄청 애먹었는데, 말씀하신 내용 생각해보니 `null을` 따로 저장하지 않더라도 충분히 종점역을 표현할 수 있네요. 🤦‍♂️🤦‍♂️
도대체 왜 이렇게 중복적이고 복잡한 로직이 들어가게 될까 코드를 짜고도 확신이 없었는데 덕분에 알게 되었습니다. 😂😂
감사합니다 ㅎㅎ 😁👍

2022-11-28 08:04 UTC, cylee9409 commented on src/main/java/nextstep/subway/domain/Sections.java
> +        }
넵넵! `exitsUpStation`과 `exitsDownStation` 메서드는 제거하고 새롭게 유효성 검증하도록 코드 작성했습니다!

2022-11-28 08:05 UTC, cylee9409 commented on src/test/java/nextstep/subway/section/SectionAcceptanceTest.java
> +        );
넵! 주신 피드백 반영해서 구간을 조회해서 검증하도록 반영했습니다~ 😎😃

2022-11-28 08:07 UTC, cylee9409 commented on src/main/java/nextstep/subway/domain/Sections.java
> +    }
위에 주신 피드백 반영하여 종점역에서 `null` 을 세팅하도록 한 부분을 제거하니 훨씬 가독성 있도록 로직 구현이 가능하여, 수정했습니다! 감사합니다~ 🙏🙏🙇‍♂️🙇‍♂️

2022-11-28 08:10 UTC, cylee9409 commented on src/main/java/nextstep/subway/application/SectionService.java
> +        Sections sections = line.addSection(sectionRequest.toSection(line, upStation, downStation, sectionRequest.getDistance()));
넵! 수정했습니다~🙇‍♂️

2022-11-28 08:37 UTC, cylee9409 commented on src/main/java/nextstep/subway/dto/LineResponse.java
> +    private List<SectionResponse> sections = new ArrayList<>();
`Line` 에는 `Sections` 가 포함되어 있어서 `Station` 에 대한 정보는 해당 항목을 통해 볼 수 있어서 변경해야겠다고 생각했습니다.. 근데 API 명세가 바뀌는군요 ㅠㅠ
수정해서 반영했습니다!

2022-11-28 11:08 UTC, cylee9409 commented on src/main/java/nextstep/subway/domain/Line.java
> +    public Line(String name, String color, int distance) {
맞춰서 수정했습니다!

수정하다가 궁금한 내용이 있었는데, 사실 `Line` 에는 `Sections` 정보가 포함되어 있고 해당 항목엔 이미 `Station` 에 대한 정보가 포함되어 있는데 `Line` 에서 `upStation`, `downStation` 을 별도로 관리해야 하는 이유를 모르겠습니다.
그리고 만약 위의 정보를 관리한다면 구간이 계속 추가되는 과정에서 해당 `upStation`과 `downStation`이 의미하는 항목이 노선의 상행종점역, 하행종점역 이라고 생각하면 될까요? 🤔

만약 그렇다면 구간이 추가되고 상행종점역과 하행종점역이 등록되는 과정에 맞춰서 `Line`의 `upStation`과 `downStation`을 맞춰서 수정해주려고 합니다.

근환님의 의견은 어떠신지 궁금합니다! 🙏

2022-11-28 11:13 UTC, cylee9409 commented
근환님, 안녕하세요.
피드백 주신 부분 내용 최대한 반영해서 커밋하였습니다. 확인 부탁드려요!!

이번 과제가 유난히 시간이 많이 소요되었고, 특히 과제하며 null 처리에 애를 먹었는데
근환님께서 종점역에 굳이 null 을 포함하지 않아도 된다고 얘기해주셔서 유레카를 외쳤습니다. 👍👍

간단한 방법이 있었는데 너무 먼 길을 돌아온 것 같네요.
피드백 주셔서 감사합니다. ㅎㅎ 🙇😂

최대한 피드백을 많이 반영했지만 추가로 더 수정해야 하거나 더 좋은 설계가 있다면 편하게 얘기해주세요.
바로 반영하도록 하겠습니다!

감사합니다 😁😁

2022-11-28 17:35 UTC, geunhwanlee commented on src/main/java/nextstep/subway/domain/Line.java
> +    public Line(String name, String color, int distance) {
현재까지의 요구사항들로 정리해본다면 `Line`을 생성할때 상행선과 하행선을 받고있고
그 이후 구간을 계속 추가하는 방식으로 구성되어있기 때문에 `Line`은 최소 한개의 구간을 가지고있어야 한다고 생각이 들어서 말씀드린거였어요. 😀

> 수정하다가 궁금한 내용이 있었는데, 사실 `Line` 에는 `Sections` 정보가 포함되어 있고 해당 항목엔 이미 `Station` 에 대한 정보가 포함되어 있는데 `Line` 에서 `upStation`, `downStation` 을 별도로 관리해야 하는 이유를 모르겠습니다.
오해가 있었나보네요. 😭
`Line`에서 `upStation`, `downStation`을 관리하는것이 아닌
초기 Line `생성시에` 한개의 구간을 함께 생성하는것을 보장하기 위해 말씀드렸던거에요!
`upStation`, `downStation`, `distance` 세개의 파라미터를 가지고 하나의 `Section`을 생성할수 있죠.

오해를 일으켜서 죄송해요. 😭
이부분은 다시 수정해주셔야할거 같아요..

2022-11-28 17:55 UTC, geunhwanlee requested changes
리뷰사항 잘 반영해주셨어요! 👍🏻

다만 일부 오해가 있어 의도와 다르게 변경된 부분이 있네요. 😭

코멘트 남겼으니 확인해주시고 재 리뷰요청 부탁드립니다. 🙏

그럼 화이팅하세요! 🔥

2022-11-28 17:55 UTC, geunhwanlee commented on src/main/java/nextstep/subway/domain/Sections.java
> +                .isPresent();
```suggestion
        boolean containsUpStation = sections.stream()
                .anyMatch(section -> section.containsStation(newSection.getUpStation()));
```
이렇게 써볼수 있겠네요!

2022-11-28 17:55 UTC, geunhwanlee commented on src/main/java/nextstep/subway/application/LineService.java
> +        System.out.println(NO_SUCH_STATION_EXCEPTION);
노선을 조회할때 초기에 받은 `upStationId`와 `downStationId`만을 가지고 역 목록을 리턴해주고있네요.
노선의 구간이 A-B-C-D-E라면
A, B, C, D, E의 정렬된 순서로 역 목록을 리턴해야하지 않을까 싶어요! 😀

노선에 속한 `Sections` 중 상행종점역을 먼저 찾은후
상행종점역부터 하행선 방향으로 탐색해나가면 정렬된 Station을 만들수 있을거에요.

상행종점역을 찾는건 임의의 `Section`에서 상행선 방향으로 탐색해 나가면 상행종점역을 찾을수 있습니다. 😀

2022-11-28 17:55 UTC, geunhwanlee commented on src/main/java/nextstep/subway/domain/Line.java
> +    public Line(String name, String color, Long upStationId, Long downStationId) {
```suggestion
    public Line(String name, String color, Station upStation, Station downStation, int distance) {
```
이렇게 파라미터를 받은 후
생성자 내부에서 `addSection(new Section(this, upStation, downStation, distance));`를 호출하는 방식으로 해보는건 어떤가요? 😀

`Line`의 `upStationId`, `downStationId`는 용도가 없으니 제거해도 될것같아요.

2022-11-29 17:19 UTC, cylee9409 commented on src/main/java/nextstep/subway/domain/Line.java
> +    public Line(String name, String color, Long upStationId, Long downStationId) {
위에 알려주신 방식 기준으로 수정 완료 했습니다~

2022-11-29 17:19 UTC, cylee9409 commented on src/main/java/nextstep/subway/application/LineService.java
> +        System.out.println(NO_SUCH_STATION_EXCEPTION);
감사합니다!
정렬되도록 소스 반영했습니다.

힌트 주신 덕분에 구현 자체는 수월하게 진행했어요! 🙏😄

2022-11-29 17:20 UTC, cylee9409 commented on src/main/java/nextstep/subway/domain/Sections.java
> +                .isPresent();
코드가 훨씬 간결해졌네요! 👍👍
좋은 메서드 하나 배워 갑니다 ㅎㅎ
반영 완료했습니다~

2022-11-29 17:31 UTC, cylee9409 commented
안녕하세요!

밤 늦게까지 리뷰하시느라 고생이 많으시네요 😥

위에 알려주신 항목 반영해서 수정 완료하였습니다!
확인 부탁 드릴게요 🙇‍♂️🙇‍♂️

이번 과정에서는 `Line` 에서 `Section` 을 바로 생성하고 불필요한 `upStation`, `downStation` 을 제거하면서 `LineRequest` 작성에서 가장 어려움을 겪었습니다.
`LineRequest` 같은 DTO 항목에는 domain 이 직접적으로 들어가지 않는 것이 좋다고 피드백 주셨던 것이 생각이 나서 처음에는 `StationResponse` 로 upStation, downStation 을 갖도록 작성했습니다.
하지만 어디선가는 해당 `StationResponse` 를 `Station으로` 치환을 해주어야 하는데 어느 곳에서 어떤 클래스가 해당 역할을 수행하는 것이 좋은지 방안이 떠오르지 않아서 이번 과제에서는 `StationResponse` 대신 `Station` 타입으로 진행했습니다.
근환님의 생각은 어떠신지 궁금하네요. 🤔🤔

늦은 시간까지 늘 꼼꼼하게 피드백 주셔서 감사하고, 이번 과제도 잘 부탁드릴게요 😄
감사합니다!

2022-11-30 15:07 UTC, geunhwanlee approved these changes
리뷰 반영 잘 해주셨어요 👍🏻

충분히 잘 해주셔서 머지하도록 하겠습니다.

고생하셨어요.
몇가지 코멘트 남겼으니 다음 단계때 검토 부탁드립니다. 🙏

그럼 다음 단계도 화이팅하세요 🔥

2022-11-30 15:07 UTC, geunhwanlee commented on src/main/java/nextstep/subway/domain/Sections.java
> +                .get();
```suggestion
        //상행종점역 찾기
        Section firstSection = sections.stream()
                .filter(this::isFirstSection)
                .findAny()
                .get();
```
이렇게 하는건 어떨까요? 😀

2022-11-30 15:07 UTC, geunhwanlee commented on src/main/java/nextstep/subway/domain/Sections.java
> +        sections = sortedSections;
```suggestion
        return sortedSections;
```
`sections`를 변경하지 않고 `sortedSections`를 리턴하는건 어떨까요? 😀

2022-11-30 15:07 UTC, geunhwanlee commented on src/main/java/nextstep/subway/dto/LineRequest.java
> +    public LineRequest(String name, String color, Station upStation, Station downStation, int distance) {
> 이번 과정에서는 Line 에서 Section 을 바로 생성하고 불필요한 upStation, downStation 을 제거하면서 LineRequest 작성에서 가장 어려움을 겪었습니다.
> LineRequest 같은 DTO 항목에는 domain 이 직접적으로 들어가지 않는 것이 좋다고 피드백 주셨던 것이 생각이 나서 처음에는 StationResponse 로 upStation, downStation 을 갖도록 작성했습니다.
> 하지만 어디선가는 해당 StationResponse 를 Station으로 치환을 해주어야 하는데 어느 곳에서 어떤 클래스가 해당 역할을 수행하는 것이 좋은지 방안이 떠오르지 않아서 이번 과제에서는 StationResponse 대신 Station 타입으로 진행했습니다.
> 근환님의 생각은 어떠신지 궁금하네요. 🤔🤔

DTO에 도메인이 들어가지 않는것이 좋다는건
DTO에서 도메인 로직을 처리하는것이 좋지 않다는 의미였지 않나 싶어요. 😀

`DTO -> 엔티티` or `엔티티 -> DTO`로 매핑하기 위해 도메인 객체를 의존하는건 상관없다고 생각합니다!

2022-11-30 15:07 UTC, geunhwanlee commented on src/main/java/nextstep/subway/application/LineService.java
> +        stations.add(StationResponse.of(line.getSections().getSectionList().get(lastIndex).getDownStation()));
상행종점역과 하행종점역만을 리턴하고있네요. 😭

`Line`을 조회했을때 `Line`이 포함하고있는 `Station`의 리스트를 리턴해야하지 않나 싶어요.

`A-B-C-D`라는 구간을 갖는 노선을 조회했다면
`A, B, C, D`라는 리스트를 리턴해줘야한다고 생각해요. 😀

2022-11-30 15:07 UTC, merged

2022-12-01 12:49 UTC, cylee9409 commented on src/main/java/nextstep/subway/application/LineService.java
> +        stations.add(StationResponse.of(line.getSections().getSectionList().get(lastIndex).getDownStation()));
넵! step4 에서 리스트를 갖도록 수정했습니다!

2022-12-01 12:50 UTC, cylee9409 commented on src/main/java/nextstep/subway/dto/LineRequest.java
> +    public LineRequest(String name, String color, Station upStation, Station downStation, int distance) {
코드를 여러번 고칠만큼 고심했는데 명쾌한 확인 감사합니다! 😁

2022-12-01 12:50 UTC, cylee9409 commented on src/main/java/nextstep/subway/domain/Sections.java
> +                .get();
step4에서 반영했습니다. 🙇🙇

2022-12-01 12:57 UTC, cylee9409 commented on src/main/java/nextstep/subway/domain/Sections.java
> +        sections = sortedSections;
이 부분은 정렬 메서드에서는 `List<Section>`인  `sortedSections` 를 반환하도록 수정하였지만, 제가 `Line에` `sections` 를 리턴하도록 설계했기 때문에 어디에선가는 해당 값을 바꿔야 하므로 마지막 `getSortedSections` 메서드에서는 치환해주었습니다!
혹시 내부적으로 sections 주소값의 치환을 지양하라는 의미이신건지 고민이 되네요. 🤔