Step4 - 구간 제거 기능 리뷰요청 드립니다.
next-step/atdd-subway-admin pull request #1014
Opened 2022-11-27 12:18 UTC by aksgudwns

구간 제거 기능 리뷰 요청드립니다!

지난번 과제에서 요청주신 내용도 반영해보았습니다
의견주신 내용 고민하며 반영해보니, 가독성 좋은 코드에 가까워지는 기분이들어 좋았습니다!

이번 리뷰도 잘 부탁드리겠습니다:)

감사합니다.

2022-11-28 01:52 UTC, seokhongkim requested changes
형준님, 4단계 미션 잘 진행해주셨습니다. 👍 
코드를 보고 궁금한 점과 고민해보시면 좋을 것 같은 내용을 코멘트로 남겼습니다.
코멘트 확인 부탁드립니다. 🙏

2022-11-28 01:52 UTC, seokhongkim commented on src/main/java/nextstep/subway/domain/Distance.java
> +        if (distance <= MINIMUM_DISTANCE) {
생성자에서 검증하는 조건은 보통 객체의 생성 조건으로, 객체는 항상 이 조건을 만족할 것이라고 기대하게 되는데요.
`setEndSectionDistance`로 인해 이 조건이 깨지는 상황(거리가 0)이 발생하는 것 같네요.
이외에 선택 가능한 몇 가지 방법이 더 있을 것 같습니다. 같이 고민해보셔도 좋겠습니다. :) 

1. `Distance`의 제약 조건을 0 이상인 경우 생성 가능(0 미만일 때 예외 발생)한 것으로 변경한다. 이 경우 구간 중간에 역이 추가되어 거리를 차감할 때는 0보다 커야 하니 혼란스러울 수도 있겠네요.
2. 종점인 경우 `Distance`를 null로 관리한다. 이 경우에는 null 처리가 필요하겠네요.
3. 종점을 다른 구간과 동일한 방법으로 관리한다. 즉, A-B-C 구간이 있을 때 전체 구간은 A-B, B-C 로 이루어지도록 만든다.

2022-11-28 01:52 UTC, seokhongkim commented on src/main/java/nextstep/subway/domain/Distance.java
> +    public Distance addDistance(Distance distance) {
`Distance`를 불변 객체로 관리해보는 것은 어떨까요?

2022-11-28 01:52 UTC, seokhongkim commented on src/main/java/nextstep/subway/domain/Distance.java
> +    public Distance compareTo(Distance distance) {
`compareTo`는 `Comparable` interface 를 떠오르게 만드는데, 보통 값을 비교한 후 결과를 반환하는 형태로 구현합니다.
이 메서드는 현재 거리에서 입력받은 거리를 뺀 값을 계산하는 것 같네요!

2022-11-28 01:52 UTC, seokhongkim commented on src/main/java/nextstep/subway/application/LineService.java
> +        line.checkStationExist(stationId);
현재의 구현은 `removeSection`을 호출하기 전에 `checkStationExist`를 호출해야 밸리데이션이 성공적으로 수행되네요.

"Tell, don't ask." 라는 말이 있습니다.
line 에게 역이 존재하는지 묻지 말고, 삭제하라고 요청한 후 역이 존재하지 않으면 예외를 던지는 건 어떨까요?

2022-11-28 01:52 UTC, seokhongkim commented on src/main/java/nextstep/subway/domain/Sections.java
>      public boolean isLast(Station station) {
`isLastByStationId` 메서드가 추가되었으니, 이 메서드는 아래와 같이 리팩터링 해보셔도 좋겠네요.
```java
return isLastByStationId(station.getId());
```

2022-11-28 01:52 UTC, seokhongkim commented on src/main/java/nextstep/subway/domain/Sections.java
> +        if (isFirstByStationId(stationId)) {
`sections`가 항상 정렬된 상태일까요?
그렇지 않다면 0번째 값이 상행 종점이라는 것이 보장되지 않을 것 같습니다.

145-148번 라인과 161-164번 라인도 모두 데이터가 정렬되어 있는 것을 전제로 작성된 로직인 것 같네요!

2022-11-28 01:52 UTC, seokhongkim commented on src/test/java/nextstep/subway/section/SectionsTest.java
> +    void sectionDistanceTest() {
단위 테스트 작성 좋습니다. 👍 

형준님께서는 단위 테스트와 인수 테스트를 어떤 기준으로 나눠서 작성하시는지 궁금하네요 :)

2022-11-28 01:52 UTC, seokhongkim commented on src/main/java/nextstep/subway/application/LineService.java
> +    public void removeSectionByStationId(Long lineId, Long stationId) {
내부 구현상으로는 `section` 을 삭제하지만, 노선에서 역 한개를 제거하는 기능인 것 같기도 하네요.

2022-11-28 10:14 UTC, aksgudwns commented on src/main/java/nextstep/subway/domain/Distance.java
> +    public Distance compareTo(Distance distance) {
넵 단순하게 subtract로 표현하는게 의미전달도 더 명확할 것 같다고 생각이드네요!
수정하겠습니다.

2022-11-28 12:27 UTC, aksgudwns commented on src/main/java/nextstep/subway/domain/Distance.java
> +        if (distance <= MINIMUM_DISTANCE) {
종점의 distance는 null로 하고 0이하일 경우 예외처리하겠습니다..
request section에서 distance를 0으로 줬을 경우 Distance에서 예외처리 진행하고자 했어서 어쩔 수 없네요..
null사용을 최대한 피해야 한다고 알고 있지만, 이미 upStation이나 downStation에서 null을 의미 있는 값(종점)으로 작업했기 때문에 이렇게 선택하였습니다..

2022-11-28 12:30 UTC, aksgudwns commented on src/main/java/nextstep/subway/domain/Distance.java
> +    public Distance addDistance(Distance distance) {
종점구간의 distance는 null로 관리하고자 해서 메서드를 아예 삭제하였습니다.
return null로 작업하는게 더 좋은 코드일까요?

2022-11-29 08:30 UTC, aksgudwns commented on src/main/java/nextstep/subway/domain/Sections.java
> +        if (isFirstByStationId(stationId)) {
다시보니 sections가 항상 정렬된 상태가아니군요..
add하는 로직에 sections가 순서에 맞춰 삽입되도록 수정하였습니다.

그리고 sections가 항상 정렬된다는 보장이 없기에 정렬과 상관없이 정상 삭제가능하도록 수정하였습니다!

2022-11-29 08:31 UTC, aksgudwns commented on src/main/java/nextstep/subway/application/LineService.java
> +    public void removeSectionByStationId(Long lineId, Long stationId) {
말씀주신대로 메서드명이 모호하여서 service와 도메인 레이어별로 역할에 맞추어 이름 수정하였습니다!

2022-11-29 08:54 UTC, aksgudwns commented on src/test/java/nextstep/subway/section/SectionsTest.java
> +    void sectionDistanceTest() {
저는 단위테스트를 도메인의 메서드별 기능테스트라 생각하고,
인수테스트는 요구사항이 충족되는지에 대한 테스트로, client가 보낸 요청을 서버가 받아서 요구사항이 응답대로 오는지에 대한 테스트로 이해했습니다...

제 코드를 보면 단위테스트가 많이 빈약해보입니다..
단위테스트를 먼저 구현하고 코드를 작성하는 습관을 들여야 할 것 같습니다!

혹시 제가 잘못 이해한 부분있다면 커멘트 부탁드리겠습니다 :)

2022-11-29 13:32 UTC, aksgudwns commented on src/main/java/nextstep/subway/domain/Distance.java
> +        if (distance <= MINIMUM_DISTANCE) {
생성자 검증조건과 객체안에 필드의 값이 이에 적절한지 까지 제가 미처 생각하지 못했습니다..!
앞으로 주의하겠습니다.

말씀주신 내용 반영하려고 저도 노력 해보았습니다. 하지만 아래와 같은 어려움이 있었습니다..
1번의 경우에는 request body에 section distance 값이 0으로 들어온 경우, 유효성 체크를 생성자에서 진행하기엔 어려움이 있어보입니다..
2번의 경우에는 @Embedded 필드가 null이여서 오류가 나는데, 검색 하여도 해결이 안되어서 포기하였습니다..

그리하여 private 생성자를 만들어서, TERMINAL_SECTION_DISTANCE를 생성할 때만 필드값을 유효성 체크없이 넣게 만들었습니다.
확인부탁드리며, 적절하지 않은 방법이면 3번 내용으로 작업하겠습니다!

2022-11-29 14:02 UTC, aksgudwns commented on src/main/java/nextstep/subway/application/LineService.java
> +        line.checkStationExist(stationId);
도메인 안에 프로세스로 서비스레이어에선 안보이게 수정해보았습니다!

2022-11-29 14:02 UTC, aksgudwns commented on src/main/java/nextstep/subway/domain/Sections.java
>      public boolean isLast(Station station) {
말씀주신 내용 적용하여 중복코드 제거하였습니다 :)

2022-11-29 14:05 UTC, aksgudwns commented
커멘트 주신부분 다시 적용해보았습니다!
확인 부탁드리며, 부족하거나 보완필요한 부분있다면 말씀주세요..!
감사합니다 :)

2022-11-30 12:32 UTC, seokhongkim commented on src/test/java/nextstep/subway/section/SectionsTest.java
> +    void sectionDistanceTest() {
말씀하신 것처럼 메서드 단위 기능에 대한 테스트와 REST API 요청을 통한 서버의 응답에 대한 테스트로 나눠서 생각해 볼 수도 있겠습니다.
이 부분은 테스트의 구현 방법이나 테스트 범위에 대한 설명인 것 같기도 합니다. :)

언제 단위 테스트를 작성하고, 언제 인수 테스트를 작성하시는지도 궁금하네요.
예를 들어, 서버가 정상적으로 응답을 주는 케이스는 인수 테스트를 작성하고, 세부적인 구현이나 예외 케이스는 단위 테스트로 검증을 하는 방법이 있을 수 있겠네요. 또는, 기능 요구사항(예외 상황을 포함)에 대해서는 인수 테스트를 추가하고, 메서드를 구현하는 과정에서는 단위 테스트를 이용해 검증하는 방법도 있을 것 같습니다.

2022-11-30 12:39 UTC, seokhongkim commented on src/main/java/nextstep/subway/domain/Distance.java
> +        return this;
불변 객체로 만드시려면 `subtract` 와 `add` 에서 모두 `return new Distance(newDistance);`의 형태로 객체를 새로 만들어서 반환해줘야 할 것 같아요!

2022-11-30 12:39 UTC, seokhongkim commented on src/main/java/nextstep/subway/domain/Distance.java
> +        if (distance <= MINIMUM_DISTANCE) {
request body 에 distance 가 0으로 들어온 경우 비정상 요청인 것 같기도 하네요. :)
여러 방법을 고민해보셨고 시도도 해보신데다, 이 부분을 수정하는 것이 미션의 목표는 아니므로 넘어가도 괜찮을 것 같습니다!

2022-11-30 12:42 UTC, seokhongkim commented on src/main/java/nextstep/subway/domain/Sections.java
> +    public void checkStationExist(Long stationId) {
service 에서 사용하는 코드를 제거했으니, private 으로 접근 제어자를 변경해도 좋겠습니다. :)

2022-11-30 12:42 UTC, seokhongkim commented on src/main/java/nextstep/subway/domain/Sections.java
> +        if (isFirstByStationId(stationId)) {
정렬과 상관 없이 정상적으로 동작하도록 수정해주신 것 좋습니다. 👍 

정렬이 되어야 하는 것이 도메인에서 반드시 필요한 부분은 아니며, 정렬을 위한 로직으로 인해 코드의 복잡도가 올라가고 성능상의 이점도 없으므로 제거해도 좋을 것 같습니다. :)

2022-11-30 12:45 UTC, seokhongkim approved these changes
형준님, 4단계 미션 코멘트 잘 반영해주셨습니다. 👍 
4단계 PR 머지하도록 하겠습니다.

ATDD 학습과 미션을 잘 진행해주셨네요. 인수 테스트와 단위 테스트를 모두 작성해보셨으니, 각 테스트의 장단점과 사용 전략에 대해서도 고민해보셔도 좋겠습니다.

남은 학습 기간에도 지금처럼 열심히 학습하셔서 목표로 하시는 성장과 성취 모두 이루시길 응원하겠습니다. 💪
ATDD 미션 잘 진행해주셨고, 고생 많으셨습니다! 👍

2022-11-30 12:45 UTC, merged