Step4
next-step/atdd-subway-admin pull request #1037
Opened 2022-12-12 06:51 UTC by diqksrk

마지막... 잘 부탁드립니다 !

2022-12-12 10:57 UTC, limwoobin commented
<img width="489" alt="image" src="https://user-images.githubusercontent.com/28802545/207028331-f36d28bd-d5d9-49f3-be5e-0f2fcb3b295c.png">
실패하는 테스트케이스가 하나 존재하는데 확인부탁드립니다!

2022-12-12 10:58 UTC, limwoobin requested changes
안녕하세요 민준님
마지막 단계도 잘진행해주셧네요 ㅎㅎ
마지막인만큼 고민해보면 좋을만한 포인트가 있어 코멘트드렸습니다.
추가로 실패하는 테스트 케이스에 대해서도 확인부탁드릴게요!

2022-12-12 10:58 UTC, limwoobin commented on src/main/java/nextstep/subway/application/LineService.java
> +        // 첫역을 삭제하는 경우
불필요 주석이나 줄개행은 지워주심 좋을것같아요

2022-12-12 10:58 UTC, limwoobin commented on src/main/java/nextstep/subway/domain/line/LineStations.java
> +    }
여기는 제네릭타입을 명시해주면 더 좋을것같습니다 ㅎㅎ

2022-12-12 10:58 UTC, limwoobin commented on src/test/java/nextstep/subway/domain/station/TestStation.java
> +}
테스트를 위한 Station 객체인가요??
테스트는 실제 사용되는 객체로 하는게 가장 신뢰성있지 않을까 싶습니다
제거하는게 좋아보여요 :)

2022-12-12 10:58 UTC, limwoobin commented on src/test/java/nextstep/subway/section/SectionAcceptanceTest.java
> +        ExtractableResponse<Response> response = 지하철역_삭제_요청됨(3);
단순 3으로 사용하니 어떤값인지 인지하기 힘드네요 ㅎㅎ
매직넘버는 지양해주시고 변수로 한번 담아 넘기는건 어떨까요??
ex) `int 지하철_id = 3;`

2022-12-12 10:58 UTC, limwoobin commented on src/test/java/nextstep/subway/section/SectionAcceptanceTest.java
> +    }
삭제검증은 단순 status code만 보기엔 신뢰도가 부족합니다
추가로 다시 노선을 조회해 삭제 후 노선의 지하철역들을 비교해보심이 어떨까요??

2022-12-12 10:58 UTC, limwoobin commented on src/test/java/nextstep/subway/domain/line/LineTest.java
> +class LineTest {
단위 테스트를 잘 작성해주셧네요
구간에 대해 추가되는 퍼블릭메소드에 대해서도 추가되면 좋을것같네요 ㅎㅎ

2022-12-12 15:25 UTC, diqksrk commented on src/main/java/nextstep/subway/application/LineService.java
> +        // 첫역을 삭제하는 경우
리팩토링 하면서 지웠다고 생각했는데!! 지우겠습니다 !

2022-12-13 07:22 UTC, limwoobin approved these changes
안녕하세요 민준님 
마지막까지 피드백반영 정말 잘 해주셨습니다 👍 👍 
크게 드릴 피드백이 없었네요 ㅎㅎ

미션이 얼마 남지 않았지만 끝까지 화이팅입니다!

2022-12-13 07:22 UTC, limwoobin commented on src/test/java/nextstep/subway/section/SectionAcceptanceTest.java
> +    }
노선조회로 검증까지 잘 해주셧네요 ㅎㅎ

2022-12-13 07:22 UTC, merged