🚀 2단계 - 지하철 노선 기능 구현
next-step/atdd-subway-admin pull request #1040
Opened 2022-12-15 17:08 UTC by withbeth

안녕하세요 리뷰어님!

연말이 가까워 지니 업무양이 많아져서 조금 늦었네요!
빠르게 달려보겠습니다 :)

2022-12-16 00:28 UTC, seokhongkim requested changes
종은님, 2단계 미션 잘 구현해주셨습니다. 👍 
코드를 보고 궁금한 점과 고민해보시면 좋을 것 같은 내용을 코멘트로 남겼습니다.
코멘트 확인 부탁드립니다. 🙏

2022-12-16 00:28 UTC, seokhongkim commented on README.md
> +### TODO
기능 요구 사항 꼼꼼하게 작성하셨네요!

2022-12-16 00:28 UTC, seokhongkim commented on src/main/java/nextstep/subway/application/LineMapper.java
> +    LineResponse mapToResponse(Line line) {
이 기능은 `LineResponse`에서 제공해도 좋을 것 같습니다. :)

2022-12-16 00:28 UTC, seokhongkim commented on src/main/java/nextstep/subway/application/LineService.java
> +        Station upStation = stationRepository.findById(lineRequest.getUpStationId())
비슷한 로직이 반복되고, 다른 곳에서도 역 조회 기능을 사용할 수 있으니 `StationService`에서 제공해주는 건 어떨까요?

2022-12-16 00:28 UTC, seokhongkim commented on src/main/java/nextstep/subway/application/LineService.java
> +        final Line line = lineRepository.findById(id)
이 로직도 private method 로 분리하면 다른 메서드에서도 함께 사용할 수 있겠네요!

2022-12-16 00:28 UTC, seokhongkim commented on src/main/java/nextstep/subway/application/LineService.java
> +@Transactional(readOnly = true)
클래스의 `@Transactional` readOnly 설정을 true 로 관리하시는 이유가 있을까요?

2022-12-16 00:28 UTC, seokhongkim commented on src/main/java/nextstep/subway/application/NotFoundException.java
> +public class NotFoundException extends RuntimeException {
적절한 custom exception 사용 좋습니다. 👍

2022-12-16 00:28 UTC, seokhongkim commented on src/main/java/nextstep/subway/application/StationMapper.java
> +    StationResponse mapToResponse(Station station) {
이 기능도 `StationResponse.from(Station station)` 으로 구현해보셔도 좋겠습니다. :)

2022-12-16 00:28 UTC, seokhongkim commented on src/main/java/nextstep/subway/domain/Sections.java
> +    private final static int FIRST = 0;
다음 단계 미션을 진행하며 고민하시겠지만, 구간이 추가되고 삭제되는 과정에서 0번 인덱스에 있는 값이 첫 번째 구간이 아닐 수도 있습니다. :)

2022-12-16 00:28 UTC, seokhongkim commented on src/main/java/nextstep/subway/domain/Sections.java
> +        while (hasDownSection(first)) {
`hasDownSection` 메서드는 `downStation`이 일치하는 구간을 조회하네요.
현 구간의 상행 구간을 찾는 기능은 아닐까요?
`findByDownStation`과 같은 기능으로 조회 후 `optional.isPresent()`를 활용해보시는 것도 좋을 것 같습니다. :)

2022-12-16 00:28 UTC, seokhongkim commented on src/main/java/nextstep/subway/domain/Sections.java
> +    private boolean hasDownSection(Station station) {
up, down 이 구간 안에서는 상행역, 하행역으로 쓰이고, 구간간에는 반대의 의미로 사용되는 것 같아요!

2022-12-16 00:28 UTC, seokhongkim commented on src/test/java/nextstep/subway/AcceptanceTest.java
> +@DirtiesContext(classMode = ClassMode.BEFORE_EACH_TEST_METHOD)
`DirtiesContext`를 활용한 테스트 격리 좋습니다. 👍 
인수 테스트가 많아지면 성능이 저하될 수 있으니, 여유가 되실 때 다른 격리 방법도 학습해보셔도 좋겠습니다. :)

2022-12-16 00:28 UTC, seokhongkim commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +public class LineAcceptanceTest extends AcceptanceTest {
꼼꼼한 인수 테스트 작성 좋습니다. 👍

2022-12-16 03:22 UTC, withbeth commented on src/test/java/nextstep/subway/AcceptanceTest.java
> +@DirtiesContext(classMode = ClassMode.BEFORE_EACH_TEST_METHOD)
다음스텝에서 DB데이터만 클리어하는 방식으로 구현해볼게요!

2022-12-16 03:23 UTC, withbeth commented on src/main/java/nextstep/subway/domain/Sections.java
> +    private boolean hasDownSection(Station station) {
아직 스텝2에 해당 요구사항이 없어 헷갈린것 같습니다!
다음스텝에서 요구사항 나오면 수정하도록하겠습니다:)

2022-12-16 03:24 UTC, withbeth commented on src/main/java/nextstep/subway/domain/Sections.java
> +        while (hasDownSection(first)) {
while문 대신, optional조언 감사합니다!
해당 요구사항 나오는 스텝에서 수정하도록 하겠습니다:)

2022-12-16 03:25 UTC, withbeth commented on src/main/java/nextstep/subway/application/LineService.java
> +@Transactional(readOnly = true)
서비스의 클래스 레벨에서 readOnly 트랜잭션을 선언하고, 
CUD 같이 데이터 변경이 있는 메서드에서만 읽기전용이 아닌 트랜잭션을 재선언 해주는방식을 사용하고 있습니다.

이를 통해서, 데이터 변경이 있는 경우 명시적으로 선언해서 실수를 예방하기 위해서 하고 있습니다.

2022-12-16 03:29 UTC, withbeth commented on src/main/java/nextstep/subway/application/LineMapper.java
> +    LineResponse mapToResponse(Line line) {
개인적으로 dto 는 정말 단순한 행위(get, dto 에서 가진 필드내에서 특정 객체를 반환) 이외에 책임을 주지 않고 있습니다.
따라서, DTO는 도메인 모델을 모르고, 의존하지 않는 방향으로 설계를 하였구요!
이부분은 팀원간의 협의의 문제같습니다 :)

2022-12-16 03:30 UTC, withbeth commented on src/main/java/nextstep/subway/application/StationMapper.java
> +    StationResponse mapToResponse(Station station) {
개인적으로 dto 는 정말 단순한 행위(get, dto 에서 가진 필드내에서 특정 객체를 반환) 이외에 책임을 주지 않고 있습니다.
따라서, DTO는 도메인 모델을 모르고, 의존하지 않는 방향으로 설계를 하였구요!
이부분은 팀원간의 협의의 문제같습니다 :)

2022-12-16 03:33 UTC, withbeth commented on src/main/java/nextstep/subway/application/LineService.java
> +        Station upStation = stationRepository.findById(lineRequest.getUpStationId())
하나의 Service가 하나의 Repository를 갖게하여 도메인을 관리하도록 하는 것도 좋은 것 같습니다 :)
수정하도록 할게요!

2022-12-16 03:34 UTC, withbeth commented on src/main/java/nextstep/subway/application/LineService.java
> +        final Line line = lineRepository.findById(id)
이 부분은 잘 이해가 가지 않았는데 조금더 풀어서 설명 부탁드려도 될까요?
다음스텝에서 수정하도록 하겠습니다

2022-12-16 04:13 UTC, withbeth commented on src/main/java/nextstep/subway/application/LineService.java
> +        Station upStation = stationRepository.findById(lineRequest.getUpStationId())
아.. 다시 생각해보니, 이번 프로젝트의 Service계층은 도메인 모델이 아니라, DTO를 반환합니다. 
따라서, 다른 서비스에서 사용할때 다시 추가적인 DTO->DomainModel 변환이 필요할 것 같습니다.

이를 해결하기 위해선, 

1) 추가적인 DTO->Domain변환을 용납하느냐
2) 서비스계층은 모두 DomainModel반환. 컨트롤러계층에서, DomainModel->DTO변환해서 반환하느냐

일것 같습니다.

2번은 전체적인 어플리케이션을 수정해야 하니, 
1번방향으로 진행하겠습니다.

2022-12-16 04:28 UTC, withbeth commented on src/main/java/nextstep/subway/application/LineService.java
> +        Station upStation = stationRepository.findById(lineRequest.getUpStationId())
수정완료했습니다 :)

2022-12-16 07:20 UTC, withbeth commented on src/main/java/nextstep/subway/application/LineService.java
> +        final Line line = lineRepository.findById(id)
코드 중복이 발생해서 메서드 분리가 필요하다는 말씀으로 이해했습니다!
수정 완료 했습니다.

2022-12-16 12:45 UTC, seokhongkim commented on src/main/java/nextstep/subway/application/LineService.java
> +@Transactional(readOnly = true)
말씀해주신 내용도 이해가 되네요!
저는 클래스의 transactional 설정은 readOnly = false 를 사용하는데요. 이유는 아래와 같습니다.
* 클래스의 설정을 `readOnly = true` 로 하고, 메서드에서 `transactional(readOnly = false)` 오버라이드 하는 경우 메서드에 설정이 잘 되었음을 테스트에서 확인하기 어렵습니다. 즉, 개발자 또는 리뷰어가 놓치는 상황이 발생할 수 있습니다.
    * 코드에서 데이터를 수정하는 작업이 발생하는지에 대한 검증은 단위테스트와 통합테스트를 통해 검증이 상대적으로 용이합니다. 그러나 트랜잭션 설정이 잘 되었는지에 대한 테스트는 상대적으로 어렵고 놓치기 쉽습니다.
* readOnly 설정을 DB replication 과 함께 사용하여 writer/reader 를 구분하는 목적으로 사용할 수 있는데, readOnly = true 가 기본인 경우 쓰기 요청이 읽기 DB로 전달되어 장애 상황이 발생할 수 있습니다. 반면, 읽기 전용으로 설정해야 하는 작업이 쓰기 DB로 전달되는 경우 부하는 늘어날 수 있으나 당장 장애 상황으로 이어지지는 않습니다.

위 내용도 한 번 같이 고민해보시면 도움이 될 것 같습니다. :)

2022-12-16 12:48 UTC, seokhongkim commented on src/main/java/nextstep/subway/application/LineService.java
> +        Station upStation = stationRepository.findById(lineRequest.getUpStationId())
서비스 계층에서 dto 를 반환하도록 구현하신 이유가 있는지도 궁금하네요!
다음 단계 미션을 진행하며 같이 이야기 나눠봐도 좋겠습니다. :)

2022-12-16 12:49 UTC, seokhongkim approved these changes
종은님, 2단계 미션 코멘트 잘 반영해주셨습니다. 👍 
2단계 PR은 머지하겠습니다.
3단계 미션에서 뵙겠습니다. 😀

2022-12-16 12:49 UTC, merged

2022-12-18 10:19 UTC, withbeth commented on src/main/java/nextstep/subway/application/LineService.java
> +@Transactional(readOnly = true)
>  DB replication 과 함께 사용하여 writer/reader 를 구분하는 목적으로 사용할 수 있는데, readOnly = true 가 기본인 경우 쓰기 요청이 읽기 DB로 전달되어 장애 상황이 발생할 수 있습니다

이부분 모르고 있었네요! 수정했습니다 :)