[인수 테스트 주도 개발] 1단계 - 지하철 노선 관리
next-step/atdd-subway-admin pull request #145
Opened 2021-05-27 17:12 UTC by enemfk777

안녕하세요 리뷰어님 :)

1단계 리뷰 요청드립니다!

업무할 때 보다 더 http method와 end-point, status code를 이용해서 restful하게 설계하는 걸 생각해 볼 수 있는 미션이어서 좋았습니다 :)

어떤 리뷰를 주실지 기대 반 걱정 반 입니다 흐흐 😅

그럼 오늘도 리뷰 감사드립니다 !

2021-05-28 10:50 UTC, slamdunk7575 requested changes
안녕하세요:) 태엽님. ATDD 미션 함께하게 된 양경준 입니다.
첫번째 미션 정말 잘 구현해주셨네요 👍 
몇가지 고민해볼 포인트에 피드백 남겨 드렸는데 확인해보시면 좋을것 같아요.
궁금한점이나 어려운점 있으면 코멘트 또는 DM 남겨주세요. 함께 고민해보아요 🔥
앞으로 미션도 화이팅 입니다!

2021-05-28 10:50 UTC, slamdunk7575 commented on docs/README.md
> +- [x] 기능구현 후 인수 테스트 리팩토링
정리 잘해주셨네요 👍 
앞으로 미션들에서 자유롭게 작성해보시면 많은 도움이 되실 거에요!

2021-05-28 10:50 UTC, slamdunk7575 commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +        assertThat(result.header("Location")).isNotBlank();
> 인수 테스트의 각 스텝들을 메서드로 분리하여 재사용하세요.
ex) 인수 테스트 요청 로직 중복 제거 등

테스트에서 중복되는 부분을 분리해서 재사용 해보면 좋을것 같아요.

예를들어 아래처럼 `요청, 응답` 부분을 나눠보시면 좋겠네요!
메소드명은 `한글 or 영어`로 작성하셔도 좋습니다 :)

```java
@DisplayName("지하철 노선을 생성한다.")
@Test
void createLine() {
        // when
        ExtractableResponse<Response> response = 지하철_노선_생성_요청("2호선", "green");

        // then
        지하철_노선_생성됨(response);
}
```

2021-05-28 10:50 UTC, slamdunk7575 commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +        params.put("color", "green");
body로 `Map`을 전달해도 좋지만 `LineRequest`를 사용해서 요청을 보내면 좋겠네요!

2021-05-28 10:50 UTC, slamdunk7575 commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +        assertThat(result.header("Location")).isNotBlank();
생성한 노선에 대한 `값 검증`도 해보시면 좋을 것 같아요 😄

2021-05-28 10:50 UTC, slamdunk7575 commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +        assertThat(actual).isEqualTo(expect);
아래와 같이 검증 할 수도 있습니다.
LineResponse에 `Equals & HashCode`가 정의되어야겠네요 :)

```java
List<LineResponse> lineResponses = result.jsonPath().getList(".", LineResponse.class);
assertThat(lineResponses).contains(createdLine1.as(LineResponse.class), createdLine2.as(LineResponse.class));
```

2021-05-28 10:50 UTC, slamdunk7575 commented on src/main/java/nextstep/subway/line/ui/LineController.java
> +    }
`ControllerAdvice`를 만들어 별도로 예외 처리를 관리해보면 어떨까요? `@RestControllerAdvice`를 활용해보세요. 
Service 단에서 발생하는 예외들도 같이 관리할 수 있을 것 같아요 :)

2021-05-28 10:50 UTC, slamdunk7575 commented on src/main/java/nextstep/subway/line/application/LineService.java
> +    }
분리를 잘해주셨네요 👍

2021-05-28 10:50 UTC, slamdunk7575 commented on src/main/java/nextstep/subway/line/application/LineService.java
> +            .collect(Collectors.toList());
`LineResponse.ofList()` 를 통해 `캡슐화` 해보면 어떨까요?

2021-05-28 10:50 UTC, slamdunk7575 commented on src/main/java/nextstep/subway/line/application/LineService.java
> +    }
`읽기 전용 조회` 로직에는 `@Transactional(readOnly = true)` 옵션을 주는 것이 좋겠네요 😄

2021-05-28 13:50 UTC, enemfk777 commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +        assertThat(result.header("Location")).isNotBlank();
리팩토링 부분을 대충 읽었네요 ㅜㅜ 중복구현을 없애서 다시 PR 드리겠습니다 😊

2021-05-28 13:51 UTC, enemfk777 commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +        params.put("color", "green");
미리 구현되어있던 StationAcceptanceTest와 너무 맞춰 작성했네요 😅 LineRequest로 바꿔보겠습니다 :)

2021-05-28 13:52 UTC, enemfk777 commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +        assertThat(result.header("Location")).isNotBlank();
앗 수정 삭제에는 검증을 추가하고 여기는 빠져있었네요

2021-05-28 13:52 UTC, enemfk777 commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +        assertThat(actual).isEqualTo(expect);
이것도 StationAcceptanceTest와 너무 형태를 맞췄네요 😅 다시 작성해보겠습니다 :)

2021-05-28 14:05 UTC, enemfk777 commented on src/main/java/nextstep/subway/line/ui/LineController.java
> +    }
전역적으로 예외처리를 해보라는 말씀이시죠? 😊 말씀하신대로 고쳐보겠습니다 :)

2021-05-28 14:05 UTC, enemfk777 commented on src/main/java/nextstep/subway/line/application/LineService.java
> +    }
이것도 생각 못하고 놓친부분이네요 감사합니다 😊

2021-05-29 08:54 UTC, slamdunk7575 commented
- 다음 미션 진행하시면서 `StationAcceptanceTest` 리팩토링도 해보시면 좋을것 같아요 :)

2021-05-29 08:56 UTC, slamdunk7575 approved these changes
피드백 반영 잘해주셨네요 👍
소소한 코멘트 남겨드렸는데 확인해보시면 좋을것 같아요.
끝까지 화이팅 입니다!

2021-05-29 08:56 UTC, slamdunk7575 commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +    }
응답 코드까지 분리하셨군요 👍

2021-05-29 08:56 UTC, slamdunk7575 commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +        지하철_노선_목록_포함됨(result, expect1, expect2);
인수 테스트를 통해 명확히 나타내고 있기 때문에 `주석`은 제거하는게 좋을것 같아요 :)

2021-05-29 08:56 UTC, slamdunk7575 commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +        Long savedId = 등록된_노선_ID(createdResponse);
`지하철_노선_등록되어_있음()` 리턴으로 `Location 값`이나 `id` 값을 바로 반환해줘도 좋겠네요.
변경을 위한 피드백은 아니니 반영하시지 않아도 괜찮습니다 😄

2021-05-29 08:56 UTC, slamdunk7575 commented on src/main/java/nextstep/subway/advice/GlobalExceptionHandler.java
> +public class GlobalExceptionHandler {
👍

2021-05-29 08:58 UTC, merged