Step1 - 지하철 노선관리 리뷰요청 드립니다.
next-step/atdd-subway-admin pull request #177
Opened 2021-06-05 05:00 UTC by yzzzzun

안녕하세요 리뷰어님. 😄 
지하철 노선관리 리뷰요청 드립니다.

이번 스텝 진행하며 두가지 문제와 궁금증이 생겼습니다.

1.
문서에 기능분리를 큼직하게 넣어서 진행하다보니 커밋을 나누지못했네요..
테스트를 작성하고 기능구현하고 테스트 확인한 후 리팩토링 까지 한단계로 이루어지다보니 이런상황이 생겼는데요..
혹시 실무에서 커밋하실때 테스트가 fail나는 상태로도 커밋메세지를 남기시나요??

2.
update에 대한 테스트에서 추가요청을한 후 수정요청을 한다음 각각의 응답 body가 다른 값을 가진다는걸 테스트하려고 했는데 디버깅을 해보니 두 객체가 동일하더라구요..
테스트 내에서의 요청이 동일한 컨텍스트로 수행되어, JPA의 영속성 컨텍스트에 의해 동일한 값이 반환되고 있다로 생각하고있는데 제가 생각한게 맞는지 궁금합니다.

즐거운 주말 보내시고, 리뷰 잘 부탁드리겠습니다. 감사합니다 :)

2021-06-05 10:45 UTC, kyucumber requested changes
안녕하세요

몇가지 코멘트 남겨두었으니 확인 부탁드립니다.

2021-06-05 10:45 UTC, kyucumber commented on README.md
>  This project is [MIT](https://github.com/next-step/atdd-subway-admin/blob/master/LICENSE.md) licensed.
```
문서에 기능분리를 큼직하게 넣어서 진행하다보니 커밋을 나누지못했네요..
테스트를 작성하고 기능구현하고 테스트 확인한 후 리팩토링 까지 한단계로 이루어지다보니 이런상황이 생겼는데요..
혹시 실무에서 커밋하실때 테스트가 fail나는 상태로도 커밋메세지를 남기시나요??
```

커밋 히스토리를 통해 롤백을 하는 경우도 있을 수 있으니 가급적이면 빌드든, 테스트든 깨지지 않는 상태로 커밋하려고 노력하고 있습니다. 다만 항상 그렇게 하긴 어려워서 깨지는 상태로 커밋하는 경우도 있습니다.

2021-06-05 10:45 UTC, kyucumber commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +		params2.put("name", "분당선");
테스트라 크게 상관은 없겠지만 `Map<String, String>`을 활용하시기 보다는

`LineRequest`를 활용해주시면 좋을 것 같네요.

2021-06-05 10:45 UTC, kyucumber commented on src/main/java/nextstep/subway/line/ui/LineController.java
> +	}
```
update에 대한 테스트에서 추가요청을한 후 수정요청을 한다음 각각의 응답 body가 다른 값을 가진다는걸 테스트하려고 했는데 디버깅을 해보니 두 객체가 동일하더라구요..
테스트 내에서의 요청이 동일한 컨텍스트로 수행되어, JPA의 영속성 컨텍스트에 의해 동일한 값이 반환되고 있다로 생각하고있는데 제가 생각한게 맞는지 궁금합니다.
```

위와 같은 질문을 남겨주셨습니다.

일단 현재 컨트롤러에서 업데이트 된 이후의 값을 응답에 포함시키지 않고 있습니다.

올려주신 코드에서 컨트롤러에서 업데이트에 성공한 line 값을 응답에 포함해서 테스트에서 확인해보니 저는 정상적으로

신분당선 -> 분당선으로 변경된 이름이 응답에 내려오는 것을 확인했습니다.

```java
@DisplayName("지하철 노선을 수정한다.")
@Test
void updateLine() {
	// given
	// 지하철_노선_등록되어_있음
	Map<String, String> params = new HashMap<>();
	params.put("color", "bg-red-600");
	params.put("name", "신분당선");

	ExtractableResponse<Response> addLineResponse = 지하철노선을_생성_요청(params);
	LineResponse createdLine = addLineResponse.response().getBody().as(LineResponse.class);

	// when
	// 지하철_노선_수정_요청
	Map<String, String> updateParams = new HashMap<>();
	String updateColor = "bg-yellow-600";
	String updateName = "분당선";
	updateParams.put("color", updateColor);
	updateParams.put("name", updateName);
	ExtractableResponse<Response> lineResponse = 지하철노선을_수정요청(createdLine.getId(), updateParams);

	LineResponse updatedLine = lineResponse.jsonPath().getObject(".", LineResponse.class);
	// then
	// 지하철_노선_수정됨
	assertThat(lineResponse.statusCode()).isEqualTo(HttpStatus.OK.value());
	assertThat(updatedLine.getName()).isEqualTo(updateName);
	assertThat(updatedLine.getColor()).isEqualTo(updateColor);
}


HTTP/1.1 200 
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sat, 05 Jun 2021 10:41:39 GMT
Keep-Alive: timeout=60
Connection: keep-alive

{
    "id": 1,
    "name": "분당선",
    "color": "bg-yellow-600",
    "createdDate": "2021-06-05T19:41:39.407",
    "modifiedDate": "2021-06-05T19:41:39.407"
}
```

어떤 부분에서 응답이 제대로 내려오지 않는지 테스트 케이스 및 데이터를 명확하게 남겨주시면 다시 확인해보도록 하겠습니다.

2021-06-05 10:45 UTC, kyucumber commented on src/main/java/nextstep/subway/line/ui/LineController.java
> +	public ResponseEntity deleteLine(@PathVariable("lineID") long lineID) {
중요한 부분은 아니지만

```suggestion
	public ResponseEntity deleteLine(@PathVariable("lineId") long lineId) {
```

일반적으로 카멜 케이스 사용 시 lineID가 아닌 lineId로 많이 사용했던 것 같습니다.

2021-06-05 10:45 UTC, kyucumber commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +	}
중복 부분을 잘 추출해주셨네요.

2021-06-05 15:49 UTC, yzzzzun commented on README.md
>  This project is [MIT](https://github.com/next-step/atdd-subway-admin/blob/master/LICENSE.md) licensed.
감사합니다. 앞으로 신경쓰도록 하겠습니다.

2021-06-05 16:03 UTC, yzzzzun commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +		params2.put("name", "분당선");
lineRequest로 수정했습니다. 훨씬 테스트코드의 가독성이 좋아지네요. 🙏🏻

2021-06-05 16:14 UTC, yzzzzun commented on src/main/java/nextstep/subway/line/ui/LineController.java
> +	}
앗.. 아닙니다. 제가 API명세를 제대로 파악안하고 구현했을때 실패했던 테스트인데 제가 잘못 구현했던것 같습니다.
혼란을드려 죄송합니다 😢

2021-06-05 16:23 UTC, yzzzzun commented on src/main/java/nextstep/subway/line/ui/LineController.java
> +	public ResponseEntity deleteLine(@PathVariable("lineID") long lineID) {
네 알겠습니다. 수정하겠습니다 :)

2021-06-06 02:50 UTC, kyucumber requested changes
피드백 잘 반영해주셨네요.

다음 단계 진행을 위해 머지할게요

2021-06-06 02:51 UTC, kyucumber approved these changes
피드백 잘 반영해주셨네요.

다음 단계 진행을 위해 머지할게요

2021-06-06 02:51 UTC, merged