1단계 - 지하철 노선 관리 리뷰 요청드립니다.
next-step/atdd-subway-admin pull request #187
Opened 2021-06-06 02:54 UTC by KwakTaeMin

안녕하세요 우아한 테크 캠프 프로 2기 곽태민입니다
리뷰 요청드리기 앞서 몇가지 질문이 있어 질문드립니다!
인수테스트 작성 후 리펙토링을 잘한 것인지 또 현재 테스트한 부분에서 빠뜨리거나 중요한 테스트 부분이 있다면 힌트라도 알려주시면 감사하겠습니다. 

잘 부탁드립니다!

2021-06-06 14:05 UTC, slamdunk7575 commented
- `StationAcceptanceTest` 도 리팩토링 해보시면 좋을 것 같아요!

2021-06-06 14:12 UTC, slamdunk7575 requested changes
안녕하세요:) 태민님. ATDD 미션 함께하게 된 양경준 입니다.
첫번째 미션 잘 구현해주셨네요 👍
몇가지 피드백 남겨 드렸는데 고민해보시면 좋을 것 같아요.
궁금한점이나 어려운점 있으면 코멘트 또는 DM 남겨주세요. 함께 고민해보아요 🔥
앞으로 미션도 화이팅 입니다!

2021-06-07 04:53 UTC, KwakTaeMin commented on src/main/java/nextstep/subway/line/application/LineService.java
> +		Line line = lineRepository.getOne(id);
찾을 수도 없을 수도 있는 부분이라 이런식으로 개발하면 더 좋을 것 같아요! 없으면 EntityNotFoundException까지 해 줄 수 있으니 아주 좋은 것 같아요 감사합니다

2021-06-07 04:54 UTC, KwakTaeMin commented on src/main/java/nextstep/subway/line/application/LineService.java
> +			.collect(Collectors.toList());
훨씬 간결해지고 추상화될 수 있으며 재사용성이 많아 캡슐화하면 훨씬 더 좋을 것 같아요 좋은 리뷰 감사합니다.

2021-06-07 04:55 UTC, KwakTaeMin commented on src/main/java/nextstep/subway/line/application/LineService.java
> +	public LineResponse findLineById(Long id) {
'@Transactional(readOnly = true)' 요런 어노테이션은 아직 어색한 부분인데 제가 스스로 좀 더 공부해볼게요! 모르겠으면 DM갑니당~~

2021-06-07 04:56 UTC, KwakTaeMin commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +	}
응답도 리펙토링을 해야하는군요 ! 감사합니다! 훨씬 간결해지고 무엇을 하는지 명확하게 알 수 있어 좋은 것 같아요

2021-06-07 04:58 UTC, KwakTaeMin commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +		assertThat(response.statusCode()).isEqualTo(HttpStatus.INTERNAL_SERVER_ERROR.value());
`@RestControllerAdivce` 를 사용하여 `@ExceptionHanlder`를 모아 관리할 수 있는 장점이 있어 중복 코드를 훨씬 줄일 수 있을 것 같아요 에러 처리하기에도 좋을 것 같구요!  좋은 리뷰 감사합니다~

2021-06-07 04:58 UTC, KwakTaeMin commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +		assertThat(response.header("Location")).isNotBlank();
넵!

2021-06-07 04:59 UTC, KwakTaeMin commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +		//지하철_노선_생성_요청
주석 제거해야겠어요 `//when` 이런것도 제거하나요 ?

2021-06-07 04:59 UTC, KwakTaeMin commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +	}
넵 변경하도록 하겠습니다~

2021-06-07 10:08 UTC, slamdunk7575 approved these changes
피드백 반영 잘해주셨네요 👍 
몇가지 코멘트 남겨드렸는데 다음 미션 진행하면서 같이 고민해보시면 좋겠네요.
끝까지 화이팅 입니다!

2021-06-07 10:08 UTC, slamdunk7575 commented on src/main/java/nextstep/subway/line/application/LineService.java
> +		Line line = lineRepository.findById(id).orElseThrow(EntityNotFoundException::new);
여러 곳에서 사용된다면 `findById()` 조회 부분을 메소드로 분리해보면 좋겠네요.

2021-06-07 10:08 UTC, slamdunk7575 commented on src/main/java/nextstep/subway/line/application/LineService.java
> +	public LineResponse updateLine(Long id, LineRequest request) {
클래스 레벨에 선언되어 있으니 `@Transactional` 제거해도 되겠네요.

2021-06-07 10:08 UTC, slamdunk7575 commented on src/main/java/nextstep/subway/line/application/LineService.java
> +		line.update(line);
업데이트가 제대로 안될 것 같은데요 👀
`request`를 활용해보세요.

2021-06-07 10:09 UTC, merged

2021-06-07 10:23 UTC, slamdunk7575 commented on src/test/java/nextstep/subway/station/StationAcceptanceTest.java
> +	}
`StationAcceptanceTest`도 잊지않고 리팩토링 해보셨네요 👍 💯