Step1. 1단계 - 지하철 노선 관리
next-step/atdd-subway-admin pull request #20
Opened 2020-12-26 03:37 UTC by byungkyu-ju

2020-12-29 01:34 UTC, kang-hyungu requested changes
안녕하세요 병규님, 리뷰어 강현구입니다 👋 
피드백이 늦어서 죄송해요 슬랙에서 메세지를 놓쳤네요
간단한 피드백 몇 가지 남겼으니 적용해보시고 리뷰 재요청주세요!

2020-12-29 01:34 UTC, kang-hyungu commented on src/main/java/nextstep/subway/line/domain/Line.java
> +	public void update(Line line) {
line이 null일 경우를 대비한 유효성 체크가 필요하겠네요
생성자에도 유효성 체크를 추가해보아요

2020-12-29 06:08 UTC, byungkyu-ju commented on src/main/java/nextstep/subway/common/BaseEntity.java
>  	@CreatedDate
https://github.com/next-step/atdd-subway-admin/pull/20#discussion_r549529505
추상클래스로 변경할 생각은 전혀 못했었네요 😢 
개선했습니다!

2020-12-29 06:09 UTC, byungkyu-ju commented on src/main/java/nextstep/subway/line/domain/Line.java
> +	protected Line() {
https://github.com/next-step/atdd-subway-admin/pull/20#discussion_r549529626
개선했습니다!

2020-12-29 06:09 UTC, byungkyu-ju commented on src/main/java/nextstep/subway/station/domain/Station.java
> +	protected Station() {
https://github.com/next-step/atdd-subway-admin/pull/20#discussion_r549529626
개선했습니다!

2020-12-29 06:09 UTC, byungkyu-ju commented on src/main/java/nextstep/subway/line/application/LineService.java
> +	private final LineRepository lineRepository;
https://github.com/next-step/atdd-subway-admin/pull/20#discussion_r549529902
개선했습니다!

2020-12-29 06:09 UTC, byungkyu-ju commented on src/main/java/nextstep/subway/station/application/StationService.java
> +	private final StationRepository stationRepository;
https://github.com/next-step/atdd-subway-admin/pull/20#discussion_r549529902
개선했습니다!

2020-12-29 06:10 UTC, byungkyu-ju commented on src/main/java/nextstep/subway/line/application/LineService.java
> +			.map(LineResponse::of)
https://github.com/next-step/atdd-subway-admin/pull/20#discussion_r549530178
개선했습니다!

2020-12-29 06:10 UTC, byungkyu-ju commented on src/main/java/nextstep/subway/station/application/StationService.java
> +			.map(StationResponse::of)
https://github.com/next-step/atdd-subway-admin/pull/20#discussion_r549530178
개선했습니다!

2020-12-29 06:21 UTC, byungkyu-ju commented on src/main/java/nextstep/subway/common/exception/CommonExceptionHandler.java
> +}
https://github.com/next-step/atdd-subway-admin/pull/20#discussion_r549530268
https://github.com/next-step/atdd-subway-admin/pull/20#discussion_r549530435
개선했습니다!
UI와 별개로 연동하는 경우 API는 정상적으로 호출되면서(ResponseEntity.ok()), 에러메시지를 담고 있어야 한다고 판단했습니다.

2020-12-29 06:22 UTC, byungkyu-ju commented on src/main/java/nextstep/subway/line/domain/Line.java
> +	}
https://github.com/next-step/atdd-subway-admin/pull/20#discussion_r549533928
개선했습니다!

2020-12-29 13:12 UTC, byungkyu-ju commented on src/main/java/nextstep/subway/common/exception/CommonExceptionHandler.java
> +		return ResponseEntity.badRequest().body(new ErrorResponse(exception));
https://github.com/next-step/atdd-subway-admin/pull/20#discussion_r549530435
에러를 반환할 때 해당하는 메시지를 리턴하도록 변경하였습니다.

2021-01-01 00:43 UTC, kang-hyungu approved these changes
병규님 피드백 반영 잘 하셨어요 👍 
pr은 머지 처리하겠습니다
수고하셨습니다!

2021-01-01 00:43 UTC, merged