Step1 - 지하철 노선 관리 리뷰 부탁드립니다.
next-step/atdd-subway-admin pull request #204
Opened 2021-06-07 14:07 UTC by gim224

## 사소한 그 어떤 것도 리뷰해주시면 감사히 반영하겠습니다.

 * rest api를 따르려 노력하였으나 부족한 점이 많을 것 같네요!

2021-06-09 02:52 UTC, kingbbode requested changes
코멘트 작성해두었습니다 :)
확인 부탁드립니다.

2021-06-09 02:52 UTC, kingbbode commented on src/main/java/nextstep/subway/line/application/LineService.java
> +        return Optional.ofNullable(line).orElseThrow(() -> new NullPointerException("존재하지 않는 노선입니다."));
`Optional` 의 비용은 생각보다 큽니다 :)
if문으로도 충분히 작성될 수 있는 코드로 보입니다.

2021-06-09 02:52 UTC, kingbbode commented on src/main/java/nextstep/subway/line/application/LineService.java
> +        Line persistLine = lineRepository.save(request.toLine()) ;
동시성을 고려한다면 `validateDuplicate` 이 통과되어 중복된 네이밍은 충분히 저장될 수 있을 것으로 보이네요 :)
저장소의 유니크 제약조건을 통해 중복을 배제하는 것이 가장 확실한 방법일 것 같네요.

2021-06-09 02:52 UTC, kingbbode commented on src/main/java/nextstep/subway/line/application/LineService.java
> +        return Optional.ofNullable(line).orElseThrow(() -> new NullPointerException("존재하지 않는 노선입니다."));
`NullPointerException` 는 우리가 가장 경계해야할 예외입니다. `NullPointerException` 은 일반적으로 500 에러로 분류됩니다. 요청이 잘못되었다라는 의미를 전달할 수 있는 `Illegal~` 과 같은 표준적인 예외상태를 활용해주세요 :)

2021-06-09 02:52 UTC, kingbbode commented on src/main/java/nextstep/subway/line/application/LineService.java
> +    private Line findByName(String name) {
예외를 다루지 않고 다른 방식으로 처리해야하는 비지니스가 생겼을 때, 그런 코드들은 어떻게 작성이 되어야 할까요?

코드 자체가 의미있고 명시적인 비지니스를 다루기 때문에, 이러한 코드는 중복이라고 보기 힘듭니다 :)

메서드로 추출된 큰 의미가 없어보입니다.

2021-06-09 02:52 UTC, kingbbode commented on src/main/java/nextstep/subway/line/domain/LineRepository.java
> +    Line findByName(String name);
null 처리에 많은 신경을 쓰고 계신 것 같은데요 :)
JPA 는 Repository 의 `Optional` 반환을 지원합니다.

```
Optional<Line> findByName(String name)
```

2021-06-09 02:52 UTC, kingbbode commented on src/main/java/nextstep/subway/line/ui/LineController.java
> +    @GetMapping(value = "/{name}")
rest 에서 path variable 로 사용될 수 있는 것은 식별자입니다.
`name` 은 식별자가 아닙니다 :)

2021-06-09 09:48 UTC, gim224 commented on src/main/java/nextstep/subway/line/application/LineService.java
> +        Line persistLine = lineRepository.save(request.toLine()) ;
오호.. 감사합니다. 동시성은 전혀 생각치도 못했네요.

2021-06-10 09:05 UTC, kingbbode requested changes
코멘트 작성해두었습니다 :)
확인 부탁드려요.

2021-06-10 12:08 UTC, gim224 commented on src/main/java/nextstep/subway/line/application/LineService.java
> +        lineRepository.save(persistLine);
오.. 감사합니다. 데이터만 바뀌었는데 update문이 실행됨을 확인했습니다.

2021-06-10 17:18 UTC, kingbbode approved these changes
잘 반영해주셨습니다 :)
머지하겠습니다.

2021-06-10 17:19 UTC, merged