[Step3] 구간 추가 기능
next-step/atdd-subway-admin pull request #239
Opened 2021-06-10 15:17 UTC by 7271kim

안녕하세요 이슬님 :)
불목 잘 보내셨나요!
Step3 신규 기능 구현 완료하였습니다ㅎ
하고 다시 짜보고 하고 다시짜보고 2~3번은 한 것 같은데..
보시면서 이상한 부분 있다거나 더 효율적으로 할 수 있는 방법이 있다면 말씀해주세요!

2021-06-11 10:50 UTC, parkeeseul requested changes
미션 잘 진행해주셨습니다! 👍 
몇 가지 코멘트 남겨드렸으니 확인 부탁드릴게요! 😄 
즐거운 금요일 이네요! 남은 시간 즐겁게 보내시길 바라요!
미션 화이팅 입니다 🔥

2021-06-11 11:48 UTC, 7271kim commented on src/main/java/nextstep/subway/line/application/LineService.java
> +        Station downStaion = findStation(request.getDownStationId());
엄청나시네요 👍 👍 👍

2021-06-11 18:08 UTC, 7271kim commented
안녕하세요 이슬님! 
요구사항에 대한 단위테스트 코드..를 배우고 안하고 있었네요 ㅠ 무엇인가 찝찝했었는데 그 부분이였습니다 ㅎㅎ 
Model 관련 핵심 비지니스 로직 테스트 케이스 추가했습니다.

기능 관련, npm 이슈가 있어서 화면을 안보고 작업하고 있다가. 이슬님이 기능상 문제가 있다고 말씀해주셔서 npm 이슈 수정 후 Front를 보면서 확인하니, 구간 등록 후 line 정보 호출 시 Station 정보가 제대로 나오지 않고 있던 버그가 있었습니다..

"노선 추가 시에 삼성 - 교대 를 구간으로 등록한 후 구간 관리에서 교대 - 선릉 을 등록할 경우 400 에러" <- 해당 에러는 아마 station 정보가 보이지 않는 와중 에러 케이스로 등록하여 그런것 같습니다. (재현이 안되어요ㅠ)

또한 "삼성 - 역삼을 구간으로 등록했을 경우는 구간이 추가되지 않고 역삼 - 교대 로 구간이 변경"은 의도한 로직입니다.  만약 A -B (20) 길이에 A - C (5) 구간을 추가한다면 A-C(5)가 신규 구간에 추가되고 기존 구간 A-B(20)은 A가 C역으로 변경되고 구간을 15로 수정하도록 로직을 짰습니다.

이슬님! JPA 버그 찾느라 거진 6시간을 투자한 것 같은데.. 문제 상황만 해결 하였지만 정확한 이유는 아직 이해가 되지 않아, 공부를 더 하겠지만.. 혹시 이슬님의 지식을 나누어 주신다면 감사하겠습니다ㅠ 

문제상황 : fetch = FetchType.LAZY로 인해 line 조회 시 sections 정보를 다 가지고 오지 못함.

지금 시간에는 꿈나라에 있으시겠죠..? ㅎㅎ
그럼 좋은 밤 되세요!

2021-06-11 18:08 UTC, 7271kim commented on README.md
> +# [Step 3] 구간 추가 기능
문의사항 남겼습니다 :)) 확인 부탁드립니다.

2021-06-12 01:12 UTC, 7271kim commented on src/main/java/nextstep/subway/section/domain/Section.java
> +    @ManyToOne
해당 부분이 궁금합니다 :)

2021-06-12 08:40 UTC, parkeeseul approved these changes
피드백 잘 반영해주셨네요! 👍 
질문 주신 사항에 대한 저의 의견 남겨두었으니 확인 부탁드립니다! 😄 
이만 머지 하겠습니다! 다음 단계 진행해주세요! 🔥

2021-06-12 08:40 UTC, parkeeseul commented on src/main/java/nextstep/subway/section/domain/Section.java
> +    @ManyToOne
> Q. 이슬님! JPA 버그 찾느라 거진 6시간을 투자한 것 같은데.. 문제 상황만 해결 하였지만 정확한 이유는 아직 이해가 되지 않아, 공부를 더 하겠지만.. 혹시 이슬님의 지식을 나누어 주신다면 감사하겠습니다ㅠ
> 문제상황 : fetch = FetchType.LAZY로 인해 line 조회 시 sections 정보를 다 가지고 오지 못함.

A. 지연로딩은 엔티티가 실제 사용될 때까지 데이터베이스 조회를 지연하는 방법을 제공합니다.
때문에 값에 직접 접근을 해야 해당 엔티티를 조회하게 되는데요. 다음과 같은 테스트 코드로 확인 해볼수 있습니다
``` java
    @Test
    void lazyLoadingTest() {
        // given
        List<Station> stations = new ArrayList<>();
        stations.add(new Station("1"));
        stations.add(new Station("2"));

        List<Station> newStations = stationRepository.saveAll(stations);

        List<Section> section = Arrays.asList(Section.of(newStations.get(0), newStations.get(1), 10));
        Line newLine = new Line("2호선", "yellow", section);

        lineRepository.save(newLine);

        em.flush();
        em.clear();

        //when
        Line line = lineRepository.findById(1l).get();

        System.out.println("------------ Station 조회 쿼리 X ------------");
        Station station = line.getSections().getSections().get(0).getUpStation();
        System.out.println("-----------------------------------------");

        System.out.println("------------ Station 조회 쿼리 O ------------");
        System.out.println(station.getName());
        System.out.println("-----------------------------------------");

    }
```

위에 말씀드린 이유로 Station 의 equals 메소드에서 문제가 발생한 것이라 예상되는데요
프록시 객체가 euqals 메서드의 매개변수로 주입되면서 other.id 의 값이 null 이 되어 의도하신 대로 equals 가 동작하지 않았습니다.
이 부분 한번 확인해보시고 지연로딩에 대해서도 한번 공부해보시면 좋을 것 같아요! 😄

2021-06-12 08:40 UTC, merged

2021-06-12 11:38 UTC, 7271kim commented on src/main/java/nextstep/subway/section/domain/Section.java
> +    @ManyToOne
line.getSections().getSections().get(0).getUpStation(); 부터가 사용한다라고 생각했는데.. 직접 객체에서 값을 꺼낼 때부터 사용한다는 개념이군요 ㅎㅎ 넵 감사합니다!