[atdd-subway-admin: Step2] 리뷰 요청드립니다.
next-step/atdd-subway-admin pull request #259
Opened 2021-06-12 15:42 UTC by chajs226

리팩토링을 하면서 중간 중간 커밋 지점을 잡지 못해, 마지막에 한번에 커밋 해버렸습니다. ㅠㅠ
개선이 필요한 부분에 대해 많은 리뷰 부탁드립니다.

2021-06-13 10:24 UTC, kingbbode requested changes
코멘트 작성해두었습니다.
확인 부탁드립니다 :)

2021-06-13 10:24 UTC, kingbbode commented on src/main/java/nextstep/subway/line/application/LineService.java
> +        Section section = sectionRepository.save(new Section(upStation,downStation, request.getDistance()));
`Optional` 을 매개변수로 사용하는 것은 안티패턴입니다 :)
명확한 데이터 값을 제공해주도록 변경 부탁드립니다.

http://homoefficio.github.io/2019/10/03/Java-Optional-%EB%B0%94%EB%A5%B4%EA%B2%8C-%EC%93%B0%EA%B8%B0/

2021-06-13 10:24 UTC, kingbbode commented on src/main/java/nextstep/subway/line/application/LineService.java
>          lineRepository.deleteById(id);
라인이 제거될 때 모두 삭제되어야하는게 맞을까요?

2021-06-13 10:24 UTC, kingbbode commented on src/main/java/nextstep/subway/line/dto/LineResponse.java
> +        HashMap<String, Station> stations = new HashMap<>();
불필요한 코드로 보이네요.

2021-06-13 10:24 UTC, kingbbode commented on src/main/java/nextstep/subway/line/dto/LineResponse.java
> +        return stationResponses;
`stream`,`flatMap` 을 사용한다면 
`List<StationResponse> stationResponses = new ArrayList<>();` 와 같은 선언방식의 코드를 제거할 수 있겠네요.

2021-06-13 10:24 UTC, kingbbode commented on src/main/java/nextstep/subway/section/domain/Section.java
> +        return stations;
명확한 데이터 구조에 대해 Map 으로 사용하는 것은 불안정성이 매우 큰 좋지않은 코드이면서 객체지향에 반하는 기법입니다.
명확한 자료 형태로 변경 부탁드립니다.

2021-06-13 10:24 UTC, kingbbode commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +        ExtractableResponse<Response> responseStation2 = requestCreateStation(stationRequest2);
테스트의 조건으로는 적당하지만 방법은 변경이 필요해보입니다.
테스트는 상호 독립적으로 작성해야합니다. 그러나 테스트의 조건을 생성할 때 같은 레이어(혹은 모듈)상의 요청을 통해 데이터를 생성하고 있는데요. 이렇게 되었을 때 역을 생성하는 요청 코드에 이상이 생겼을 때 노선 관련 기능에서 조건을 생성하다가 코드가 실패하며, 무엇이 실패했는지 전달받기가 어려워집니다 :)

현재의 레이어보다 더 하위의 레이어의 인터페이스를 통해 조건을 만들어야합니다.
AcceptanceTest 의 tearDown 에는 DataBaseCleanUp이라는 코드가 있는 것을 보니, 이 테스트의 하위 레이어는 바로 인프라스트럭처로 이어지는 것으로 보이네요 :)
~Repository 를 사용하거나 다른 방법을 통해 조건 데이터에 대한 설정을 할 수 있을 것으로 보입니다.

2021-06-14 08:50 UTC, chajs226 commented on src/main/java/nextstep/subway/line/application/LineService.java
> +        Section section = sectionRepository.save(new Section(upStation,downStation, request.getDistance()));
JpaRepository 에서 findById 의 return 값이 Optional로 선언되어 있는데, findById를 실제 사용할 때는 Optional으로 받지 말라는 말씀이신가요?
orElseThrow를 활용해서 데이터가 없을 때, exception을 발생하도록 수정했습니다. 의도하신 부분이 맞는건지요?

2021-06-14 08:57 UTC, chajs226 commented on src/main/java/nextstep/subway/line/application/LineService.java
>          lineRepository.deleteById(id);
역은 라인에 종속적이지 않은데 잘못 삭제한 것 같습니다. section까지 삭제하는 것으로 변경했습니다.

2021-06-14 14:26 UTC, chajs226 commented on src/main/java/nextstep/subway/section/domain/Section.java
> +        return stations;
map 구조를 제거했습니다.

2021-06-14 20:14 UTC, chajs226 commented on src/main/java/nextstep/subway/line/dto/LineResponse.java
> +        HashMap<String, Station> stations = new HashMap<>();
getStations 메소드를 삭제했습니다.

2021-06-14 21:12 UTC, chajs226 commented on src/main/java/nextstep/subway/line/dto/LineResponse.java
> +        return stationResponses;
flatmap을 사용하는 방식으로 변경했습니다. 그러다보니 Station클래스의 getUpStation, getDownStation 메소드도 필요없어져서 삭제했고, List<station>을 반환하는 메소드를 추가했습니다. 코드가 한결 간결해졌네요~ :)

2021-06-14 21:43 UTC, chajs226 commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +        ExtractableResponse<Response> responseStation2 = requestCreateStation(stationRequest2);
말씀하신대로 역생성을 Repository를 활용해서 직접 생성하도록 별도의 메소드로 분리했습니다. 테스트 코드가 훨씬 간결해졌네요 :)

2021-06-15 15:41 UTC, kingbbode approved these changes
잘 반영해주셨네요 :)
머지하겠습니다.

2021-06-15 15:41 UTC, kingbbode commented on src/main/java/nextstep/subway/line/application/LineService.java
> +        Section section = sectionRepository.save(new Section(upStation,downStation, request.getDistance()));
매개변수는 메서드인자를 말합니다.

첨부한 내용 중 `Optional을 생성자나 메서드 인자로 사용 금지` 에 대한 내용입니다 :)

2021-06-15 15:41 UTC, merged