[3단계 - 구간 추가 기능] 리뷰 요청 드립니다.
next-step/atdd-subway-admin pull request #263
Opened 2021-06-13 09:55 UTC by ttuop

안녕하세요!

이번 주는 회사 일 때문에 시간이 부족해서 리뷰 요청이 늦어졌네요.

1, 2 단계에 비해서 고민할거리가 많아서 시간이 오래 걸렸습니다.

Line -> LineStations -> LineStation -> Station

이런식으로 fetch join 을 사용해보려고 했는데 잘 안 되네요.

원래 안 되는 건지 아직 공부를 더 해봐야할 것 같네요.

2021-06-13 13:27 UTC, young891221 requested changes
안녕하세요, 봉진님!
미션 구현을 열심히 해주신게 느껴집니다 💯 
몇 가지 크고 작은 코멘트 드렸습니다. 확인 부탁드립니다:)

2021-06-13 13:27 UTC, young891221 commented on src/main/java/nextstep/subway/linestation/domain/LineStation.java
> +            .filter(s -> !s.equals(this.station))
별건 아닌데 성능에 아주 미세하게 영향이 있다고 생각해서요. &&조건으로 처리하는게 어떨까요?ㅎ

2021-06-13 13:27 UTC, young891221 commented on src/main/java/nextstep/subway/linestation/domain/LineStations.java
> +        final Predicate<LineStation> condition3 = ls -> ls.isSameStation(lineStation.getNextStation());
이렇게 3개를 조건으로 넣을 필요가 있을까요? 맨위의 조건 하나면 처리되는 부분같아서요.

2021-06-13 13:27 UTC, young891221 commented on src/main/java/nextstep/subway/linestation/domain/LineStations.java
> +    public List<Station> orderedStations() {
좀 비효율적인 정렬인것 같습니다. 계속 N! 루프를 돌면서 처리가 되는 형식인데 lineStations의 자료구조를 LinkedList로 가져가서 삽입,삭제를 좀 더 용이하게 처리해 보면 어떨까요?

2021-06-13 13:56 UTC, ttuop commented on src/main/java/nextstep/subway/linestation/domain/LineStations.java
> +        final Predicate<LineStation> condition3 = ls -> ls.isSameStation(lineStation.getNextStation());
LineStation#getPreviousStation, LineStation#getNextStation 호출하면 LineStation 이 아닌 Station 이 리턴되서

새로 추가된 Station 정보를 업데이트 하려면 LineStation 이 있어야 해서 이런 방식으로 하게 됐습니다.

고민 좀 해보겠습니다.

2021-06-13 13:56 UTC, ttuop commented on src/main/java/nextstep/subway/linestation/domain/LineStations.java
> +    public List<Station> orderedStations() {
효율적인 방법을 고민해보겠습니다! 👍

2021-06-13 15:27 UTC, ttuop commented
LineStation Entity 를 개발하면서 제가 착각한 게 있었네요.

LineStation 이전과 다음 역을 모두 LineStation Entity 를 참조하도록 했어야 했는데 Station 을 참조하는 바람에 로직이 복잡해지고
정렬 알고리즘도 효율적이지 않았습니다.

개선했으니 한 번 봐주세요~ 🐱‍🏍🐱‍🏍

2021-06-14 00:31 UTC, young891221 approved these changes
정렬은 조금 아쉽지만, 다른 부분은 잘 처리해 주셨네요 👍 
추가드릴 코멘트가 없습니다. 머지할게요!

2021-06-14 00:31 UTC, merged