[인수테스트주도개발] 2단계 - 인수 테스트 리팩터링
next-step/atdd-subway-admin pull request #264
Opened 2021-06-13 11:43 UTC by jaewanLee

안녕하세요~ 
피드백 반영하고 2단계 진행했습니다.
리뷰요청드립니다.

2021-06-13 19:13 UTC, tearight requested changes
안녕하세요.
코멘트 남겨드렸으니 확인 부탁드립니다.

2021-06-13 19:13 UTC, tearight commented on src/main/java/nextstep/subway/line/application/LineService.java
> +        List<Long> stationIds = line.getSections().stream().map(section -> Arrays.asList(section.getUpStationId(), section.getDownStationId())).flatMap(Collection::stream).collect(Collectors.toList()
한 줄에 너무 많은 내용이 있어서 가독성을 헤치네요. 수정이 필요해보입니다.

2021-06-13 19:13 UTC, tearight commented on src/main/java/nextstep/subway/line/application/LineService.java
> +                .collect(Collectors.toList());
Line 이 함수를 제공해준다면 가독성이 개선 될 것 같네요.

2021-06-13 19:13 UTC, tearight commented on src/main/java/nextstep/subway/line/application/LineService.java
> +        return lines.stream().map(line -> LineResponse.of(line, getStations(line, stationMap))).collect(Collectors.toList());
가독성은 조금 좋지 않아 개선이 필요해보입니다.
조회를 위해 쿼리를 최소화하는 부분을 신경써주신건 좋네요. 👍

2021-06-13 19:13 UTC, tearight commented on src/main/java/nextstep/subway/line/domain/Section.java
> +    private int distance;
@Column 을 명시적으로 써주시고, column name 도 적어주시는게 좋을 것 같아요.
왜 이렇게 해야할지 생각해보시면 좋을 것 같습니다.

2021-06-13 19:13 UTC, tearight commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +                10);
의미가 불분명한 매직넘버는 상수로 바꿔주시면 좋을 것 같습니다.

2021-06-13 19:13 UTC, tearight commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +        ExtractableResponse<Response> response = 지하철_노선_삭제_요청(pathParams);
지하철_노선_삭제_요청에 id 값을 전달해주고 내부에서 Map 을 만들어주면 더 깔끔해질 것 같습니다.

2021-06-13 19:13 UTC, tearight commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +    }
Map 을 파라미터로 넘겨주는 것은 가장 좋지 않은 방법인 것 같습니다.
함수 내부를 보지 않는 한 어떤 값을 key 와 value로 줘야할지 알 수 없기 때문입니다.
따라서 API 요청에 Map이 필요하더라도 파라미터로 값을 명시적으로 받아서 내부에서 Map 으로 만들어주는 것이 좋을 것 같습니다.

2021-06-13 19:13 UTC, tearight commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +                10);
한 줄로 적어주셔도 좋을 것 같습니다. 파라미터가 복잡하지 않아서 여러줄로 나뉘는건 오히려 가독성을 헤치는 것 같습니다.

2021-06-13 19:13 UTC, tearight commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +        assertThat(response.body().jsonPath().getList("stations", Station.class).stream().map(Station::getId).collect(Collectors.toList())).containsExactly(1L, 2L);
이와 같은 검증을 함수로 축약하면 더 읽기 좋을 것 같습니다.

2021-06-13 19:28 UTC, tearight commented
안녕하세요, 전체적으로 코드 구현에 능숙하신 것 같습니다.👍
그러나 코드 가독성 부분이 아쉽습니다. 
가독성을 개선할 수 있는 중점적인 포인트를 말씀드리겠습니다.

1. Stream 에 대한 사용을 우회해보자.
1.1 Stream 을 사용하는 것이 나쁜 것은 아니지만 객체지향적으로 설계할 수 있는 것들이 Stream 을 사용함으로써 잊혀지고 있는 것 같습니다.
예를 들면 Stream 을 사용하게 되면 객체에게 부탁하는 것이 아닌 객체의 값을 꺼내서 바깥에서 연산하게 됩니다.
LineService 에서 station Id 를 꺼내오는 부분이 대표적으로 해당됩니다. 객체에게 부탁하게 되면 Line 에 getStationsId() 라는 메소드가 생길 수 있을 것으로 보입니다.
1.2 그리고 flatMap 등 Stream 에서 지원하는 API 에 맞춰주기 위해 리턴타입이 Stream 으로 된다던가 콜렉션 형태로 강제된다던가 하는 제약이 존재하게 됩니다. 특정한 로직에서 사용하기에는 편할 수 있으나, 시야를 객체 자체로만 좁혀보면 이해할 수 없는 이해하기 어려운 코드가 될 수도 있습니다.
1.3 Stream 의 chaining 의 의도를 이해하기 어려워질 수 있습니다. 이 부분은 함수로 묶어서 개선될 수도 있을걸로 보입니다.

2. 인수테스트는 개발자 중심이 아니라 협업하는 동료 중심
인수테스트 작성은 개발자가 하지만 동료가 읽을거라는 생각으로 작성하시는게 좋을 것 같습니다. 따라서 그 어떤 코드보다 가독성이 1순위가 되어야 합니다.

3. 매직넘버 사용은 무조건 상수화
숫자 1L, 2L 은 이해하기 어렵습니다. 강남역_ID 등으로 상수화 된다면 이해하기 좀 더 쉬워질 것 같습니다.

2021-06-15 11:19 UTC, jaewanLee commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +    }
좋은 피드백 감사합니다

2021-06-15 11:31 UTC, jaewanLee commented on src/main/java/nextstep/subway/line/domain/Section.java
> +    private Long downStationId;
안녕하세요 
피드백 반영해 연관관계로 변경 해두었는데 연관관계 설정에 대해 궁금한점이 있어 문의드립니다.

Section이 Station을 연관관계로 가짐으로써 Line이 Station을 연쇄적으로 엔티티 내부에서 사용할 수 있게 되었는데요.
혹시 이런 연관관계로 인한 복잡성이나, 추후에 Station이 Line과의 연관관계가 필요해지거나 할때 상호참조의 문제는 없을까요??
또 Id만을 갖고 있어 in절 조회를 해 매핑 할 수 있었는데요! 연관관계로 변경하고 나니 한번씩 코드는 간단해지지만 쿼리가 여러번 발생할 것 같더라구요. 
연관관계로 설정하는 장점과 그에 따라 발생할 수 있는 문제점이 있는지 이는 어떻게 해결하는지 등이  궁금합니다.

2021-06-18 17:14 UTC, tearight commented on src/main/java/nextstep/subway/line/domain/Section.java
> +    private Long downStationId;
1. 연관관계로 인한 복잡성
연관관계로 인한 복잡성은 1:M 관계에서도 많이 느끼셨을 것 같아요
`Line.addStation(), Station.setLine()` 등이 이러한 예이지요.
이런 부분은 최대한 단방향 관계로 연관관계를 맺으면 복잡도가 많이 줄어듭니다.

다만 연관관계를 맺어야 하냐는 실무와 조금 동떨어진다는 느낌도 많이 받으실 거에요.
제가 하는 실무에서는 모든 객체가 연관관계를 맺는것은 아니지만 DDD 의 Aggregate 를 구성할때는 연관관계를 맺습니다.
JPA 에서 연관관계를 맺어서 객체지향적으로 사용하는 연습을 하시면 이 경험이 추후 DDD 를 적용하시는데에도 큰 도움이 될 거에요.

2. 상호 참조의 문제는 없을지 ?
클래스간 상호 참조는 없는 것이 가장 베스트이지만 요즘에는 어느정도 허용되는 패턴인 것 같아요.
특히 JPA 는 연관관계에 엔티티를 직접적으로 넣어줘야 하기 때문에 상호참조를 제거하기가 어려워서 신경쓰지 않는 요소중 하나입니다.

3. 쿼리 최적화
JPA 가 아무래도 쿼리 최적화를 놓칠 수 있는 부분이 많아서 각별히 주의를 해야 하기는 합니다.
그러나 이 부분도 다양한 방법으로 해결 할 수 있습니다.
- 단순 테이블 연결 : jpql 을 통한 Fetch join
- 조건이 복잡한 테이블 연결 : querydsl 을 통한 쿼리 후 쿼리 결과를 엔티티에 매핑
연관관계가 복잡한 엔티티의 경우에는 엔티티를 위한 CustomRepository 를 만들고 querydsl 을 사용하여 매핑하는 구현을 가장 많이 합니다.

JPA 에 익숙한 사용자는 쿼리 제어가 능숙하기 때문에 연관관계를 통한 이득을 제일 많이 볼 거라고 생각합니다.

2021-06-18 17:22 UTC, tearight approved these changes
안녕하세요. 
다음 단계 진행하기 위해 Section<->Station 간 연관관계에 대한 수정이 필요해보여요.
다음 단계 진행하기 전에 연관관계를 수정해주시고 진행해주시면 좋을 것 같습니다.
이번 단계는 머지를 진행하겠습니다.

2021-06-18 17:22 UTC, tearight commented on src/main/java/nextstep/subway/line/domain/Line.java
> +        }
포맷팅 확인을 부탁드릴게요.

2021-06-18 17:22 UTC, tearight commented on src/main/java/nextstep/subway/line/dto/LineResponse.java
> +        }
포맷팅 확인을 부탁드릴게요.

2021-06-18 17:22 UTC, tearight commented on src/main/java/nextstep/subway/section/domain/Section.java
> +    private Station downStation;
onetoone 일경우 station 은 여러 섹션에 속하지 못합니다.
예를 들면 역이 3개인 노선이 있다고 해볼게요.
```
  [섹션1]  [섹션2]
삼성역 - 선릉역 - 강남역
```
이런식으로 섹션이 두개가 될 텐데요. 선릉역 같은 경우는 섹션1, 섹션2 둘 다에 포함이 되어야겠지요.
따라서 @manytoone 으로 연관관계를 바꿔주셔야 될 것 같습니다.

2021-06-18 17:22 UTC, merged