🚀 3단계 - 구간 추가 기능
next-step/atdd-subway-admin pull request #278
Opened 2021-06-14 13:02 UTC by mskangg

안녕하세요! 이슬님! 😃
PR이 늦었습니다..ㅠㅠ
이번 과정하면서 삽질을 겁나했네요.. 난이도가 확 올라간 느낌이 들었습니다.
과정 진행하면서 Station(Entity) 비교하면서 엄청 삽질했네요 ㅎㅎ
Intellij가 만들어주는 equals() 메서드를 그대로 사용하다보니 문제가 생겼었습니다..
덕분에 JPA와 프록시에 대해서 딥다이브했네요 😃

그럼 이번 코드리뷰도 잘 부탁드립니다! 😁
감사합니다.

2021-06-14 23:08 UTC, parkeeseul requested changes
미션 잘 진행해주셨네요! 👍 
몇 가지 코멘트 남겨드렸으니 확인 부탁드립니다! 😄 
미션 화이팅 이예요! 🔥

2021-06-15 01:23 UTC, mskangg commented on src/main/java/nextstep/subway/line/domain/Distance.java
> +    }
구간을 등록할 때 `역 사이에 새로운 역을 등록할 경우 기존 역 사이 길이보다 크거나 같으면 등록을 할 수 없습니다.` 의 예외 상황은 `Section`이 처리해야할 책임이라고 생각하여 `Section`에서 `Distance`에게 메세지를 보내어 구현하였습니다.
그런데 `Distance`에서 `거리는 0보다 커야한다`라는 예외상황도 처리하고 있으니 구간이 가진 책임을 옮겨도 괜찮겠네요!

2021-06-15 04:08 UTC, mskangg commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +    }
변경완료하였습니다. 👍

2021-06-15 04:09 UTC, mskangg commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +                .filter(section -> section.getUpStation().equals(station))
[getter 메소드를 사용하지 않도록 리팩토링한다.](https://www.slipp.net/questions/565)
이 글을 참고하여 리팩토링하였습니다!
`객체지향 생활체조 원칙의 "규칙 9: 게터/세터/프로퍼티를 쓰지 않는다."` 를 지키기 위해서 평소에도 신경을 써야겠네요!
메세지... 기억하겠습니다.
감사합니다 리뷰어님 💯

2021-06-15 04:32 UTC, mskangg commented on src/test/java/nextstep/subway/line/SectionAcceptanceTest.java
> +@DisplayName("지하철 구간 관련 기능")
앗..! 도메인, 서비스 테스트에선 진행했는데 제가 인수조건 테스트에는 추가하지 않았네요..!
추가완료했습니다. 😅

2021-06-16 00:32 UTC, parkeeseul approved these changes
피드백 잘 반영해주셨네요! 👍 
다음단계 진행해주세요! 😄 
인수테스트 미션 마지막 단계네요! 화이팅 입니다! 🔥

2021-06-16 00:32 UTC, merged