[ATDD - 4단계] 리뷰 요청드립니다.
next-step/atdd-subway-admin pull request #286
Opened 2021-06-15 15:26 UTC by Donghui-Lee

2021-06-16 11:41 UTC, kingbbode requested changes
코멘트 작성해두었습니다.
확인 부탁드려요 :)

2021-06-16 11:41 UTC, kingbbode commented on src/main/java/nextstep/subway/line/domain/LineSections.java
> +    public void removeSectionByStation(Station station) {
객체 타입으로 `Station` 인게 명확해서 `by~` 를 꼭 붙일 필요는 없을 것 같아요!

2021-06-16 11:41 UTC, kingbbode commented on src/main/java/nextstep/subway/section/domain/Distance.java
> +
`distance` 를 검증하는 테스트 코드가 부족해보이네요 :)

2021-06-17 01:31 UTC, Donghui-Lee commented on src/main/java/nextstep/subway/line/domain/LineSections.java
> +    public void removeSectionByStation(Station station) {
좋은 말씀 감사합니다. :)

2021-06-17 01:32 UTC, Donghui-Lee commented on src/main/java/nextstep/subway/section/domain/Distance.java
> +
넵 미흡한 부분 피드백 해주셔서  감사합니다. :)

2021-06-17 14:02 UTC, merged