[Step 3] 구간 추가 기능
next-step/atdd-subway-admin pull request #288
Opened 2021-06-15 19:24 UTC by chae-yh

### Description
스텝 3 구간 추가 기능 입니다. 지하철 노선에 기 등록된 역이 존재할 때 새로운 역을 추가하는 역할을 합니다.

이번에도 꽤 어려웠습니다만 동시에 꽤 재밌기도 했습니다. 어느정도 복잡한 내용을 설계하면서 많이 고민하던 시간이 힘들기만 하진 않았던 것 같습니다.
이번에는 로직을 service가 아닌 domain에서 하도록 노력을 하였고, service 단에서는 db에 접근하여 데이터를 영속성 컨텍스트에 올려두는 역할만 하도록 하였습니다. service 에서 해당하는 데이터를 db에서 가져오는 방법을 통해 개발을 익숙하게 진행하고 싶은 생각이 들었으나, 해당 방법은 현재 저희가 받는 교육(객체지향)과 반하는 db 의존적인 개발이 되는 것 같아 지양하도록 노력하였습니다.
Exception을 어떻게 설계해야 하는지도 무척 어려웠습니다. 추가하는 section의 두 역이 기 등록된 역에 존재하지 않는다면 bad request 를 리턴해야 하는지 아니면 no contents를 리턴해야 하는지.. 등 애매한 부분이 있어 고민한 결과를 현재 pr의 exception으로 작성하였습니다.

내용 확인 부탁드립니다. 감사합니다 : )

2021-06-16 14:15 UTC, kyucumber requested changes
안녕하세요

몇가지 코멘트 남겨두었으니 확인 부탁드립니다.

2021-06-16 14:15 UTC, kyucumber commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +	}
이 메소드를 통해선 정렬된 역을 반환받을 수 없습니다.

`getStationMap`과 같은 이름은 어떨까요?

2021-06-16 14:15 UTC, kyucumber commented on src/main/java/nextstep/subway/line/dto/SectionRequest.java
> +	private int distance;
Bean Validation을 사용해보셔도 좋을 것 같아요~

```suggestion
      @NotNull
	private Long upStationId;
      @NotNull
	private Long downStationId;
      @NotNull
	private int distance;
```

2021-06-16 14:15 UTC, kyucumber commented on src/main/java/nextstep/subway/line/ui/LineController.java
> +		return ResponseEntity.ok().build();
생성된 Section에 대한 정보를 반환해주시면 어떨까요?

2021-06-16 14:15 UTC, kyucumber commented on src/test/java/nextstep/subway/line/SectionAcceptanceTest.java
> +	String lineId;
중요한 부분은 아니지만 접근 제한자를 붙여주시면 어떨까요?

2021-06-17 15:55 UTC, chae-yh commented on src/main/java/nextstep/subway/line/application/LineService.java
> +		Line line = lines.findById(lineId).orElseThrow(() -> new NoSuchElementException("There is no line for the id"));
동일 수행하는 부분 있어 같이 메소드로 추출하였습니다.
확인 감사합니다 : )

2021-06-17 15:58 UTC, chae-yh commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +	List<Section> list = new ArrayList<>();
일급 컬렉션이나 wrapping class가 가지는 필드명을 지을 때 종종 해당 필드명을 클래스와 동일한 이름을 지어도 되는지에 대해 애매한 생각이 듭니다. 무언가 해당 클래스명보다 구체적인 명칭을 적어주고 싶은데, list 라는 이름은 추후 자료형이 바뀌거나 할 때 같이 변경될 소지도 있어 부족한 느낌이 있네요 ㅎㅎ

해당 필드명은 sections로 변경하였습니다. 확인 감사합니다.
추가로 리뷰어 님은 일급 컬렉션, wrapping class 의 필드명을 클래스 이름과 동일하게 짓는 것에 대해 어떻게 생각하시는지 궁금합니다 : )

2021-06-17 16:02 UTC, chae-yh commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +	private void addList(Section targetSection, Section candidate, Station upStation, Station downStation) {
해당 메서드는 추가 여부에 대한 판단이 끝나서 실제 section을 추가해주고, 기존 section을 수정하는 역할을 합니다. 좋은 이름이 잘 생각나지는 않는데, section을 다시 정렬해준다는 의미로 rearrangeSections 로 바꿔봤습니다. 혹시 이건 어떨까요...?

2021-06-17 16:06 UTC, chae-yh commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +	}
이름 짓는게 쉽지 않네요 : ) 
기존 구간에 연결되는 역이 존재하는지 여부를 판단한다는 의미에서 validateExistsConnectedStationToOldLine 
라고 지어봤는데 어떨까요...?

2021-06-17 16:08 UTC, chae-yh commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +			.collect(Collectors.toSet());
해당 스트림을 getDistinceStations() 이라는 메소드로 추출하여 의미를 명확히 해보았습니다.
확인 감사합니다 : )

2021-06-17 16:11 UTC, chae-yh commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +	}
꽤 고민했던 부분인데 getStationMap가 더 좋을 것 같네요 : )
해당 내용으로 반영했습니다. 
감사합니다 : )

2021-06-17 16:14 UTC, chae-yh commented on src/test/java/nextstep/subway/line/SectionAcceptanceTest.java
> +	String lineId;
접근제한자 빠진 곳이 몇군데 있네요. 해당 부분 추가해주었습니다.
확인 감사합니다 : )

2021-06-17 16:42 UTC, chae-yh commented on src/main/java/nextstep/subway/line/ui/LineController.java
> +		return ResponseEntity.ok().build();
좋은 것 같습니다 ㅎㅎ body 에 담아 리턴하도록 변경하였습니다.

2021-06-17 16:44 UTC, chae-yh commented on src/main/java/nextstep/subway/line/dto/SectionRequest.java
> +	private int distance;
넵. 입력 받을 때 널 체크를 따로 해주지 않아도 되어 좋은 것 같습니다 : )
추가로 
https://bottom-to-top.tistory.com/14
이런 링크도 있네요 @NotNull 과 nullable = false 의 차이점에 대한 내용인데 공부가 되네요 ㅎㅎ
감사합니다 : )

2021-06-17 17:23 UTC, chae-yh commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +	private boolean addSectionWithCommonUpStation(Section candidate) {
한 메소드가 두가지 역할을 같이 하고 있네요...
boolean 을 체크하는 메소드와 실제 section 을 분리하여 반영하였습니다.
추가로 해당 부분 수정하며, magic number constant number 화 하였습니다. 초기에 배운 것들을 자주 잊어서 부지런히 적용해야 할 것 같습니다.

감사합니다 : )

2021-06-17 17:30 UTC, chae-yh commented
좋은 피드백 내용이 많아 공부가 많이 됐네요. 감사합니다 : )
말씀 주신 내용 수정하여 다시 pr 드립니다.

2021-06-18 10:35 UTC, kyucumber commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +	List<Section> list = new ArrayList<>();
저는 동일하게 사용하는 부분에 대해 거부감은 없었던 것 같아요.

`List<Section>`의 경우 sections라는 이름과 동일한 역할을 수행하고 있어서 저는 동일하게 짓는게 좀 더 자연스럽다고 생각합니다.

이름이 같아서 문제가 되는 경우가 아니라면 같게 할거 같아요.

2021-06-18 10:36 UTC, kyucumber commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +	private void addList(Section targetSection, Section candidate, Station upStation, Station downStation) {
추가하는 부분 또한 재정렬 하는 부분에 포함될 수 있기에 괜찮은 것 같아요.

내부에서 rearrange 하는 부분도 메소드를 분리하고, addSection 등의 심플한 이름으로 해주셔도 될것 같기도 하네요.

요 부분은 편하신대로 해주시면 될 것 같아요.

2021-06-18 10:38 UTC, kyucumber approved these changes
피드백 잘 반영해주셨습니다.

남겨두신 코멘트에 대해 답변 남겨두었으니 확인 부탁드릴게요.

https://github.com/next-step/atdd-subway-admin/pull/288#discussion_r654326344
https://github.com/next-step/atdd-subway-admin/pull/288#discussion_r654327372

다음 단계 진행을 위해서 머지하겠습니다.

2021-06-18 10:39 UTC, merged

2021-06-19 05:18 UTC, chae-yh commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +	}
이 부분 코멘트를 작성안했었네요;; 해당 부분 addSectionWithCommonUpStation 으로 메소드 추출해보았습니다.
확인 감사합니다. : )

2021-06-19 05:26 UTC, chae-yh commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +	private void addList(Section targetSection, Section candidate, Station upStation, Station downStation) {
이 코멘트를 보실진 모르겠지만... 말씀주신대로 rearrangeSections 도 책임이 두 가지이네요. 해당 부분을 addSection 과  modifuySeciton으로 수정하여 다음 스텝에서 반영하겠습니다.
확인 감사합니다 : )