Step4 - 구간제거 기능 리뷰요청 드립니다.
next-step/atdd-subway-admin pull request #290
Opened 2021-06-16 05:35 UTC by yzzzzun

안녕하세요 리뷰어님!

마지막 단계 리뷰요청 드리며, 이번 리뷰도 잘부탁드리겠습니다 😄

2021-06-16 14:40 UTC, kyucumber requested changes
안녕하세요

간단한 몇가지 코멘트 남겨두었으니 확인 부탁드립니다.

다음 요청 시 머지하도록 할게요.

2021-06-16 14:40 UTC, kyucumber commented on src/main/java/nextstep/subway/line/ui/LineController.java
> +		return ResponseEntity.ok().build();
delete의 경우 noContent로 표현하기도 합니다.

참고 부탁드려요~ 변경하실 필요는 없습니다.

2021-06-16 14:40 UTC, kyucumber commented on src/main/java/nextstep/subway/section/domain/Sections.java
> +		if ((sectionSize == SECTION_COUNT_ONE) && (sectionSize == removableSectionsCount)) {
SECTION_COUNT_ONE인 경우 별도의 조건을 추가로 체크할 필요가 없을 것 같은데

`(sectionSize == removableSectionsCount)` 의 경우 어떤 의도로 조건에 추가해주신건지 여쭤봐도 될까요?

2021-06-16 14:40 UTC, kyucumber commented on src/main/java/nextstep/subway/section/domain/Sections.java
> +			upSection.combineSectionDistance(downSection));
요 부분의 경우 해당 도메인에 대한 지식이 없으면 이해하기 힘들수도 있을 것 같아요.

병합된 구간을 반환하는 부분도 메소드로 추출해 의도를 잘 드러낼 수 있지 않을까요?

2021-06-16 14:40 UTC, kyucumber commented on README.md
> +      - 연결된 두 구간의 상 하행선을 기준으로 새로운 구간을 만든다.
구간 제거의 경우도 꼼꼼하게 잘 처리해주셨네요 👍  마지막까지 고생 많으셨습니다.

2021-06-17 10:03 UTC, yzzzzun commented on src/main/java/nextstep/subway/section/domain/Sections.java
> +		if ((sectionSize == SECTION_COUNT_ONE) && (sectionSize == removableSectionsCount)) {
sectionSize가 유일하게 하나이고 삭제할 역의 입력이 기존 구간에 없는 역으로 전달될 경우를 대비해서 추가한 조건입니다.
구간은 하나지만 오류 메세지는 구간에 존재하지 않는 역을 제거하려는 경우에대한 메세지를 보내줘야 할 것 같아서요!

2021-06-17 10:21 UTC, yzzzzun commented on src/main/java/nextstep/subway/section/domain/Sections.java
> +			upSection.combineSectionDistance(downSection));
저렇게 풀게되면 하나하나 분석해야해서 가독성이 덜어지겠네요.. 신경쓰도록 하겠습니다 👍🏻

2021-06-18 10:13 UTC, kyucumber approved these changes
마지막까지 고생 많으셨습니다. 🙏

2021-06-18 10:13 UTC, merged