step2 인수테스트 리팩토링 리뷰 요청드립니다
next-step/atdd-subway-admin pull request #304
Opened 2021-06-18 18:09 UTC by yevgnenll

2단계 인수테스트 리팩토링 요청 드립니다
너무 늦어져서 조마조마 하네요 ㅠㅠ

2021-06-19 01:28 UTC, ssosso requested changes
승권님~ 오랜만이예요:)
피드백 드리오니 확인 부탁드립니다~

2021-06-19 01:28 UTC, ssosso commented on src/main/java/nextstep/subway/line/domain/Line.java
> +        return sections.getSections().stream()
Sections에게 getStations에 대한 역할을 맡기면 어떨까요~?
그러면 section.getSections를 할 필요 없을거 같아요~

2021-06-19 01:28 UTC, ssosso commented on src/main/java/nextstep/subway/station/domain/Station.java
> +        return COMPARATOR.compare(this, o);
station의 id만으로 정렬을 하게 되면 station을 만든 순서대로 정렬되어 외부에 제공될 거 같아요~
station은 어떤 순서로 만들어질지 모르기 때문에 다른 방법은 없을까요~?

2021-06-19 01:28 UTC, ssosso commented on src/test/java/nextstep/subway/line/application/LineServiceTest.java
> +        assertThat(response.getStations().size()).isEqualTo(2);
test에 단순하게라도 `// given` `// when` `// then` 주석을 넣어주면 어떨까요~? 
추가적인 내용을 넣어주면 더 좋구요:)

2021-06-19 01:28 UTC, ssosso commented on src/test/java/nextstep/subway/line/application/LineServiceTest.java
>          lineService.delete(line.getId());
station이 없는 경우에 대한 테스트가 없어요~

2021-06-19 01:28 UTC, ssosso commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +            .when().delete(expected.header(PATH_FROM_HEADER))
RestAssured
            .given().log().all()
와 같은 부분이 반복되는데 하나의 코드로 관리하면 어떨까요~?

2021-06-19 05:45 UTC, yevgnenll commented on src/main/java/nextstep/subway/line/domain/Line.java
> +        return sections.getSections().stream()
sections 에게 이관하여  `return sections.getStations()` 와 같이 수정하였습니다~

2021-06-19 05:45 UTC, yevgnenll commented on src/test/java/nextstep/subway/line/application/LineServiceTest.java
> +        assertThat(response.getStations().size()).isEqualTo(2);
앗!! 넵 코드 정리하다가 빼먹었네요 ㅜㅜ 감사합니다

2021-06-19 05:57 UTC, yevgnenll commented on src/test/java/nextstep/subway/line/application/LineServiceTest.java
> +        assertThat(response.getStations().size()).isEqualTo(2);
넵 시나리오를 꿀잼나게 추가하였습니다~!

2021-06-19 05:57 UTC, yevgnenll commented on src/test/java/nextstep/subway/line/application/LineServiceTest.java
>          lineService.delete(line.getId());
넵넵 확인해보니 NotExistLineException 을 같이 사용하더라구요 NotExistStationException 도 함께 구현하여
테스트를 추가하였습니다~!

2021-06-19 05:58 UTC, yevgnenll commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +            .when().delete(expected.header(PATH_FROM_HEADER))
오오....... 그런 좋은 생각이...!!

2021-06-19 05:58 UTC, yevgnenll commented on src/main/java/nextstep/subway/line/domain/Line.java
> +        return sections.getSections().stream()
저 이제 스터디 시작하는데 종료하고 와서 요건 반영해두겠습니다.. 이건 좀 고민되네요 ㅠㅠ

2021-06-19 11:48 UTC, yevgnenll commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +            .when().delete(expected.header(PATH_FROM_HEADER))
StationAcceptanceTest 에도 함께 적용하였습니다~!

2021-06-19 11:50 UTC, yevgnenll commented on src/main/java/nextstep/subway/station/domain/Station.java
> +        return COMPARATOR.compare(this, o);
compare 를 제외하는게 좋겠어요

왜냐하면 section 의 asStation 에서 

```java
    public List<Station> asStations() {
        return Arrays.asList(upStation, downStation);
```

를 통해서 upStation, downStation 순서를 결정해주기 때문이에요. 따로 sort 하는 함수를 호출하지 않는 이상
이 정렬이 변경되지 않을 것이고 유지될 것이기 때문에 compareTo를 제외하는 것으로 변경하였습니다~!

2021-06-20 05:57 UTC, ssosso requested changes
승권님~ 반영해주신 부분 확인하였습니다:)
추가 피드백 드리오니 확인 부탁드립니다~

2021-06-20 05:57 UTC, ssosso commented on src/main/java/nextstep/subway/station/dto/StationResponse.java
> +        return COMPARATOR.compare(this, o);
여긴 아직 compare이 남아있고 sort하고 있네요~ 말씀드린 거처럼 id로 정렬될 거 같아요~

2021-06-20 06:05 UTC, yevgnenll commented on src/main/java/nextstep/subway/station/dto/StationResponse.java
> +        return COMPARATOR.compare(this, o);
어우 깜빡했네요 ㅜㅜ 바로 수정했습니다~!!!!

2021-06-20 06:41 UTC, ssosso approved these changes
승권님~ 수정해주신 부분 확인했습니다:)!
다음 단계 진행 부탁드립니다~

2021-06-20 06:41 UTC, merged