Step4 리뷰 부탁드립니다~!
next-step/atdd-subway-admin pull request #316
Opened 2021-06-21 08:27 UTC by lkimilhol

안녕하세요!

마지막 미션입니다. 이번 미션을 진행하면서 배웠던 부분들을 좀 지켜보면서 하려고 했는데요. 관련 하여 피드백 부탁드리겠습니다.

아래는 질문입니다...!

Q. 이번 미션을 진행하면서 equals 메서드가 제대로 동작하지 않아서 꽤 많은 시간을 소요했는데요. 확인해보니 Station의 equals가 실행 될 때 proxy 객체와 비교를 하고 있어 false가 떨어진 것을 확인하였습니다. 해당 부분은 equals 메서드를 수정하여 해결하였는데요...! 해당 방법대로 하면 좋을지 아니면 proxy 객체를 초기화 하여 비교하도록 해야할지... 아니면 상황마다 조금씩 다를지 ^^;; 조언 부탁드리겠습니다...!

Q. hashcode 메서드의 lazy loading 관련하여 적용을 해보았는데요! 구현을 제대로 한 것이 맞을까요? 
제가 이해한 바로는 Line을 lineId로 한번 더 매핑하여  hashcode 메서드에서 lineId를 통하여 해시코드가 동작하도록 한 것이었습니다. 맞게 이해한 것일까요?! (hashcode 메서드에 Line이 있으면 결국 hashcode 메서드가 동작할때 Line을 불러오게 되고 proxy 객체일때 초기화가 이뤄지기 때문에 계속적으로 쿼리가 날라갈수 있기 때문)

2021-06-21 13:16 UTC, tearight requested changes
기존 설계가 잘 되어있어 큰 변경이 없네요. 👍
코멘트를 남겨드렸으니 확인 부탁드려요.

2021-06-21 13:16 UTC, tearight commented on src/main/java/nextstep/subway/section/domain/Section.java
> +        return Objects.hash(id, lindId, upStation, downStation, distance);
넵 이 부분을 말씀드린게 맞습니다. upStation 과 downStation 도 id 만 넘겨주는 것이 어떨까요 ?

2021-06-21 13:16 UTC, tearight commented on src/main/java/nextstep/subway/section/domain/Sections.java
> +        }
enum 으로 연속적인 if 문을 없애는 방법도 있을 수 있겠네요.
이 부분은 수정하지 않으셔 됩니다. 그냥 이런 방법이 있을 수 있다 말씀드리는 것이라.

2021-06-21 13:16 UTC, tearight commented on src/test/java/nextstep/subway/section/SectionAcceptanceTest.java
> +
테스트케이스가 꼼꼼하시네요. 👍

2021-06-21 13:23 UTC, tearight commented
>Q. 이번 미션을 진행하면서 equals 메서드가 제대로 동작하지 않아서 꽤 많은 시간을 소요했는데요. 확인해보니 Station의 equals가 실행 될 때 proxy 객체와 비교를 하고 있어 false가 떨어진 것을 확인하였습니다. 해당 부분은 equals 메서드를 수정하여 해결하였는데요...! 해당 방법대로 하면 좋을지 아니면 proxy 객체를 초기화 하여 비교하도록 해야할지... 아니면 상황마다 조금씩 다를지 ^^;; 조언 부탁드리겠습니다...!

>Q. hashcode 메서드의 lazy loading 관련하여 적용을 해보았는데요! 구현을 제대로 한 것이 맞을까요?
제가 이해한 바로는 Line을 lineId로 한번 더 매핑하여 hashcode 메서드에서 lineId를 통하여 해시코드가 동작하도록 한 것이었습니다. 맞게 이해한 것일까요?! (hashcode 메서드에 Line이 있으면 결국 hashcode 메서드가 동작할때 Line을 불러오게 되고 proxy 객체일때 초기화가 이뤄지기 때문에 계속적으로 쿼리가 날라갈수 있기 때문)

먼저 equals 구현에 필요한 멤버와 hashcode 구현에 필요한 멤버가 달라서는 안됩니다.
HashSet 등의 자료형에서는 중복을 제거하기 위해 hashcode() 를 주로 사용할 거고요, Objects.equals 에서는 equals 를 사용하는 등 동등비교가 내용이 다르면 디버깅할 때 큰 혼란이 발생합니다.

여기서 선택지는 두개인데요, id 만 비교할 것인지 내부 객체를 비교할 것인지 고민을 하셔야 할 것 같네요. 선택에 따른 trade-off 는 각각 존재합니다. 저라면 id 를 택할 것 같습니다. 이유는 equals() 호출하는 경우는 직접하는 것 이외에도 다른 자바 API 를 통해서 암시적으로 호출할 가능성이 항상 존재하기 때문에 불필요한 쿼리를 방지하기 위해, @Transactional 바깥에서 lazy 된 객체를 찾을 시  LazyInitializationException 이 발생할 수도 있기 때문이지요.

2021-06-22 07:43 UTC, lkimilhol commented on src/main/java/nextstep/subway/section/domain/Distance.java
> +        return new Distance(value - requestDistance.value);
마이너스를 생성자를 통해서 체크하도록 했었는데요! 리뷰어님 말씀대로 순서가 헷갈릴만한거 같습니다!
수정하였습니다!

2021-06-22 07:43 UTC, lkimilhol commented on src/main/java/nextstep/subway/section/domain/Section.java
> +        return Objects.hash(id, lindId, upStation, downStation, distance);
아 그렇네요. 센스가 부족했습니다! 수정하였습니다!

2021-06-22 07:43 UTC, lkimilhol commented on src/main/java/nextstep/subway/section/domain/Sections.java
> +        }
네 감사합니다! 해당 부분은 제가 따로 공부해보도록 하겠습니다!

2021-06-22 07:44 UTC, lkimilhol commented on src/test/java/nextstep/subway/section/SectionAcceptanceTest.java
> +
덕분입니다!! 테스트작성에 관하여 많이 배웠습니다!

2021-06-22 07:51 UTC, lkimilhol commented
안녕하세요! 코멘트 달아주신내용 숙지한뒤 코드 수정하였습니다!

질문이 하나 있는데요~! 코멘트 달아주신 내용을 제가 제대로 이해하였는가 싶어서요!

hashcode 부분에서 같이 않다고 판명한 로직은
equals 메서드 중
``
if (o == null || getClass() != o.getClass()) return false; (o.getClass가 proxy였음)
``
부분이었는데요. 이 부분을 수정했었는데 일단 다시 롤백을 하였습니다. (ide에서 자동 작성 된 hashcode 이용)

이후 비즈니스 로직상에서 station을 == 비교를 하였습니다.
안의 값을 동일한데 proxy 객체라 클래스가 달라서 난 에러로 확인을 하였거든요.

제가 수정한 방법을 어떨까요?

추가로 말씀해 주신 내용중 id 값이나 객체 내부의 값 비교라 하시면 equals 메서드 내에서 일까요?!
아니면 제가 수정한거처럼 비즈니스 로직에서 일까요?!

2021-06-22 11:19 UTC, tearight commented
> 안녕하세요! 코멘트 달아주신내용 숙지한뒤 코드 수정하였습니다!
> 
> 질문이 하나 있는데요~! 코멘트 달아주신 내용을 제가 제대로 이해하였는가 싶어서요!
> 
> hashcode 부분에서 같이 않다고 판명한 로직은
> equals 메서드 중
> `if (o == null || getClass() != o.getClass()) return false; (o.getClass가 proxy였음)`
> 부분이었는데요. 이 부분을 수정했었는데 일단 다시 롤백을 하였습니다. (ide에서 자동 작성 된 hashcode 이용)
> 
> 이후 비즈니스 로직상에서 station을 == 비교를 하였습니다.
> 안의 값을 동일한데 proxy 객체라 클래스가 달라서 난 에러로 확인을 하였거든요.
> 
> 제가 수정한 방법을 어떨까요?

equals 에서 Id 비교를 하는 것을 말씀드렸습니다.
기본적으로 동등(equal)비교와 동일(==) 비교를 아실 것 같지만 혹시나 싶어 관련 링크를 남길게요.
https://ecsimsw.tistory.com/entry/%EC%9E%90%EB%B0%94-equals%EC%99%80-%EB%B9%84%EA%B5%90-%EC%97%B0%EC%82%B0%EC%9E%90%EC%9D%98-%EC%B0%A8%EC%9D%B4-String-Pool
동일 비교는 [객체의 인스턴스가 동일한가?] 를 묻는 논리연산자인데요, 인스턴스가 동일한가? 를 묻는게 아니라면 왠만하면 equals 를 사용하시는 것을 추천드립니다. 
일단 equals 는 내부적으로 동일(==) 비교를 포함하고 있고, 우리가 모르는 동등 조건 또한 같이 비교해주기 때문에 정확도가 높습니다.
그리고 두번째로 JPA 에서는 같은 ID 의 값을 DB 에서 조회해오더라도 동일비교가 False 일 수 있습니다.
같은 ID 를 조회해도 동일비교가 서로 실패하는 케이스는 다음과 같습니다.
1. repository 에서 쿼리메소드를 통해 조회한 객체
2. 1번과 다른 트랜잭션에서 같은 방법으로 조회한 객체
3. 객체 그래프 탐색중 얻은 proxy 객체
4. JPQL 또는 querydsl 을 통해서 조회한 객체

이렇게 같은 내용이어도 각각이 동일비교에서 false 로 연산됩니다. 따라서 어떤 데이터 조회 방법을 통해 station 을 넣을지 도메인 계층에서는 알 수 없기 때문에 동일(==)비교를 해서는 안됩니다.

2021-06-22 11:23 UTC, tearight requested changes
동일 비교에 대한 코멘트를 남겼습니다. 마지막으로 확인 부탁드립니다.

2021-06-22 11:25 UTC, tearight commented
이 == 비교에 대한 부분은 코멘트만 확인해주셔도 되고 개선을 해주셔도 됩니다.
request changes 는 더 이상 하지 않으려 합니다(다른 미션도 진행하셔야 하기에).
따라서 코멘트 확인 해주시고 PR 다시 넣어주시면 바로 머지하고 미션을 종료하도록 하겠습니다.

2021-06-23 02:34 UTC, lkimilhol commented
안녕하세요! 해당 내용 확인했습니다!
동일 비교, 동등 비교에 대해서는 알고 있는 내용인데요. 다른 미션 진행하면서 동일 비교를 하는 부분을 봤었는데, 다른 미션의 코드를 바꾸는것이 맞겠네요! 말씀해주신 4가지 사항에 대해서는 모르고 있었는데 (JPA 공부 더 열심히 해야겠습니다 ㅠ_ㅠ) 정말 감사드립니다.

번거롭게 죄송합니다만...

``
@Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Station station = (Station) o;
        return Objects.equals(id, station.id) && Objects.equals(name, station.name);
    }
``

에서


``
 if (o == null || getClass() != o.getClass()) return false;
`` 

이 부분에서 getClass() != o.getClass() 에 걸려 return false; 를 해주고 있었는데요. 

id 비교를 말씀해주셨는데 
equals 메서드 안의 내용을 모두 제거하고 id 비교만 하는것을 말씀해주신걸까요...?! (null 과 타입 비교는 지우면 안될거같아서 약간 제가 혼란이 왔습니다 ㅠ)
만약에 맞다면 다른 로직에서 equlas를 사용할때 문제는 없을까? 하는 생각이 좀 들었습니다!

따라서 해결 방법을 고민해보면 equlas 메서드를 호출하는 부분에서 id 값을 비교 하거나 
getClass를 instanceof 로 체크하는 것이라고 생각을 했는데요 (이전에 제가 수정했던 방식입니다.)

관련된 블로그 링크입니다..!
https://kihoonkim.github.io/2017/01/27/JPA(Java%20ORM)/4.%20JPA-%ED%94%84%EB%A1%9D%EC%8B%9C%20%EC%99%80%20%EC%A7%80%EC%97%B0%EB%A1%9C%EB%94%A9/

이렇게 되면 equals와 hashcode 내에서도 같은 멤버로 동작하기 때문에 문제가 없을것이라고 생각하였습니다...!

제가 리뷰어님의 코멘트를 제대로 이해하지 못한거 같네요 ㅠ

말씀해주신대로 이대로 머지 해주셔도 좋을거 같습니다...! 
감사합니다 :)

2021-06-23 12:10 UTC, tearight commented
클래스 비교는 제가 까마득히 잊고 있었네요. instanceof 로 교체되면 적절할 것 같습니다. 잘 연구해주신 것 같습니다. 👍
instanceOf 로 비교 후 id 를 하면 될 것 같네요.
equals 비교를 순차적으로 하자면 다음과 같습니다.
1. 동일 인스턴스 비교
2. instanceOf 비교
3. 형 변환 후 멤버 비교(이 부분에 id 비교가 들어가겠죠?)

2021-06-23 12:10 UTC, tearight approved these changes
끝까지 JPA 에 대해 많은 연구를 해주셔서 저도 다시 한번 상기하는 시간을 가졌습니다.
미션은 이만 끝내도록 하겠습니다. 앞으로의 미션도 화이팅입니다!

2021-06-23 12:11 UTC, merged