4단계 - 구간 제거 기능
next-step/atdd-subway-admin pull request #317
Opened 2021-06-21 12:22 UTC by fDevJc

안녕하세요. 주말 잘보내셧나요~? 😀
4단계 많은 피드백 부탁드리겠습니다
감사합니다

질문) 
역삭제의 여러경우 (첫역,중간역,마지막역, 예외사항) 등을 SectionsTest에 테스트하고 
인수테스트에서는 정상적인 중간역 삭제 경우만 테스트했습니다. 인수테스트에서도 모든 사항을 테스트할 필요가 있을까요?

2021-06-22 13:20 UTC, wheejuni requested changes
안녕하세요. 간단히 피드백드릴 부분이 한 가지 있고요, 질문에 대한 답변도 인라인 코멘트로 남겼습니다.
확인 부탁드리겠습니다. 감사합니다! 💯

2021-06-22 13:35 UTC, fDevJc commented on src/test/java/nextstep/subway/section/SectionAcceptanceTest.java
> +    @Test
네엡 답변감사합니다!

2021-06-22 14:08 UTC, fDevJc commented on src/main/java/nextstep/subway/section/domain/Sections.java
> +
말씀해주신 분기방법이 맞을까요??

2021-06-23 13:11 UTC, wheejuni approved these changes
수고 많으셨습니다. 👍

2021-06-23 13:11 UTC, merged