Atdd2
next-step/atdd-subway-admin pull request #325
Opened 2021-06-23 01:03 UTC by tinyhhj

안녕하세요 김규남님
Atdd 2단계 리뷰 요청드려요.

생각보다 단순한 모델인것 같으면서도, 도메인 설계와 jpa에 경험이 부족하다보니 더 어렵게 느껴졌습니다.
jpa 설계시 대개는 특정 부모(라인)을 기준으로 자식(역)들을 조회하는 경우가 많다보니, 자연스럽게 OneToMany와 JoinColumn을
이용해서 단방향 1:N 관계를 생각하게 되는데요. 대부분의 블로그 경우 update오버헤드가 발생하기때문에 1:N 양방향을 권장하고 있네요.

규남님도 1:N의 관계매핑시 양방향으로 설계를 많이하시는지 궁금합니다. 또한 단방향으로 사용하는 특정 경우가 있다면 어떤 케이스인지 공유해주시면 도움이 될것 같습니다

감사합니다!

2021-06-23 15:26 UTC, kyucumber requested changes
안녕하세요

몇가지 코멘트 남겨두었으니 확인 부탁드립니다.

2021-06-23 15:26 UTC, kyucumber commented on src/main/java/nextstep/subway/line/application/LineService.java
>      }
서비스 바깥으로 `Line` 엔티티가 노출되고 있네요.

open session in view 설정이 켜져있는 경우 문제가 없지만

영속성 컨텍스트 바깥으로 엔티티가 나가면 LAZY가 걸려있는 경우 문제가 될 수 있습니다.

`Line`은 Lazy로 연관관계 매핑이 된 값이 존재했던 것 같은데 가급적이면 영속성 컨텍스트 바깥으로 엔티티가 노출되지 않도록 변경해주세요.

2021-06-23 15:26 UTC, kyucumber commented on src/main/java/nextstep/subway/line/domain/Line.java
> +    }
아래 요구사항에 대해 다시 고민해보세요.

현재는 단순히 구간별 상행, 하행역을 flatMap으로 뽑고 중복을 제거한 뒤 반환하는 것으로 보이네요.
순서대로 저장하는 경우는 정상적인 순서로 역이 반환되겠지만, 역의 삭제 및 수정에 따라 순서가 보장되지 않을 것 같아요.

- [ ] 상행역 부터 하행역 순으로 정렬되어야 함

2021-06-23 15:26 UTC, kyucumber commented on src/main/java/nextstep/subway/station/application/StationService.java
> +    public Station findById(Long id) {
`find`와 `get`은 어떤 차이가 있을까요?

https://granger.tistory.com/50

2021-06-23 15:26 UTC, kyucumber commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> -//    }
불필요한 코드는 지워주시면 어떨까요?

2021-06-23 15:26 UTC, kyucumber commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +    Station 강남역;
```suggestion
    private Station 광교역;
    private Station 강남역;
```

2021-06-23 15:26 UTC, kyucumber commented on src/main/java/nextstep/subway/line/domain/Line.java
> +    }
사용하지 않는 부분이네요, 제거하면 어떨까요?

2021-06-23 15:29 UTC, kyucumber commented
```
규남님도 1:N의 관계매핑시 양방향으로 설계를 많이하시는지 궁금합니다. 또한 단방향으로 사용하는 특정 경우가 있다면 어떤 케이스인지 공유해주시면 도움이 될것 같습니다
```

저도 가급적 1:N 시 양방향 매핑을 사용합니다.

데이터가 많지 않고 크게 부담이 없는 경우 1:N 단방향으로 설계하기도 합니다.

2021-06-25 14:18 UTC, tinyhhj commented on src/main/java/nextstep/subway/line/application/LineService.java
>      }
이런 문제가 있을 수 있겠네요.

Line대신 pojo형태로 노출시켜야겠네요
피드백 감사합니다!

2021-06-25 14:44 UTC, tinyhhj commented on src/main/java/nextstep/subway/station/application/StationService.java
> +    public Station findById(Long id) {
이런 차이를 생각해본적이 없었는데

중요한 정보네요 감사합니다.

2021-06-25 17:40 UTC, tinyhhj commented on src/main/java/nextstep/subway/line/domain/Line.java
> +    }
@OrderColumn을 통해서 순서를 유지하게끔 수정했습니다.

2021-06-26 11:12 UTC, kyucumber commented on src/main/java/nextstep/subway/station/domain/Sections.java
> +    private List<Section> sections = new LinkedList<>();
`@OrderColumn` 어노테이션을 사용해주셨는데

순서를 JPA 내부에서 관리하게 될 것 같아요. 구간의 삭제 또는 추가시에 이 순서를 임의로 정렬해주실 수 있을까요?

정렬할 수 있더라도 데이터 관리가 굉장히 어려워 질 것 같습니다.

간단한 예시를 아래에 추가해두었으니 확인하시고 코멘트 남겨주시면 감사하겠습니다.

기존 구간 목록
- Section 강남 역삼 order 0
- Section 역삼 잠실 order 1

신규 추가 구간
- Section 역삼 선릉

이 경우 아래와 같이 재 배치가 되어야 합니다. `@OrderColumn` 기능으로 커버가 가능할까요?

- Section 강남 역삼 order 0
- Section 역삼 선릉 order 1
- Section 선릉 잠실 order 2

2021-06-26 11:13 UTC, kyucumber requested changes
OrderColumn을 사용해주신 부분에 대해 코멘트 남겨두었습니다.

아래 코멘트 확인 부탁드립니다.

https://github.com/next-step/atdd-subway-admin/pull/325#discussion_r659154986

2021-06-27 01:48 UTC, tinyhhj commented on src/main/java/nextstep/subway/station/domain/Sections.java
> +    private List<Section> sections = new LinkedList<>();
@OrderColumn 사용한 이유는 노선 조회시 순서대로 불러오기 위한 용도로 사용했습니다. 
노선에서 특정 구간 추가 및 삭제는 LinkedList를 이용해서 특정 index에 적용 가능하도록  사용했습니다.

규남님의 예시상황에서 새로운 구간을 index 1에 추가하면 순서를 알맞게 추가가 가능할 것으로 생각됩니다. 

혹시라도 제가 놓친 부분이 있다면 알려주시면 감사하겠습니다!

2021-06-27 02:51 UTC, kyucumber commented on src/main/java/nextstep/subway/station/domain/Sections.java
> +    private List<Section> sections = new LinkedList<>();
OrderColumn 관련된 기능을 착각해서 코멘트를 조금 이상하게 남겨드렸군요 😭 

구간의 신규 추가 시 병합 및 삭제, 삭제 시 병합 등에 대한 부분을 잘 정의해주시면 크게 상관은 없을 것 같습니다.

다만 데이터 정합성을 맞추는 부분이 조금 더 까다로워지고, `@OrderColumn` 사용에 따른 리스크는 감수해주셔야 될 것 같네요.

2021-06-27 02:52 UTC, kyucumber approved these changes
코멘트 남겨둔 부분 확인 부탁드립니다.

https://github.com/next-step/atdd-subway-admin/pull/325#discussion_r659252794

다음 단계 진행을 위해 머지할게요

2021-06-27 02:52 UTC, merged