[인수테스트주도개발] 4단계 - 구간 제거 기능
next-step/atdd-subway-admin pull request #339
Opened 2021-06-28 10:31 UTC by jaewanLee

안녕하세요
3단계 피드백 반영 후, 4단계 구간 제거 기능 추가했습니다.
리뷰요청드립니다.

2021-06-28 12:41 UTC, tearight requested changes
안녕하세요, 코멘트 작성하였으니 확인 부탁드릴게요.

2021-06-28 12:41 UTC, tearight commented on src/main/java/nextstep/subway/line/domain/LineStation.java
> +    }
이 클래스에서 명시적으로 lineId 를 갖고 있는 것이 좋을 것 같습니다.
서로 Line 이 다른 LineStation 이라 할지라도 역만 같으면 equals 연산이 true 로 반환되어 버그가 발생할 여지가 있겠네요.

2021-06-28 12:41 UTC, tearight commented on src/main/java/nextstep/subway/line/domain/LineStations.java
> +                .filter(lineStation -> lineStation.getUpStationId() == lineStationId)
BoxedNumber 에 대한 동등성을 검사해야 하는 것이므로 Objects.equals 로 비교하는 게 좋겠네요.
IntelliJ 에서 표시해주는 경고로 보이는데 적극적으로 이러한 경고들을 봐주시면 더 깔끔한 코딩이 될 것 같습니다.

2021-06-28 12:41 UTC, tearight commented on src/test/java/nextstep/subway/line/LineStationDeleteAcceptanceTest.java
> +public class LineStationDeleteAcceptanceTest extends AcceptanceTest {
구간 삭제를 하면 노선 길이가 어떻게 변화하는지에 대한 시나리오가 필요해보이네요.

2021-06-29 11:12 UTC, jaewanLee commented on src/main/java/nextstep/subway/line/domain/LineStation.java
> +    }
equals 연산이 필요하지 않아 제거하는 방향으로 변경했습니다.

이미 LineStations에서 joinColumn으로 line_id를 선언해, 해당 클래스에 lineId를 명시적으로 갖고 있는것이 불가능했었는데요. 어떤방법으로 변경할 수 있었을까요??

2021-06-29 12:43 UTC, tearight commented on src/main/java/nextstep/subway/line/domain/LineStation.java
> +    }
한번 더 @Column 으로 매핑하는 것이 가능합니다.

```
@Column(name ="", insertable=false, updatable=false)
Long lineStationId; 
```

이런식으로 매핑을 하시면 읽기 전용으로 값을 읽어오게 됩니다.

2021-06-29 12:44 UTC, tearight approved these changes
피드백 잘 적용해주셨네요. 👍
질문에 대해서는 코멘트로 남겼으니 확인만 해주시면 될 것 같습니다.
미션은 이것으로 마치도록 하겠습니다.
나머지 미션도 화이팅입니다!

2021-06-29 12:44 UTC, merged