1단계 - 지하철 노선 관리
next-step/atdd-subway-admin pull request #344
Opened 2021-07-02 12:20 UTC by ascii92der

개인 사정으로 인해 미션 진행이 많이 늦었습니다. ㅠㅠ

그래도 공부하려는 목적이니 꼼꼼히 잘 봐주세용 ㅎㅎ (_ _);;

미션 진행중 궁금한 내용이 있어 아래에 같이 첨부합니다.

[미션 자료](https://woowacourse.github.io/tecoble/post/2020-08-19-rest-assured-vs-mock-mvc/)로 주신 위 링크를 보면 ```controller test``` 시에 ```@WebMvcTest```를 사용하면 된다고 해서 사용하려 하는데...
해당 어노테이션을 쓰면 정상적으로 테스트가 되지 않습니다.
```@SpringBootTest``` 어노테이션을 사용해야 테스트가 동작하는데...
제 설정이 문제인지, 아니면 안되는 이유가 있는 것인지 알 수 있을까요??

빠른 리뷰는... 사랑입니다!! ㅎㅎ

2021-07-04 05:31 UTC, kang-hyungu requested changes
철원님 리뷰 요청 주신 내용 확인했습니다.
몇 가지 코멘트 남겼으니 수정해보시고 리뷰 재요청주세요.
궁금한 점 생기면 dm 주시거나 코멘트 남겨주세요

2021-07-04 05:31 UTC, kang-hyungu commented on src/main/java/nextstep/subway/line/application/LineService.java
> +    public static final String LINE_NOT_EXISTED = "해당 노선이 없습니다 : ";
접근제어자를 public으로 열어둘 필요가 있을까요?

2021-07-04 05:31 UTC, kang-hyungu commented on src/main/java/nextstep/subway/line/application/LineService.java
> +        Line line = lineRepository.findById(id)
```java
    Line line = lineRepository.findById(id)
                .orElseThrow(() -> new NoSuchElementException(LINE_NOT_EXISTED + id));
```
이 부분이 반복적으로 나오는데 메서드로 추출하면 어떨까요

2021-07-04 05:31 UTC, kang-hyungu commented on src/main/java/nextstep/subway/line/ui/LineController.java
> +    public ResponseEntity handleDataIntegrityViolationException(DataIntegrityViolationException e) {
리턴 타입에 제네릭 타입을 명시해주세요

2021-07-04 05:31 UTC, kang-hyungu commented on src/test/java/nextstep/subway/line/LineAcceptance.java
> +public class LineAcceptance {
http 호출이 get, post, put, delete 단위로 반복해서 나타나네요
LineAcceptanceTest 클래스와 다른 인수 테스트 클래스도 AcceptanceTest를 상속하고 있으니 저 클래스에서 중복 코드를 줄일 수 있는 메서드를 추가해보면 어떨까요

```java
public <T> static ExtractableResponse<T> post(T request, String path) {

        return RestAssured
                .given().log().all()
                .body(request)
                .contentType(MediaType.APPLICATION_JSON_VALUE)
                .when()
                .post(path)
                .then().log().all().extract();
    }
```

2021-07-04 05:31 UTC, kang-hyungu commented on src/test/java/nextstep/subway/line/ui/LineControllerTest.java
> +class LineControllerTest {
1. 인수 테스트가 있는데 컨트롤러 테스트를 따로 추가한 이유가 있을까요?
2. WebMvcTest 어노테이션을 사용했을 때 어떤 에러 메시지를 받았나요? 어떤 빈을 못찾았다고 나올텐데 WebMvcTest 어노테이션 코드에 있는 주석을 읽어보시면 도움이 될 것 같네요.

2021-07-05 05:58 UTC, ascii92der commented on src/main/java/nextstep/subway/line/application/LineService.java
> +    public static final String LINE_NOT_EXISTED = "해당 노선이 없습니다 : ";
인텔리제이 추출 기능을 사용하다보니 확인을 못했네요;;

private로 수정하였습니다

2021-07-05 05:58 UTC, ascii92der commented on src/main/java/nextstep/subway/line/application/LineService.java
> +        Line line = lineRepository.findById(id)
반복 메소드로 추출하였습니다.

2021-07-05 05:59 UTC, ascii92der commented on src/main/java/nextstep/subway/line/ui/LineController.java
> +    public ResponseEntity handleDataIntegrityViolationException(DataIntegrityViolationException e) {
타입 명시하였습니다 ㅎㅎ

2021-07-05 06:00 UTC, ascii92der commented on src/test/java/nextstep/subway/line/LineAcceptance.java
> +public class LineAcceptance {
중복 메소드로 추출하여 AcceptanceTest에 추가하였습니다.

전체적으로 코드 중복에 대해 고려를 안했네요 ㅠ

2021-07-05 06:08 UTC, ascii92der commented on src/test/java/nextstep/subway/line/ui/LineControllerTest.java
> +class LineControllerTest {
1. AcceptanceTest가 있으므로 controllerTest가 별도로 필요없다고 생각하긴 했지만...
인수 테스트 주도 개발>인수 테스트 도구에 ```MockMvc vs RestAssured``` 관련 링크가 있어, 공부를 해보란 의미로 받아들여 추가하여 테스트를 해보았습니다.

2. WebMvcTest를 사용하였을 때, lineRepository createBean 관련 에러 메시지를 받았고,
@mockbean으로 lineRepository를 추가해주니 에러 메시지가 Station 관련 ceateBean 에러로 변경 되었습니다.
그래서 말씀하신대로 WebMvcTest 안에 주석일 읽고,  
@AutoConfigureMockMvc 를 없애고 controllers = {LineController.class}, useDefaultFilters = false 를 추가해서 테스트를 해보았지만
WebMvcTest 내에 @AutoConfigureMockMvc 가 추가되어 있어 그런것인지... 지속적으로 에러 메시지가 발생하네요 ㅠㅠ

2021-07-05 07:37 UTC, ascii92der commented on src/test/java/nextstep/subway/line/ui/LineControllerTest.java
> +class LineControllerTest {
https://stackoverflow.com/questions/45350546/entitymanagerfactory-not-found-in-springboot

위 링크를 보고 Jpa관련 Config를 만들어 profile로 구별하여 WebMvcTest가 정상 동작하도록 수정해보았습니다~!!

해당 부분도 같이 commit 했습니다.!!

2021-07-05 22:24 UTC, kang-hyungu approved these changes
철원님 피드백 반영 잘하셨습니다.
다음 미션 진행해주세요
pr은 머지 처리하겠습니다

2021-07-05 22:24 UTC, kang-hyungu commented on src/test/java/nextstep/subway/line/LineAcceptance.java
> +    public static ExtractableResponse<Response> 지하철_노선_조회_요청(ExtractableResponse<Response> createResponse) {
get 메서드를 사용해도 되겠네요

2021-07-05 22:24 UTC, merged

2021-11-15 12:33 UTC, gracefulBrown commented on src/test/java/nextstep/subway/line/ui/LineControllerTest.java
> +class LineControllerTest {
개인적으로 인수 테스트를 만들 땐 mock사용을 지양합니다.
그 이유는 @MockBean(이나 테스트 더블 객체)을 사용 할 경우 여러개 테스트 클래스를 동시에 테스트 수행 할 경우 속도가 느려지기 떄문인데요 자세한 설명은 강의 때 드리도록 하겠습니다 :)

2021-11-15 12:33 UTC, boorownie commented on src/test/java/nextstep/subway/line/ui/LineControllerTest.java
> +class LineControllerTest {
개인적으로 인수 테스트를 만들 땐 mock사용을 지양합니다.
그 이유는 @MockBean(이나 테스트 더블 객체)을 사용 할 경우 여러개 테스트 클래스를 동시에 테스트 수행 할 경우 속도가 느려지기 떄문인데요 자세한 설명은 강의 때 드리도록 하겠습니다 :)