"인수 테스트 주도 개발" 1단계 - 지하철 노선 관리
next-step/atdd-subway-admin pull request #35
Opened 2020-12-28 08:23 UTC by orgojy

안녕하세요. 강현구 리뷰어님! 반갑습니다~!
연휴는 잘보내셨나요?
"우아한테크캠프 Pro" 수강생 안이민입니다.
PR 요청 드립니다. 리뷰 잘부탁드려요! 👍

2020-12-29 02:12 UTC, kang-hyungu requested changes
안녕하세요 이민님, 리뷰어 강현구입니다 👋 
1단계 구현 잘 해주셨어요
간단한 몇 가지 피드백 남겼는데 수정하시고 리뷰 재요청주세요~!

2020-12-29 02:12 UTC, kang-hyungu commented on src/main/java/nextstep/subway/line/application/LineService.java
> +        lineRepository.save(line);
save 따로 안해도 update 동작하지 않나요?

2020-12-29 02:12 UTC, kang-hyungu commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +        지하철_노선_수정됨(response);
http 응답 상태만 체크하지 말고 업데이트도 잘 됐는지 확인하는 테스트를 추가해보면 어떨까요

2020-12-29 15:23 UTC, orgojy commented on src/main/java/nextstep/subway/line/application/LineService.java
> +        lineRepository.save(line);
네 맞습니다. 더티 체킹이 트랜잭션 안에서 됩니다.
제거하도록하겠습니다. 👍

2020-12-29 15:48 UTC, orgojy commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +        지하철_노선_수정됨(response);
넵. 지하철 노선 이름과 색상에 대해서도 테스트 코드에서 체크하는 것으로 수정하였습니다.

2020-12-30 00:36 UTC, kang-hyungu approved these changes
이민님 피드백 반영 잘 하셨습니다 👏 
pr은 머지 처리하겠습니다 수고하셨습니다

2020-12-30 00:36 UTC, kang-hyungu commented on src/test/java/nextstep/subway/station/StationAcceptanceTest.java
> +        ExtractableResponse<Response> createResponse1 = 지하철역_생성_요청("강남역");
```suggestion
        ExtractableResponse<Response> 강남역 = 지하철역_생성_요청("강남역");
        ExtractableResponse<Response> 역삼역 = 지하철역_생성_요청("역삼역");
```
이렇게 변수명을 지어주면 좀더 코드 읽기 좋지 않을까요?

2020-12-30 00:36 UTC, merged