[ Step4 - 구간 제거 기능 ] 리뷰 요청드립니다.
next-step/atdd-subway-admin pull request #350
Opened 2021-07-06 18:29 UTC by KyungSik9870

안녕하세요 리뷰어님! 😀
4단계 미션 리뷰 요청드립니다!
지난번 단계에서 거리를 검사하는 테스트가 빠진것같아 그부분도 추가해보았습니다!

제가 인수테스트를 작성할때 발생하는 RuntimeException 에 대해서, HttpStatus 를 INTERNAL_SEVER_ERROR 로 반환하였는데요
혹시 이런예외 상황에서 권장하는 반환타입이나 예외처리 방식이 있을까요??

저번에 피드백을 받고, 실무에서 ExceptionHandler를 적용해보았는데
Enum타입으로 미리 예외코드를 정의하고, 커스텀한 Exception 의 필드에 예외코드를 넣어 어떤 오류인지 구체화해보았습니다.
그 후에 ResponseEntity 에 담아서 리턴을 해주었는데, 더 좋은 방식이 있는지. 권장하는 방식이 있는지 궁금합니다 🧐

2021-07-07 13:51 UTC, wheejuni requested changes
수고 대단히 많으셨습니다 💯 
크게 건드릴 부분은 없는데요, 애플리케이션 전반에서 발생할 만한 예외 상황 정리해보시고, 이에 맞는 예외 클래스들 작성하시는 연습만 한번 하고 바로 머지하면 좋을 것 같습니다. 
진행하시면서 궁금하신 부분은 추가 질문 남겨주시기 바랍니다. 감사합니다. 👍

2021-07-07 13:51 UTC, wheejuni commented on src/main/java/nextstep/subway/line/ui/LineController.java
> +	@ExceptionHandler(RuntimeException.class)
`RuntimeException` 을 500번대 상태코드로 매핑하는 것 나쁘지 않아 보입니다.
다만 제가 우려하는 것은 지금 이렇게 핸들러에서 캐치하기에 `RuntimeException` 은 너무 포괄적인 범위입니다.
다양한 예외 상황에 대해 좀 더 구체적인 처리가 필요하지는 않을지요? 이 예외는 애플리케이션단 아래 레이어들에서도 많이 올라올 수 있는 예외일텐데요...

2021-07-07 13:51 UTC, wheejuni commented on src/main/java/nextstep/subway/section/domain/Section.java
> +			this.distance = new Distance(0);
제가 지금 봤는데 indent 설정이 여덟칸으로 되어있는 듯 하네요...
4 spaces가 컨벤션이므로 이 부분 설정에서부터 수정해주시면 좋을 것 같네요.

2021-07-08 08:49 UTC, KyungSik9870 commented on src/main/java/nextstep/subway/line/ui/LineController.java
> +	@ExceptionHandler(RuntimeException.class)
넵 감사합니다! 너무 포괄적이여서 구체적인 처리가 필요한 예외상황을 오히려 놓칠수도 있을것같네요!
갑사합니다! 수정해보겠습니다 😀

2021-07-08 08:50 UTC, KyungSik9870 commented on src/main/java/nextstep/subway/section/domain/Section.java
> +			this.distance = new Distance(0);
엇 이거는 실제 제 소스에서는 4 spaces 로 보이고, 인텔리제이 설정에서도 4로 되어있는데 왜이렇게 보일까요..ㅠㅠ🥲

2021-07-09 14:35 UTC, wheejuni approved these changes
수고 많으셨습니다. 👍

2021-07-09 14:35 UTC, merged