Step3 - 구간 추가 기능
next-step/atdd-subway-admin pull request #363
Opened 2021-11-12 16:26 UTC by devyonghee

안녕하세요 리뷰어님!!
2단계에 이어서 3단계도 잘 부탁드리겠습니다!!

생각보다 구간 추가하는 부분이 굉장히 어려웠던 것 같습니다. 😅😅😅
이전에 코멘트 해주신 부분들도 수정했습니다!! 😆

2021-11-13 14:46 UTC, jaeyeonling requested changes
구간 추가 기능을 잘 구현해주셨어요 👍 
소소한 코멘트 남겨두었으니 확인 부탁드려요~

2021-11-13 14:46 UTC, jaeyeonling commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +            list.get(index)
index를 신경쓰는 코드 때문에 가독성이 떨어지는 것 같은데, 구현 코드를 봤을 때 index를 통한 장점을 찾지 못했는데 Section의 index를 추가해주신 이유를 공유해주실 수 있을까요!?

2021-11-13 14:46 UTC, jaeyeonling commented on src/test/java/nextstep/subway/line/SectionAcceptanceTest.java
> +class SectionAcceptanceTest extends AcceptanceTest {
테스트 가독성이 매우 높네요 💯

2021-11-14 08:52 UTC, devyonghee commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +            list.get(index)
안녕하세요 재연님
어제 재연님과 dm으로 나눈 대화대로 `index` 컬럼을 제거하게 됐습니다 🔥
테스트가 코드를 보호해주고 있어서 마음 편하게 리팩토링이 된 것 같아요 ✅😆
생각보다 정렬하는 부분의 코드도 그리길지 않아 재연님께서 의도해주신게 어떤건지 알게된 것 같아요!!🤔

제가 고정관념이 있었던 것 같은데 깨닫게 해주셔서 감사합니다👍
많이 배워갑니다🙇‍♂️🙇‍♂️🙇‍♂️
혹시 변경된 코드에서 이상한 부분이 있는지 추가 리뷰도 부탁드리겠습니다!🙇‍♂️

2021-11-15 06:07 UTC, jaeyeonling approved these changes
마지막까지 미션 잘 진행해주셨습니다 👍 
수 많은 코멘트 반영하시느라 고생 많으셨어요 😄 
해당 요청은 머지하도록 하겠습니다 다음 미션도 화이팅입니다!!

2021-11-15 06:07 UTC, merged