Step2 지하철 노선 구간 조회
next-step/atdd-subway-admin pull request #39
Opened 2020-12-28 16:04 UTC by daeul-jeong

PR 보냅니다

2020-12-29 12:06 UTC, hongsii requested changes
2단계 요구사항 구현도 잘 해주셨네요!
몇 가지 피드백 남겼으니 참고하셔서 반영해주세요!

2020-12-29 12:06 UTC, hongsii commented on src/test/java/nextstep/subway/line/LineDistanceAcceptanceTest.java
> +		params.put("distance", distance);
REST-Assured는 직렬화도 지원하니 이를 고려해봐도 좋을 것 같아요 :)

- https://github.com/rest-assured/rest-assured/wiki/Usage#serialization

2020-12-29 13:38 UTC, daeul-jeong commented on src/main/java/nextstep/subway/line/domain/Line.java
> +    private List<Station> stationList;
네 복수형으로 짓는 습관을 들여야겠네요

2020-12-30 07:50 UTC, hongsii approved these changes
피드백 반영을 빠르게 잘 해주셨네요! 👍 
간단한 피드백 남겼으니 다음 단계에서 함께 반영해주세요~!

2020-12-30 07:50 UTC, hongsii commented on src/main/java/nextstep/subway/line/domain/Line.java
> +    public Line(String name, String color,int distance, List<Station> stationsList) {
여기도 바꾸면 좋을 것 같아요~!

2020-12-30 07:50 UTC, hongsii commented on src/test/java/nextstep/subway/line/LineDistanceAcceptanceTest.java
> +		assertThat(stationNames.equals(Arrays.asList(upStationName, downStationName))).isTrue();
assertj 에는 가독성을 높이기 위한 검증문을 많이 제공하니 이를 활용해봐도 좋을 것 같아요 :)

* https://github.com/assertj/assertj-examples/blob/main/assertions-examples/src/test/java/org/assertj/examples/IterableAssertionsExamples.java


검증문

```suggestion
		assertThat(stationNames).containsExactly(upStationName, downStationName);
```

혹은 검증 데이터 추출 및 검증

```suggestion
		assertThat(lineResponse.getStations())
		.extracting(Station::getName)
		.containsExactly(upStationName, downStationName);
```

2020-12-30 07:50 UTC, merged

2021-01-01 12:15 UTC, daeul-jeong commented on src/main/java/nextstep/subway/line/domain/Line.java
> +    public Line(String name, String color,int distance, List<Station> stationsList) {
넹👌🏻

2021-01-01 12:15 UTC, daeul-jeong commented on src/test/java/nextstep/subway/line/LineDistanceAcceptanceTest.java
> +		assertThat(stationNames.equals(Arrays.asList(upStationName, downStationName))).isTrue();
저런 함수도 있었네요 감삼다