[STEP3] 지하철 노선에 구간 등록
next-step/atdd-subway-admin pull request #40
Opened 2020-12-28 18:46 UTC by hhlyn0328

- 구간 등록을 위해서 기존에 List<Section> 이던 부분을 LineSections라는 일급컬렉션으로 변경해봤습니다
- 지난번 피드백 주셨던 노선 등록 시, 종점역을 각각 findById 하던 부분 수정해봤는데 이 얘기를 하셨던게 맞을지 모르겠네요 ㅎㅎ
   jpaRepository.findByIdIn 으로 학습테스트를 진행해보니 정렬을 입력한 아이디 리스트대로 주지 않아서 별도로 다시 뽑아내야하더라구요.. 
   querydsl이나 nativequery에 대한 이야기셨다면 힌트만 조금 주시면 어디 메모해뒀다가 다음에 더 살펴보겠습니다 😄 
- JPA 쓰면서 매핑시에도 최대한 객체로 가져가려고 했었는데 이 때문에 상행역/하행역 비교로직에서 생각해야되는 부분이 많았네요
 그래서 Section 객체의 참조 데이터들을 다 ID 로 변경해버릴까 하다가 우선은 그냥 진행했습니다 

피드백 주시면 또 고민해보겠습니다
감사합니다 :)

2020-12-29 06:53 UTC, young891221 requested changes
안녕하세요, 혜린님!
3단계 미션 반영이 잘 되어 있네요 👍 
몇 가지 개선할 코멘트 드렸습니다. 확인 부탁드립니다:)

2020-12-29 06:53 UTC, young891221 commented on src/main/java/nextstep/subway/line/application/LineService.java
> +        Station downStation = findOneStationById(stations, request.getDownStationId());
우선 이렇게 처리하는게 맞습니다ㅎㅎ
in절의 순서를 일관되게 가져가려면 `order by`를 주어서 처리할 수도 있습니다.
지금처럼 루프를 돌더라도 O(2)만큼만 도는게 무조건 보장되기에 크게 영향이 없네요.

2020-12-29 06:53 UTC, young891221 commented on src/test/java/nextstep/subway/line/SectionAcceptanceTestResponse.java
> +		assertThat(resultStationIds).containsAll(expectedStationIds);
id 순서비교와 함께 distance까지 올바르게 들어갔는지 비교가 필요해 보입니다.

2020-12-29 06:53 UTC, young891221 commented on src/main/java/nextstep/subway/line/dto/SectionRequest.java
> +	public SectionRequest() {
private or protected

2020-12-29 06:53 UTC, young891221 commented on src/main/java/nextstep/subway/line/ui/LineController.java
> +    @ExceptionHandler(IllegalArgumentException.class)
`IllegalArgumentException` 이외의 디폴트 예외처리가 필요해 보입니다. 이때는 status를 500으로 처리해야 될 것 같습니다.

2020-12-29 06:53 UTC, young891221 commented on src/main/java/nextstep/subway/section/domain/Section.java
> +		return origin.getId().equals(target.getId());
Station.java에서 equals(), hashcode()를 구현하면 아이디로만 비교하지말고 객체 비교가 가능해 보입니다.

2020-12-29 06:53 UTC, young891221 commented on src/test/java/nextstep/subway/line/SectionAcceptanceTest.java
> +public class SectionAcceptanceTest extends AcceptanceTest {
테스트 구성 잘 해주셨네요 💯 
보기 편합니다ㅎ

2020-12-29 06:53 UTC, young891221 commented on src/main/java/nextstep/subway/line/domain/LineSections.java
> +        return result;
sections에 `@OrderBy`을 사용하면 단순해지지 않을까 생각됩니다.

2020-12-29 06:53 UTC, young891221 commented on src/main/java/nextstep/subway/line/application/LineService.java
> +        Station station = findNullableStationById(sectionRequest.getDownStationId());
잘못된 값으로 인해 2개 모두 null을 반환할 때의 예외가 필요해 보입니다.

2020-12-29 06:53 UTC, young891221 commented on src/main/java/nextstep/subway/line/application/LineService.java
> +            return null;
null을 반환하기보다는 Optional<Station>으로 처리하는게 좀 더 깔끔해 보이네요.

2020-12-29 17:02 UTC, hhlyn0328 commented on src/main/java/nextstep/subway/line/domain/LineSections.java
> +        return result;
이 부분은 @OrderBy를 어떻게 활용할 수 있을지 감이 안옵니다 ㅠㅠ 
중간 구간을 추가했을 때, DB 상에서는 더 나중에 등록되고 있어서 어떤 값을 기준으로 정렬할 수 있는지 모르겠어요.. 
구간 추가시에 기존 구간을 다지우고 재등록 해야할까요? ㅠㅠ

2020-12-29 17:04 UTC, hhlyn0328 commented on src/main/java/nextstep/subway/line/ui/LineController.java
> +    @ExceptionHandler(IllegalArgumentException.class)
`IllegalArgumentException` 를 포함한 RuntimeException Handler로 변경하고 
에러메세지를 body 에 담아 넘기도록 했습니다 
인수테스트 로직에서 어떤 이슈가 발생했는지 로그에 잘 보이지 않았었는데 이리하니 잘 보이네요 
이 부분이 맞는 방향일까요?

2020-12-30 00:54 UTC, young891221 commented on src/main/java/nextstep/subway/line/ui/LineController.java
> +    @ExceptionHandler(IllegalArgumentException.class)
제가 의도한 부분은 IllegalArgumentException 핸들러는 그대로 두고 RuntimeException을 핸들링하는 놈을 추가하는 방향이였습니다.
IllegalArgumentException은 현재와 같이 올바르지 않은 파라미터로 400으로 나가고 로직내의 오류는 500으로 처리하는 방향이 맞습니다ㅎ

2020-12-30 01:09 UTC, young891221 commented on src/main/java/nextstep/subway/line/domain/LineSections.java
> +        return result;
음...생각해 보니 조금 복잡할 수 있겠군요. 두 가지 방식이 있을것 같습니다.
1. Section에 order필드를 추가해 순서 개념을 적용한다. 좋지 않은 방식일것 같습니다. 중간에 순서가 변경되면 나머지도 모두 변경되야 하기에...
2. 현재는 pre만 등록하는데 next도 등록한다. 링크드리스트와 동일한 개념이 됩니다. 근데 프로시져 쿼리를 사용해야 될 것 같네요ㅠㅠ

현재와 같은 방식이 최선일것 같네요ㅎㅎ;;

2020-12-30 01:09 UTC, young891221 requested changes
리뷰 반영 감사합니다ㅎㅎ
에러 핸들링에 대한 부분만 추가 수정하고 머지하겠습니다. 확인 부탁드려요~!

2020-12-30 01:55 UTC, hhlyn0328 commented on src/main/java/nextstep/subway/line/ui/LineController.java
> +    @ExceptionHandler(IllegalArgumentException.class)
앗! ㅋㅋ 넵 다시 살려두고 테스트도 변경하겠습니다

2020-12-30 01:56 UTC, hhlyn0328 commented on src/main/java/nextstep/subway/line/domain/LineSections.java
> +        return result;
😨  넵 좋지 않은 방법일 수는 있지만 위처럼 2가지가 있을 수 있다는 것 담아두겠습니다

2020-12-30 10:13 UTC, young891221 approved these changes
열렬한 리뷰 반영 감사합니다ㅎㅎ
머지하겠습니다. 다음 단계 진행해 주세요~!

2020-12-30 10:13 UTC, merged