1단계 - 지하철 노선 관리
next-step/atdd-subway-admin pull request #410
Opened 2021-11-19 13:05 UTC by doyoung0205

안녕하세요 ! 3주차 첫번째  미션 구현하여 PR 요청 드립니다.
사방 팔방으로 팩트로 뼈때려주시면 제대로 맞겠습니다.
감사합니다.

2021-11-20 05:41 UTC, na-mul requested changes
안녕하세요 도영님! 
인수 테스트 주도 개발 단계를 함께하게 될 노동환입니다.
노력이 듬뿍 들어간 코드를 올려주신 점 감사드립니다 🙇‍♂️
몇가지 코멘트를 달아보았으니 검토해주셔서 다시 Request 올려주세요!

2021-11-20 05:41 UTC, na-mul commented on src/main/java/nextstep/subway/common/ExceptionAdvice.java
> +@RestController
`ControllerAdvice`는 `Controller`가 아니므로,

`@Controller` + `@ResponseBody`인 `@RestController` 보다는 
단순히 `@ControllerAdvice` + `@ResponseBody`로 적는 것이 나을 것입니다.

`@RestControllerAdvice`로 줄여 쓸 수도 있으니 참고해주세요!🙇‍♂️

2021-11-20 05:41 UTC, na-mul commented on src/main/java/nextstep/subway/line/application/LineService.java
> +    @Transactional(propagation = Propagation.REQUIRES_NEW)
트렌젝션 격리 수준을 특별하게 지정해주신 것은 좋은 연습으로 보입니다!
자꾸 써봐야 지식도 늘어나니까요.

다만 본 메소드가 `Propagation.REQUIRES_NEW`로 지정되야 하는 특별한 이유는 없어보입니다.
혹시 제가 놓친 부분이 있을까요?

2021-11-20 05:41 UTC, na-mul commented on src/main/java/nextstep/subway/line/application/LineService.java
> +        lineRepository.flush();
트렌젝션이 종료되면 자동으로 flush가 호출될 것입니다. 미리 호출할 이유는 없어보여요!
특별한 이유가 있는 것이 아니라면 제거를 부탁드립니다.

2021-11-20 05:41 UTC, na-mul commented on src/main/java/nextstep/subway/line/application/LineService.java
> +        validateExistsByName(request.getName());
name이 unique 조건이 걸려있음에도, 이름 중복 체크를 해주신 분은 거의 없는데 말이죠.
이건 정말 잘 해주신 것 같습니다 👍

이름의 중복을 체크하는 것은 정말 도메인 레벨에서 하고 싶은 일이지만, 
아무래도 DB를 한번 조회해야 하기에 `Service`에 있을 수 밖에 없겠죠...

이 로직을 넣으시면서 그런 고뇌도 해보셨을 것으로 보여요! 
스스로 난이도를 높이는 좋은 공부방법이라 생각합니다. 🙇‍♂️

2021-11-20 05:41 UTC, na-mul commented on src/main/java/nextstep/subway/line/application/LineService.java
> +    }
select 문을 한번 감싸서 delete를 하게 되면 최종적으로 select문이 두번 발생하게 됩니다.
deleteById 내부적으로 select문이 존재하기 때문이지요.

deleteById에서 select 대상이 없으면 예외가 발생하는데요,
요 에러를 캐치해서 `NotFoundLineByIdException`를 발생시키는 방향으로 한다면,
최종적으로 발생하는 select쿼리를 한번으로 줄일 수 있을 것입니다.

2021-11-20 05:41 UTC, na-mul commented on src/main/java/nextstep/subway/line/domain/Line.java
> +@Table(indexes = @Index(name = "line_name_index", columnList = "name"))
name은 이미 유니크 키이기에 따로 인덱스를 추가하지 않아도 될 것으로 보입니다. 
유니크 키는 다른 말로 유니크 인덱스라고도 불려요! 
그러므로 이 부분의 index 정의는 생략해주셔도 좋을 것 같아요. 🙇‍♂️

2021-11-20 05:41 UTC, na-mul commented on src/main/java/nextstep/subway/line/dto/LineResponse.java
> +    }
각 필드들 자신의 equals와 hashCode 함수를 다시 호출하여, 꼼꼼하게 재정의해주셨군요!

참고로 말씀드리면 null일 것을 고려해서 if문을 넣어주시지 않으셔도 `Objects.equals(id, that.id)` 등을 사용해주시면 내부적으로 null 체크까지 포함한 결과를 알려주게 됩니다.

또한 작성해주신 hashCode도 Objects.hash와 동일한 로직으로 보입니다.
`Objects.hash(id, name, createdDate, modifiedDate)`로 간단하게 줄일 수 있어보여요! 🙏

그리고 이렇게 재정의해주실 때도 가급적이면 자바 코드 컨벤션을 지켜주시면 감사하겠습니다 🙇‍♂️

그리고 가장 중요한 것은, 혹시 이 객체만 꼼꼼하게 equals와 hashCode를 재정의해주신 이유가 있을까요?
Response 클래스는 보통 비즈니스 로직의 처리가 모두 끝난 내용을 담고 있기에, 
이를 사용하여 동일성을 비교하는 등의 로직 처리가 없는 경우가 대부분이라고 생각합니다.

2021-11-20 05:41 UTC, na-mul commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +    @MethodSource("blankStrings")
예외 케이스까지 인수테스트에 잘 녹여주셨군요!
작성에 너무 힘드시지 않으셨기를 바랄 뿐입니다. 😭

이렇게 꼼꼼한 인수테스트가, 그것도 재사용이 철저하게 고려된 리펙토링 하에 만들어져 있다면 정말 너무 좋을 것 같아요!!

다만 덕분에 인수테스트가 너무 작성하기 힘들고 어려운 일이 된다면, 아무래도 실무에 적용하기 점점 어려워지겠죠.
인수테스트는 무리하지 마시고 정상 케이스로 꼼꼼히 작성해주셔도 충분한 의미가 있습니다.
예외 상황은 단위테스트로도 어느정도 대응 가능하다고 생각합니다.

다시 한 번 말씀드리지만, 본 단계에서 정말 고생 많이 해주셨습니다! 인수 테스트에 대한 정성 👍 입니다.

2021-11-20 05:41 UTC, na-mul commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +    @MethodSource("blankStrings")
이 부분은 
```
    @NullAndEmptySource
    @ValueSource(strings = "   ")
```
로 대체하여 보면 어떠할까 건의드려봅니다.
`@MethodSource`는 정말 강력한 기능을 가졌지만, 그만큼 테스트 코드의 분석에 depth가 하나 더 추가되게 됩니다.
결과가 동일하다면, 조금 더 단순한 방법으로 찾아가는 것이 협업에 도움이 될 것이라 생각합니다.

2021-11-20 05:41 UTC, na-mul commented on src/test/java/nextstep/subway/line/LineAcceptanceVerify.java
> +public class LineAcceptanceVerify {
전반적으로 인수테스트의 리팩터링에 큰 힘을 쏟아주셔서 감사합니다! 👍

2021-11-21 06:21 UTC, doyoung0205 commented on src/main/java/nextstep/subway/line/application/LineService.java
> +    }
처음엔 `deleteById` 가 void 타입이라 어떻게 예외처리 할지 고민하다 `existsById` 로 분기처리를 하였지만, 
내부적으로 `EmptyResultDataAccessException` 을 예외처리하고 있었네요. 
말씀 주신 부분으로 에러를 캐치하는 방향으로 수정하였습니다.

2021-11-21 06:24 UTC, doyoung0205 commented on src/main/java/nextstep/subway/line/domain/Line.java
> +@Table(indexes = @Index(name = "line_name_index", columnList = "name"))
인덱스에 대해서 잘 몰랐는데 피드백 주셔서 감사합니다.
기본키, 유니크, 외래키 가 기본적으로 생성되나 보군요. 
지금은 일단 인수테스트에 매진하고 커리큘럼 뒤쪽에 인덱스에 대한 과정이 있으니 그때 더 열심히 공부하도록 하겠습니다 !

2021-11-21 06:27 UTC, doyoung0205 commented on src/main/java/nextstep/subway/line/dto/LineResponse.java
> +    }
테스트 코드 작성시 containsAll 메소드로 일치한지 확인하는 검증 단계가 있어서 재정의 하였습니다.

LineAcceptanceTest -> @DisplayName("지하철 노선 목록을 조회한다.") findAllLines

2021-11-21 06:28 UTC, doyoung0205 commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +    @MethodSource("blankStrings")
이런식으로 두개를 쓸 수 있는 방법을 배웠습니다. 감사합니다.

2021-11-21 06:29 UTC, doyoung0205 commented on src/main/java/nextstep/subway/common/ExceptionAdvice.java
> +@RestController
사용하지 않는 어노테이션도 포함되어있는 상황이였네요. 감사합니다 ! 반영하였습니다.

2021-11-21 06:31 UTC, doyoung0205 commented on src/main/java/nextstep/subway/line/application/LineService.java
> +    @Transactional(propagation = Propagation.REQUIRES_NEW)
맞습니다. 이번 코스에서 `Propagation` 를 처음 접하게 되었고 친해지고 싶어서 사용해보았습니다.
지금 상황에서는 굳이 필요 없을 것 같네요. 삭제 하도록 하겠습니다.
계속 트랜잭션 옵션을 생각하면서 미션을 진행하면서 필요하다고 생각할 때 사용하도록 하겠습니다 !

2021-11-21 06:32 UTC, doyoung0205 commented on src/main/java/nextstep/subway/line/application/LineService.java
> +        lineRepository.flush();
updateLine 메소드의 결과에는 변경된 시간을 전달하는 DTO 가 반환 됩니다.
flush 를 하지 않았을 경우, 변경된 시간을 DTO 의 담을 수 가 없다고 판단하여 사용하였습니다.

2021-11-21 06:33 UTC, doyoung0205 commented on src/main/java/nextstep/subway/line/application/LineService.java
> +        validateExistsByName(request.getName());
감사합니다 !

2021-11-21 06:35 UTC, doyoung0205 commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +    @MethodSource("blankStrings")
인수테스트가 끝과 끝의 접점이 되는 테스트 라고 생각합니다.
서비스 동작과 관련하여 마음이 불편하지 않고 심리적 안정감을 찾기위해서 
여러 시나리오의 대한 테스트를 작성해보았습니다.

2021-11-21 06:35 UTC, doyoung0205 commented on src/test/java/nextstep/subway/line/LineAcceptanceVerify.java
> +public class LineAcceptanceVerify {
감사합니다 !!

2021-11-21 06:36 UTC, doyoung0205 commented on README.md
> +## 사용자 스토리
감사합니다 ! 
혼자서 하는게 아니라 팀원 들이랑 같이 테스트 가능한 요구사항을 작성한다는 생각으로 작성하고 있습니다 !

2021-11-21 06:37 UTC, doyoung0205 commented
전반적으로 칭찬을 많이 해주셔서 너무 기분이 좋습니다. 
제가 어깨가 ㄷ자가 될 수 있으니 사방 팔방으로 팩트로 뼈때려주시면 정신차리고 더 열심히 하겠습니다.

2021-11-21 07:41 UTC, na-mul approved these changes
안녕하세요, 도영님.
남겨드린 코멘트에 대해 의견도 잘 정리해주시고, 코드 수정도 꼼꼼히 잘 해주셨습니다. 👍
이제 다음 단계부터 본격적으로 API 변경에 대응하게 되네요.
인수 테스트 작성에 큰 힘을 쏟아주신 것이, 다음 단계를 거침없이 진행하는 데 도움이 되길 바랍니다! 🙏

2021-11-21 07:41 UTC, na-mul commented on src/test/java/nextstep/subway/line/LineAcceptanceVerify.java
> +        assertThat(responseJsonPath.getList("color", String.class)).containsAll(colors);
jsonPath도 잘 활용해주셨군요! 인수테스트 연습 단계인 만큼, `restassured`의 다양한 기능들에 대해 잘 연습해주신 점 칭찬드립니다 👍

2021-11-21 07:41 UTC, merged