1단계 - 지하철 노선 관리 코드리뷰 요청합니다.
next-step/atdd-subway-admin pull request #439
Opened 2021-11-21 17:18 UTC by wookeeeeeee

안녕하세요.
리뷰어님 반갑습니다!

나름 리팩토링 해본다고 해봤는데, 부족한 점이 많을 것 같습니다.

잘부탁드립니다! 😄

2021-11-22 10:26 UTC, minsungryu requested changes
태욱님 안녕하세요, ATDD 미션 함께 진행하게 되었네요.
몇 가지 피드백을 남겼는데 확인해주시면 좋을 것 같습니다 :)
잘 부탁드립니다.

2021-11-22 10:26 UTC, minsungryu commented on src/main/java/nextstep/subway/line/application/LineService.java
> +    public LineResponses findAllLines() {
조회 메서드의 경우 `@Transactional(readOnly = true)`를 선언하는 것은 어떨까요?

2021-11-22 10:26 UTC, minsungryu commented on src/main/java/nextstep/subway/line/dto/LineResponses.java
> +        return Collections.unmodifiableList(lineResponses);
일급 컬렉션의 불변성을 보장하기 위해 방어적 복사를 해주셨군요 👍

2021-11-22 10:26 UTC, minsungryu commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +    Stream<DynamicTest> 지하철_노선_시나리오() {
덕분에 `DynamicTest`에 대해서 처음 알게 되었네요 감사합니다 :)
다만 `DynamicTest`가 `LineAcceptanceTest`에 적합한 상황인지는 잘 모르겠습니다.
어떤 의도로 `DynamicTest`를 작성해주신건지 설명해주실 수 있을까요?

2021-11-22 10:26 UTC, minsungryu commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +    public static final Map<String, Object> CREATE_LINE_FIXTURE = new HashMap<String, Object>() {{
테스트 클래스에서는 크게 관련없는 얘기일 수는 있지만 DBI는 권장되지 않는 방식이라고 하니 참고하시면 좋을 것 같습니다.
https://rules.sonarsource.com/java/RSPEC-3599

2021-11-22 10:26 UTC, minsungryu commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +        final HashMap<String, Object> params = new HashMap<String, Object>() {{
별도로 요청 Dto 객체를 선언하면 어떨까요?

2021-11-22 10:26 UTC, minsungryu commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
`RestAssured`를 통해 요청을 보내는 부분이 반복되는데 이를 리팩터링해볼 수 있을까요?
그리고 요구사항이 좀 더 명확히 드러나도록 메서드를 추출해서 인수 테스트를 개선해볼 수 있을 것 같습니다.

2021-11-22 10:26 UTC, minsungryu commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
테스트 픽스처 설치 관련해서는 여러가지 방법이 있겠지만 각각의 장단점을 살펴보는 것도 좋을 것 같습니다.

- https://jojoldu.tistory.com/611?category=1011740
- https://jobjava00.github.io/book/xunit/08/
- https://jobjava00.github.io/book/xunit/09/

2021-11-22 10:27 UTC, wookeeeeeee commented on src/main/java/nextstep/subway/line/application/LineService.java
> +    public LineResponses findAllLines() {
`@Transactional(readOnly = true)`

선언함으로서 오는 성능 이득은 사실 크게 없다는 것으로 알고있는데,

혹시 명시성 때문에 그런것일까요?

2021-11-22 10:31 UTC, wookeeeeeee commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +    Stream<DynamicTest> 지하철_노선_시나리오() {
인수테스트는 시나리오를 확인하는 과정이라고 생각해서,

지하철 노선 생성 => 목록 조회 => 노선 하나 조회 => 노선 수정 => 노선 삭제

까지 한 흐름으로 이뤄질 수 있는 시퀀스라고 생각을 해서 `DynamicTest` 로 작성을 했습니다.

2021-11-22 10:34 UTC, wookeeeeeee commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +        final ExtractableResponse<Response> createResponse2 = createLine(params);
`anotherCreateResponse` 로 변경하도록 하겠습니다!

2021-11-22 10:38 UTC, wookeeeeeee commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +    public static final Map<String, Object> CREATE_LINE_FIXTURE = new HashMap<String, Object>() {{
좋은 자료감사합니다!
아래 리뷰주신 내용과 더불어서 Dto 객체로 변경하도록 하겠습니다.

2021-11-22 10:38 UTC, wookeeeeeee commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +        final HashMap<String, Object> params = new HashMap<String, Object>() {{
`Dto` 객체로 변경하도록 하겠습니다.

지금 보니 `Map`도 아니고 `HashMap`으로 해놨네요

2021-11-22 10:40 UTC, wookeeeeeee commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
리팩터링하려면 제 생각에 단순히 메서드로 빼기 보다는
`RestAssured` 를 래핑해서 given when then 을 delegate 해야하지 않을까 라는 생각이 드는데

이 부분은 어떻게 생각하시는지 궁금합니다.

2021-11-22 10:44 UTC, wookeeeeeee commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
자료감사합니다!
고민했던 부분이나 문제점이라고 생각했었던 부분들이 잘 나와있어서 많은 도움이 되었습니다.

2021-11-22 15:42 UTC, minsungryu approved these changes
태욱님, ATDD 1단계 구현하시느라 고생하셨습니다.
추가적인 코멘트를 남겼는데요
확인해주시고 다음 단계에서 반영해주시면 좋을 것 같습니다.

2021-11-22 15:42 UTC, minsungryu commented on src/test/java/nextstep/subway/RestAssuredDelegator.java
> +        return this;
체이닝 없이 바로 `response`를 반환해도 될 것 같은데 이유가 있으신걸까요?
실수로 다른 메서드를 호출해서 response 상태가 바뀔 염려도 있어보입니다.

패턴을 사용하기보단 메서드 추출만으로도 적절히 추상화해도 되지 않을까 생각이 드네요.
그리고 이를 감싸서 인수 테스트를 조금 더 고객의 요구사항을 잘 설명할 수 있도록 표현해보면 좋을 것 같습니다.

2021-11-22 15:42 UTC, minsungryu commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
이런 부분들을 앞서 추상화된 메서드를 활용해서 요구사항이 명확히 드러나게 표현해주면 더 좋을 것 같습니다.

2021-11-22 15:42 UTC, minsungryu commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +    Stream<DynamicTest> 지하철_노선_시나리오() {
말씀하신 테스트의 순서가 `DynamicTest`를 사용하는데 적합한 근거라고 느껴지지가 않는데요

요구사항이 변경된다면 어떤 테스트 사이에 새로운 테스트를 추가해야할까요?
지금은 코드 베이스가 적어서 바로 보일 수는 있지만 점점 더 힘들어질텐데 유지보수에 좋지 않을 것 같습니다.

만약 말씀하신 테스트 순서가 중요하다면 데이터가 생성되지 않은 경우 삭제 테스트가 실패할 수 있는데
이는 테스트 간 독립성을 보장하지 못해 좋지 않은 방법이라고 생각이 드네요.

제가 이해하기로는 `DynamicTest`는 `ParameterizedTest`를 대체할 수 있는 수단으로써 의미가 있는 것 같습니다.
만약 순서를 지정하고 싶은 경우는 몇 가지 다른 방법이 있으니 알아보셔도 좋을 것 같습니다.

2021-11-22 15:42 UTC, minsungryu commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
일단은 메서드를 빼보는 것부터 시작해보면 어떨까요?
작은 부분부터 점진적으로 설계를 개선해보면 좋을 것 같습니다.
좋은 일반화는 의도에 의해 발명되지 않고 경험에 의해 발견된다는 말이 떠오르네요.

2021-11-22 15:42 UTC, merged

2021-11-23 03:55 UTC, wookeeeeeee commented on src/test/java/nextstep/subway/line/LineFixture.java
> +public class LineFixture {
해당 내용은 2단계 내용인지는 모르고 포함시켰습니다 ㅠ
프론트엔드 소스 돌리고 노선등록하는걸 요청해봤는데 해당 내용들도 요청 보내도록 `name`, `color` 외의 값도 요청 보내게 되어있더라구요 실제 소스에 되어있지 않더라도 인수테스트에 필요한 부분 이라고 생각해서 따로 분리해서 만들었습니다.

기획 의도대로 되어있지 않은 상태라는 판단이었습니다.

2단계에 반영되는 내용이라면, 굳이 `LineFixture` 라는게 필요 없을 것같습니다.

2단계 진행할 때 변경하도록 하겠습니다!

2021-11-23 03:58 UTC, wookeeeeeee commented on src/test/java/nextstep/subway/RestAssuredDelegator.java
> +        return this;
체이닝 한 이유는 위임객체에게 마지막 then 까지 수행할수있도록 역할을 위임 하기 위함이었습니다.

말씀대로 `노선_목록조회`, `노선_조회`, `노선_생성` 등과 같은 이름으로 의미있게 메서드 분리하는 방향으로 변경하겠습니다!