2단계 - 인수 테스트 리팩터링
next-step/atdd-subway-admin pull request #452
Opened 2021-11-22 16:26 UTC by ryu-sh

안녕하세요 민성님!
이번 미션을 하면서 이전에 피드백 주신 무엇을 하려는지 설명을 했으면 좋겠다고 하셔서 테스트를 리팩터링 하였습니다.
아직 atdd가 익숙하지 않아서 제대로 한건지는 잘 모르겠습니다😭
리뷰 잘 부탁드립니다!

2021-11-23 10:54 UTC, minsungryu requested changes
성호님 ATDD 2단계 멋지게 구현해주셨군요!
나날이 코드가 발전하는 것 같습니다 👍 
몇 가지 코멘트를 남겼는데요
확인해주시고 다시 리뷰 요청 주시면 좋을 것 같습니다 :)

2021-11-23 10:54 UTC, minsungryu commented on src/main/java/nextstep/subway/line/domain/Line.java
> +    public void addSection(Section section) {
양방향 매핑을 해주셨군요
`section`이 이미 다른 `line`에 연결되어 있는 경우 어떻게 될까요?
객체 그래프에 대해 한 번 더 고민해보시면 좋을 것 같습니다.

2021-11-23 10:54 UTC, minsungryu commented on src/main/java/nextstep/subway/line/domain/Line.java
> +    public List<StationResponse> getStationResponse() {
엔티티가 외부 응답 구조에 대해 알고 있는 것이 좋을까요?
의존성 방향은 항상 저수준에서 고수준으로
구체적인 것에서 추상적인 것으로 향해야 합니다.

DIP와 SDP에 대해 공부해보시면 좋을 것 같습니다!

2021-11-23 10:54 UTC, minsungryu commented on src/main/java/nextstep/subway/line/dto/LineRequest.java
> +    public Line toLine(Station upStation, Station downStation) {
DTO가 엔티티에 대해 알고 있는 것보다는 별도 레이어에서 변환 과정을 추가해보는 것은 어떨까요?

2021-11-23 10:54 UTC, minsungryu commented on src/main/java/nextstep/subway/line/dto/LineResponse.java
> +    private List<StationResponse> stations = new ArrayList<>();
이런 부분은 일급 컬렉션으로 구현해보면 어떨까요?

2021-11-23 10:54 UTC, minsungryu commented on src/main/java/nextstep/subway/section/domain/Section.java
> +        this.line = line;
양방향 관계에서 `line`을 변경해주는 경우 기존 `line`과의 관계를 끊어주는 과정도 필요하지 않을까요?

2021-11-23 10:54 UTC, minsungryu commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +    private ExtractableResponse<Response> 지하철_노선_수정_요청(LineResponse savedLineResponse) {
메서드가 `id`, `name`, `color`를 받으면 재사용이 더 쉽지 않을까요?

2021-11-23 10:54 UTC, minsungryu commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +    private ExtractableResponse<Response> 지하철_노선_종점역_추가하여_생성_요청(Long stationId1, Long stationId2) {
메서드 인자의 이름이 1, 2로 끝나기 보다는
상행선과 하행선임을 표현해주는 이름은 어떨까요?

2021-11-23 10:54 UTC, minsungryu commented on src/test/java/nextstep/subway/station/TestStationFactory.java
> +    public static StationResponse 역_미리_생성(String name) {
지하철역을 생성하는 행위를 할 뿐인데 미리 생성한다는 표현이 저한테는 다소 어색하게 느껴지는데요,
나중에 생성하는 경우도 있는걸까요?

2021-11-23 10:54 UTC, minsungryu commented on src/test/java/nextstep/subway/utils/TestPostRequestFactory.java
> +public class TestPostRequestFactory {
`TestGetRequestFactory`와 합치면 중복 코드를 제거할 수 있을 것 같은데 어떻게 생각하시나요?

2021-11-25 17:59 UTC, ryu-sh commented on src/main/java/nextstep/subway/line/dto/LineResponse.java
> +    private List<StationResponse> stations = new ArrayList<>();
요구사항에서 response 값이 List로 나와있어서 list로 했습니다. 일급컬렉션으로 수정하고 테스트 해봤는데 객체안의 리스트가 담겨서 요구사항의 response와 달랐습니다.

2021-11-25 18:01 UTC, ryu-sh commented
안녕하세요 민성님!
의존성에 대해서 잘 몰랐었는데 이번 기회를 통해 알게 되었습니다  피드백 감사드립니다! 
다만 제가 피드백을 이해하고 잘 수정했는지는 자신이 없습니다 ㅠㅠ
리뷰 잘 부탁드립니다! 😊

2021-11-26 05:41 UTC, minsungryu approved these changes
성호님 2단계도 잘 구현해주신 것 같습니다 👍 
추가로 남긴 코멘트는 확인해주시고
다음 단계 진행하실 때 고려해보셔도 좋을 것 같습니다 :)
PR은 merge 하겠습니다~

2021-11-26 05:41 UTC, minsungryu commented on src/main/java/nextstep/subway/line/domain/Line.java
> +        section.setLine(this);
만약 기존에 존재하는 `section`을 다시 추가한다면 동일한 `section`이 중복되어 나타날텐데 괜찮을까요?
그리고 기존에 `line`이 있는지 검사해서 객체 그래프를 제거해주는게 좋지 않을까요?

2021-11-26 05:41 UTC, minsungryu commented on src/main/java/nextstep/subway/line/dto/LineResponse.java
> +    private List<StationResponse> stations = new ArrayList<>();
아 그렇군요~
그런 경우는 아래처럼 일급컬렉션 내부 데이터를 반환하도록 만들어볼 수도 있을 것 같다는 생각이 드네요 :)
```java
public List<StationResponse> getStations() {
    return stations.getAsList();
}
```

2021-11-26 05:41 UTC, minsungryu commented on src/main/java/nextstep/subway/section/domain/Section.java
> +    private int distance;
기회가 된다면 값 객체로 만들어 보는 것도 연습에 도움이 될 것 같습니다!

2021-11-26 05:41 UTC, minsungryu commented on src/main/java/nextstep/subway/section/domain/Section.java
> +        this.line = line;
`line`의 `addSection`을 호출하지 않으면 객체 그래프가 DB 상태와 불일치할 가능성이 있지 않을까요?
참고로 이런 양방향 연관 관계 편의 메서드는 무한 루프가 일어나지 않도록 신경도 써주셔야 해요!

2021-11-26 05:41 UTC, minsungryu commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +        지하철_노선_수정됨(savedLineResponse, response);
이 메서드만으로는 지하철 노선이 어떻게 수정되어서 테스트를 만족시키는지 알기 어려운 것 같습니다.
기대값을 적절히 하드코딩해서 의도를 표현해주는 것은 어떨까요?
아래 포스트가 도움이 될 것 같습니다.
https://jojoldu.tistory.com/615?category=1036934

2021-11-26 05:41 UTC, minsungryu commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +    private void 지하철_노선_생성_실패됨(ExtractableResponse<Response> response) {
어떤 오류 메시지를 반환하는지도 검증하도록 만들면 테스트를 이해하는데 도움이 되지 않을까요?

2021-11-26 05:41 UTC, minsungryu commented on src/test/java/nextstep/subway/utils/TestRequestFactory.java
> +        if (httpMethod.equals(HttpMethod.GET)) {
조건문 비교는 상수를 앞에 두는 것이 더 Null safety하지 않을까요?

2021-11-26 05:41 UTC, merged

2021-11-26 05:42 UTC, minsungryu commented
> 안녕하세요 민성님! 의존성에 대해서 잘 몰랐었는데 이번 기회를 통해 알게 되었습니다 피드백 감사드립니다! 다만 제가 피드백을 이해하고 잘 수정했는지는 자신이 없습니다 ㅠㅠ 리뷰 잘 부탁드립니다! 😊

너무 잘 하고 계십니다! 자신감을 가지세요 😄 
저도 제가 가진 지식과 경험을 기반으로 제안을 드리는 것이고
성호님이 뭔가 잘 몰라서 바꿔야한다는 것은 아니니
오히려 적극적으로 의견주시고 같이 성장해나가면 좋을 것 같습니다 :)