Step3 pr
next-step/atdd-subway-admin pull request #46
Opened 2020-12-29 14:54 UTC by louisJu

안녕하세요. 주환석입니다.
3단계 구간등록 미션 pr 요청드립니다.
이번 단계에서 등록 및 validation check 부분 관련해서 많은 피드백 부탁드리겠습니다.
좀 더 깔끔하게 코드 작성이 가능할 것 같아 보이는데... 이게 최선일지 약간 의문이 들어서요... 

미리 감사드립니다! :)

2020-12-30 07:43 UTC, hongsii requested changes
2단계 요구사항 구현도 잘 해주셨네요! 👍 
몇 가지 피드백 남겼으니 참고하셔서 반영해주세요 :)

2020-12-30 07:43 UTC, hongsii commented on src/main/java/nextstep/subway/line/application/LineService.java
> +        List<Section> sections = line.getSections();
구간 관리의 책임를 가진 일급 컬렉션을 추출해 구간과 관련된 비즈니스 로직을 위임해보면 어떨까요?

JPA를 사용할 때에는 객체지향스러운 코드를 작성하기 위해 데이터를 가진 객체에게 행위를 처리하도록 만드는 것이 좋습니다.
그렇기 때문에 가능하면 서비스는 DB에서 도메인 객체를 조회하고, 조회 혹은 생성한 도메인을 활용하도록 만들고, 상세한 비즈니스 로직 처리는 도메인에게 넘기면 좋을 것 같아요!

도움이 되실만한 링크를 같이 첨부합니다 :)

* https://archfirst.org/domain-driven-design-6-layered-architecture/
* https://www.slideshare.net/baejjae93/ss-151545329
* http://uniknow.github.io/AgileDev/site/0.1.8-SNAPSHOT/parent/ddd/core/layered_architecture.html

2020-12-30 07:43 UTC, hongsii commented on src/test/java/nextstep/subway/section/SectionAcceptanceTest.java
> +                        station1.getId() + "", station2.getId() + "",
메서드 인자를 String 전달하면 지금처럼 사용하는 곳마다 `+ ""` 를 붙여줘야 하는 불편함이 있지 않을까요?
메서드 인자로 Long으로 받아서 내부적으로 String 으로 변환하면 어떨까요?

2020-12-30 07:43 UTC, hongsii commented on src/test/java/nextstep/subway/section/SectionAcceptanceTest.java
> +    @DisplayName("노선에 구간을 등록한다.")
작성하신 테스트는 `새로운 역을 하행 종점으로 등록할 경우` 입니다.
아래의 요구사항도 정상적으로 동작하는지 테스트를 작성해보면 어떨까요?

* 역 사이에 새로운 역을 등록할 경우
* 새로운 역을 상행 종점으로 등록할 경우

2020-12-30 07:43 UTC, hongsii commented on src/main/java/nextstep/subway/section/domain/Section.java
> +        return false;
```suggestion
        return this.getStation().equals(newSection.getUpStation())
                || this.getStation().equals(newSection.getStation())
```

2020-12-30 07:43 UTC, hongsii commented on src/main/java/nextstep/subway/line/application/LineService.java
> +                newSection.setDistance(newSection.getDistance() - section.getDistance());
거리를 빼야하는 이유가 무엇일까요..? 의도가 명확히 드러나지 않아 이해하기 어렵네요 🤔

2020-12-30 08:14 UTC, louisJu commented on src/main/java/nextstep/subway/line/domain/Line.java
> +    public void setSections(Section section) {
아 ㅎㅎ 지금보니 저도 충분히 오해할만한....
변경하겠습니다~

2020-12-30 08:58 UTC, louisJu commented on src/main/java/nextstep/subway/line/application/LineService.java
> +                newSection.setDistance(newSection.getDistance() - section.getDistance());
기존에 등록된 구간의 distance를 새로 등록되는 distance와 비교해서 값을 변경해야 합니다. 
그래서 위와같은 - 계산이 들어갔는데... 어떻게 하면 좀 더 명확하게 보일 수 있을까요?

2020-12-30 16:48 UTC, louisJu commented
안녕하세요! 주환석입니다~
말씀하신 방향으로 코드 리펙토링을 진행해봤는데요! 
리뷰 부탁드립니다~
혹시 잘못된 부분이나 수정할 부분이 있다면 말씀 부탁드립니다!!
감사합니다~

2020-12-31 10:43 UTC, hongsii approved these changes
피드백 반영을 깔끔하게 잘 해주셨네요!
몇 가지 피드백 남겼으니, 다음 단계에서 함께 반영해주세요!

2020-12-31 10:43 UTC, hongsii commented on src/main/java/nextstep/subway/section/domain/Sections.java
> +        }
구간 길이는 `updateSection(...)` 에서 업데이트하기 전에 체크하면 반복횟수를 조금이나마 줄일 수 있지 않을까요?

2020-12-31 10:43 UTC, hongsii commented on src/main/java/nextstep/subway/section/domain/Sections.java
> +    public void updateSection(Section newSection) {
내부 로직을 각각 메서드로 추출해서 의미를 부여해보면 어떨까요?

2020-12-31 10:43 UTC, hongsii commented on src/test/java/nextstep/subway/section/SectionAcceptanceTest.java
> +    }
같은 case1인데 변수만 다르기 때문에 `@ParameterizedTest` 를 활용할 수 있지 않을까요?

2020-12-31 10:43 UTC, hongsii commented on src/main/java/nextstep/subway/line/application/LineService.java
> +                newSection.setDistance(newSection.getDistance() - section.getDistance());
앗.. 그렇네요.. 제가 그 요구사항을 놓쳤습니다.. ㅠㅠ
의미가 명확히 드러나지 않는다면 변수로 선언하거나, 메서드로 추출하면 이름을 통해 의미를 부여할 수 있습니다!

2020-12-31 10:44 UTC, merged

2020-12-31 14:32 UTC, louisJu commented on src/main/java/nextstep/subway/section/domain/Sections.java
> +        }
예외처리는 한 곳에서 하는게 가독성 측면에서 좋을 것 같아서 그렇게 처리했는데 말씀하신 것 처럼 반복횟수를 줄이는 방향으로 변경해보겠습니다!