Step1 - 지하철 노선 관리
next-step/atdd-subway-admin pull request #47
Opened 2020-12-29 17:32 UTC by PilhwanKim

미리 코드리뷰 감사드립니다.

요구사항

- 지하철 노선 관련 기능의 인수 테스트를 작성하기
- 지하철 노선 관련 기능 구현하기
- 인수 테스트 리팩터링

2020-12-30 10:12 UTC, young891221 requested changes
안녕하세요, 레온님
첫 번째 미션 인수 테스트 작성 잘 해주셨네요 👍 
몇 가지 간단한 코멘트들 드렸습니다. 확인 부탁드립니다:)

2020-12-30 10:12 UTC, young891221 commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +        Map<String, String> params1 = new HashMap<>();
조회 대상이 없을 때의 케이스도 추가되면 좋을것 같습니다.

2020-12-30 10:12 UTC, young891221 commented on src/main/java/nextstep/subway/line/application/LineService.java
> +        lineRepository.save(line);
영속된 상태라 save() 메서드 없이도 저장되지 않나요?ㅎㅎ

2020-12-30 10:12 UTC, young891221 commented on src/main/java/nextstep/subway/line/application/LineService.java
> +        lineRepository.deleteById(lineId);
대상이 없을때 삭제시 예외처리가 필요합니다. + 테스트 케이스

2020-12-30 10:12 UTC, young891221 commented on src/main/java/nextstep/subway/line/application/LineService.java
> +        return LineResponse.of(lineRepository.getOne(lineId));
여기도 대상이 없을때의 케이스 부탁드립니다.

2020-12-30 10:16 UTC, PilhwanKim commented on src/main/java/nextstep/subway/line/application/LineService.java
> +        lineRepository.save(line);
ㅎㅎㅎ Django ORM 은 무조건 save 해야해서, 동시에 같이 쓰니 헷갈리네요.

2020-12-30 10:20 UTC, PilhwanKim commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +        Map<String, String> params1 = new HashMap<>();
할까말까 고민이었는데 추가해서 올리겠습니다~

2020-12-30 10:23 UTC, PilhwanKim commented on src/main/java/nextstep/subway/common/GlobalExceptionHandler.java
> +public class GlobalExceptionHandler {
https://www.baeldung.com/exception-handling-for-rest-with-spring#2-defaulthandlerexceptionresolver

이 내용과 관련되어 있는 걸까요?

2020-12-31 09:39 UTC, young891221 approved these changes
리뷰 반영 잘 해주셨네요 💯 
머지하겠습니다. 다음 단계 진행해 주세요!

2020-12-31 09:39 UTC, merged