Step3 - 구간 추가 기능
next-step/atdd-subway-admin pull request #512
Opened 2021-11-27 20:33 UTC by lewisseo91

안녕하세요~
구간 추가 기능 완료 후 PR 보냅니다. 
리뷰 해 주셔서 감사합니다!

구간 추가 기능에서 이리저리 많이 헤매면서 커밋을 해서 
커밋 로그가 깔끔하지 않습니다. 죄송합니다!

---
### 느낀 점

처음 시도했던 것이 가장 앞 노드에 (null <- 상행 종점역) 삽입 방법이었고 
null의 무서움을 잘 깨닫고 선회하였습니다.

다음으로 시도했던 것은 ArrayList.add(index, Element)를 이용해서 순서를 찾아서 주입하는 방법이었고
add 후에 다시 get을 할 때는 id로 받아와서 제대로 된 결과를 볼 수 없었고,
이에 OrderColumn을 시도하였습니다. 그리고 log에서 n+1 이슈를 발견하였고

현재 시도한 방법은 ArrayList에 무조건 add로 넣은 후에 
변경해야 할 기존 구간의 역이 있다면 변경하는 방법입니다.
ListResponse로 받을 때에 첫 구간, 마지막 구간을 찾아서 iterate 하게 처리하는 방법을 선택하였습니다.

하지만 노선을 dto로 받을 때 마다 정렬을 해야 한다는 점이 비효율적인 것 같아서 고민 중에 
일단 PR보내게 되었습니다.

혹시 더 괜찮은 방법이 있다면 추천 해 주시면 감사하겠습니다!

2021-11-29 00:36 UTC, 5minho requested changes
안녕하세요 동현님!
3단계 구현 잘해주셨네요~
개선해보면 좋을점들을 코멘트로 남겼는데요
확인해주시면 감사하겠습니다!

2021-11-29 00:36 UTC, 5minho commented on src/main/java/nextstep/subway/station/dto/StationResponse.java
> +    private static List<StationResponse> getSortedStations(List<Section> sections) {
정렬 로직을 DTO 에 작성해주신 이유가 있을까요?
제 생각에는 상-하행 순으로 역을 정렬하는 로직은 핵심 비즈니스 로직이라 도메인에 위치해서 단위 테스트로 보호 받아야 한다고 생각해요.

2021-11-29 00:36 UTC, 5minho commented on src/test/java/nextstep/subway/line/domain/LineColorTest.java
> +
색 값은 빈값이 될 수 없다. 이런 테스트도 작성해보면 어떨까요?

2021-11-29 00:42 UTC, 5minho commented
> ### 느낀 점
> 처음 시도했던 것이 가장 앞 노드에 (null <- 상행 종점역) 삽입 방법이었고 null의 무서움을 잘 깨닫고 선회하였습니다.
> 
> 다음으로 시도했던 것은 ArrayList.add(index, Element)를 이용해서 순서를 찾아서 주입하는 방법이었고 add 후에 다시 get을 할 때는 id로 받아와서 제대로 된 결과를 볼 수 없었고, 이에 OrderColumn을 시도하였습니다. 그리고 log에서 n+1 이슈를 발견하였고
> 
> 현재 시도한 방법은 ArrayList에 무조건 add로 넣은 후에 변경해야 할 기존 구간의 역이 있다면 변경하는 방법입니다. ListResponse로 받을 때에 첫 구간, 마지막 구간을 찾아서 iterate 하게 처리하는 방법을 선택하였습니다.
> 
> 하지만 노선을 dto로 받을 때 마다 정렬을 해야 한다는 점이 비효율적인 것 같아서 고민 중에 일단 PR보내게 되었습니다.
> 
> 혹시 더 괜찮은 방법이 있다면 추천 해 주시면 감사하겠습니다!

저는 이 방식이 복잡하지 않고 쉽게 파악이 가능해서 좋다고 생각해요👍
지하철 노선과 역들은 잘 바뀌지 않는 데이터이기 때문에 동현님께서 생각하시는 비효율적인 부분은 추후 캐시로 개선이 가능할거 같아요

2021-11-29 00:52 UTC, lewisseo91 commented on src/main/java/nextstep/subway/line/dto/LineRequest.java
> +        return Line.of(getName(), getColor(), upStation, downStation, distance);
dto의 값을 입력할 때 string으로 받을 지 값 객체로 받을 지 생각하다가 
이도저도 아닌 상태로 놔두고 있었네요.

바꿨다가 다시 넣었다가 하는 이상한 작업을 수행하고 있었습니다.

이 부분은 LineRequest에는 String으로 받도록 수정하겠습니다~!

2021-11-29 00:52 UTC, lewisseo91 commented on src/test/java/nextstep/subway/line/domain/LineColorTest.java
> +
empty는 생각하지 못한 부분입니다!
피드백 감사합니다~!

2021-11-29 00:57 UTC, lewisseo91 commented on src/main/java/nextstep/subway/station/dto/StationResponse.java
> +    private static List<StationResponse> getSortedStations(List<Section> sections) {
Section 객체가 생성과 구간 추가의 책임을 가지고 있어 
정렬의 책임까지 가지기 보다는 
정렬 로직을 다른 곳에 책임을 옮기려고 시도하였습니다.

하지만 다시 생각해보니 핵심 비즈니스 로직에 들어가는데 
DTO 안에 작성한 것은 문제가 있네요!

감사합니다~ 수정하겠습니다.

2021-12-01 04:58 UTC, lewisseo91 commented
안녕하세요~!

피드백 수정 후에 재요청 PR보냅니다.

JPA 와 함께 프로그래밍 하면서 고민하는 부분이 많아진 것이 불변 객체 부분인 것 같습니다.
Entity의 default constructor 가 필수가 되면서 final 키워드를 넣지 못해서 
뭔가 반쪽 짜리 wrapper 만 만드는 느낌이 듭니다.

그런데 그렇다고 불변하게 설정하고 immutable 설정(update false) 을 한 후에
다시 update 될 때마다 새로운 insert를 넣는 것은 쿼리 낭비에 배꼽이 더 커지는 결과가 너무 뻔히 보입니다.

이번에 수정하면서 이 부분에 생각이 많아지는 것 같습니다!

그럼 잘 부탁드립니다. 좋은 하루 되세요!

2021-12-01 05:44 UTC, lewisseo91 commented
안녕하세요~!

피드백 수정 후에 재요청 PR보냅니다.

JPA 와 함께 프로그래밍 하면서 고민하는 부분이 많아진 것이 불변 객체 부분인 것 같습니다.
Entity의 default constructor 가 필수가 되면서 final 키워드를 넣지 못해서 
뭔가 반쪽 짜리 wrapper 만 만드는 느낌이 듭니다.

그런데 그렇다고 불변하게 설정하고 immutable 설정(update false) 을 한 후에
다시 update 될 때마다 새로운 insert를 넣는 것은 쿼리 낭비에 배꼽이 더 커지는 결과가 너무 뻔히 보입니다.

이번에 수정하면서 이 부분에 생각이 많아지는 것 같습니다!

그럼 잘 부탁드립니다. 좋은 하루 되세요!

2021-12-02 16:03 UTC, 5minho approved these changes
안녕하세요 동현님!
피드백 잘 반영해주셨습니다!!
리뷰가 늦어서 죄송합니다🙏🏻
이제 마지막 단계네요!!
마지막 까지 화이팅입니다!!!!

2021-12-02 16:03 UTC, merged