Step2 - 인수 테스트 리팩터링
next-step/atdd-subway-admin pull request #516
Opened 2021-11-28 09:02 UTC by changjinpark

리뷰어님. 인수 테스트 리팩터링 2단계 미션 제출합니다!

1단계 리뷰에 대한 코멘트는 밑의 링크에 적어두었습니다.
https://github.com/next-step/atdd-subway-admin/pull/478

2021-11-29 02:48 UTC, 5minho requested changes
안녕하세요 창진님~
2단계 미션 하시느라 고생 많으셨습니다!!
좀 더 개선해보면 좋아보이는 것들을 코멘트에 남겼는데요
확인 부탁드립니다~

2021-11-29 02:48 UTC, 5minho commented on src/main/java/nextstep/subway/line/application/LineService.java
> +        Line line = lineRepository.findById(id).orElseThrow(() -> new RuntimeException("요청 노선이 존재하지 않음"));
피드백 반영을 잘 해주셨네요.👍
좀 더 보완 해주셨으면 하는 점이 있는데요.
예외 메세지에 조회하려고 하는 노선의 id 도 같이 포함되면 디버깅하기 더 좋지 않을까요? 
또 RuntimeException 을 그대로 던지는것 보다, 지하철역 서비스에서 사용하는 커스텀 예외를 만들어보는건 어떨까요?
Controller 에서 RuntimeException 를 잡아서 badRequest 로 응답하고 있는데, 이렇게 되면 어떤 문제점이 있을지 고민해보셨으면 좋을거 같아요

2021-11-29 02:48 UTC, 5minho commented on src/main/java/nextstep/subway/line/domain/Line.java
> +        }
이렇게 한다면 만약 프론트에서 노선의 색만 바꾸고 싶을때 바꾸지 못할거 같은데요?
제 생각에는 service 단에서 Name 으로 DB 에 조회 쿼리를 날려 중복 Name 을 가진 노선이 있으면 예외를 던지는게 좋을거 같아요

2021-11-29 02:48 UTC, 5minho commented on src/main/java/nextstep/subway/line/domain/Line.java
> +    public boolean isSameLineName(LineRequest lineRequest) {
사용하지 않는 메서드는 제거해주시기 바랍니다 🙏🏻

2021-11-29 02:48 UTC, 5minho commented on src/main/java/nextstep/subway/line/dto/LineResponse.java
> +
강의에 나와있는 API 요구사항 스펙이랑 다른거 같습니다.
![image](https://user-images.githubusercontent.com/20471248/143797995-0740bc36-4546-4165-ad81-bfdab807f55d.png)

2021-11-29 02:48 UTC, 5minho commented on src/test/java/nextstep/subway/station/StationAcceptanceTest.java
> -                .extract();
중복코드 제거 잘해주셨네요 👍

2021-11-29 02:48 UTC, 5minho commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
>  import nextstep.subway.AcceptanceTest;
현재 도메인 엔티티의 단위 테스트가 하나도 없는데요 인수테스트 만큼이나 도메인레이어 테스트는 중요합니다
엔티티들의 단위테스트도 작성해보는건 어떨까요

2021-11-29 13:15 UTC, changjinpark commented on src/main/java/nextstep/subway/line/dto/LineResponse.java
> +
옙, API 요구사항과 맞지 않는 부분이 있어서 fix 했습니다.

![image](https://user-images.githubusercontent.com/64358371/143874350-6eb3ada3-4982-4f6f-813b-5025a7ccfcae.png)

2021-11-29 13:44 UTC, changjinpark commented on src/main/java/nextstep/subway/line/domain/Line.java
> +        }
음.. 계속 고민하다보니, update()할 때 중복 노선 이름이 있는지 유효성 처리나 예외 처리를 하는게 맞을까하는 의문이 생깁니다. 말씀하신 방법으로 해도.. 여전히 노선의 색만 바꾸고 싶을 때 바꾸지 못하지 않을까요?🤔🤔 어렵네요..ㅎㅎ

2021-11-29 14:22 UTC, changjinpark commented on src/main/java/nextstep/subway/line/application/LineService.java
> +        Line line = lineRepository.findById(id).orElseThrow(() -> new RuntimeException("요청 노선이 존재하지 않음"));
네! 예외처리 메세지에 id를 추가하면 디버깅하기 수월한 코드가 될 것 같습니다.
그리고 지하철역 서비스에서만 사용하는 커스텀 예외를 만들어서 변경했습니다.
Controller에는 커스텀 예외마다 따로 badRequest를 응답하도록 만드는게 좋을까요? 
![image](https://user-images.githubusercontent.com/64358371/143882931-183a1118-e0cd-480d-aece-0d2ce350c894.png)

2021-11-30 12:03 UTC, 5minho commented on src/main/java/nextstep/subway/line/application/LineService.java
> +        Line line = lineRepository.findById(id).orElseThrow(() -> new RuntimeException("요청 노선이 존재하지 않음"));
Controller 에서 RuntimeException 으로 잡아서 badRequest 로 응답하면, badRequest 가 아닌 케이스도 badRequest 로 응답해버리지 않을까요? RuntimeException 을 상속하고 있는 자바 표준 예외도 많으니까요. 응답을 수행하다 예상치 못하게 서버 개발자 실수로 
 RuntimeException 이 났는데 그걸 badRequest 라고 응답해버리면 안될거 같아요.

상황에 맞는 커스텀 예외를 만들고 예외에 따라 적절한 응답을 해주는게 더 좋은거 같습니다. 
커스텀 예외 발생시 모두 badRequest 응답을 해야 한다면 이렇개 하나로 묶어서 핸들링을 할 수 있어요
```
@ExceptionHandler({NotFoundException.class, CannotUpdateException.class})
    public ResponseEntity handleRuntimeException(RuntimeException e) {
        return ResponseEntity.badRequest().build();
    }
```

2021-11-30 12:15 UTC, 5minho commented on src/main/java/nextstep/subway/line/domain/Line.java
> +        }
> 이렇게 한다면 만약 프론트에서 노선의 색만 바꾸고 싶을때 바꾸지 못할거 같은데요?

이 코멘트는 제가 착각하고 잘못 피드백을 드렸네요 죄송합니다ㅜ 🙇🏻🙇🏻🙇🏻🙇🏻 
창진님 말씀이 맞습니다. 이렇게 해도 여전히 노선의 색만 바꾸고 싶으면 바꾸지 못하죠
하지만 중복 노선 체크를 service layer 로 빼신건 의미가 있어요.
노선을 저장시 중복체크를 해야하기 때문이에요

```
// LineService.java
LineResponse saveLine(LineRequest request)
```

2021-11-30 12:37 UTC, 5minho approved these changes
안녕하세요 창진님!
피드백 반영 해주시느라 고생많으셨습니다~
코멘트는 다음 미션 진행해주시면서 확인부탁드려요~~
다음 미션도 화이팅 입니다

2021-11-30 12:37 UTC, 5minho commented on src/test/java/nextstep/subway/line/LineTest.java
> +@DataJpaTest
repository CRUD 테스트를 해주셨네요.
사실 제가 의도한건 도메인 객체(엔티티)를 활용한 노선, 역 도메인의 요구사항 테스트였어요. 
하지만 repository 테스트도 의미가 없는것은 아니니 괜찮아요!

다음 단계를 진행하실때는 해당 테스트 이름을 LineRepositoryTest 로 바꾸시고 새로운 LineTest 를 만들어서 
`도메인의 요구사항` 을 위한 단위테스트들을 만들어보시면 좋을거 같아요!
예시입니다.

```
@DisplayName("노선의 역들을 상-하행 순으로 정렬할 수 있다.")
@Test
void orderStationsTest() {
    //given
    Station 강남역 = new Station("강남역");
    Station 광교역 = new Station("광교역");;
    Line 신분당선 = new Line("신분당선", "bg-red-600", 강남역, 광교역, 10);

    //when
    List<Station> orderedStations = 신분당선.getStationsInOrder();

    //then
    assertThat(orderedStations).containsExactly(강남역, 광교역);
}
```

2021-11-30 12:37 UTC, 5minho commented on src/main/java/nextstep/subway/line/domain/Section.java
> +    public Section() {
엔티티의 기본생성자는 외부에서 호출을 못하도록 protected 로 해주시면 좋을거 같아요

2021-11-30 12:38 UTC, merged

2021-11-30 13:40 UTC, changjinpark commented on src/main/java/nextstep/subway/line/application/LineService.java
> +        Line line = lineRepository.findById(id).orElseThrow(() -> new RuntimeException("요청 노선이 존재하지 않음"));
예시 감사합니다. 덕분에 이해가 잘되었습니다. 코드에 반영하였습니다.

2021-11-30 13:45 UTC, changjinpark commented on src/main/java/nextstep/subway/line/domain/Line.java
> +        }
네네. SaveLine에서 노선 이름 중복 체크를 하도록 바꾸었습니다.
물론 Line 엔티티의 name 필드에 @Column(unique = true) 어노테이션이 있어서 중복 이름이 저장되지는 않겠지만,
불필요하게 insert 쿼리를 날리지 않아도 된다는 장점이 있겠네요~

![image](https://user-images.githubusercontent.com/64358371/144057930-73055d7c-50e0-4e1c-979d-d6d215974d73.png)

2021-11-30 13:47 UTC, changjinpark commented on src/test/java/nextstep/subway/line/LineTest.java
> +@DataJpaTest
예시 감사합니다. 다음 단계에서 도메인의 요구사항을 위한 단위 테스트 적용해보겠습니다.