Step3 - 구간 추가 기능
next-step/atdd-subway-admin pull request #520
Opened 2021-11-28 15:18 UTC by Junhong-Kim

안녕하세요.
구간 추가 기능 코드리뷰 요청드립니다!
감사합니다. ☺️

2021-11-28 15:35 UTC, Junhong-Kim commented on src/test/java/nextstep/subway/section/SectionAcceptanceTest.java
> +        assertThat(지하철_노선_조회_요청(lineId).jsonPath().getList("stations.name", String.class)).containsExactly("강남역", "양재역", "광교역");
안녕하세요.
step3를 진행하면서 잘 진행되지 않는 부분이 있어 질문드립니다.

구간 추가 API 요청 후 response로 station 목록이 정렬된 상태로 정상 반환됩니다.
그런데, 이후 노선 조회 API를 통해 조회해보면 역이 정상적으로 반환되지 않고 구간이 덮어 씌워져 반환됩니다.

며칠 동안 이유를 찾아본 결과 노선 조회 API에서 line 조회 시,
proxy 객체로 반환되고 있는 것이 영향이 되어 문제가 발생하고 있는 것으로 생각이 듭니다.

proxy 객체는 실제 사용될 때 실제 객체를 반환하는 것으로 알고 있는데,
직접 해당 객체를 touch하거나 조회해봐도 실제 객체로 반환되지 않고 있습니다.

proxy 객체의 실제 객체에 접근하기 위해 다양한 방법을 시도해보았는데,
강제로 `Hibernate.unproxy()`를 사용할 때만 실제 객체가 반환되고 있습니다.

위 이유로 인해서 구간 추가는 정상적으로 되었으나, 이후 노선 조회 시 response에 역 목록이 정상적으로 반환되지 않아서
`노선에 구간 추가 성공 후 노선 조회` 테스트 케이스가 실패하고 있는데 원인을 알 수 있을까 해서 질문드립니다. 😭

2021-11-28 15:44 UTC, Junhong-Kim commented on src/main/java/nextstep/subway/section/domain/Sections.java
> +        upStations.removeAll(downStations);
노선 조회 API 요청시 이 부분에서 section, station이 proxy 객체로 반환되어 `removeAll` 기능이 정상 동작하지 않고 있습니다.

2021-11-29 13:57 UTC, nokchax requested changes
안녕하세요, 준홍님!
질문주신 것에 답변 남겼는데요, 확인후에 재요청 부탁드립니다.!

2021-11-29 13:57 UTC, nokchax commented on src/main/java/nextstep/subway/station/domain/Station.java
> +    }
```suggestion
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Station)) return false;
        Station station = (Station) o;
        return Objects.equals(getId(), station.getId());
    }
```
우선 프록시 객체가 어떨때 생기는지 찾아보세요!
또한 entity 의 equals는 조심히 사용하셔서 프록시 객체를 비교하게 되더라도 올바르게 동작할 수 있도록 해주어야 합니다. :)
이번 리뷰는 수정하신 후에 진행하도록 할게요!

2021-11-29 15:46 UTC, Junhong-Kim commented on src/main/java/nextstep/subway/station/domain/Station.java
> +    }
제안해주신 방법으로 equals를 수정하니 테스트 케이스가 바로 성공되네요!! 🥰
며칠 동안 고민하면서 답답한 마음에 PR로 질문드렸는데 명쾌한 해결 방법을 알려주셔서 정말 감사드립니다. 👍

우선, 지하철 노선 조회 API 요청 시 proxy 객체가 생성된 이유는 `Line` entity 클래스 멤버 변수로 정의된,
`Sections` 일급 컬렉션에 sections가 `fetch = FetchType.LAZY`로 되어있어서 proxy 객체가 생성되는 것으로 알고 있습니다.

기존 로직에서는 proxy 객체가 `if (o == null || getClass() != o.getClass()) return false;` 로직을 타면서,
proxy 객체 비교 결과가 false로 반환되어 발생한 문제로 파악되었습니다.

따라서, equals를 `if (!(o instanceof Station)) return false;`로 수정해서 Station proxy 객체도 같은 타입으로 판단하고,
`return Objects.equals(getId(), station.getId());` 구문에서 값을 비교하도록 가이드해주신 부분 확인했습니다. 🙆‍♂️

다만, 답변해주신 내용에 대해 좀 더 아티클들을 찾아보면서 질문이 한 가지 생겼습니다.
entity 클래스는 실제 객체가 아닌 proxy 객체를 반환할 수도 있어서 entity 클래스의 equals 사용을 지양하는 것이 좋을까요?

만약, entity 클래스 equals 사용을 지양해야 한다면 컬렉션을 사용하는 이점을 누리지 못하게 될 것 같은데,
`Objects.equals(getId(), station.getId());` 형태로 유니크한 값을 직접 비교하는 방식이 지향될까요? 🤔

p.s.
이번 미션에서 리뷰어님 덕분에 많은 것을 배울 수 있었는데,
답답했던 부분도 한 번에 해결해주셔서 다시 한번 감사드립니다!! 😍

2021-11-30 11:04 UTC, nokchax requested changes
안녕하세요, 준홍님! 도움이 됐다니 다행이네요 :)
추가적으로 코멘트 남겼는데 확인후 재요청 부탁드립니다 🙇‍♂️

2021-11-30 11:04 UTC, nokchax commented on src/main/java/nextstep/subway/section/domain/Sections.java
> +    private void validateDistance(Section newSection, Section oldSection) {
distance를 검증하는 로직 또한 하나의 section내에 새로운 section을 전달(메세지를 전달)해서 처리할 수 있을거 같아요

2021-11-30 11:04 UTC, nokchax commented on src/main/java/nextstep/subway/station/domain/Station.java
> +    }
equals는 다양한 곳에서 사용되기 때문에 equals 사용을 지양하는 것은 옳지 않은 결론인거 같아요
말씀드렷듯이 entity 클래스의 equals를 프록시 객체와 비교시에도 잘 동작하도록 오버라이드 하신 후에 사용해야합니다.

2021-11-30 15:16 UTC, Junhong-Kim commented on src/main/java/nextstep/subway/section/domain/Section.java
> +                .orElse(null);
`section.getNextSection(sections)` 구문이 잘 안 읽혀서 `section.hasNextSection()` 메서드를 추가했습니다.
그리고 stream 결과로 `null`을 반환하지 않고 예외가 발생하도록 수정했습니다.

2021-11-30 15:17 UTC, Junhong-Kim commented on src/main/java/nextstep/subway/section/domain/Sections.java
> +        if (oldSection != null) {
Optional 안티 패턴을 수정했습니다! 👍

2021-11-30 15:17 UTC, Junhong-Kim commented on src/main/java/nextstep/subway/section/domain/Sections.java
> +            oldSection.setDistance(oldSection.getDistance() - newSection.getDistance());
두 작업은 항상 같이 수행돼야 하므로 `updateUpStation()`, `updateDownStation()` 메서드를 생성했습니다.

2021-11-30 15:18 UTC, Junhong-Kim commented on src/main/java/nextstep/subway/section/domain/Sections.java
> +    private void validateDistance(Section newSection, Section oldSection) {
업데이트 전 유효성 검사가 되어야 하므로 `updateUpStation()`, `updateDownStation()` 내부로 로직을 옮겼습니다.

2021-11-30 15:21 UTC, Junhong-Kim commented on src/main/java/nextstep/subway/station/domain/Station.java
> +    }
entity 클래스에서 `equals`는 proxy 객체를 생각하며 항상 주의해서 사용해야겠네요. 😉
의견 감사드립니다!

2021-11-30 15:24 UTC, Junhong-Kim commented
테스트 코드가 잘 작성되어 있어서 리팩토링에 대한 두려움이 전혀 없었네요!
새삼 테스트 코드의 중요성에 대해 느꼈습니다. 👍

그리고 `Optional`에 대한 안티 패턴을 학습하고, 생각을 조금 바꾸니 더 읽기 쉬운 코드를 작성할 수 있었습니다.
감사합니다! 🥰

2021-12-01 12:24 UTC, nokchax approved these changes
안녕하세요 준홍님! 잘 수정해 주셨네요, 코드가 훨씬 읽기 좋아졌습니다 👍 
이번 단계는 이만 머지할게요, 다음 단계 진행해주세요 :)

2021-12-01 12:24 UTC, nokchax commented on src/main/java/nextstep/subway/line/domain/Line.java
> +        while (section.hasNexSection()) {
👍

2021-12-01 12:25 UTC, merged