Step2 - 인수 테스트 리팩터링
next-step/atdd-subway-admin pull request #521
Opened 2021-11-28 15:40 UTC by devsigner9920

안녕하세요!

2단계 미션 진행해보았습니다.

인수테스트에서 어느 부분을 건드려야할지, 그리고 기존에 작성한 코드들과의 관계에서 기능이 추가 됐을 때 어떻게 하면 더 확장 가능하게 작성할지 

고민이 많이 되는 미션이었습니다..

특히 구간 설정 부분에서는 추후에 확장성을 고려하느라 고민을 많이 하여 작성한 것 같습니다!

매번 피드백 감사드립니다!

2021-11-29 13:54 UTC, leeyohan93 requested changes
피드백 잘 반영해주시고 2단계도 잘 구현해주셨네요 👍 👍
몇가지 코멘트를 남겨 놓았으니 확인 부탁드립니다 :)
리뷰가 늦어져서 죄송해요 🙏  다음 리뷰는 좀 더 빨리 드릴 수 있도록 해볼게요 😄

2021-11-29 13:54 UTC, leeyohan93 commented on src/main/java/nextstep/subway/common/ServiceException.java
> +  private final HttpStatus status;
계층 구조

2021-11-29 13:54 UTC, leeyohan93 commented on src/main/java/nextstep/subway/sections/domain/Distance.java
> +public class Distance {
클래스를 작게 분리하는 것은 정말 중요하지만, 적절한 책임에의해 만들어져야하며 항상 오버엔지니어링은 경계해야합니다 :)

Distance는 어떤 책임을 가지고 있을까요? 제가 생각하기에는 0이상의 숫자(거리)를 나타낼 수 있다고 생각이 드는데요 !
책임을 수행하고 있는 것이 없다면 오버엔지니어링 일 수 있습니다 참고해주세요 😄 

물론 이후에 거리 계산을 위해서 미리 추가하셨을 수도 있지만, 필요할 때에 추가가 되는 것이 좋은 것 같습니다 👍

2021-11-29 13:54 UTC, leeyohan93 commented on src/main/java/nextstep/subway/line/domain/Line.java
> +  @Id
기존에 작성된 클래스는 들여쓰기가 4칸인데 최근 작성된 클래스는 들여쓰기가 2칸이네요! 
포맷이 변경된 이유가 있으실까요? 어느 쪽도 괜찮지만 하나로 통일이 되어야할 것 같습니다 😄

2021-11-29 13:54 UTC, leeyohan93 commented on src/main/java/nextstep/subway/line/domain/Line.java
> +  }
기본 생성자의 접근제어자는 protected가 좋을 것 같습니다 :)

2021-11-29 13:54 UTC, leeyohan93 commented on src/main/java/nextstep/subway/line/domain/Line.java
> +  }
사용하지 않는 코드는 제거해주셔도 좋을 것 같아요 !

2021-11-29 13:54 UTC, leeyohan93 commented on src/main/java/nextstep/subway/line/application/LineService.java
>          }
예외에 좀 더 자세한 메시지를 만들 수 있도록 하는건 어떨까요 ?
```java
    lineRepository.findByName(request.getName())
                .ifPresent(line -> {
                    throw new LineDuplicateException(line.getName());
                });
```

2021-11-29 13:54 UTC, leeyohan93 commented on src/main/java/nextstep/subway/sections/domain/SectionRepository.java
> +}
Section은 현재 Line을 통해 관리(생성, 삭제)되고 있기 때문에 별도의 Repository는 필요없어도 될 것 같네요 🤔

2021-11-29 13:54 UTC, leeyohan93 commented on src/main/java/nextstep/subway/sections/domain/Section.java
> +package nextstep.subway.sections.domain;
section과 line을 패키지 단위로 나누어주셨는데요 ! 지금은 두 패키지 사이에서 의존성의 사이클이 만들어지고 있네요!

의존성의 사이클이 있다는 것은, 한 패키지의 변경 사항이 생겼을 때 다른 패키지도 변경해야하는 것을 의미합니다.

엔티티 또한 양방향 연관관계를 맺고 있기 때문에 하나의 패키지로 합쳐지는 것이 더욱 적합해 보이기도 하네요! 🤔

원준님은 어떻게 생각하시나요?

관련된 좋은 세미나 영상을 공유해드릴게요!

[https://www.youtube.com/watch?v=dJ5C4qRqAgA](https://www.youtube.com/watch?v=dJ5C4qRqAgA)

2021-11-29 13:54 UTC, leeyohan93 commented on src/main/java/nextstep/subway/sections/domain/Section.java
> +  public Section() {}
Section의 기본생성자도 protected로 변경해주세요 :)

2021-11-29 13:54 UTC, leeyohan93 commented on src/main/java/nextstep/subway/sections/domain/Sections.java
> +  public Section upEndPoint() {
클래스 내부에서 사용하는 메서드는 private으로 설정해주세요 :)

2021-11-29 13:54 UTC, leeyohan93 commented on src/main/java/nextstep/subway/sections/domain/Sections.java
> +  public Stations getUpToDownStations() {
메서드의 기능을 검증해 줄 단위테스트들이 존재하지 않는 것 같습니다 !
인수 테스트 미션이지만 도메인 클래스들에 대한 단위테스트 또한 기본적으로 작성해주시면 좋을 것 같아요 :)

2021-11-29 13:54 UTC, leeyohan93 commented on src/main/java/nextstep/subway/station/domain/Stations.java
> +public class Stations {
> 클래스를 작게 분리하는 것은 정말 중요하지만, 적절한 책임에의해 만들어져야하며 항상 오버엔지니어링은 경계해야합니다.

Stations는 어떤 책임을 가지고 있을까요 ?

2021-11-29 13:54 UTC, leeyohan93 commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +    private void 지하철_노선_생성됨(ExtractableResponse<Response> createResponse) {
Test Fixture 클래스를 만들어 테스트에 필요한 부분들은 따로 관리해보면 어떨까요 ?
Test Fixture 관련된 흥미로운 포스팅도 공유드릴게요! :)

[https://jojoldu.tistory.com/611](https://jojoldu.tistory.com/611)

2021-11-29 13:54 UTC, leeyohan93 commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +        stationRepository.save(SEOKSU_STATION);
Test Fixture를 반영해보면 해당 BeforeEach는 필요하지 않을 수 있겠네요 🤔

2021-11-29 15:50 UTC, devsigner9920 commented on src/main/java/nextstep/subway/sections/domain/Distance.java
> +public class Distance {
아하.. 넵 명심하겠습니다 ㅎㅎ 습관적으로 추후에 필요하겠지 싶어서 오버 엔지니어링하는게 잦네요! 고치도록 하겠습니다!

2021-11-29 15:51 UTC, devsigner9920 commented on src/main/java/nextstep/subway/line/domain/Line.java
> +  @Id
앗 컴퓨터를 새로 바꿔서 인텔리제이 설정이 날아가서요 ㅠ 여태 2space로 통일하며 쓰다가 설정이 꼬인거 같습니다 ㅠ

2021-11-29 15:51 UTC, devsigner9920 commented on src/main/java/nextstep/subway/line/domain/Line.java
> +  }
아하 넵 알겠습니다!

2021-11-29 15:51 UTC, devsigner9920 commented on src/main/java/nextstep/subway/line/domain/Line.java
> +  }
넵 오버엔지니어링 경계!

2021-11-29 15:53 UTC, devsigner9920 commented on src/main/java/nextstep/subway/sections/domain/SectionRepository.java
> +}
넵 현재 시점에서 필요 없는 부분들에 대해선 간소화하겠습니다!

2021-11-29 15:53 UTC, devsigner9920 commented on src/main/java/nextstep/subway/line/application/LineService.java
>          }
앗 그러네요..! 알겠습니다!

2021-11-29 15:56 UTC, devsigner9920 commented on src/main/java/nextstep/subway/sections/domain/Section.java
> +  public Section() {}
넵! 신경쓰겠습니다 ㅎㅎ

2021-11-29 15:58 UTC, devsigner9920 commented on src/main/java/nextstep/subway/station/domain/Stations.java
> +public class Stations {
역들은 중복되지 않아야 합니다..! 앗 신경써서 고민해가지구 작성하겠습니다

2021-11-29 15:59 UTC, devsigner9920 commented on src/main/java/nextstep/subway/sections/domain/Sections.java
> +  public Stations getUpToDownStations() {
아하 넵 작성했다가 다음 파트에서 해야하려나! 해서 삭제 했습니다 ㅋㅋㅋ 그런거에 구애받지 않고 작성하도록 하겠습니다 ㅎㅎ

2021-11-29 15:59 UTC, devsigner9920 commented on src/main/java/nextstep/subway/sections/domain/Sections.java
> +  public Section upEndPoint() {
넵 알겠습니다!

2021-11-29 16:00 UTC, devsigner9920 commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +    private void 지하철_노선_생성됨(ExtractableResponse<Response> createResponse) {
포스팅 보고 시도해보겠습니다! 좋은 자료 정말 감사드립니다 ㅎ

2021-11-29 16:00 UTC, devsigner9920 commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +        stationRepository.save(SEOKSU_STATION);
넵! 반영해보겠습니다 ㅎㅎ

2021-11-29 16:06 UTC, devsigner9920 commented on src/main/java/nextstep/subway/sections/domain/Section.java
> +package nextstep.subway.sections.domain;
아 맞아요.. 안그래도 의존성이 있어서 이걸 나눈게 맞나 싶어서 고민을 하다가 그래도 최소한의 단위로 가져가는게 어떨까? 해서 나누어 봤습니다!
요한님 말씀대로 양방향 연관관계기 때문에 하나의 패키지 내에서 컨트롤하는게 더 적절한거 같습니다 ㅎㅎ

세미나 영상 보고 애매하다고 생각한 부분에 대해서 확실히 짚고 넘어 가겠습니다! 감사합니다 :)

2021-12-01 01:19 UTC, leeyohan93 approved these changes
피드백을 잘 반영해주셨네요 👍 👍 
피드백도 todo 리스트를 통해 관리하고 커밋 단위를 나누어주신것이 정말 좋았습니다 👍 
소소한 코멘트를 남겨드렸으니 확인부탁드리고 이번 단계는 머지하겠습니다 😄 
다음 단계도 화이팅입니다 🔥

2021-12-01 01:19 UTC, leeyohan93 commented on src/main/java/nextstep/subway/station/domain/Stations.java
> +  private static final long ONE = 1;
특정 숫자를 가리키는 상수명은 지양해야합니다 :)
만약 최소 존재해야하는 역이 2개로 바뀐다면 상수명도 바뀌어야 되기 때문이에요 ! 😄

2021-12-01 01:19 UTC, leeyohan93 commented on src/main/java/nextstep/subway/station/domain/Stations.java
> +      .count();
아래와 같이 변수명을 수정해보는건 어떨까요? station1은 어떤 것을 의미하는지 알기 어렵게 됩니다!

```java
  private void duplicaStationValidate(List<Station> stations, Station newStation) {
    long matchCount = stations.stream()
      .filter(station -> station.equals(station))
      .count();
```

2021-12-01 01:19 UTC, leeyohan93 commented on src/main/java/nextstep/subway/line/domain/Distance.java
> +  }
setter는 제거해주시면 좋을 것 같아요 :)

2021-12-01 01:19 UTC, leeyohan93 commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +      if (nextSection == null) break;
while문 안에 if문이 들어가서 들여쓰기가 2개가 넘어가게 되었네요..!

이전 단계에 들여쓰기를 2로 제한하는 요구사항이 있었는데 이번 미션에서도 지켜주시면 좋을 것 같습니다 :)

2021-12-01 01:19 UTC, leeyohan93 commented on src/main/java/nextstep/subway/station/domain/Station.java
> +  public boolean equals(Object o) {
엔티티 클래스의 equals는 id만을 비교해야 한다고 생각합니다.

그 이유는 equals는 동등성 비교를 의미하고, 동등성 비교라는 것은 두 객체의 주소가 다르더라도 같은 것 임을 어떻게 보장할 것인지에 관한 이야기이기 때문입니다!

이 이야기를 JPA에서 바라보면, 엔티티를 조회한 후 1차 캐시를 초기화하고 다시 데이터베이스에서 동일한 엔티티를 읽어오는 경우 새로운 객체가 생성되어도 두 엔티티 객체는 equals를 통해 동등성이 보장되어야 한다는 것이지요.

또 다른 예로 엔티티를 조회한 후에 값을 바꾸더라도 값을 바꾸기 이전과 동등한 row 임을 파악할 수 있게 equals를 활용해야 하고 때문에 다른 필드는 equals의 구현에서 빠져야 한다고 생각합니다!

관련해서 이전 미션에서 최태현 리뷰어님께서 남겨주신 좋은 피드백이 있는데 참고해주셔도 좋을 것 같아요 :)
[next-step/jwp-qna#318 (comment)](https://github.com/next-step/jwp-qna/pull/318#discussion_r750846656)

👍

2021-12-01 01:19 UTC, leeyohan93 commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +        지하철_노선_생성_요청(new LineRequest("1호선", "blue", 1L, 2L, 10));
생성 요청으로 사용하게되면 생성 요청 시 잘못된 응답이 올 가능성이 있을 것 같아요 ! 🤔 

`지하철_노선_생성_요청` 대신 
`지하철_노선_등록되어_있음` 이라는 메서드를 만들고 그 안에서 생성 요청과 생성 검증을 같이 하도록 하여 사용하면 어떨까요?

2021-12-01 01:19 UTC, merged

2021-12-01 06:17 UTC, devsigner9920 commented on src/main/java/nextstep/subway/station/domain/Stations.java
> +  private static final long ONE = 1;
아하 넵 알겠습니다 :) 상수 이름 지을때도 항상고민스러운 부분이 많네요 ㅠ 다음에 적용하여 미션진행해보겠습니다!

2021-12-01 06:19 UTC, devsigner9920 commented on src/main/java/nextstep/subway/station/domain/Stations.java
> +      .count();
아하 넵 변수명 신경쓰겠습니다!

2021-12-01 06:25 UTC, devsigner9920 commented on src/main/java/nextstep/subway/line/domain/Distance.java
> +  }
@leeyohan93 
Distance객체가 @Embeddatable을 쓰다보니 인텔리제이서 
`For property-based access both setter and getter should be present` 에러를 뱉어서 Setter 까지 지정해줘야 하는지 하고 했습니다!

근데.. 요한님의 피드백을받고 왜 Embeddable에서 이런 오류가 날까? 하며 찾아본 결과 
아래 김영한님의 답변을 보아서 적용해보겠습니다!
피드백 덕분에 또 새로운 사실을 알고 가네요 ㅎㅎ

감사합니다!

https://www.inflearn.com/questions/78106

2021-12-01 06:25 UTC, devsigner9920 commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +      if (nextSection == null) break;
앗 그러네요..  좀 더 다른방법으로 접근해보겠습니다! 감사합니다!

2021-12-01 06:32 UTC, devsigner9920 commented on src/main/java/nextstep/subway/station/domain/Station.java
> +  public boolean equals(Object o) {
아하 넵 생각해보면 그러네요 JPA가 캐싱하는 데이터는 각 엔티티의 키값일텐데.. 조회하고 동등성이 보장되지 않을수도있겠군요..!
관련한 피드백 참고하겠습니다! 감사합니다!

2021-12-01 06:35 UTC, devsigner9920 commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +        지하철_노선_생성_요청(new LineRequest("1호선", "blue", 1L, 2L, 10));
아하..! 되어있음으로 만들고 그 안에서 요청 및 검증까지..! 알겠습니다! 다음 미션에서 적용하여 진행하겠습니다 :)