3단계 - 구간 추가 기능 코드 리뷰 요청드립니다.
next-step/atdd-subway-admin pull request #526
Opened 2021-11-29 09:58 UTC by codingknowjam

안녕하세요 
드디어 ㅠ 3단계를 하네요
작성하면서 인수테스트 시나리오 먼저 작성하고 기능구현을 하도록 진행해봤습니다.
성공테스트먼저 하고 후에 실패테스트를 작성하는 순으로 작업을 하니 기능요구사항 정의하기가 수월했던것 같습니다.
현재 계속 되는 고민중 ㅎ나는 Section을 따로 패키지를 구성해야 할지 Line도메인과 같은 패키지내에서 사용해야할지 잘 모르겠습니다.
어떻게 하는게 좋을까요??
항상 좋은 피드백 감사합니다.

2021-11-29 13:32 UTC, kang-hyungu commented
> 현재 계속 되는 고민중 ㅎ나는 Section을 따로 패키지를 구성해야 할지 Line도메인과 같은 패키지내에서 사용해야할지 잘 모르겠습니다.

section을 따로 분리해야겠다고 판단한 이유가 있을까요? line과 section의 관계를 어떻게 보느냐에 따라 달라질 수도 있겠네요.

2021-11-29 13:32 UTC, kang-hyungu requested changes
상우님 몇 가지 피드백 남겼습니다.
수정해보시고 리뷰 재요청주세요.

2021-11-29 13:32 UTC, kang-hyungu commented on src/main/java/nextstep/subway/exception/ExceptionController.java
> +	public ResponseEntity<Object> handleIllegalArgsException(DataIntegrityViolationException e) {
Object가 아닌 Void로 처리해도 되지 않나요?

2021-11-29 13:32 UTC, kang-hyungu commented on src/main/java/nextstep/subway/line/application/LineService.java
> +		Line line = lineRepository.findById(id)
```suggestion
		Line line = findById(id)
```

중복이 보이네요

2021-11-29 13:32 UTC, kang-hyungu commented on src/main/java/nextstep/subway/line/application/LineService.java
> +	private void validateAllContainStation(Line line, Station... stations) {
도메인 객체의 단위 테스트를 작성해보시면 이 조건이 적용되지 않겠네요.
비즈니스 로직의 유효성 검사는 서비스가 아닌 도메인 객체에서 처리해주세요.
81라인도 동일합니다.

2021-11-29 13:32 UTC, kang-hyungu commented on src/main/java/nextstep/subway/line/domain/Line.java
> +	public boolean notContain(Station[] stations) {
allContain는 가변인자인데 이 메서드는 배열로 처리한 이유가 무엇인가요? 일관성을 맞춰주세요.

2021-11-29 13:32 UTC, kang-hyungu commented on src/main/java/nextstep/subway/line/domain/Section.java
> +	public void updateSequence(int sequence) {
메서드 이름만 다르지 setter랑 차이가 없지 않나요?
updateSequence, updateUpStation를 분리할 필요가 없고 외부에서 값을 계산해서 넣어줄 필요가 없을 것 같은데 적절하게 기능을 부여해보시기 바랍니다.

2021-11-29 13:32 UTC, kang-hyungu commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +	private boolean ifAddMiddleStartLocation(Section section) {
anyMatch라는 기능을 사용해보아요

2021-11-29 13:32 UTC, kang-hyungu commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +	public boolean notContain(Station[] stations) {
파라미터 일관성을 맞춰 주시고 noneMatch라는 기능을 활용하시면 더 자연스러운 코드 작성이 가능합니다.

2021-11-29 13:32 UTC, kang-hyungu commented on src/test/java/nextstep/subway/line/domain/SectionsTest.java
>  	public void SectionsAddTest() {
깨지는 테스트가 있으니 점검해보시기 바랍니다.
그리고 단위 테스트로 비즈니스 로직이 정상 동작하는지 꼭 점검하시기 바랍니다.

![image](https://user-images.githubusercontent.com/15669435/143876418-ad4bba0c-aa3e-49d2-9660-41c6ea33f9a3.png)

2021-11-30 06:41 UTC, codingknowjam commented on src/main/java/nextstep/subway/line/domain/Section.java
> +	public void updateSequence(int sequence) {
현구님 안녕하세요
피드백 주신거를 어제 밤새 고민해봤는데 ㅠ 아무리 생각해봐도 값을 바꿔주는 요소는 필요하다고 생각됩니다.
메서드 이름만 다른건 사실이지만, 제가 의도한것은 단순히 set이 아니라 기존의 값이 바뀐다해서 update라는 명칭으로 작성했었습니다.
그리고 sequence의 경우는 하나의 메서드로 갱신할 수 있었지만, 상행과 하행의 역들을 구간이 새로 추가되는 위치에 따라 업데이트 해줘야하는 필드가 달라져서 setter와 같은 성격의 메서드가 필요하다고 생각됩니다.
혹시 어느 부분을 수정하면 말씀해주신 피드백처럼 수정이 가능할지 좀 더 상세하게 알려주시면 감사하겠습니다.

2021-12-01 02:19 UTC, kang-hyungu approved these changes
상우님 피드백 반영하신 내용 확인했습니다.
추가로 남긴 코멘트는 다음 미션 진행하면서 적용해주세요
pr은 머지 처리하겠습니다. 수고하셨어요

2021-12-01 02:19 UTC, kang-hyungu commented on src/main/java/nextstep/subway/exception/ExceptionController.java
> +	public ResponseEntity DataIntegrityViolationException(DataIntegrityViolationException e) {
1. 제네릭을 제거하지 마시고 Void라는 타입을 사용해보세요.
2. 메서드명은 네이밍 컨벤션을 지켜주세요

2021-12-01 02:19 UTC, kang-hyungu commented on src/main/java/nextstep/subway/line/domain/Line.java
> +		if (sections.allContain(section)) {
Line 객체를 통하지 않고 Sections 객체에 직접 section 객체를 추가할 때 중복된 section을 추가할 수 있겠네요.
비즈니스 규칙을 다시 점검해보아요

2021-12-01 02:19 UTC, kang-hyungu commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +		System.out.println("##");
이 코드는 제거하는게 좋겠네요

2021-12-01 02:20 UTC, merged