🚀 2단계 - 인수 테스트 리팩터링
next-step/atdd-subway-admin pull request #531
Opened 2021-11-30 10:53 UTC by vvshinevv

안녕하세요? 2단계를 진행하고 있는 최홍희입니다.

JPA를 회사에서 사용하고 있는데 매번 복사 붙여넣기 방식으로 개발을 하고 있어서,
이번 기회에 제대로 사용해보고 싶은 마음에 공부를 좀 더 해보면서 하느라 늦었습니다.

특히 이전 과제에서 콘솔 로또 어플리케이션을 개발했을 때, 일급 콜렉션을 사용했었는데,
이것을 어떻게 JPA에 연결해서 쓸 수 있을지 처음 적용해 봤는데, 뭔가 더 객체 지향적으로
개발이 되는 것 같아서 뿌듯했습니다.

그러다가 한가지 궁금한 점이 생겼는데요,
보통 DTO에는 Getter/Setter 를 허용하고 VO에서는 Getter만 허용한다고 배웠습니다.
1. 그런데 Entity 같은 도메인에는 Getter/Setter 허용이 가능할까요? 이전 JPA 학습에서도 Entity 클래스에 Getter/Setter를 사용하는 것 같아서요 여쭙습니다.
2. 그리고 제가 Entity (Sections) 클래스에 비지니스 로직을 구현했는데, Entity 클래스에는 DB 정보를 나타나는 데이터이기 때문에 순수하게 필드 정도만 들어가야한다 라고 생각이 들었습니다. Entity 클래스에 안에 비지니스 로직을 구현해도 객체지향적으로 괜찮을 걸까요?!

아낌없는 리뷰 부탁드리겠습니다.
감사합니다.

2021-12-01 10:43 UTC, minsungryu commented
> 1. 그런데 Entity 같은 도메인에는 Getter/Setter 허용이 가능할까요? 이전 JPA 학습에서도 Entity 클래스에 Getter/Setter를 사용하는 것 같아서요 여쭙습니다.

무분별한 getter/setter는 지양하는게 좋습니다.
대신에 의미있는 메서드를 통해 상태를 변경하는 것이 더 좋을 것 같아요~

> 2. 그리고 제가 Entity (Sections) 클래스에 비지니스 로직을 구현했는데, Entity 클래스에는 DB 정보를 나타나는 데이터이기 때문에 순수하게 필드 정도만 들어가야한다 라고 생각이 들었습니다. Entity 클래스에 안에 비지니스 로직을 구현해도 객체지향적으로 괜찮을 걸까요?!

엔티티는 최고 수준의 정책으로써 도메인의 핵심 비즈니스 로직에 대한 책임을 갖고 있습니다.
서비스마다 비즈니스 로직이 흩어져있는 것보다 엔티티에서 비즈니스 로직을 구현해서 응집력을 높이는 편이 좋아보입니다.
이 부분은 객체지향 관점도 좋지만 아키텍처 관점에서 더 좋을 것 같습니다.

![image](https://user-images.githubusercontent.com/22931598/144220232-dad34f04-d112-4ff1-a6ba-993c81f98be2.png)

2021-12-01 10:44 UTC, minsungryu requested changes
홍희님 안녕하세요!
2단계 구현 잘 해주셨네요~
몇 가지 간단한 코멘트를 남겼는데요,
확인해주시고 다시 리뷰 요청주시면 좋을 것 같습니다 :)

2021-12-01 10:44 UTC, minsungryu commented on src/main/java/nextstep/subway/line/application/LineService.java
> +        persisLine.update(lineRequest.toLine(upStation, downStation));
persis 오타가 있는 것 같네요!
개인적으로 `persistLine`은 `노선을 저장하라`는 메서드명같은 느낌이 드는데요
`line`만으로도 충분하지 않을까 싶은 생각이 드네요~

2021-12-01 10:44 UTC, minsungryu commented on src/main/java/nextstep/subway/line/dto/LineRequest.java
> +    private Long upStationId;       // 추가
불필요한 주석은 제거해주시는게 좋지 않을까요?

2021-12-01 10:44 UTC, minsungryu commented on src/main/java/nextstep/subway/section/domain/Sections.java
> +    private Station getFirstStation(Map<Station, Station> sortedStations) {
코드를 이해하기 다소 어려운 느낌이 드는데요
`Section`을 활용해볼 수는 없을까요?
`add`하는 과정에서 정렬을 한다면 `get`과정이 조금 더 편할 수도 있겠다는 생각이 드네요.
또는 `Comparable` 인터페이스를 구현한다면 로직이 더 간단해질 수도 있지 않을까요?

2021-12-01 10:44 UTC, minsungryu commented on src/main/java/nextstep/subway/station/domain/Station.java
> +        return Objects.equals(id, station.id) && Objects.equals(name, station.name);
개체는 id만으로 동등성 검사를 하는게 좋지 않을까요?
아래 포스트를 읽어보시면 도움이 될 것 같습니다.
https://jaeyeolshin.github.io/2016-02-06/difference-between-entity-and-value-object/

2021-12-01 10:44 UTC, minsungryu commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +        response.body("name", hasItems("신분당선", "3호선"));
요구사항이 변경된 것에 대한 인수 테스트 변경은 없는걸까요?

2021-12-02 16:09 UTC, vvshinevv commented
안녕하세요? 먼저 아낌없는 리뷰 감사드립니다!
먼저 `Sections` 클래스에서 말씀해주신 `Section` 클래스를 활용해보면 어떻냐는 말씀에 깊이 생각을 해봤는데,
제가 어떻게 구현을 해야할지 감이 잘 오지 않았습니다.


그래서 조금 개선을 해봤는데,
```
private Station getFirstStation() {
        List<Station> upStreamStations = sections.stream().map(Section::getUpStation).collect(Collectors.toList());
        List<Station> downStreamStations = sections.stream().map(Section::getDownStation).collect(Collectors.toList());

        return upStreamStations.stream()
                .filter(upStreamStation -> !downStreamStations.contains(upStreamStation))
                .findFirst()
                .orElseThrow(IllegalArgumentException::new);
}
```
먼저 `상행역`, `하행역` 리스트를 각각 생성하고, `하행역` 리스트에 `상행역`을 찾아서 반환해 주도록 했습니다.
왜냐하면 `하행역`에 포함되지 않는다면 결국 가장 처음으로 시작하는 역일 것이라고 생각했기 때문입니다.
그리고 그 상행역부터 Map 자료구조를 활용해서 하행역까지 리스트를 만들어주도록하였습니다.

제 머리에선 이게 가장 최선인데.. 좀 더 간단하게 할 수 있는 방법이 있을까요? ✍️

2021-12-03 12:10 UTC, minsungryu commented
안녕하세요 홍희님!
제가 코멘트 설명이 조금 부족했던 것 같습니다.
잦은 조회로 인한 성능 하락을 방지하고자 `Map`을 사용하셨던 걸로 기억하는데요,
저는 성능도 중요하지만 일단은 학습 과정에서 객체의 협력을 통해 문제를 풀어나가길 바라는 마음에
`Section` 개체를 직접 활용하면 좋을 것 같다고 말씀을 드렸습니다.

리스트가 정렬된 (상행역 - 하행역) 구간을 가지고 있다면 큰 고민 없이 바로 첫 번째 요소를 반환해도 될텐데요,
추가하는 과정에 정렬하는 로직을 넣는다거나 `Comparable`을 구현하고 `SortedSet`과 같은 자료 구조를 활용해보는 방법도 있을 것이라 생각했습니다.
지금은 리스트가 정렬된 상태가 아니라고 본다면 홍희님이 하신 방법도 충분히 괜찮은 방법이라고 생각합니다.
물론 여기서도 성능을 생각한다면 상행역과 하행역을 `List` 대신 `Set`에 담아서 사용하는 방법도 있을 것 같긴 하네요.

그러던 중 문득 연결 리스트처럼 구간이 이전 구간과 다음 구간에 대한 포인터를 가지고 있다면 이 문제를 조금 더 쉽게 해결할 수도 있지 않을까란 생각도 들었습니다.
정답은 없겠지만 홍희님과 얘기를 나누면서 좋은 방법을 찾아가는 과정도 즐거운 것 같네요 :)

2021-12-03 12:12 UTC, minsungryu approved these changes
홍희님, ATDD 2단계 구현 잘 해주셨네요!
다음 단계 진행부탁드려요~
PR은 merge 하겠습니다!

2021-12-03 12:13 UTC, merged