Atdd4단계 리뷰 요청합니다.
next-step/atdd-subway-admin pull request #537
Opened 2021-12-01 05:43 UTC by nhs0912

안녕하세요. 구간 제거 미션 작성해서 제출합니다. 

리뷰 부탁드려요 :)

2021-12-02 17:00 UTC, 5minho requested changes
안녕하세요 희석님!
리뷰가 늦어서 죄송합니다ㅜ
4단계 미션 잘해주셨어요!
조금 더 개선해보면 좋을 것들 코멘트 달았는데요
확인 부탁드립니다!

2021-12-02 17:00 UTC, 5minho commented on src/main/java/nextstep/subway/line/domain/Line.java
> +        isLastOneSection();
마치 boolean 타입을 반환할거 같은 메서드명인데요! is, has 대신 앞에 check 같은 접두사를 붙이는건 어떨까요?

2021-12-02 17:00 UTC, 5minho commented on src/main/java/nextstep/subway/line/domain/Line.java
> +    public Sections sections() {
내부에서만 사용하는거 같은데 외부에 공개 하지 말고 `private` 으로 감춰보는건 어떨까요?

2021-12-02 17:00 UTC, 5minho commented on src/main/java/nextstep/subway/line/domain/Line.java
> +    public Section findSection(Station upStation, Station downStation) {
테스트에서만 사용하는 것이라면 접근제한자를 public 으로 제공하는 것보다는 default 로 두는 것도 좋을거 같아요

2021-12-02 17:00 UTC, 5minho commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +public class Sections {
일급컬렉션으로 리팩터링해보셨군요 👍

2021-12-02 17:00 UTC, 5minho commented on src/main/java/nextstep/subway/line/domain/Line.java
> +        }
sections 에서 역들을 가져와서 검사 하는것 보다는 sections 에게 물어보는건 어떨까요?
```
if(sections.contains(station)) {
    //...
}
```

2021-12-02 17:00 UTC, 5minho commented on src/main/java/nextstep/subway/line/domain/Section.java
> +    }
값 내부를 변경하면서 반환하는 메서드 구조는 좋은 구조가 아닙니다.
명령과 조회를 분리해보아요
[명령과 조회를 분리하라](https://goodgid.github.io/Clean-Code-Function-Separate-Commands-and-Inquiries/)

2021-12-02 17:00 UTC, 5minho commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +        }
중간역 일 때 두 개의 구간들을 삭제 하고 새로운 구간을 추가하는 식으로 하셨는데요.
잘하셨지만 구간 추가와 비슷한 구조로 리팩토링 해보면 어떨까요?

```
// 삭제할 수 없는 케이스 검사
// 중간역 수정
// 컬렉션에서 제거
```

구간 추가와 비슷한 구조라 코드파악하기도 좋고
지금은 두 개의 delete 쿼리와 하나의 insert 쿼리 총 3개의 쿼리가 나가게 되는데
위와 같이 변경하면 하나의 delete 쿼리와 하나의 update 쿼리가 나가서 성능상 이점도 있어요.

현재 로직이 테스트로 보호 받고 있으니 테스트가 보호해주는 상황에서 리팩토링하는 경험을 해보시면 좋을거 같습니다.

2021-12-04 03:45 UTC, nhs0912 commented on src/main/java/nextstep/subway/line/domain/Line.java
> +        isLastOneSection();
isLastOneSection() method의 뜻이 마지막 남은 section인지 아닌지를 판별하는 method인데요. 

checkLastOneSection() 이라고 이름을 짓는다면 check를 하긴 하는데 마지막 구간에 어떤 부분을 체크하는지가 명확해보이지 않아서 isLastOneSection() 이라고 이름을 지었거든요. 왜냐하면 is라는게 존재여부를 나타낸다고 생각해서요.(영어를 잘 못하지만 ㅠ) 

혹시 민호님 생각에는 is와 check를 구분하는 기준이 따로 있으실까요??

2021-12-04 04:13 UTC, nhs0912 commented on src/main/java/nextstep/subway/line/domain/Line.java
> +    public Sections sections() {
private으로 하는 것이 좋겠네요

2021-12-04 04:23 UTC, nhs0912 commented on src/main/java/nextstep/subway/line/domain/Line.java
> +    public Section findSection(Station upStation, Station downStation) {
getFirstStation() 와 getLastStation()는 SectionsTest에서만 사용하긴 하지만 default로 둔다면 같은 패키지 상에서만 사용할 수가 있는데요. 제 생각에는 public으로 해야할거 같은데 default로 두어야하는 이유를 더 자세히 들을 수 있을까요??

2021-12-05 06:50 UTC, 5minho commented on src/main/java/nextstep/subway/line/domain/Line.java
> +        isLastOneSection();
저도 영어를 잘하지 못합니다 ㅎㅎ 
제가 위의 피드백을 드린이유는 관례상 [조건자가 is](https://github.com/Yooii-Studios/Clean-Code/blob/master/Chapter%2002%20-%20%EC%9D%98%EB%AF%B8%20%EC%9E%88%EB%8A%94%20%EC%9D%B4%EB%A6%84.md#%EB%A9%94%EC%84%9C%EB%93%9C-%EC%9D%B4%EB%A6%84) 로 시작하기 때문이에요.  
어느정도 관례를 따라 준다면 동료들과 협업하기 좋지 않을까요?

저는 boolean 으로 반환하는 메서드는 (is, has, should 같은 접두사를 붙이고)
내부에서 조건에 맞지 않을때 예외를 발생시키는 메서드는 (check, validate 같은 접두사를 붙여요)

2021-12-05 07:27 UTC, 5minho commented on src/main/java/nextstep/subway/line/domain/Line.java
> +    public Section findSection(Station upStation, Station downStation) {
희석님과 협업하는 개발자들은 findSection 이 테스트 용으로 만든건지 아니면 서비스 요구사항을 구현하기 위해 만들어진건지 모릅니다.
그냥 사용해버릴수 있죠. 근데 findSection 이 지금 테스트로 보호 받는 상황도 아니고 굳이 테스트를 위한 메서드가 외부에서 호출되는것 보다 그걸 방지하는게 더 좋지 않을까요?

그리고 테스트 코드 패키지와 프로덕트 코드 패키지는 맞추어 도메인 테스트와 인수테스트를 분리하는게 좋아보여요.
도메인 테스트는 스프링 관련 설정이 없는 순수한 자바 객체 테스트라 테스트가 빠르고, 인수테스트는 그렇지 않아 느리다는 특징이 있는데요.
때문에 도메인테스트와 인수테스트를 분리하여 테스트를 실행하는 시점을 다르게 하면 장점이 있습니다.
예를 들면 빌드시 마다 도메인테스트만 실행하게 해서 빠르게 개발하고, PR 을 생성할때는 인수테스트까지 포함되어 실행하게 해서 이런식으로 운영할 수 도 있고요.

2021-12-05 07:44 UTC, 5minho approved these changes
안녕하세요 희석님!
피드백 반영 확인했습니다~
마지막 단계까지 고생많으셨어요!
남은 미션도 화이팅입니다!!!

2021-12-05 07:44 UTC, 5minho commented on src/main/java/nextstep/subway/line/domain/Distance.java
> +    public int minus(Distance distance) {
```
public Distance minus(Distance distance) {
    return new Distance(this.distance - distance.distance);
}
```

Distance 를 리턴하면 유효성 검사까지 한꺼번에 할 수 있어서 좋은거 같아요

2021-12-05 07:44 UTC, 5minho commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +                    .filter(it -> it.getUpStation() == station)
`it.equalUpStation(station)`
getter 를 사용하지 않고 이런식으로 객체에게 물어봐도 좋을거 같습니다.

2021-12-05 07:44 UTC, merged

2021-12-08 10:33 UTC, nhs0912 commented on src/main/java/nextstep/subway/line/domain/Line.java
> +    public Section findSection(Station upStation, Station downStation) {
그렇네요! 테스트의 종류에 따라 속도의 차이가 있으니깐 이런 부분을 고려하면 좋겠네요! 
다음 미션부터는 고려해서 구현해볼게요! 감사합니다 :)