Step4 : 구간 제거 기능
next-step/atdd-subway-admin pull request #545
Opened 2021-12-02 17:56 UTC by codeleesh

안녕하세요 리뷰어님!
날씨가 많이 쌀쌀해졌습니다. 건강 조심하세요!

Step4 : 구간 제거 기능 구현을 하였습니다.
이야기해주신데로 큰 어려움없이 구현을 하였는데, 
Cascade에 관해서 기존 ALL로 되어 있는 부분이 너무 포괄적인것 같아서 PERSIST와 REMOVE로 설정하였습니다.

2가지 여쭤보고 싶은 부분이 있습니다.
첫번째는 Cascade 옵션 설정하는 부분에서 ALL을 실제 현업에서 사용하는 케이스가 있는지 궁금합니다..
두번째는 인수테스트를 작성하면서 느낀 부분인데, 지하철 구간 삭제까지 오다보니 인수테스트를 위한 행사코드가 너무 많아진 느낌이었습니다.
지하철 구간 삭제를 위해서는 지하철 역 등록, 노선 등록, 구간 등록 등의 코드들이 필요하고 중복처럼 느껴지는데요. 해당 부분들을 제거하고 진행하자니 전체 시나리오가 연결이 되지 않는것처럼 느껴집니다. 실제 현업에서 어떻게 사용하시는 코멘트해주실수 있으실까요?

그럼 소중한 리뷰 기다리고 있겠습니다.
감사합니다.

2021-12-03 15:42 UTC, jhhj424 commented
> 안녕하세요 리뷰어님! 날씨가 많이 쌀쌀해졌습니다. 건강 조심하세요!

날이 정말 추워졌네요 ㅠ
어제부터 조금 감기가 걸려서 불편한 상태입니다.. ㅋㅋ :( 
상호님은 몸관리 잘 하셔서 무탈하시길 바라겠습니다 !!

> Step4 : 구간 제거 기능 구현을 하였습니다. 이야기해주신데로 큰 어려움없이 구현을 하였는데, Cascade에 관해서 기존 ALL로 되어 있는 부분이 너무 포괄적인것 같아서 PERSIST와 REMOVE로 설정하였습니다.
> 
> 2가지 여쭤보고 싶은 부분이 있습니다. 첫번째는 Cascade 옵션 설정하는 부분에서 ALL을 실제 현업에서 사용하는 케이스가 있는지 궁금합니다.. 

Casecade를 고민해보셨군요~ 👍 

일단 저는 오히려 Casecade를 사용할때는 보통 Casecade ALL 을 사용하는 편입니다.
이유는 완전히 A 객체 하위에 B 객체가 종속되어서 완전히 라이프 사이클이 같을때만 사용하기 때문입니다.
이렇지 않은 관계에서 Casecade 를 사용하게되면 추 후에 관리하기 힘들어질거라고 생각이 되네요~

위의 경우가 아니라면 보통 Persist 정도만 사용해서 같이 저장되도록 구현하고 나머지는 보통 잘 사용안하게 되네요... :)

관련해서 DDD(도메인 주도 설계) 의 Aggregate 라는 개념과 Aggregate Root 를 찾아보시면 도움이 될 것 같고, Aggregate Root 와 하위 엔티티의 관계에서 라이프사이클이 동일할때 사용하는걸로 저는 보통 정의내리고 있습니다 !!

애매하다고 판단된다면 그냥 사용 안하시는것이 복잡도를 줄이는데 도움이 되기도 할 것 같습니다 👍 

> 두번째는 인수테스트를 작성하면서 느낀 부분인데, 지하철 구간 삭제까지 오다보니 인수테스트를 위한 행사코드가 너무 많아진 느낌이었습니다. 지하철 구간 삭제를 위해서는 지하철 역 등록, 노선 등록, 구간 등록 등의 코드들이 필요하고 중복처럼 느껴지는데요. 해당 부분들을 제거하고 진행하자니 전체 시나리오가 연결이 되지 않는것처럼 느껴집니다. 실제 현업에서 어떻게 사용하시는 코멘트해주실수 있으실까요?

좋은 고민을 해주셨네요 ~
지금까지 단계별로 미션을 진행하면서 앞선 작업들이 다 필요했기 때문에 그렇게 작성해주셨고, 이런 고민을 남겨주신걸로 보입니다.
일단 삭제의 경우 앞선 작업들이 다 필요하기 때문에 픽스처들을 작성하는건 어쩔 수 없다고 생각합니다.
혹시 이런 중복이 싫으시다면 완전히 하나의 시나리오 사이클이 완벽하게 개발이 완료되면 중복된 앞선 테스트를 제거하고, 전체 시나리오를 테스트하는 인수테스트만 남겨놓아도 될 것 같습니다.
인수 테스트에 더해서 기능 단위 테스트도 같이 있으면 좋겠네요 ~

이렇게만 작성되어있어도 추후에 리팩터링이나 기능추가시 문제될 것 같지 않네요 :)

2021-12-03 16:03 UTC, jhhj424 requested changes
안녕하세요 상호님~
마지막 단계까지 잘 작성해주셨네요 💯 
질문사항에 대해서 코멘트 남겼습니다, 그리고 마지막이니 만큼 조금 더 생각해보거나 정리해보면 좋을만한 점 코멘트 남겼으니 같이 확인 부탁드리겠습니다 :)
금방 수정 가능하실 것 같으니 한번만 더 요청드리겠습니다 👍 
정말 날이 많이 추워졌는데 상호님도 건강 조심하세요 ㅎㅎ

2021-12-03 16:03 UTC, jhhj424 commented on src/test/java/nextstep/subway/section/domain/SectionsTest.java
> +        final Station 구의역 = new Station(4L, "구의역", 노선);
지금 보니 여기서 사용되고있는 `노선`이라는 객체의 의미때문에 보기 조금 헷갈리네요
조금 더 명확하게 무슨 노선인지 드러내주면 읽기 더 좋을 것 같아요 :)

2021-12-03 18:10 UTC, codeleesh commented on src/test/java/nextstep/subway/section/domain/SectionsTest.java
> +        final Station 구의역 = new Station(4L, "구의역", 노선);
네 노선이 주는 의미가 명확하지 않는것 같습니다! 여기에서는 `이호선`이라는 의미를 주는 것이 명확해보입니다!

2021-12-03 18:10 UTC, codeleesh commented on src/test/java/nextstep/subway/section/domain/SectionsTest.java
> +    @DisplayName("노선에 종점이 제거되면 다음으로 오던 역이 종점이 된다.")
네 의미가 테스트 하려는 메소드와 맞지 않은것 같아서 좀 더 풀어서 적었습니다!

2021-12-03 18:11 UTC, codeleesh commented on src/test/java/nextstep/subway/section/domain/SectionTest.java
> +    @DisplayName("노선에 종점이 제거되면 다음으로 오던 역이 종점이 된다.")
네 해당 메소드가 테스트 하려는 의미와 맞지 않은것 같아서 좀 더 풀어서 적었습니다!

2021-12-03 18:12 UTC, codeleesh commented on src/main/java/nextstep/subway/section/domain/Sections.java
> +    private boolean adUpStationAndMiddlStation(Section targetSection, Section original) {
감사합니다.

2021-12-03 18:27 UTC, codeleesh commented on src/main/java/nextstep/subway/section/domain/Section.java
> +    @ManyToOne(fetch = FetchType.LAZY, cascade = {CascadeType.PERSIST, CascadeType.REMOVE})
네 이해하였습니다! 연습을 좀 더 해봐야겠습니다! 공유해주셔서 감사합니다. 
현재 Section에서 Cascade를 잘못 설정한것 같습니다.

2021-12-04 12:56 UTC, jhhj424 approved these changes
안녕하세요 상호님~ 🙇🏻‍♂️
마지막 미션 피드백 요구사항까지 꼼꼼하게 완료해주셨네요 💯 
항상 꼼꼼하게 피드백 반영 해주시느라 고생 많으셨습니다 :)
이번 미션은 여기까지지만 언제든 궁금하신점이 있다면 DM 주세요~
앞으로의 미션들도 응원하도록 하겠습니다 👊

2021-12-04 13:38 UTC, merged