Step4 - 구간 제거 기능
next-step/atdd-subway-admin pull request #551
Opened 2021-12-03 16:41 UTC by lewisseo91

안녕하세요~!

구간 제거 기능 기능 완성하고 PR 보냅니다.

저번 단계에서 한글 변수로 바꾸는 것을 추천 해 주셔서 바꿔보고 가독성이 더 좋아지는 것 같아
나름대로 Fixture 부분이나 필요할 것 같다고 생각되는 부분들을 한글 이름으로 바꾸어 보았습니다.

잘 부탁드립니다~!

2021-12-04 16:35 UTC, 5minho requested changes
안녕하세요 동현님!
저번 피드백 반영, 4단계 미션 다 잘해주셨네요!!
조금 개선해보면 좋을만한 점 코멘트 달았는데요~
확인부탁드립니다!

2021-12-04 16:35 UTC, 5minho commented on src/test/java/nextstep/subway/section/domain/SectionTest.java
> +    }
꼼꼼하게 테스트 하시는거 좋네요 👍

2021-12-04 16:35 UTC, 5minho commented on src/test/java/nextstep/subway/line/domain/SectionsTest.java
> +    }
성공 케이스도 한번 테스트 해보면 어떨까요?
```
@DisplayName("구간 사이에 있는 역을 제거할 수 있다.")
```

2021-12-04 16:35 UTC, 5minho commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +    private StationResponse 강남역;
이번에 테스트에서 한글 변수명을 써보신 선택은 괜찮은 선택같아요!
꼭 가독성 뿐만 아니더라도 동현님께서 미션중에 이런시도 저런시도 해보시는것 자체가 좋은거 같습니다. 👍

2021-12-04 16:35 UTC, 5minho commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +        removeSectionIfStationExist(station);
두 개의 구간들을 삭제 하고 새로운 구간을 추가하는 식으로 해보셨군요!! 👍
물론 잘하셨지만 구간 추가와 비슷한 구조로 리팩토링 해보면 어떨까요?

1. 삭제할 수 없는 케이스 검사
2. 중간역 수정
3. 컬렉션에서 제거

구간 추가와 비슷한 구조라 코드파악하기도 좋고
지금은 두 개의 delete 쿼리와 하나의 insert 쿼리 총 3개의 쿼리가 나가게 되는데
위와 같이 변경하면 하나의 delete 쿼리와 하나의 update 쿼리가 나가서 성능상 이점이 있어요.

일단 Sections 도메인 테스트에 역 제거 테스트를 작성하고 테스트가 보호해주는 상황에서 리팩토링을 해보시는 경험을 한번 해보셨으면 좋겠습니다!

2021-12-04 16:35 UTC, 5minho commented on src/main/java/nextstep/subway/line/domain/Sections.java
>  package nextstep.subway.line.domain;
지금 Sections 는 line 패키지내에 있고 Section 과 Distance 는 section 패키지내에 있던데요.
제 생각에는 section 자체가 line 에 종속적인 도메인이라고 생각되어 section 패키지가 따로 있는것 보다 section 이 line 패키지 내에 있어도 될 거 같아요.

2021-12-04 17:21 UTC, lewisseo91 commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +        removeSectionIfStationExist(station);
좋은 제안 감사합니다!
바로 시도 해 보겠습니다~

2021-12-04 17:22 UTC, lewisseo91 commented on src/main/java/nextstep/subway/line/domain/Sections.java
>  package nextstep.subway.line.domain;
맞습니다!
이 부분도 좋은 피드백 감사합니다~!

2021-12-04 18:21 UTC, lewisseo91 commented
안녕하세요~

말씀해 주신 피드백들을 되새겨 보면서 코드를 수정한 후 재요청 드립니다.

첫 업로드 때는 update 후 remove 방식이 로직을 생각하다가 꼬여서 안 될 것 같다고 생각했지만
말씀해 주신 이후로 다시 해 보니 더 깔끔하고 query도 덜 발생하는 좋은 방식인 것을 알게 되었습니다.

좋은 피드백 많이 주셔서 정말 감사합니다!

2021-12-05 20:33 UTC, 5minho approved these changes
안녕하세요 동현님!
피드백 반영해주신거 확인했습니다~
이번 미션 진행 해주시느라 고생 많으셨고
앞으로 남은 미션도 화이팅입니다!!!

2021-12-05 20:34 UTC, 5minho commented
> 안녕하세요~
> 
> 말씀해 주신 피드백들을 되새겨 보면서 코드를 수정한 후 재요청 드립니다.
> 
> 첫 업로드 때는 update 후 remove 방식이 로직을 생각하다가 꼬여서 안 될 것 같다고 생각했지만 말씀해 주신 이후로 다시 해 보니 더 깔끔하고 query도 덜 발생하는 좋은 방식인 것을 알게 되었습니다.
> 
> 좋은 피드백 많이 주셔서 정말 감사합니다!

다른 방식으로 하는게 귀찮으셨을 수도 있는데 흔쾌히 피드백 반영해주셔서 감사드립니다!
정말 고생하셨고 마지막 미션까지 화이팅입니다!!

2021-12-05 20:34 UTC, merged