4단계 - 구간 제거 기능
next-step/atdd-subway-admin pull request #561
Opened 2021-12-05 08:27 UTC by sungdukim

안녕하세요 동환님,

드디어 마지막 4단계네요. 진행이 너무 느려서 리뷰 주시느라 너무 고생하셨습니다!!

3단계에서 주셨던 피드백 반영해서 공통 로직을 추출해봤는데, 서비스 간 참조를 피하면서 공통 로직을 어떻게 추출하면 좋을지는 아직 확신이 없어요. `LineService`가 `SectionService`를 의존하게 변경해봤어요. `findLineById` 메소드도 어떻게 보면 `line` 패키지내에서는 계속 쓰일 것 같은데, 이런것들도 다 추출하시는지 (만약 한다면 어디로) 궁금합니다!

그럼 마지막 남은 미션도 잘부탁드리겠습니다! 😁

2021-12-06 05:08 UTC, na-mul requested changes
안녕하세요 성두님.
4단계도 정말 깔끔히 잘 진행해주셨습니다. 👍
approve해도 문제없을 완성도이지만, 
그래도 조금 더 의견을 교류하며 성장을 도와드리고 싶은 마음에 request change를 한번 요청드려요!
소소하지만 코멘트들을 참고하셔서 한번 수정해주셔서 다시 reqeust 올려주시면 감사하겠습니다. 🙇‍♂️

2021-12-06 05:08 UTC, na-mul commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +    public void deleteStation(final Station station) {
로직은 훌륭히 잘 개발해주신 것 같아요! 👍

2021-12-06 05:12 UTC, na-mul commented
> 3단계에서 주셨던 피드백 반영해서 공통 로직을 추출해봤는데, 서비스 간 참조를 피하면서 공통 로직을 어떻게 추출하면 좋을지는 아직 확신이 없어요. LineService가 SectionService를 의존하게 변경해봤어요. findLineById 메소드도 어떻게 보면 line 패키지내에서는 계속 쓰일 것 같은데, 이런것들도 다 추출하시는지 (만약 한다면 어디로) 궁금합니다!

이 질문에 대해서도 추가로 말씀드리지자면, `findLineById`는 다른 곳에서도 (이를테면 SectionService) 사용하면 물론 좋겠지만,
의존성을 양방향으로 맺을 수 없을 거에요
(LineService에서 SectionService를 주입받는 동시에 SectionService에서도 LineService를 주입받을 수는 없습니다.)

그리고 line 패키지에서 어찌보면 LineService가 가장 대표(root) 도메인과 관련되어 있으므로 이왕 의존성을 설정한다면 LineService에서 SectionService를 주입받는 것이 나을 것입니다. 

즉 정리드리자면 `findLineById`는 어쩔수 없이 추출하지는 않는다.. 로 정리해볼 수 있겠네요!

2021-12-06 15:08 UTC, sungdukim commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +            final Section downSection = maybeDownSection.get();
`Optional`이 익숙하지 않아서 의도하신대로 피드백을 잘 반영한건지 모르겠어요. `Sections::deleteStation` 메소드에서 `sections`를 두번만 순회하려고 하다보니 (upSection, downSection) Optional을 갖고 있게 되네요... 🤔

2021-12-06 15:08 UTC, sungdukim commented on src/main/java/nextstep/subway/line/application/SectionService.java
>      private final StationRepository stationRepository;
너무 좋은 피드백 감사합니다!! 한가지 궁금한점은

> StationRepository를 직접 호출하기보다는 StationService를 호출하는 편이 일반적으로 더 낫습니다.

은 어떤 의미일까요?

제가 단순하게 생각했을때는 
- `StationRepository`가 `StationService`에 비해 변경 될 일이 적지 않을까?
- `StationService`가 분리되어 여러 곳에서 공통으로 사용되기보다는 특정 DTO를 반환하는 하나의 유즈케이스가 된다면?

와 같은 의문이 들어서요! 

한편 `Line`에서 `StationRepository`를 직접 접근해서 사용하는건 `Station`의 영역을 침범하는 것 같기도 하구요. 피드백 기다려보겠습니다~ 😁

2021-12-06 15:09 UTC, sungdukim commented on src/main/java/nextstep/subway/line/application/LineService.java
>          return lines.stream()
`@Transactional(readOnly = true)` 애노테이션이 실제로 데이터를 쓰는 행위가 발생했을 때 예외를 발생시키지는 않아서 굳이 사용해야하는가에 대한 의문이 있었는데, 그보다 얻는 득이 많아 보이기도 하네요! 좋은 피드백 감사합니다. 👍

2021-12-06 15:09 UTC, sungdukim commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +    public void deleteStation(final Station station) {
구간을 찾는 로직과, 두 구간을 합치는 로직을 분리해봤습니다.

2021-12-06 15:09 UTC, sungdukim commented on src/main/java/nextstep/subway/line/application/SectionService.java
> +
이런 사소한(?) 의사 결정도 앞으로는 잘 챙겨봐야겠습니다. 감사합니다! 👍

2021-12-06 15:16 UTC, sungdukim commented
이번 미션도 그냥 끝내시지 않고 너무 좋은 피드백주셔서 감사합니다!! 👍👍

https://github.com/next-step/atdd-subway-admin/pull/561#discussion_r763094077 피드백 주신것에 대해서 궁금한점이 있어 다시 질문을 하나 드렸는데, 동환님 의견을 듣고 정리해서 반영해보려고합니다. 피드백을 바로 적용하는것보다는 한번 더 짚고 넘어가면 도움이 될 것 같아서요! 끝이 아쉬워서일지도... 😅  ㅋㅋㅋㅋ

2021-12-06 23:38 UTC, na-mul commented on src/main/java/nextstep/subway/line/application/SectionService.java
>      private final StationRepository stationRepository;
> StationRepository가 StationService에 비해 변경 될 일이 적지 않을까?

물론 `StationRepository`를 직접 사용하는 편이 물론 단계를 하나 생략하는 것이기 때문에 오히려 코드의 변경 가능성이 적을 거에요.
하지만 StationRepository를 직접 사용하게 되면, 추후 Station을 어디서 변경시키는 지 추적이 너무 어려워집니다. 마치 변수를 public으오 열어두고 getter도 사용하지 않고 그대로 참조해서 쓰는 느낌이죠.

그래서 Service를 거쳐서 일부러라도 한번 로직을 거치게 하고 쓰곤 합니다. 

```
    private List<Station> getStations(final Long upStationId, final Long downStationId) {
        final List<Station> stations = stationRepository.findAllById(
            Arrays.asList(upStationId, downStationId)
        );
        if (stations.size() != 2) {
            throw new NoSuchElementException();
        }
        return stations;
    }

```
위 메소드는 `SectionService` 있는 메소드지만, 메소드만 봤을 때는 꼭 `StationService`에 있을 것만 같죠.
StationRepository를 직접 가져다 쓰는 것을 허용하게 되면, 이렇게 로직이 이곳저곳 흩어지게 되는 것 같아요.

> StationService가 분리되어 여러 곳에서 공통으로 사용되기보다는 특정 DTO를 반환하는 하나의 유즈케이스가 된다면?
이 질문은 제가 잘 이해하지 못한 것 같아요. 좀 더 상세히 설명해주실 수 있으실까요?

2021-12-06 23:38 UTC, na-mul commented on src/main/java/nextstep/subway/line/application/SectionService.java
>      private final StationRepository stationRepository;
> StationService가 분리되어 여러 곳에서 공통으로 사용되기보다는 특정 DTO를 반환하는 하나의 유즈케이스가 된다면?

이 질문은 제가 잘 이해하지 못한 것 같아요. 좀 더 상세히 설명해주실 수 있으실까요?

2021-12-07 01:02 UTC, sungdukim commented on src/main/java/nextstep/subway/line/application/SectionService.java
>      private final StationRepository stationRepository;
아하, 어떤 의미로 말씀해주신 줄 잘 알겠어요! 제가 고민했던 부분은, 만약 `지하철역의 목록을 조회한다`라는 요구 사항이 있을 때  A라는 서비스와 B라는 서비스에서 말하는 `지하철역의 목록`이 다를 수 있다고 생각했습니다. 특히나 지금처럼 패키지가 다른 경우에는 거의 다르지 않을까? 라는 생각이었어요. 예를 들어, 서비스 A에서는 DB에 있는 모든 지하철의 역을 조회하고 싶고, 서비스 B에서는 위의 상황과 같이 상행역, 하행역 두개만을 담은 지하철역의 목록이 될 수 있는 것 처럼요.

글로 적다보니 서비스의 책임을 잘 분리하고 `지하철 목록 조회`와 같은 네이밍보다는 뭔가 더 구체적인 메소드명을 짓는게 좋겠다는 결론으로 도달하는 것 같네요. 🤣

2021-12-07 01:03 UTC, sungdukim commented on src/main/java/nextstep/subway/line/application/SectionService.java
>      private final StationRepository stationRepository;
해당 부분은 저녁에 작업해서 올려보도록 하겠습니다! 🙏🙏

2021-12-07 03:06 UTC, na-mul commented on src/main/java/nextstep/subway/line/application/SectionService.java
>      private final StationRepository stationRepository;
과제에 대해 깊이 고민해주셔서 정말 감사합니다. 

> 예를 들어, 서비스 A에서는 DB에 있는 모든 지하철의 역을 조회하고 싶고, 서비스 B에서는 위의 상황과 같이 상행역, 하행역 두개만을 담은 지하철역의 목록이 될 수 있는 것 처럼요.

이건 결국  지하철역의 목록을 제공하는 `StationService` 쪽에서 두가지의 요구사항을 다 만족시키는 부분을 각각 만들어줘야합니다. 서비스A와 B의 요구사항이 서로 다르다고 로직을 아에 서비스A와 B에서 만들도록 해버리면 안되는 것이지요.
사실 그러면 너무 서비스 의존적인 로직이 `StationService` 에 많아지게 됩니다. 

사실 이제부터는 정답이 있다기보다는 이런 견해도 있다는 의견으로 받아들여주시면 좋겠습니다.
클린 아키텍처와 헥사고널 아키텍처 등을 보면 그런 고민이 잘 드러나 있긴 합니다.
지금 저희가 하고있는 전통적인 계층형 아키텍처와는 다른 지향점을 가지고 있어, 이번 과제에서 바로 적용하기는 어려울거에요.
한번 참고삼아 공부만 해두면 좋을 것 같습니다.
(https://engineering-skcc.github.io/microservice%20inner%20achitecture/inner-architecture-2/)

2021-12-07 03:12 UTC, na-mul commented on src/main/java/nextstep/subway/line/domain/Sections.java
>  }
이 부분부터는 저도 제 개인적인 생각으로 받아들여주시면 좋겠어요.

```
    private List<Section> getUpDownSection(final Station middleStation) {
        return Stream.concat(
                sections.stream()
                        .filter(s -> Objects.equals(s.getUpStation(), middleStation)),
                sections.stream()
                        .filter(s -> Objects.equals(s.getDownStation(), middleStation)))
                .collect(Collectors.toList());
    }
```

이런 느낌으로 한번에 상행종점과 하행종점을 List로 받고, size를 체크하는 것으로  ifPresent나 get를 대체할 수 있을지도 모릅니다. 

위의 코드가 정답이라기보다는 그냥 이런 방법도 있겠구나.. 정도로 사고를 열어두는 방향으로만 참고 부탁드릴게요 ㅎㅎ

2021-12-07 11:41 UTC, sungdukim commented on src/main/java/nextstep/subway/line/application/SectionService.java
>      private final StationRepository stationRepository;
마지막까지 함께 고민해주셔서 너무 감사합니다! 평상시에 크게 신경쓰지 않던 부분인데 동환님과 얘기 나누면서 정리가 많이 된 것 같고, 앞으로 생각해볼거리들도 함께 주셔서 아주 좋은 경험이었습니다. 헥사고널 아키텍처를 적용해본적은 없는데 조만간 한번 시도해봐야겠어요. 👍 👍

2021-12-07 12:14 UTC, sungdukim commented on src/main/java/nextstep/subway/line/domain/Sections.java
>  }
오호, 이런 방법이 있었네요! 좋은 아이디어 같아서 한번 적용해봤어요. 👍 👍

2021-12-08 15:08 UTC, na-mul approved these changes
안녕하세요, 성두님. 
4단계 approve해도 문제 없을 것 같습니다. 긴 미션 고생 많으셨습니다. 
이번 미션이 성두님의 성장에 보탬이 되었기를 바랍니다. 😊
남은 3주간의 과정도 잘 마무리하실 수 있기를 희망합니다 ^^

2021-12-08 15:08 UTC, na-mul commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +        final Section downSection = upDownSections.get(DOWN_SECTION_INDEX);
수정하시는데 고생이 많으셨습니다.

다만 별도의 상수를 정의해야만 List에서 Section을 의미있게 꺼낼 수 있는 것은 아무래도 조금 아쉽게 느껴집니다.
코드가 복잡하긴 한 상황인거죠.
하지만 저 역시 현 상황에서 성두님이 작성해주신 것 보다 더 나은 코드를 상상하기는 어렵습니다.

현재의 코드가 이전의 Optional을 활용한 코드보다 더 나을까, 아니면 그렇지 않을까
무엇이 더 클린한 코드에 가까울까.. 항상 고민이 되곤 합니다.

상두님의 고민과 성장을 응원합니다! 😊

2021-12-08 15:08 UTC, merged

2021-12-09 13:52 UTC, sungdukim commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +        final Section downSection = upDownSections.get(DOWN_SECTION_INDEX);
> 다만 별도의 상수를 정의해야만 List에서 Section을 의미있게 꺼낼 수 있는 것은 아무래도 조금 아쉽게 느껴집니다.

저도 코드 변경하면서 이 부분이 제일 맘에 걸렸는데, 트레이드 오프의 하나겠죠? 정말 감사합니다!