Step1 - 지하철역 인수 테스트 작성
next-step/atdd-subway-admin pull request #591
Opened 2022-05-20 09:21 UTC by heowc

지하철역 인수 테스트 작성 PR 입니다.

2022-05-20 16:13 UTC, dhmin5693 requested changes
안녕하세요, 원철님.
ATDD 미션을 함께하게 된 민동휘라고 합니다.
벌써 3번째 미션이라니 미션에 대한 열정이 넘치시는군요 👍 

첫 번째 미션 코드를 가독성 좋게 잘 구성해주셨어요.
약간의 피드백을 남겼으니 확인 후 다시 리뷰요청 부탁드립니다.

2022-05-20 16:13 UTC, dhmin5693 commented on src/test/java/nextstep/subway/station/StationAcceptanceTest.java
> +        assertStatusCode(response, HttpStatus.CREATED);
Gradle Test 실행 시 테스트 메소드의 실행 순서에 따라 이 부분에서 테스트가 실패할 수 있습니다.
데이터베이스가 롤백되지 않은 상태로 다음 테스트가 실행되어 unique 해야 하는 name이 한 테이블에 두 개 이상 들어갈 수 있기 때문이에요.

1단계의 프로그래밍 요구사항에 `한 번에 실행하는 경우 실패할 수 있는 가능성`을 배제하라는 문구가 있지만,
간단하게 수정할 수 있는 부분이라 코멘트 남겨보았습니다.

2022-05-20 16:13 UTC, dhmin5693 commented on src/test/java/nextstep/subway/station/StationAcceptanceTest.java
> +    private static void assertStatusCode(ExtractableResponse<Response> response, HttpStatus badRequest) {
두 번째 매개변수명이 어색하네요.

2022-05-20 16:13 UTC, dhmin5693 commented on src/test/java/nextstep/subway/station/StationAcceptanceTest.java
> +    private static ValidatableResponse callCreateStation(String name) {
이 메소드 아래로 전부 static 메소드인데 혹시 static을 사용한 이유가 있으실까요?

2022-05-21 00:56 UTC, heowc commented on src/test/java/nextstep/subway/station/StationAcceptanceTest.java
> +    private static ValidatableResponse callCreateStation(String name) {
static을 사용하게 되면 상태가 변경되는 객체에 의존하지 않는다 (보통 상태가 변경되는 객체 등을 static으로 두지 않기 때문에) 라는 의미를 담을 수 있어서 주로 private static 메소드를 주로 작성하는 편입니다!

2022-05-21 00:56 UTC, heowc commented on src/test/java/nextstep/subway/station/StationAcceptanceTest.java
> +    private static void assertStatusCode(ExtractableResponse<Response> response, HttpStatus badRequest) {
툴로 메소드 분리하면서 미처 챙기지 못했네용 👍

2022-05-21 00:57 UTC, heowc commented on src/test/java/nextstep/subway/station/StationAcceptanceTest.java
> +        assertStatusCode(response, HttpStatus.CREATED);
메소드 시작전에 지하철 역을 모두 지우는 식으로 처리하겠습니다 :)

2022-05-21 03:16 UTC, dhmin5693 commented on src/test/java/nextstep/subway/station/StationAcceptanceTest.java
> +    private static ValidatableResponse callCreateStation(String name) {
상태가 변경되지 않는 객체를 static으로 두는건 자바의 메모리 공간 활용 방법 상 유리하기 때문입니다.
상태가 변경되지 않기 때문에 static으로 사용하는건 아닙니다.

static 메소드에 적용되는 별도의 컨벤션 규칙을 본 적이 없긴 합니다.
다만 보통 다른 static 메소드에서 참조하기 때문에 static 메소드로 만들거나, 다른 메소드에서 인스턴스 생성 없이 불러다 쓰는 목적으로 만들기 때문에 혼자만의 규칙인 경우 원철님이 생각하신 static 메소드의 의미 전달이 잘 안될 수 있다고 생각합니다.

2022-05-21 03:17 UTC, dhmin5693 approved these changes
수고 많으셨습니다.
코멘트 하나 남겼는데 나중에 확인 부탁드립니다 :)

다음 미션 진행해주세요.

2022-05-21 03:17 UTC, merged

2022-05-21 03:20 UTC, dhmin5693 commented on src/test/java/nextstep/subway/station/StationAcceptanceTest.java
> +        assertStatusCode(response, HttpStatus.CREATED);
제 의도는 다른 역 이름을 사용하는 것이었는데요,
지금 방법도 큰 상관은 없을듯 하네요 :)

2022-05-21 06:50 UTC, heowc commented on src/test/java/nextstep/subway/station/StationAcceptanceTest.java
> +    private static ValidatableResponse callCreateStation(String name) {
> 상태가 변경되지 않는 객체를 static으로 두는건 자바의 메모리 공간 활용 방법 상 유리하기 때문입니다.
> 상태가 변경되지 않기 때문에 static으로 사용하는건 아닙니다.

넵, 맞습니다.

> static 메소드에 적용되는 별도의 컨벤션 규칙을 본 적이 없긴 합니다.

제가 주로 컨트리뷰션 하는 오픈소스에는 사용할 수 없는 경우에는 컨벤션엔 없지만, 리뷰를 통해 inline method를 권장하는 편입니다. (위와 같은 경우가 아니라도 여러가지 측면이 있겠죠?) 그래서 습관적으로 static 키워드를 붙이는 것도 있습니다.

2022-05-21 06:56 UTC, heowc commented on src/test/java/nextstep/subway/station/StationAcceptanceTest.java
> +    private static ValidatableResponse callCreateStation(String name) {
1단계에도 리뷰를 받았던 내용인데... 계속 나오는 부분인거보니 지양하도록 하겠습니다 😅