Step2 - 지하철 노선 기능
next-step/atdd-subway-admin pull request #616
Opened 2022-05-25 13:39 UTC by KangSeongHyo

안녕하세요~

인수테스트 2단계 지하철 노선 기능 리뷰 부탁드립니다.

감사합니다.

--- 
하나 질문이 있습니다~!!
개별적인 인수테스트에 격리는 ``@Sql`` 을 이용해서 테이블을 DROP 하는 방식으로 
처리하였고 각각 실행시에는 정상적으로 테스트가 통과하도록 했습니다.

그런데 문제가 전체 테스트코드를 동시에 실행해보면 
노선 인수테스트가 먼저 실행되는 경우에는 전부 통과하지만

지하철역 인수테스트가 먼저 실행되는 경우 뒤늦게 실행된
노선 인수테스트에서 Table Drop 이 발생해서

지하철역 인수테스트 중 **기존에 역 이름이 있으면 오류 발생**  이부분에서 테스트 실패가 발생합니다. 중간에 데이터가 없어지면서 기존 역이름이 없어지는 경우인데요

테스트들은 결국 같은 DB를 바라보고 있어서 이부분을 어떻게 해야할지 고민을 해봤는데
각 테스트에 순서를 부여 할 수 있는지 찾아봤는데 제가 못찾은 건지 모르겠지만 ㅜㅜ
 이부분은 지금 프로젝트의 Junit 라이브러리 보다 상위 버전에만 있는것 같더라구요
  
아니면 제가 못찾은 다른 방식으로 테스트 클래스 간 이슈를 해결할 방법이 있는지 궁금합니다~!!

PS.
아니면 노선 인수테스트와 지하철역 인수테스트를 완전히 분리해야할까요?
노선 인수테스트시에 지하철역을 생성하는데 이부분이 FK로 연결되어  DROP Table (Station Line)으로 격리를 했는데
이 기능은 필요하다고 느껴지는데 노선 인수테스트에서는 제외를 해야하는 부분일까요?

2022-05-26 16:05 UTC, parkeeseul requested changes
피드백이 많이 늦었네요! 양해해 주셔서 감사합니다 🙏 
몇 가지 코멘트와 질문 주신 사항에 대한 저의 의견 남겨두었으니 확인해 보시고
궁금하신 점이 있다면 추가로 남겨주세요! 
즐거운 금요일 되시고 화이팅 입니다 🔥

2022-05-26 16:05 UTC, parkeeseul commented on src/main/java/nextstep/subway/application/LineService.java
> +    @Transactional
어떠한 차이가 있을까요? 😄 
```suggestion
    @Transactional(readOnly = true)
```

2022-05-26 16:05 UTC, parkeeseul commented on src/main/java/nextstep/subway/domain/collection/Stations.java
> +    public void addStaion(Station pangyo) {
변수명이 판교 인걸까요..? 🤔 
```suggestion
    public void addStation(Station pangyo) {
```

2022-05-26 16:05 UTC, parkeeseul commented on src/main/java/nextstep/subway/dto/LineResponseDTO.java
> +    private final List<StationResponseDTO> stations;
StationResponseDTO 는 지하철역 api 응답에서도 사용하고 있는데요, 재사용 되고 있네요  
지하철 노선의 응답을 확인해 주세요 😄

2022-05-26 16:05 UTC, parkeeseul commented on src/test/java/nextstep/subway/acceptance/LineAcceptanceTest.java
> +        params1.put("downStationId", 2);
생성한 역의 id 가 반드시  1, 2가 될꺼라는 보장이 있을까요? 😄

2022-05-26 16:05 UTC, parkeeseul commented on src/test/resources/drop_test_table.sql
> +CREATE TABLE LINE (ID BIGINT GENERATED BY DEFAULT AS IDENTITY, CREATED_DATE TIMESTAMP, MODIFIED_DATE TIMESTAMP, COLOR VARCHAR(255), DELETED BOOLEAN NOT NULL, NAME VARCHAR(255), PRIMARY KEY (ID));
DROP 을 하시는 이유가 있으신가요?
TRUNCATE 를 사용해보면 어떨까요? 😄

2022-05-26 16:05 UTC, parkeeseul commented on src/main/java/nextstep/subway/application/LineService.java
> +@Service
> Q. 테스트들은 결국 같은 DB를 바라보고 있어서 이부분을 어떻게 해야할지 고민을 해봤는데
> 각 테스트에 순서를 부여 할 수 있는지 찾아봤는데 제가 못찾은 건지 모르겠지만 ㅜㅜ
> 이부분은 지금 프로젝트의 Junit 라이브러리 보다 상위 버전에만 있는것 같더라구요
> 
> 아니면 제가 못찾은 다른 방식으로 테스트 클래스 간 이슈를 해결할 방법이 있는지 궁금합니다~!!

A. 테스트 간의 순서가 생긴다면 각각의 테스트는 독립적이라고 볼 수 없고 서로간에 의존하게 됩니다.
이렇게 되면 의존하고 있는 테스트가 수정이 되거나 실패할 경우에 독립되어져야 하는 다른 테스트가 영향을 받게 되면서
테스트 코드가 깨지게 되거나 어떤 부분이 잘못된 테스트인지 확인하기 어려워 지게 되는데요,
때문에 의존하지 않는 독립적인 테스트를 작성하는 것이 좋을 것 같아요.

> PS.
> 아니면 노선 인수테스트와 지하철역 인수테스트를 완전히 분리해야할까요?
> 노선 인수테스트시에 지하철역을 생성하는데 이부분이 FK로 연결되어 DROP Table (Station Line)으로 격리를 했는데
> 이 기능은 필요하다고 느껴지는데 노선 인수테스트에서는 제외를 해야하는 부분일까요?

Q. 코멘트를 남겨두었으니 한번 확인해 보시고 진행해 보시면 좋을 것 같아요
어려우신 부분이 있다면 코멘트 남겨주세요!  😄 
화이팅 입니다 🔥

2022-05-26 21:16 UTC, KangSeongHyo commented on src/main/java/nextstep/subway/application/LineService.java
> +    @Transactional
리뷰감사합니다~ 단순히 읽기 전용 설정이라고 생각했었는데 찾아보니
플러시가 발생하지 않아 쓰기 수정 삭제를 방지하고
수정이 없기 때문에 영속성 컨텍스트에서도 해당 엔티티들의 스냅샷을 생성하지 않아
성능향상에 도움을 주는군요~!! 
수정하도록 하겠습니다.

2022-05-26 21:17 UTC, KangSeongHyo commented on src/main/java/nextstep/subway/domain/collection/Stations.java
> +    public void addStaion(Station pangyo) {
앗.. 수정하겠습니다..

2022-05-27 01:20 UTC, KangSeongHyo commented on src/test/resources/drop_test_table.sql
> +CREATE TABLE LINE (ID BIGINT GENERATED BY DEFAULT AS IDENTITY, CREATED_DATE TIMESTAMP, MODIFIED_DATE TIMESTAMP, COLOR VARCHAR(255), DELETED BOOLEAN NOT NULL, NAME VARCHAR(255), PRIMARY KEY (ID));
TRUNCATE로 처리했을때 id Sequence 때문에 DROP으로 했었는데
제가 고민이 좀더 부족했었던 것 같습니다. 수정했습니다~!!

2022-05-27 01:22 UTC, KangSeongHyo commented on src/test/java/nextstep/subway/acceptance/LineAcceptanceTest.java
> +        params1.put("downStationId", 2);
불필요한 ID 검증은 제거했고
보장이 없는 리뷰에 힌트를 얻어 격리 처리에도
적용할수 있었습니다!! 감사합니다.

2022-05-27 01:25 UTC, KangSeongHyo commented on src/main/java/nextstep/subway/dto/LineResponseDTO.java
> +    private final List<StationResponseDTO> stations;
이부분은 inner class로 수정해보았는데 어떤가요?

일부러 코드를 재사용하려고 이렇게 많이 사용하곤 했는데 ㅜㅜ
생각해보니 StationResponseDTO 에서 API 필드가 변경되는경우
그대로 영향을 받겠군요! 하나 더 배워갑니다!!

2022-05-27 01:30 UTC, KangSeongHyo commented on src/main/java/nextstep/subway/application/LineService.java
> +@Service
이부분은 위에서 힌트를 얻어서 
각 인수 테스트의 사용하는 params도 영향이 가지않도록 별도로 분리했고

DB의 ID Sequence는 결국 두 인수테스트에 영향을 받기 때문에
불필요한 id 검증하는 부분이나 보장 되지 않는 ID 값을 직접 사용하는
부분들을 제거해보았습니다~!!
추가적으로 피드백 주시면 반영해보도록 하겠습니다! 리뷰 감사합니다!

2022-05-27 13:07 UTC, parkeeseul requested changes
피드백 잘 반영해 주셨네요! 👍 
몇 가지 추가 코멘트 남겨두었으니 확인 부탁드립니다 😄 
즐거운 주말 되세요! 🔥

2022-05-27 13:07 UTC, parkeeseul commented on src/main/java/nextstep/subway/application/LineService.java
> +        if (lineRequestDTO.getUpStationId() != null) {
upStationId 와 downStationId가 null 이면 어떻게 되나요? 🤔

2022-05-27 13:07 UTC, parkeeseul commented on src/main/java/nextstep/subway/application/LineService.java
> +        }
비슷한 코드가 중복되는데요, 중복을 제거해 볼 수 없을까요? 😄

2022-05-27 13:07 UTC, parkeeseul commented on src/test/java/nextstep/subway/test/DatabaseClean.java
> +    public void trancateAll() {
@_@ 매의 눈 ! 😄 
```suggestion
    public void truncateAll() {
```

2022-05-27 13:07 UTC, parkeeseul commented on src/test/java/nextstep/subway/acceptance/LineAcceptanceTest.java
> +        }
Station 을 truncate 하지 않고 위와 같이 해주시는 이유가 있으신가요? 😄

2022-05-27 13:21 UTC, KangSeongHyo commented on src/main/java/nextstep/subway/application/LineService.java
> +        if (lineRequestDTO.getUpStationId() != null) {
null인 경우에는 노선만 생성된 상태가 됩니다.

이부분은 고민해봤는데 노선을 먼저 만드는 후에 지하철을 연결하는 경우도 
있을 것 같아서 처리해보았습니다.~!

2022-05-27 13:22 UTC, KangSeongHyo commented on src/main/java/nextstep/subway/application/LineService.java
> +        }
메서드로 분리하였습니다!

2022-05-27 13:22 UTC, KangSeongHyo commented on src/test/java/nextstep/subway/test/DatabaseClean.java
> +    public void trancateAll() {
아.. 영알못이었네요 ㅜㅜ 수정했습니다!!

2022-05-27 13:25 UTC, KangSeongHyo commented on src/test/java/nextstep/subway/acceptance/LineAcceptanceTest.java
> +        }
이부분은 Line 인수테스트 인데 Station까지 Truncate하는게 맞는건가 싶어서
한번 생성 후 다시 처리안하도록 한 부분인데 다시보니 지저분한 감도 있고
다른 테스트에 영향을 주는 느낌도 있군요..

전체 truncate 하도록 변경했습니다!!

2022-05-28 01:29 UTC, KangSeongHyo commented on src/main/java/nextstep/subway/application/LineService.java
> +        if (lineRequestDTO.getUpStationId() != null) {
프론트를 보니 null인 경우 오류나는게 맞는것 같아서 수정하였습니다~!!

2022-05-28 14:07 UTC, parkeeseul approved these changes
피드백 잘 반영해 주셨네요 👍 
한 가지 코멘트 남겨두었으니 확인 부탁드리고
이번 단계 머지하도록 하겠습니다!
다음 미션 진행해 주세요! 🔥

2022-05-28 14:07 UTC, parkeeseul commented on src/main/java/nextstep/subway/application/LineService.java
> +        line.addStation(upStation);
stationId 가 null 인 경우 적절한 예외를 발생하도록 해주면 어떨까요? 😄

2022-05-28 14:07 UTC, merged