1단계 지하철역 인수테스트 작성
next-step/atdd-subway-admin pull request #656
Opened 2022-05-28 14:29 UTC by SanghoLee-dev

안녕하세요. 김준홍 리뷰어님!

1단계 지하철역 인수테스트를 작성해봤습니다. 최대한 주석으로 써주신 given, when, then 을 만족시키려고 해봤습니다. 

잘부탁드리겠습니다.

2022-05-29 13:24 UTC, Junhong-Kim requested changes
안녕하세요.
인수 테스트 주도 개발 미션을 함께하게된 리뷰어 김준홍입니다! ☺️

1단계 미션 잘 구현해주셨습니다 👍
리뷰 내용 확인하시고 다시 요청해주시면 감사드립니다!

2022-05-29 13:24 UTC, Junhong-Kim commented on src/test/java/nextstep/subway/station/StationAcceptanceTest.java
> +        ExtractableResponse<Response> response = createStationAndReturnResponse("강남역");
가독성을 높이기 위해 인수 테스트 코드에서 예외적으로 한글 메서드를 사용해도 좋을 것 같아요!

2022-05-29 13:24 UTC, Junhong-Kim commented on src/test/java/nextstep/subway/station/StationAcceptanceTest.java
> +    private ExtractableResponse<Response> createStationAndReturnResponse(final String name) {
공통 메서드 추출 👍
다만, `private` 메서드 위치를 정렬하면 좋을 것 같아요.

2022-05-29 13:24 UTC, Junhong-Kim commented on src/test/java/nextstep/subway/station/StationAcceptanceTest.java
> +        assertThat(response.body().jsonPath().getList("name")).contains("강남역", "역삼역");
`assertAll()`을 활용한 검증 방법에 대해 살펴보고 적용하면 좋을 것 같아요.

2022-05-29 13:24 UTC, Junhong-Kim commented on src/test/java/nextstep/subway/station/StationAcceptanceTest.java
> +                .when().post("/stations")
`url`도 상수 값으로 추출하면 좋을 것 같아요.

2022-05-29 13:24 UTC, Junhong-Kim commented on src/test/java/nextstep/subway/station/StationAcceptanceTest.java
>  @SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
새로운 인수 테스트를 만들 때마다 중복되는 코드가 될 것 같네요.
재사용할 수 있는 코드로 만들어보면 좋을 것 같아요.

2022-06-01 15:07 UTC, SanghoLee-dev commented on src/test/java/nextstep/subway/station/StationAcceptanceTest.java
> +        ExtractableResponse<Response> response = createStationAndReturnResponse("강남역");
테스트 코드의 메소드명을 제외하고는 한글 메소드 사용을 거의 안해서 생각을 못해봤네요. 한글메소드로 가독성으로 높여보겠습니다!

2022-06-01 15:11 UTC, SanghoLee-dev commented on src/test/java/nextstep/subway/station/StationAcceptanceTest.java
> +                .when().post("/stations")
상수값 추출을 깜박했네요. 추출하겠습니다.

2022-06-01 15:12 UTC, SanghoLee-dev commented on src/test/java/nextstep/subway/station/StationAcceptanceTest.java
> +    private ExtractableResponse<Response> createStationAndReturnResponse(final String name) {
`private` 메소드를 하위로 정렬 해볼게요.

2022-06-01 15:23 UTC, SanghoLee-dev commented on src/test/java/nextstep/subway/station/StationAcceptanceTest.java
> +        assertThat(response.body().jsonPath().getList("name")).contains("강남역", "역삼역");
`assertAll` 을 잘 사용해보지 않아 몰랐네요. 혹시 여러번 assertion 을 하는거보다 `assertAll` 을 사용하는게 어떤 장점이 있을까요?

2022-06-01 15:24 UTC, SanghoLee-dev commented on src/test/java/nextstep/subway/station/StationAcceptanceTest.java
>  @SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
중복코드를 제거하기 위해 `BaseSubwayTest` 를 만들어보겠습니다.

2022-06-02 09:53 UTC, Junhong-Kim commented on src/test/java/nextstep/subway/station/StationAcceptanceTest.java
> +        assertThat(response.body().jsonPath().getList("name")).contains("강남역", "역삼역");
`assertAll()`은 assertion이 실패한 이후도 검증합니다.
그러나 `assertThat()`은 assertion이 실패한 이후는 검증하지 않습니다.
[참고](https://gracelove91.tistory.com/108)할 만한 링크도 함께 공유드립니다. ☺️

2022-06-02 10:02 UTC, Junhong-Kim approved these changes
1단계 미션 잘 구현해주셨습니다 👍
소소한 코멘트 남겼는데 다음 단계 시작 전 반영해보면 좋을 것 같아요.

그리고 PR 댓글로 질문 남겨주신 사항은 대댓글로 답변드렸습니다.
다음 미션도 화이팅입니다! ☺️

2022-06-02 10:02 UTC, Junhong-Kim commented on src/main/java/nextstep/subway/ui/StationController.java
>  @RestController
controller에서 사용될 url prefix로 상수 값을 사용하는 것 보다는,
`@RestController`의 `value` 값을 설정하는게 좋을 것 같아요.
```suggestion
@RestController("/stations")
```

2022-06-02 10:02 UTC, Junhong-Kim commented on src/main/java/nextstep/subway/ui/UrlConstant.java
> +public class UrlConstant {
`UrlConstant` 클래스는 불필요해보여요!

2022-06-02 10:02 UTC, Junhong-Kim commented on src/test/java/nextstep/subway/BaseSubwayTest.java
> +    }
메서드로 추출한 `RestAssured` 로직은 도메인에 따라 각 테스트 클래스에 위치 시키는게 좋을 것 같아요.

2022-06-02 10:03 UTC, merged

2022-06-02 14:36 UTC, SanghoLee-dev commented on src/main/java/nextstep/subway/ui/UrlConstant.java
> +public class UrlConstant {
앗 제가 잘못 이해했나봐요 제거 하겠습니다.

2022-06-02 14:46 UTC, SanghoLee-dev commented on src/test/java/nextstep/subway/BaseSubwayTest.java
> +    }
너무 지하철에 대해 테스트하는것 같죠? 저도 옮기면서 그런 생각을 했습니다. 각 테스트 클래스로 옮기겠습니다.

2022-06-02 14:52 UTC, SanghoLee-dev commented on src/main/java/nextstep/subway/ui/StationController.java
>  @RestController
일단 url prefix 상수 값은 전부 제거 했습니다. 

음 혹시 url 중복 때문인가요? `@RequestMapping` 으로 선언하라는 말씀이신가요?
`@RestController` 의 `value` 값은 bean 이름 인거 같은데요. 제가 이해가 잘 안되서 어떤 이유인지 알 수 있을까요?

2022-06-02 14:57 UTC, Junhong-Kim commented on src/main/java/nextstep/subway/ui/StationController.java
>  @RestController
네, 말씀해주신 것처럼 `@RequestMapping`이 맞습니다!
제가 오타를 쳤네요 🥲