Step2 - 지하철 노선 기능
next-step/atdd-subway-admin pull request #699
Opened 2022-05-31 09:09 UTC by yulmucha

안녕하세요.
리뷰 요청드립니다.
감사합니다.

2022-05-31 12:49 UTC, seokhongkim requested changes
전율님, ATDD 2단계 미션 잘 구현해주셨습니다. 👍 

코드에 피드백 조금 남겼으니 확인 부탁드립니다. 🙏 
추가로 궁금하신 점이나 이야기 나누고 싶은 부분이 있다면 깃헙 코멘트 또는 슬랙 DM 으로 편하게 말씀 부탁드립니다.

2022-05-31 12:49 UTC, seokhongkim commented on src/main/java/nextstep/subway/application/LineService.java
> +        Station upStation = stationRepository.findById(request.getUpStationId()).orElseThrow(NotFoundException::new);
1. `findById().orElseThrow()` 가 비슷한 형식으로 반복될 것 같은데, 리팩토링해보는 건 어떨까요?
2. `NotFoundException` 에 어떤 데이터가 존재하지 않는지도 같이 알려주면 좋을 것 같아요! (e.g., 입력 id 값)

2022-05-31 12:49 UTC, seokhongkim commented on src/main/java/nextstep/subway/NotFoundException.java
> +public class NotFoundException extends RuntimeException {
필요한 예외를 정의해서 사용하시는 것 좋습니다. 👍

2022-05-31 12:49 UTC, seokhongkim commented on src/main/java/nextstep/subway/application/LineService.java
> +        Line line = lineRepository.findById(id).get();
1. 데이터가 없는 경우 무슨 예외가 발생할까요? 이 경우 클라이언트에게는 어떤 응답이 전달될까요?
2. 이것도 위에서 `Station` 을 조회하는 코드와 유사하게 `findById.orElseThrow` 패턴이 될 수 있겠네요!

2022-05-31 12:49 UTC, seokhongkim commented on src/main/java/nextstep/subway/application/LineService.java
> +        lineRepository.deleteById(id);
존재하지 않는 데이터를 삭제하려고 하는 경우 어떤 예외가 발생하며, 클라이언트에게는 어떤 응답이 전달될까요?

2022-05-31 12:49 UTC, seokhongkim commented on src/main/java/nextstep/subway/domain/Line.java
> +    public void update(Line newLine) {
`update` 를 메소드를 사용하려는 다른 개발자가 봤을 때, `Line` 데이터 중 어떤 값이 사용되는지 알 수 있는 방법이 있을까요?

2022-05-31 12:49 UTC, seokhongkim commented on src/main/java/nextstep/subway/dto/LineRequest.java
> +    public Line toLine(Station upStation, Station downStation) {
필드에 있는 `upStationId` 와 인자로 넘어온 `upStation` 이 동일한 데이터를 가리키는지(`upStationId` 로 조회한 데이터인지) 보장할 수 있는 방법이 있을까요?
`LineRequest` 에서 `Station` 을 받아서 `Line` 을 만드는 게 적절한 역할인지도 고민이 되네요.

2022-05-31 12:49 UTC, seokhongkim commented on src/main/java/nextstep/subway/ui/LineController.java
> +public class LineController {
여러 API 에서 발생할 수 있는 예외를 공통으로 처리할 수 있는 방법은 어떤 게 있을까요?

2022-05-31 12:49 UTC, seokhongkim commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +@DirtiesContext(classMode = DirtiesContext.ClassMode.BEFORE_EACH_TEST_METHOD)
`DirtiesContext` 를 사용하시면 테스트를 격리할 수 있다는 장점이 있는 반면, 테스트 실행이 오래 걸릴 수 있다는 단점도 있을 것 같아요.
왜 `DirtiesContext` 를 사용하면 테스트가 오래 걸리는지, 다른 방법으로 격리할 수 있는 건 어떤 게 있을지 고민해보시면 좋을 것 같습니다!

2022-06-01 11:40 UTC, yulmucha commented on src/main/java/nextstep/subway/application/LineService.java
> +        Line line = lineRepository.findById(id).get();
`NoSuchElementException` 예외가 발생하고 `500 Internal Server Error`가 전달됩니다.
API 예외 처리를 안 했네요. 😅

2022-06-01 11:42 UTC, yulmucha commented on src/main/java/nextstep/subway/application/LineService.java
> +        lineRepository.deleteById(id);
`EmptyResultDataAccessException` 예외가 발생하고 `500 Internal Server Error`가 전달됩니다.
마찬가지로 API 예외 처리를 안 했네요. 😅

2022-06-01 11:52 UTC, yulmucha commented on src/main/java/nextstep/subway/dto/LineRequest.java
> +    public Line toLine(Station upStation, Station downStation) {
❗️ 필드 `upStationId` 값과 전혀 관계 없는 인자 `upStation`가 들어올 수도 있는 어처구니 없는 일이 발생하네요.

2022-06-01 12:57 UTC, yulmucha commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +@DirtiesContext(classMode = DirtiesContext.ClassMode.BEFORE_EACH_TEST_METHOD)
테스트마다 실행 전에 매번 컨텍스트를 초기화(서버 재시작 및 DB 스키마 재생성)하기 때문에 느립니다.
컨텍스트를 유지하되 테스트 실행 전에 데이터는 다 날리는 방법이 있길래 한번 적용해 보았습니다.
SQL 스크립트를 관리하는 일이 추가되겠지만 상당히 빨라져서 좋네요!

2022-06-01 13:06 UTC, yulmucha commented on src/main/java/nextstep/subway/application/LineService.java
> +        Station upStation = stationRepository.findById(request.getUpStationId()).orElseThrow(NotFoundException::new);
`find`의 경우 아예 `Repository`에게서 확실한 `Entity`를 받을 수 있으면 좋겠다 싶어서(존재하지 않으면 직접 지정한 Exception을 던짐)
`findById()`를 활용하여 `getById()`를 직접 구현했고 이걸 사용하도록 수정했습니다.
그런데 interface라서 `findById()`를 private으로 두는 등 사용하지 못하도록 막을 수가 없는 것 같네요.

2022-06-01 13:20 UTC, yulmucha commented on src/main/java/nextstep/subway/ui/LineController.java
> +public class LineController {
여러 방법이 있지만, 가장 편리한 `@ExceptionHandler`를 사용하는 방법을 선택했고, 일반적인 경우에 `Controller`들 공통으로 처리할 수 있도록 `@ControllerAdvice`를 사용한 handler를 만들었습니다.

2022-06-01 13:28 UTC, yulmucha commented on src/main/java/nextstep/subway/domain/Line.java
> +    public void update(Line newLine) {
파라미터는 덩어리로 받고 심지어 함수 이름에도 뚜렷한 정보가 없어서, 직접 함수 내부를 보지 않는 한 제대로 알 수가 없네요.
함수 이름을 `replace`로 바꾸거나 파라미터 쪼개서 받는 게 나을 것 같습니다.

2022-06-01 14:05 UTC, yulmucha commented on src/main/java/nextstep/subway/dto/LineRequest.java
> +    public Line toLine(Station upStation, Station downStation) {
`LineRequest`에 `static`으로 `toLine(LineRequest request, Station upStation, Station downStation)` 함수를 만들 수 있겠지만 편리하자고 만드는 건데 파라미터도 많고 편리하지 않네요. 말씀하신 대로 역할이 적절한지도 의문이 생기고요.
그래서 그냥 바로 생성자를 사용하도록 했습니다.

2022-06-02 11:55 UTC, seokhongkim commented on src/main/java/nextstep/subway/application/LineService.java
> +        Station upStation = stationRepository.findById(request.getUpStationId()).orElseThrow(NotFoundException::new);
`get` 과 `find` 로 동작이 다른 것을 구분하셔서, `findById` 가 필요한 곳에서는 사용할 수 있도록 남겨놓아도 괜찮을 것 같습니다. 😀

2022-06-02 11:57 UTC, seokhongkim commented on src/main/java/nextstep/subway/dto/LineRequest.java
> +    public Line toLine(Station upStation, Station downStation) {
지금 작성하신 방법도 저는 괜찮다고 생각합니다.

이후 `LineRequest` 에서 `Line` 으로 변경할 일이 많아진다면, `Converter` 와 같이 컨버팅 목적의 컴포넌트를 추가해볼 것 같습니다.

2022-06-02 12:03 UTC, seokhongkim approved these changes
전율님, ATDD 2단계 미션 잘 마무리해주셨습니다. 👍 

간단한 피드백을 하나 남겼는데, 3단계 미션 진행하시면서 고민해보셔도 좋을 것 같습니다.
2단계 PR은 이만 머지하도록 하겠습니다.

3단계 미션에서 뵙겠습니다. 😀

2022-06-02 12:03 UTC, seokhongkim commented on src/main/java/nextstep/subway/domain/StationRepository.java
> +    default Station saveOne(Station station) {
1. `save` 와 `saveOne` 의 차이를 `Repository` 를 사용하는 입장에서 코드 구현을 보기 전까지는 모를 것 같아요.
2. 개인적으로는 중복 이름의 예외 처리는 비즈니스 로직에 가깝다고 생각되어, 레포지토리보다는 서비스 계층에 있는 것이 더 어울리지 않을까 싶습니다.

2022-06-02 12:03 UTC, merged