Step4 - 구간 제거 기능
next-step/atdd-subway-admin pull request #711
Opened 2022-06-01 05:23 UTC by KangSeongHyo

안녕하세요~
구간 제거 기능 미션 완료했습니다. 리뷰부탁드립니다~
감사합니다.~

---
피드백 주셨던 DTO 부분은 Domain이 의존하지 않도록 제거 완료했습니다~!!
한가지 고민한 부분이 있는데 하나로 묶으려고 했는데
이부분이 과연 묶는 의미가 있을까라는 생각이 들었습니다.

생각해본 부분은
일단 메서드를 나누는 경우는 행동하는데에 있어 4개의 필드가 모두 필요해 제외했고
객체로 묶는 경우는 SectionInfo 라는 객체를 생성하여 (혹시 단순 묶는 객체의 경우 메서드 postfix를 어떤걸로 정하시는지도 궁금합니다!(BO? VO? DTO?))
Service에서 변환해서 전달 or Domain 내부에서 inner class로 변환 하는 경우를 생각해봤는데요
        
제생각에 결국 두가지 모두 불필요한 생성한 객체에 getter 메서드만 늘어나는건 아닌가 싶기도 한데
리뷰어님은 어떻게 생각하시는지 궁금합니다!!

2022-06-02 01:20 UTC, parkeeseul requested changes
4단계 미션 잘 진행해 주셨네요! 👍 
몇 가지 코멘트와 질문 주신 사항에 대한 저의 의견 남겨두었으니 확인 부탁드립니다! 😄 
즐거운 하루 되세요! 🔥

2022-06-02 01:20 UTC, parkeeseul commented on src/test/java/nextstep/subway/acceptance/SectionAcceptanceTest.java
> +    @DisplayName("지하철 노선에 구간을 등록 한다.")
노선 구간 등록, 노선 구간 등록 실패, 삭제 등으로 테스트를 묶어 주셨는데요,
이렇게 테스트를 작성해 주신 이유가 있으신가요? 😄 
이떠한 이점이 있다고 생각하시나요?

2022-06-02 01:20 UTC, parkeeseul commented on src/main/java/nextstep/subway/domain/collection/LineStations.java
> +        boolean isExistSectionByDownSation = isExistSectionByDownSataion(station);
@_@ 매의 눈! 😄 
```suggestion
        boolean isExistSectionByUpStation = isExistSectionByUpStation(station);
        boolean isExistSectionByDownStation = isExistSectionByDownStation(station);
```

2022-06-02 01:20 UTC, parkeeseul commented on src/main/java/nextstep/subway/domain/collection/LineStations.java
> +    private void addBetweenSectionByDownStation(Line line, Station upStation, Station downStation, Long distance) {
> Q1. 한가지 고민한 부분이 있는데 하나로 묶으려고 했는데
> 이부분이 과연 묶는 의미가 있을까라는 생각이 들었습니다.
> 
> 생각해본 부분은
> 일단 메서드를 나누는 경우는 행동하는데에 있어 4개의 필드가 모두 필요해 제외했고
> 객체로 묶는 경우는 SectionInfo 라는 객체를 생성하여 (혹시 단순 묶는 객체의 경우 메서드 postfix를 어떤걸로 정하시는지도 궁금합니다!(BO? VO? DTO?))

A1. 클린코드 에서는 불용어를 추가한 이름은 아무런 정보를 제공하지 못하기 때문에 지양해야 한다고 이야기 하는데요,
Section, SectionInfo 는 어떤 차이가 있을까요? 😄 
```
불용어를 추가한 이름 역시 아무런 정보를 제공하지 못한다.
Product, ProductInfo, ProductData라 부른다면 개념을 구분하지 않은 채 이름만 달리한 경우이다. Info, Data는 a, an, the와 마찬가지로 의미가 불분명한 불용어다.
```
> Service에서 변환해서 전달 or Domain 내부에서 inner class로 변환 하는 경우를 생각해봤는데요
> 
> 제생각에 결국 두가지 모두 불필요한 생성한 객체에 getter 메서드만 늘어나는건 아닌가 싶기도 한데
> 리뷰어님은 어떻게 생각하시는지 궁금합니다!!

A2.  불필요 하다고 생각된다면 굳이 객체를 생성하지 않아도 될 것 같아요.
이전 리뷰에도 말씀드렸던 것 처럼 코드 스멜을 한번 고민 보는 포인트로 생각해보고
필요하다고 생각될때 한번 분리해보면 좋을 것 같아요 😄

2022-06-02 09:21 UTC, KangSeongHyo commented on src/main/java/nextstep/subway/domain/collection/LineStations.java
> +        boolean isExistSectionByDownSation = isExistSectionByDownSataion(station);
앗.. ㅜㅜ 수정했습니다~!!

2022-06-02 09:25 UTC, KangSeongHyo commented on src/main/java/nextstep/subway/domain/collection/LineStations.java
> +    private void addBetweenSectionByDownStation(Line line, Station upStation, Station downStation, Long distance) {
A1 같은 경우 실무에서도 자주 저렇게 쓰는데 답변해주신걸 보고 다시생각해보니
코드 상에서도 동일한 클래스네임으로 무분별하게 쓰고 있던게 생각이 많이 났습니다..
결국 중복코드가 생성이 되는 원인이었군요.. 불용어를 안쓰도록 노력해야겠네요!
클린코드는 읽어본다면서 미루고 있었는데 꼭 읽어 보도록 하겠습니다!

A2도 감사드리고 일할때 코드 스멜 포인트를 잡고 적절하게 쓸수 있도록 노력해야겠네요!

2022-06-02 09:45 UTC, KangSeongHyo commented on src/test/java/nextstep/subway/acceptance/SectionAcceptanceTest.java
> +    @DisplayName("지하철 노선에 구간을 등록 한다.")
미션 내용 마지막 부분에 인수테스트 피드백의 통합 처리하기를 읽어 보았습니다..!
맨처음에 리뷰 주셨던 여러개로 나눈 인수테스트를 하나로 처리 하는 부분은
사실 따로 처리하면서도 보기나 파악하는데 좋지 않은가? 라는 의문이 들었습니다..

조금 더 진행하고 피드백을 보고 생각을 해보았는데 
인수테스트는 사용자 시나리오를 검증 주 목적 인데 분리하다보니 너무 단순 API 테스트가 아닌가 싶었고

통합처리해보니 유기적으로 연결된 API들에 대한 보호도 되는 이점이 있는 것 같았습니다.
그리고 말씀해 주셨던 중복제거에 대한 효과 & 테스트간 고립에도 신경을 덜 써도 되는   
이점 있다고 느껴졌습니다!

2022-06-03 00:22 UTC, parkeeseul commented on src/test/java/nextstep/subway/acceptance/SectionAcceptanceTest.java
> +    @DisplayName("지하철 노선에 구간을 등록 한다.")
의견 공유해 주셔서 감사합니다 성효님 👍 
말씀 주신 인수테스트를 통합하면 시나리오의 흐름대로 테스틀 할 수 있다는 장점이 있는 것 같아요.
다만 지하철 `노선에 구간을 등록 한다`의 인수테스트 통합은 시나리오 흐름이라기 보다는
구간을 등록할 때 나오는 예외케이스들을 통합해 둔게 아닌가 하는 생각이 들었는데요,
개인 적으로는 해당 인수테스트는 테스트 중복에 제거에 대한 이점이 적은 것 같고
 예외 케이스에 대해서는 분리해 주는 것이 테스트의 의도를 더 파악하기 좋을 것 같다는 생각이 드는데
이부분 어떻게 생각하시는지 궁금하네요! 😄

2022-06-03 00:24 UTC, parkeeseul approved these changes
피드백 잘 반영해 주셨네요! 👍 
의견 주신 부분에 대한 한가지 추가 의견 남겨두었으니 확인 부탁드리고
혹시 추가적인 의견 있으시다면 코멘트 남겨주세요! 😄 

그동안 많은 피드백 반영해 주시느라 정말 고생 많으셨습니다!
코멘트 하나하나 성효님이 의견을 남겨주셔서 즐거웠네요! 🙏 
남은 미션들도 꼭 완주하셔서 많은 인사이트 얻어 가시길 바라요!
마지막까지 화이팅 입니다 🔥

2022-06-03 00:24 UTC, merged

2022-06-03 07:54 UTC, KangSeongHyo commented on src/test/java/nextstep/subway/acceptance/SectionAcceptanceTest.java
> +    @DisplayName("지하철 노선에 구간을 등록 한다.")
안그래도 이부분 고민을 했었는데 분리해주는 것이 더 의도 파악에 도움이 되는군요!! 
리뷰 감사드립니다~!!