Step4 : 구간 제거 기능
next-step/atdd-subway-admin pull request #719
Opened 2022-06-01 15:07 UTC by mond-page

안녕하세요, 리뷰어님 ( _ _)
Step3에서 리뷰해주신 대로 [Distance 객체로 반환](https://github.com/next-step/atdd-subway-admin/pull/669#discussion_r884999748)하여 좀 더 활용하도록 처리하였습니다.
삭제해 주는 부분(구간을 두개로 합치는 부분)은 id를 새로 따는게 맞다고 판단하여 
기존 객체들을 지우고 새로운 객체를 만드는 식으로 처리하였습니다.

벌써 마지막 단계라 아쉽네요 🥲🥲🥲
시간나실 때 리뷰 부탁드리겠습니다 : )
이번 한 주도 화이팅입니다 !!

2022-06-02 15:45 UTC, enemfk777 requested changes
안녕하세요 영건님 🙇‍♂️
일이 좀 바빴어서 리뷰가 늦어져 대단히 죄송합니다 😭
구간 제거 기능은 정말 쉽게 구현해주셨네요 👍
소소한 코멘트를 드렸으니 고민해 보시고 다시 한 번 요청 부탁드립니다!
마지막까지 화이팅입니다 🙏

2022-06-02 15:45 UTC, enemfk777 commented on src/main/java/nextstep/subway/domain/Sections.java
> +    private Section findSameDownStation(Station station) {
Optional 에서 null을 반환하는건 바람직하지 못한 패턴 같아요 :)
nullSafety 를 위해 만들어진 Optional의 존재 이유를 무시하게 된다고 생각되는데요,
Optional을 반환하게 바꿔보시는건 어떨까요? :)

2022-06-02 15:45 UTC, enemfk777 commented on src/main/java/nextstep/subway/domain/Sections.java
> +        return getInOrderStations().contains(station);
메서드 내에서 클래스 내부의 다른 퍼블릭 메서드를 호출하는 것은 지양하는 편이 좋습니다 :)
퍼블릭 메서드는 협력하는 다른 객체와 메세지를 주고받는 용도로 존재하는 메서드이기 때문에
내부의 다른 메서드에서 사용하는 순간 객체지향 프로그래밍 원칙 중 단일 책임 원칙을 어기는 것으로 볼 수 있을 것 같습니다.

이 원칙을 어김으로써 아래와 같은 문제가 일어날 것 같은데요

> A라는 객체와 협력하기 위해 만든 B라는 메서드를
> C라는 객체와 협력하기위해 존재하는 D라는 메서드 내부에서 사용하게되면,
> A라는 객체와 협력하는데 필요한 요구사항이 바뀌어 B를 재정의 해야할 때
> A와 관계없는 D까지 영향을 받게 되어버립니다.

영건님의 생각은 어떠신가요? 😄

2022-06-02 18:08 UTC, mond-page commented on src/main/java/nextstep/subway/domain/Sections.java
> +        return getInOrderStations().contains(station);
리뷰어님 말씀에 백 번 공감합니다. 👍👍👍
작성 당시에 stream을 써서 또 HashSet 만드는 비용보다 있는 메소드를 활용하자고 생각했는데,
지금와서 보니 결국엔 또 Inorder하는 비용이 더 클 것 같네요. 

해당부분 SRP 원칙 지킬 수 있도록 개선하였습니다 : )

2022-06-02 18:09 UTC, mond-page commented on src/main/java/nextstep/subway/domain/Sections.java
> +    private Section findSameDownStation(Station station) {
Optional 의도를 놓치고 있었네요. 해당 부분 개선해서 진행하였습니다 : )

2022-06-02 18:18 UTC, mond-page commented on src/main/java/nextstep/subway/domain/Sections.java
>          }
리뷰어님 하나 궁금한 부분이 있습니다  : )
**비어있는지 확인하는 검증로직**을 `getInOrderSections` 최상단에 옮기면 
while 부분도 제거하고 깔끔하게 돌릴 수 있을 것 같은데요

```java
private List<Section> getInOrderSections() {
        if (isEmpty()) {
            return Collections.emptyList();
        }
        List<Section> inOrderStation = new ArrayList<>();
        return generateInOrderStationNew(inOrderStation, lineFirstSection());
```

이렇게 되어 버리면 **마지막 요소를 가져오는 부분**이 언젠간 사용되면 오류가 발생할 것 같아 lineFirstSection안에 역할을 두는게 더 맞다고 판단하였습니다. 혹시 리뷰어님 생각이 궁금합니다 !

2022-06-02 18:23 UTC, mond-page commented
리뷰어님 말씀해주신 사항 반영해보았습니다. 
주중 마지막인데, 금요일 마무리 잘하시길 바라겠습니다 : )
(일이 바쁘신 와중에 신경써 주셔서 감사합니다 🙇‍♂️🙇‍♂️🙇‍♂️🙇‍♂️)

2022-06-02 18:23 UTC, mond-page commented on src/main/java/nextstep/subway/domain/Sections.java
>          }
이해가 안갈 수도 있을 것 같은데, 안가시면 말씀부탁 드리겠습니다. !!

2022-06-03 16:34 UTC, enemfk777 approved these changes
안녕하세요 영건님 🙇‍♂️

마지막 피드백까지 잘 반영해주셨습니다!!

코드들을 깔끔하게 작성해주셔서 리뷰 드리며 함께 배운 소중한 시간이었습니다 :)

마지막으로 질문 주신사항에 대해 코멘트를 남겨드렸으니, 확인 부탁드리며,
이번 단계는 이만 머지하도록 하겠습니다!

인수 테스트 주도 개발 미션 진행하시느라 고생 많으셨습니다!
남은 미션도 화이팅입니다!! 💪

2022-06-03 16:34 UTC, enemfk777 commented on src/main/java/nextstep/subway/domain/Sections.java
> +                .contains(station);
section에게 station을 전달하면 포함 여부를 반환하는 메서드가 있다면 이부분이 좀더 간결해 질 수 있을 것 같아요 :)

2022-06-03 16:34 UTC, enemfk777 commented on src/main/java/nextstep/subway/domain/Sections.java
>          }
오류가 발생할것 같다는 말씀이
```
private Section lineFirstSection() {
//        if (isEmpty()) {
//            return null;
//        }
    return findFirstSection(this.sections.get(size() - 1));
}
```

이렇게 되어있을 때 어느순간 sections의 size가 0이라면 오류가 발생할 것 같다는 말씀이실까요?? :)

그렇다면, Sections는 생성할때부터 size가 0이 될 수 없게 설계해보시는 건 어떨까요?
구간이 최소 1개는 있어야한다는 요구사항이 있으므로 요구사항을 어기게 되는 것은 아닐 것 같아요 :)

sections의 empty 생성자를 사용하지 않고, 늘 최소 1개의 인자를 받아 초기화 한다면 해당 문제는 발생하지 않을 것 같습니다.

단 Line 생성부터 고쳐야할 것 같고, 그에따라 깨지게 될 수많은 테스트코드들을 다시 고쳐야한다는 고통이 뒤따르겠네요 😨

2022-06-03 16:34 UTC, merged

2022-06-04 15:15 UTC, mond-page commented on src/main/java/nextstep/subway/domain/Sections.java
>          }
이해해주신 부분이 맞습니다 
말씀해 주신 방향으로 잡고 개인적으로 개선해보도록 하겠습니다 : )

마지막까지 감사합니다 !