Step2 - 지하철 노선 기능 리뷰 요청 드립니다
next-step/atdd-subway-admin pull request #723
Opened 2022-06-01 16:12 UTC by millennion-jin

저번 리뷰에서 질문 드린 내용에 상세히 답변해주셔서 정말 감사드립니다.

이번 2단계 기능 구현에서는
아직 구간 개념을 추가해두지 않다보니 임시적으로 Station이 lineId를 가지고
Line이 해당 Station들을 OneToMany로 사용하고 있는데
이 부분은 3단계에서 구간 개념이 추가되면서 수정될 예정입니다.

2단계 까지는 할만하다고 생각했는데 뭔가 3단계를 설명을 보니 쉽지 않겠다는 생각이 드네요 ㄷ

2단계 리뷰 잘 부탁 드립니다!

2022-06-02 23:08 UTC, chae-yh requested changes
진웅님 안녕하세요! 두번째 미션 잘 작성해주셨습니다 👍 
다만 고민해보시면 좋을 것 같은 내용이 있어 코멘트 남겨드렸으니 확인 부탁드립니다!

감사합니다 : )

2022-06-02 23:08 UTC, chae-yh commented on docs/README.md
> +### 구현 필요기능
구현 필요한 목록을 잘 작성해주셨네요 👍

2022-06-02 23:08 UTC, chae-yh commented on src/main/java/nextstep/subway/application/LineService.java
> +@Transactional(readOnly = true)
여기에 Transactional을 걸고 readOnly는 해당 메소드에만 붙이는 건 어떨까요...?
Transactional이 더 많기도 하고 readOnly가 특수한 경우라서 해당 하는 메소드에만 작성하는 것은 어떨까요...?

2022-06-02 23:08 UTC, chae-yh commented on src/main/java/nextstep/subway/domain/Line.java
> +    private List<Station> stations = new ArrayList<>();
미션 요구 사항 중에 상행 종점과 하행 종점을 등록할 수 있어야 합니다!
현재 구조에서는 상행 종점과 하행 종점을 구분하지 못하는 형태일 것 같은데 어떻게 생각하시나요!

2022-06-02 23:08 UTC, chae-yh commented on src/main/java/nextstep/subway/application/LineService.java
> +        persistLine.addStation(downStation);
lineRequest 의 distance 의 값이 사용되지 않는 것 같습니다!

2022-06-02 23:08 UTC, chae-yh commented on src/main/java/nextstep/subway/dto/LineResponse.java
> +    public static LineResponse of(Line line) {
파라미터가 하나일 경우 보통 관례적으로 from을 써줍니다
```
1) from
매개 변수를 하나 받아서 해당 타입의 인스턴스를 반환하는 메서드에 주로 사용합니다.
Date date = Date.from(instnace);
2) of
여러 매개변수를 받아 적합한 타입의 인스턴스를 반환하는 집계 메서드에서 주로 사용합니다.
List list = List.of(1, 2, 3);
3) valueOf
from과 of와 비슷한 의미를 갖습니다.
Integer i = Integer.valueOf(10);

- 이펙티브 자바
```

2022-06-02 23:08 UTC, chae-yh commented on src/main/java/nextstep/subway/dto/LineResponse.java
> +    }
사용하지 않는 getter 도 있는 것 같은데, 사용하지 않는 메서드는 지우는 것은 어떨까요...?

2022-06-02 23:08 UTC, chae-yh commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +    public static ExtractableResponse<Response> createOneLine(String lineName, String lineColor, Long upStationId,
메서드 분리 잘해 주셨습니다 👍

2022-06-02 23:08 UTC, chae-yh commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +                .body(params)
여기서 HashMap 보다는 이미 만드신 LineRequest를 사용해볼 수도 있지 않을까요...?

2022-06-02 23:08 UTC, chae-yh commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +@DirtiesContext(classMode = ClassMode.BEFORE_EACH_TEST_METHOD)
테스트 격리 좋습니다 👍

2022-06-02 23:08 UTC, chae-yh commented on src/main/java/nextstep/subway/application/LineService.java
> +        Station upStation = stationRepository.getById(lineRequest.getUpStationId());
getById는 method extract 해줄 수 있지 않을까요...?

2022-06-02 23:08 UTC, chae-yh commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +        assertThat(lineResponse.getName()).isEqualTo("짱비싼선");
노선명이 인상적이네요 ㅎ.ㅎ;;

2022-06-02 23:08 UTC, chae-yh commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +    @LocalServerPort
이 부분은 LineAcceptanceTest, StationAcceptanceTest 둘 다에서 사용되는데 공통으로 사용할 수 있지 않을까요...?

2022-06-02 23:08 UTC, chae-yh commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +        Long upStationId_b = StationAcceptanceTest.createOneStation("수원역").jsonPath().getLong("id");
_b 는 어떤 의미일까요...?

2022-06-02 23:08 UTC, chae-yh commented on src/test/java/nextstep/subway/station/StationAcceptanceTest.java
> +    public static ExtractableResponse<Response> createOneStation(String stationName) {
LineAcceptanceTest에서 사용하기 때문에 Public static으로 바꾸신 것 같습니다! 이런 역할을 하는 메서드들만 모아서 클래스로 분리해보는 것은 어떨까요...?

2022-06-03 14:44 UTC, millennion-jin commented on src/main/java/nextstep/subway/application/LineService.java
> +@Transactional(readOnly = true)
말씀 하신대로 그 편이 더 효율적일 것 같습니다
해당 부분 변경하겠습니다

2022-06-03 14:54 UTC, millennion-jin commented on src/main/java/nextstep/subway/dto/LineResponse.java
> +    public static LineResponse of(Line line) {
평상시에는 저도 from을 사용하곤 하는데
기존 코드에 너무 신경을 쓰지 않고 복붙해 왔던 것 같습니다
앞으로는 좀 더 신경을 쓰도록 하겠습니다

2022-06-03 15:32 UTC, millennion-jin commented on src/main/java/nextstep/subway/application/LineService.java
> +        persistLine.addStation(downStation);
distance 를 빼먹었네요 ㄷㄷㄷ
추가했습니다

2022-06-03 15:35 UTC, millennion-jin commented on src/main/java/nextstep/subway/domain/Line.java
> +    private List<Station> stations = new ArrayList<>();
구간 관련 구현은 다음 스텝이니
구간 구현 전에는 api 예제에서 리턴되는 형태 정도만 맞추면 되겠지 라는
안일한 마음으로 구현을 하게 되어 이렇게 됐습니다 ㅠ
앞으로는 좀 더 요구사항을 맞출 수 있도록 노력하겠습니다

2022-06-03 15:37 UTC, millennion-jin commented on src/main/java/nextstep/subway/dto/LineResponse.java
> +    }
평상시 업무에서는 lombok 을 사용하다 보니 모든 get 메서드들을 허용해 주는데에 있어 너무 관대해 진 것 같습니다.
lombok을 쓰지 않는 동안만이라도 최대한 엄격하게 구현해 보도록 노력해 보겠습니다.

2022-06-03 15:39 UTC, millennion-jin commented on src/main/java/nextstep/subway/application/LineService.java
> +        Station upStation = stationRepository.getById(lineRequest.getUpStationId());
extract 가능할 것 같은데
해당 부분이 제거됐습니다 ㄷㄷ

2022-06-03 16:23 UTC, millennion-jin commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +        Long upStationId_b = StationAcceptanceTest.createOneStation("수원역").jsonPath().getLong("id");
테스트라고 변수 명을 너무 대충 지었던 것  같습니다 
사실은 _b 는 분당선 친구들이고 _sb 는 신분당선 친구들이었습니다 ㅜ

2022-06-03 16:47 UTC, millennion-jin commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +                .body(params)
그렇게 변경하도록 하겠습니다

2022-06-03 16:48 UTC, millennion-jin commented on src/test/java/nextstep/subway/station/StationAcceptanceTest.java
> +    public static ExtractableResponse<Response> createOneStation(String stationName) {
공용 static 메서드들이니 util로 빼는게 나을 것 같긴 합니다
별도 클래스로 분리시키도록 하겠습니다.

2022-06-03 17:00 UTC, millennion-jin commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +    @LocalServerPort
네 해당 부분은 인수 테스트 기본형 Abstract 클래스를 생성하여
각 인수 테스트 클래스에 적용 시켰습니다

2022-06-03 17:06 UTC, millennion-jin commented on src/main/java/nextstep/subway/dto/LineRequest.java
> +    public Long getUpStationId() {
getUpstationId 와 getDownStationId 메서드가 사용되지 않아 지웠었는데
해당 메서드들을 지우자 Line 생성시에 아직 저장되지 않은 Station이기 때문에 flush가 필요하다는 에러가 발생했습니다.
Request에서 Line 객체로의 변경 시 
id 값 만을 가지고 있는 Station 객체를 만들어 Line에 넣어 준 뒤 Line 을 저장 하고 있어
위 두 메서드가 쓰일 일이 없을 것으로 보이는데 왜 이런 문제가 발생하는지 잘 모르겠습니다.

2022-06-03 17:07 UTC, millennion-jin commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +        assertThat(lineResponse.getName()).isEqualTo("짱비싼선");
신분당선 너무 비싼 것 같습니다 ㅠ

2022-06-03 17:08 UTC, millennion-jin commented
요즘 회사가 너무 바쁘다 보니 피드백 주신 것을 빨리빨리 반영하지도 못하고
과제 진도도 빠르게 나가지 못하는 것 같네요 ㅠㅠ
주말에도 출근을 하게 될 것 같지만 어떻게든 짬을 내서 열심히 해보도록 하겠습니다!

2022-06-04 15:43 UTC, chae-yh approved these changes
진웅님 안녕하세요! 피드백 잘 반영해주셨습니다 👍 질문하신 내용과 조금 더 생각해보면 좋을만한 내용 코멘트 남겨드렸으니 확인 부탁드립니다! 
미션은 이 정도면 목표를 달성한 것으로 생각되어 merge 하겠습니다! 다음 미션 진행 부탁드립니다!

회사일이 바쁘시다고 말씀주셨는데, 프로젝트가 한창이신 것 같네요... 파이팅 하시고, 말씀하신 것 처럼 조금씩이라도 시간을 내어 미션 완주하시길 빌겠습니다!

감사합니다 : )

2022-06-04 15:43 UTC, chae-yh commented on src/main/java/nextstep/subway/dto/LineRequest.java
> +    public Long getUpStationId() {
스프링에서는 직렬화할 때 특정 클래스 구조를 가져야 하기 때문입니다. 
https://jojoldu.tistory.com/407 참고 부탁드립니다!

2022-06-04 15:43 UTC, chae-yh commented on src/main/java/nextstep/subway/domain/Line.java
> +    private Station downStation;
상행 종점 / 하행 종점을 잘 구분해주셨습니다 👍 다만 현재의 구조라면 상행 종점 / 하행 종점**만** 등록 가능할 것 같습니다! 여러개의 역이 들어갈 수 있는 구조가 되어야 할 것 같습니다만, 해당 구조 변경은 다음 스텝에서 진행될 거라 기대합니다 : )

2022-06-04 15:43 UTC, chae-yh commented on src/test/java/nextstep/subway/util/StationTestUtil.java
> +public class StationTestUtil {
메소드 분리 잘 해주셨습니다 👍

2022-06-04 15:44 UTC, merged