Step1 리뷰 요청 드립니다.
next-step/atdd-subway-admin pull request #726
Opened 2022-06-02 14:29 UTC by jiyeonghwang

안녕하세요. 황지영입니다.
Step1 리뷰 요청 드립니다!
잘 부탁드립니다.

2022-06-03 09:33 UTC, parkeeseul requested changes
안녕하세요 지영님! 인수 테스트 주도 개발 미션을 함께 하게 된 박이슬 입니다 😄 
1단계 미션 잘 진행해 주셨네요! 👍 
몇 가지 코멘트 남겨두었으니 확인 부탁드립니다 
함께 이번 미션 잘 진행해 보아요! 화이팅 입니다 🔥

2022-06-03 09:33 UTC, parkeeseul commented on src/test/java/nextstep/subway/station/StationAcceptanceTest.java
> +        assertThat(response.jsonPath().getList(".", StationResponse.class).size()).isEqualTo(2);
assertAll 에 대해서 학습해 보면 어떨까요? 😄

2022-06-03 09:33 UTC, parkeeseul commented on src/test/java/nextstep/subway/station/StationAcceptanceTest.java
> +        assertThat(response.jsonPath().getList(".", StationResponse.class).size()).isEqualTo(2);
hasSize 를 사용해 볼 수도 있을 것 같아요 😄 
```suggestion
        assertThat(response.jsonPath().getList(".", StationResponse.class))..hasSize(2);
```

2022-06-03 09:33 UTC, parkeeseul commented on src/test/java/nextstep/subway/station/StationAcceptanceTest.java
> +        names.stream().forEach(s -> createStation(s));
지하철역 생성, 삭제 인수테스트에서 중복으로 발생하는 코드인데요,
중복을 제거해 볼 수 있는 방법은 없을까요? 😄

2022-06-03 09:33 UTC, parkeeseul commented on src/test/java/nextstep/subway/station/StationAcceptanceTest.java
> +                        .extract();
해당 부분도 조회/삭제 두 인수테스트에서 중복이 발생하네요!
중복을 제거해 보면 어떨까요? 😄

2022-06-04 10:52 UTC, jiyeonghwang commented
안녕하세요, 이슬님! 
피드백주신 `assertAll`, `hasSize` 적용 및 중복코드 제거하였습니다.! 
테스트 코드에서 메소드를 분리해서 재사용해도 되는건지 의문이었는데,
중복코드보단 메소드 분리가 추후 관리적인 측면에서도 좋을 것 같습니다!
자세한 피드백 감사드립니다.

2022-06-04 14:09 UTC, parkeeseul approved these changes
피드백 잘 반영해 주셨네요! 👍 
한 가지 코멘트 남겨두었으니 확인 부탁드리고
다음 단계 진행해 주세요! 😄 
화이팅 입니다 🔥

2022-06-04 14:09 UTC, parkeeseul commented on src/test/java/nextstep/subway/station/StationAcceptanceTest.java
> +    void createStation(String name) {
해당 메서드에 @DisplayName 을 작성해 주신 이유가 있으실까요? 😄

2022-06-04 14:09 UTC, merged

2022-06-04 14:23 UTC, jiyeonghwang commented on src/test/java/nextstep/subway/station/StationAcceptanceTest.java
> +    void createStation(String name) {
부연 설명 느낌으로 남겨놓았었는데, 지금 보니 굳이란 느낌이 들긴 하네요..! 
제거하도록 하겠습니다!