2단계 지하철노선 기능
next-step/atdd-subway-admin pull request #747
Opened 2022-06-04 15:00 UTC by SanghoLee-dev

2단계 작업 진행해봤습니다.
1단계에 merge 전에 피드백 주셨던것도 수정해봤습니다.

다시 한번 잘부탁드립니다.

2022-06-05 01:58 UTC, Junhong-Kim requested changes
2단계 미션 잘 구현해주셨습니다 👍
리뷰 내용 확인하시고 다시 요청해주시면 감사드립니다.

2022-06-05 01:58 UTC, Junhong-Kim commented on src/main/java/nextstep/subway/application/LineService.java
> +        final List<Long> ids = asList(lineRequest.getUpStationId(), lineRequest.getDownStationId());
Util 클래스 메서드는 `static import`를 지양해서 어떤 Util 메서드인지 알 수 있으면 좋을 것 같아요.

2022-06-05 01:58 UTC, Junhong-Kim commented on src/main/java/nextstep/subway/domain/Line.java
> +    private long downStationId;
`Station` 엔티티 클래스를 사용하도록 수정해보면 좋을 것 같아요.

2022-06-05 01:58 UTC, Junhong-Kim commented on src/main/java/nextstep/subway/domain/Line.java
> +    private long distance;
원시 값을 포장해서 사용해보면 좋을 것 같습니다.

2022-06-05 01:58 UTC, Junhong-Kim commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +        final ExtractableResponse<Response> updateResponse = RestAssured.given().log().all()
이 로직도 메서드 추출이 가능해보입니다.

2022-06-05 01:58 UTC, Junhong-Kim commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +        final ExtractableResponse<Response> deleteResponse = RestAssured.given().log().all()
`RestAssured`를 사용하는 로직들은 가독성을 고려해서 재사용 가능하게 해주세요.

2022-06-05 01:58 UTC, Junhong-Kim commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +                () -> assertThat(deleteResponse.statusCode()).isEqualTo(NO_CONTENT.value()),
검증하는 로직들도 메서드를 추출해서 가독성을 높일 수 있을 것 같아요.

2022-06-05 15:53 UTC, SanghoLee-dev commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +        final ExtractableResponse<Response> deleteResponse = RestAssured.given().log().all()
네 재사용 가능하게 리팩토링 해볼게요.

2022-06-05 15:59 UTC, SanghoLee-dev commented on src/main/java/nextstep/subway/domain/Line.java
> +    private long downStationId;
앗 2단계에서는 지하철노선과 역의 매핑하는 기능이 없다고 해서 아예 엔티티 매핑을 하면 안되는줄 알았어요. 수정해볼게요.

2022-06-05 16:01 UTC, SanghoLee-dev commented on src/main/java/nextstep/subway/application/LineService.java
> +        final List<Long> ids = asList(lineRequest.getUpStationId(), lineRequest.getDownStationId());
Util 클래스의 메소드는 `static import` 를 지양하시는군요. 혹시 어떤 이유가 있으실까요? 그리고 주로 어떤 메소드에서 `static import` 를 하시는편이신가요?

2022-06-05 16:02 UTC, SanghoLee-dev commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +                () -> assertThat(deleteResponse.statusCode()).isEqualTo(NO_CONTENT.value()),
검증로직도 반복된느 부분은 메소드 추출을 해볼게요.

2022-06-05 16:09 UTC, SanghoLee-dev commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +        final ExtractableResponse<Response> updateResponse = RestAssured.given().log().all()
메소드 추출 할게요.

2022-06-05 16:45 UTC, SanghoLee-dev commented on src/main/java/nextstep/subway/domain/Line.java
> +    private long distance;
원시값 포장을 놓쳤네요. 수정하겠습니다.

2022-06-06 13:23 UTC, Junhong-Kim commented on src/main/java/nextstep/subway/application/LineService.java
> +        final List<Long> ids = asList(lineRequest.getUpStationId(), lineRequest.getDownStationId());
이전에 코멘트 남겨드린 것처럼 `static import` 를 지양하는 이유는 어떤 클래스의 메서드를 사용했는지 명시하기 위함입니다.
저는 테스트 작성시 사용되는 코드를 제외하고는 `static import` 사용을 지양하는 편입니다.
정답이 있는 것은 아니니 `static import`를 사용할 범위를 협업하는 개발자 분들과 컨벤션을 정하는게 좋을 것 같아요.

2022-06-06 13:33 UTC, Junhong-Kim approved these changes
피드백 잘 반영해주셨습니다.
소소한 코멘트 남겼는데 다음 단계 시작 전 반영해보면 좋을 것 같아요.
이번 단계는 이만 merge 하겠습니다.

그리고 PR 댓글로 질문 남겨주신 사항은 코멘트로 답변드렸습니다.
다음 미션도 화이팅입니다! ☺️

2022-06-06 13:33 UTC, Junhong-Kim commented on src/main/java/nextstep/subway/application/LineService.java
> +        return LineResponse.of(lineRepository.save(lineRequest.toLine(findStationById(lineRequest.getUpStationId()),
`규칙 4: 한 줄에 점을 하나만 찍는다.` 규칙을 만족하지 못하고있어요.
메서드 호출 후 반환되는 값을 바로 사용하고 있는 로직들을 수정해보면 좋을 것 같아요.

2022-06-06 13:34 UTC, merged

2022-06-06 14:06 UTC, SanghoLee-dev commented on src/main/java/nextstep/subway/application/LineService.java
> +        return LineResponse.of(lineRepository.save(lineRequest.toLine(findStationById(lineRequest.getUpStationId()),
앗 `규칙 4: 한 줄에 점을 하나만 찍는다.` 이 규칙을 놓치고 있었네요. 수정 해놓겠습니다. :thumbsup: