3단계 - 구간 추가 기능
next-step/atdd-subway-admin pull request #758
Opened 2022-06-05 13:08 UTC by chj1768

안녕하세요 리뷰어님. 🙇 
3단계 구간 추가 PR 요청 드립니다. 
잘 부탁드립니다.

2022-06-06 03:20 UTC, chae-yh requested changes
현지님 안녕하세요! 세번째 step 잘 작성해주셨습니다 👍 그런데 구조 관련해서 조금 더 고민해보셨으면 좋을만한 내용이 있어 코멘트 드리니 확인 부탁드립니다!

감사합니다 : )

2022-06-06 03:20 UTC, chae-yh commented on README.md
> +- [X] 지하철 구간 추가 기능을 구현한다.
기능 구현 목록 작성 좋습니다 👍

2022-06-06 03:20 UTC, chae-yh commented on src/main/java/nextstep/subway/domain/Line.java
> +    private List<LineStation> lineStations = new ArrayList<>();
lineStations가 처리하는 로직이 많아보입니다. 일급컬렉션으로 추출하고, 해당 로직을 옮겨보는 것은 어떨까요...?

2022-06-06 03:20 UTC, chae-yh commented on src/main/java/nextstep/subway/domain/Line.java
> +        return getAllSections().stream().filter(it -> it.getPreStation() == null).findFirst()
getAscEndSection
it
와 같은 축약어는 가능한 사용하지 않는 방향으로 작성해봐도 좋을 것 같습니다!

2022-06-06 03:20 UTC, chae-yh commented on src/main/java/nextstep/subway/dto/SectionRequest.java
> +            throw new IllegalArgumentException("허용되지 않는 distance 입니다.");
dto는 단순히 데이터를 전달하는 역할을 합니다. null check까지는 괜찮겠지만, 이러한 validation은 실제 도메인의 로직과 밀접한 관계있으므로 domain으로 옮기는 것은 어떨까요...?

2022-06-06 03:20 UTC, chae-yh commented on src/main/java/nextstep/subway/domain/LineStation.java
> +public class LineStation implements Comparable<LineStation> {
Section이란 단어가 많이 쓰이는데, LineStation보다는 Section으로 이름을 변경하는 것은 어떤가요...?

2022-06-06 03:20 UTC, chae-yh commented on src/main/java/nextstep/subway/application/LineService.java
> +        if (sectionRequest.hasPreStation()) {
preStation 만 null check를 따로 해주는 이유가 있을까요...?

2022-06-06 03:20 UTC, chae-yh commented on src/main/java/nextstep/subway/domain/Line.java
> +    public LineStation getDescEndSection() {
getAscEndSection() / getDescEndSection() 는 내부에서만 쓰이는데 public으로 열릴 필요가 있을까요...?

2022-06-06 03:20 UTC, chae-yh commented on src/main/java/nextstep/subway/domain/Line.java
> +                .orElseThrow(RuntimeException::new);
Exception은 조금 더 구체적으로 작성해봐도 좋을 것 같습니다!

2022-06-06 03:20 UTC, chae-yh commented on src/main/java/nextstep/subway/domain/LineStation.java
> +        return new LineStation(line, station, null, 0);
첫 구간과 끝 구간을 구분하기 위해 null을 넣으신 것 같습니다! 그런데 이런 구조면 예를 들어 첫 구간 혹은 끝 구간을 삭제해야 할 경우 변경이 어렵지 않을까요...?

2022-06-06 03:20 UTC, chae-yh commented on src/main/java/nextstep/subway/domain/Line.java
> +        this.lineStations.add(LineStation.section(this, station, preStation, startSection.getDistance() + distance));
LineStation의 distance가 시작역에서부터 해당 역까지의 거리를 저장하는 것으로 보입니다! 이 경우 중간에 구간이 더해지거나 삭제된다면 그 뒤로 모든 구간이 영향을 받는 형태입니다. O(n)으로 데이터 전체를 탐색하는 비용이 클 것 같고, 구간 추가 및 삭제 요청이 들어올 때 마다 해당 노선의 전체 데이터가 업데이트가 되어야하는 형태가 되어 트래픽이 커지면 크게 영향받는 구조로 보입니다.
변경되는 데이터를 줄여볼 수는 없을까요...?

2022-06-06 03:20 UTC, chae-yh commented on src/main/java/nextstep/subway/dto/LineRequest.java
> +    public LineRequest(String name, String color, long upStationId, long downStationId, Integer distance) {
여기서 wrapper type으로 바꾼 이유가 있을까요...?

2022-06-06 03:20 UTC, chae-yh commented on src/main/java/nextstep/subway/dto/LineResponse.java
> +    private LineResponse(Long id, String name, String color, List<LineStation> stations) {
LineStaion은 도메인인데, 도메인을 그대로 리턴하기보다는 response로 변환해서 전달하는 것은 어떨까요...?

2022-06-06 03:20 UTC, chae-yh commented on src/test/java/nextstep/subway/application/LineTest.java
> +class LineTest {
단위 테스트 좋습니다 👍

2022-06-06 03:20 UTC, chae-yh commented on src/test/java/nextstep/subway/dto/SectionRequestTest.java
> +    void Distance_가_NULL_이거나_0_이하_일_수_없다() {
assertAll 을 써볼 수도 있을 것 같습니다!

2022-06-06 03:20 UTC, chae-yh commented on src/main/java/nextstep/subway/dto/StationResponse.java
> +    public static StationResponse of(LineStation station) {
정적 팩토리 메서드에서 파라미터가 한개면 보통 from을 사용합니다!
```
메서드 명명 방식
1) from
매개 변수를 하나 받아서 해당 타입의 인스턴스를 반환하는 메서드에 주로 사용합니다.
Date date = Date.from(instnace);
2) of
여러 매개변수를 받아 적합한 타입의 인스턴스를 반환하는 집계 메서드에서 주로 사용합니다.
List list = List.of(1, 2, 3);
3) valueOf
from과 of와 비슷한 의미를 갖습니다.
Integer i = Integer.valueOf(10);
- 이펙티브 자바
```

2022-06-06 03:20 UTC, chae-yh commented on src/test/java/nextstep/subway/line/LineStationAcceptanceTest.java
> +public class LineStationAcceptanceTest extends AcceptanceTest {
인수테스트 좋습니다 👍 해피 케이스말고, 오류가 나는 케이스에 대해서도 작성해보면 좋을 것 같습니다!

2022-06-06 14:21 UTC, chj1768 commented on src/main/java/nextstep/subway/domain/Line.java
> +    private List<LineStation> lineStations = new ArrayList<>();
@chae-yh 
요 말씀은 @Embedded 를 사용하여 분리하는 방식으로 생각되는데요. 
시도해 보았는데, 의도대로 동작하지 않는 부분이 있어서 질문드립니다. 
임베디드 타입을 적용하여 List<LineStation> 을 래핑한 LineStations 라는 객체를 만들고 Line 내 멤버 필드로 지정했습니다.
이후 Line 을 조회할 때 다대일 연관관계를 가지는 Lazy 속성의 LineStations 를 entityGraph path 로 지정하여 조회하는 경우
@EntityGraph(attributePaths = { "lineStations" })
기존처럼 한번에 eager 조회가 되지 않네요. 😭 
요약하면 아래 사항이 궁금합니다. 🙏 

**임베디드 타입을 사용할 때는 다른 최적화 방식을 취해야 하는걸까요~?**

2022-06-06 19:08 UTC, chj1768 reviewed
@chae-yh 
리뷰어님, 리뷰주신 코멘트들 포함해서 전체적으로 수정했습니다. 
다만, 구간 테이블 구조를 변경하는 바람에 커밋단위로 수정 코멘트를 달기가 어려워져서 요 리뷰로 전달드려요.

> LineStation의 distance가 시작역에서부터 해당 역까지의 거리를 저장하는 것으로 보입니다! 이 경우 중간에 구간이 더해지거나 삭제된다면 그 뒤로 모든 구간이 영향을 받는 형태입니다. O(n)으로 데이터 전체를 탐색하는 비용이 클 것 같고, 구간 추가 및 삭제 요청이 들어올 때 마다 해당 노선의 전체 데이터가 업데이트가 되어야하는 형태가 되어 트래픽이 커지면 크게 영향받는 구조로 보입니다.
> 변경되는 데이터를 줄여볼 수는 없을까요...?

요부분을 중점적으로 Section 엔티티 구조를 변경해보았습니다. 
대략 이렇게 생각해봤습니다. (그림 이상해서 죄송해요 😭 )
![image](https://user-images.githubusercontent.com/15382538/172229246-889ec65e-e189-44b2-b989-0b4216f8c0e3.png)
매번 꼼꼼한 리뷰 감사드리고, 또 생각해볼만한 부분이 있다면 코멘트 부탁드려요. 🙇

2022-06-07 16:49 UTC, chae-yh approved these changes
현지님 안녕하세요! 피드백 잘 반영해주셨습니다 💯 
질문 주신 내용과 구조 관련된 내용 코멘트로 남겨드리니 확인 부탁드립니다. 하지만 이정도면 미션의 목적을 달성했다고 생각되어 merge 하겠습니다.

이제 마지막 미션이네요 파이팅 입니다 : )

2022-06-07 16:49 UTC, chae-yh commented on src/main/java/nextstep/subway/dto/SectionRequest.java
> +        if (distance == null) {
여기서의 null check는 Bean Validation을 사용해봐도 좋을 것 같습니다
이런 내용도 참조해봐도 좋을 것 같아요!
https://tecoble.techcourse.co.kr/post/2020-09-20-validation-in-spring-boot/

2022-06-07 16:49 UTC, chae-yh commented on src/main/java/nextstep/subway/domain/Section.java
> +    private Station station;
구조 관련해서는 여기서 답변 드리겠습니다.
우선 좋은 구조로 변경해주셨습니다 👍 하지만 한 발자국 더 나아가보는 것도 좋을 것 같아 첨언 드립니다.
현재 구조가 station을 기준으로 previous / next 를 가지고 있는 형태입니다. 이 경우 가장 앞에 있는 staion 혹은 가장 뒤에 있는 station의 경우 null을 갖게 되고, db에도 null로 업데이트 될 것입니다. 
그렇다면, section이 하행 / 상행만 가지고 있으면 어떨까요...?

2022-06-07 16:49 UTC, chae-yh commented on src/main/java/nextstep/subway/domain/Section.java
> +    @ManyToOne(fetch = FetchType.LAZY, cascade = { CascadeType.ALL })
혹시 여기에 CascaseType을 ALL 로 주신 것은 어떤 이유 때문일까요...?

2022-06-07 16:49 UTC, chae-yh commented on src/main/java/nextstep/subway/domain/Sections.java
> +        nextSection.updateDistance(half);
거리를 임의로 계산해서 넣으면 데이터를 확인할 때 잘못된 시그널을 줄 수 있지 않을까요...?

2022-06-07 16:49 UTC, chae-yh commented on src/main/java/nextstep/subway/domain/Sections.java
> +            return null;
null을 인수로 전달하거나 리턴하는 것은 좋지 않은 패턴입니다
```
null을 반환하지마라 / null을 전달하지 마라
 - 클린코드, 7장 오류처리
```
가능한 null을 사용하지 말아보는 것은 어떨까요...?

2022-06-07 16:49 UTC, chae-yh commented on src/main/java/nextstep/subway/domain/Line.java
> +    private List<LineStation> lineStations = new ArrayList<>();
임베디드 타입의 Lazy 일대다 연관관계일 때도 fetch join으로 한번에 가져올 수 있습니다. @EntityGraph의 경우는 한 번 해봐야 알 것 같은데, 가능할 것이라고 생각합니다.
이건 저도 한 번 확인해보고 전달 드리겠습니다!

2022-06-07 16:49 UTC, chae-yh commented on src/main/java/nextstep/subway/application/LineService.java
> +        return stationRepository.findById(stationId).orElse(null);
값이 없으면 에러를 내보내는 것은 어떨까요...?

2022-06-07 16:49 UTC, chae-yh commented on src/main/java/nextstep/subway/domain/Sections.java
> +        return this.sections.stream().filter(section -> Objects.equals(station, section.getStation())).findFirst()
section에 station을 전달해서 해당 station이 있는지 메시지를 전달할 수 있지 않을까요...?
seciton쪽에 getter가 너무 많은데, 단순히 데이터를 가져와서 처리하기 보다는 메시지를 전달하여 로직을 처리하는 형태가 좋아보입니다!

2022-06-07 16:49 UTC, chae-yh commented on src/main/java/nextstep/subway/domain/Sections.java
> +                .orElseThrow(NoSuchElementException::new);
에러도 구체적으로 작성되면 좋을 것 같습니다!

2022-06-07 16:50 UTC, merged