Step4 - 구간 제거 기능
next-step/atdd-subway-admin pull request #761
Opened 2022-06-05 15:47 UTC by kmmin78

안녕하세요, 태화님!

인수 테스트 주도 개발 미션의 4단계 - 구간 제거 기능 PR 드립니다.

드디어 마지막 미션이네요. 🙂

마지막 리뷰도 잘 부탁드립니다! 🙇‍♂️

2022-06-06 06:48 UTC, wooobo requested changes
스펙을 유추 할 수 있도록 인수테스트를 잘작성해주셨네요 :)

몇가지 피드백 남겨 드렸는데 확인후 재요청 부탁드려요~ :pray:

2022-06-06 06:48 UTC, wooobo commented on src/main/java/nextstep/subway/docs/README.md
> +  - [x] 구간제거
요구사항 꼼꼼하게 정리하셔서 한눈에 들어오네요! :100:

2022-06-06 06:48 UTC, wooobo commented on src/main/java/nextstep/subway/domain/Line.java
> +    public void removeSectionByStationId(final Long stationId) {
`removeSectionBy` 인자가 한개이니 이렇게해도 될것같아요 :)

2022-06-06 06:48 UTC, wooobo commented on src/main/java/nextstep/subway/domain/Sections.java
> +        if (sections.size() <= 1) {
```
final int MINIMUM_SIZE = 1;
if (sections.size() <= MINIMUM_SIZE) {
```
간단한 숫자라도 의미있는 네이밍으로 상수화 한다면 좀 더 코드를 읽기에 도움 될것같아요!

2022-06-06 06:48 UTC, wooobo commented on src/main/java/nextstep/subway/domain/Sections.java
> +        if (sections.size() <= 1) {
메서드를 분리한다는건 코드의 복잡도를 잘게 나누고 적절하게 책임을 분리 한다는것도 있겠지만,
사람이 쉽게 이해할 수 있도록 한번 패키징 한다고도 볼 수 있을 것 같아요. `(의도를 들어내는 네이밍)` :thinking: 


`checkSectionLessOrEqualThanOne` 을 사람이 이해하기 쉬울지 의문이에요 단순히 코드를 글로 풀어쓴것 같아요.
한글로 말해본다면 `삭제가 가능한 사이즈인지 검증` 이렇게 생각해보면 어떨까요?
그렇다면 저는 이렇게 생각해보았어요 `validateRemoveAbleSize`

민성님의 생각은 어떠신가요? :smile:

2022-06-06 06:48 UTC, wooobo commented on src/main/java/nextstep/subway/domain/Sections.java
>          return nextSection.map(section -> section.getDownStation());
` return nextSection.map(Section::getDownStation);` 이렇게도 가능합니다~

2022-06-06 06:48 UTC, wooobo commented on src/main/java/nextstep/subway/dto/LineResponse.java
> +        this.sections = line.getSections()
```
this.sections = line.sectionsToList().stream()
      .map(SectionResponse::of)
      .collect(Collectors.toList());
```
개행처리가 다소 많은것 같아요 :thinking: 
지금이 이상한건 아닙니다! 저의 관점으로 생각해주세요~

2022-06-06 06:48 UTC, wooobo commented on src/test/java/nextstep/subway/section/SectionAcceptanceTest.java
> +        final ExtractableResponse<Response> 결과 = 지하철구간_삭제_요청(lineId, -1L);
`-1L` 은 잘못된 숫자 입력에 대한 테스트 일것같아요.

`Station`이 존재하면서 `Line`에는 없는 `ID`값이 적합하지 않을까요? :thinking:

2022-06-06 07:02 UTC, kmmin78 commented on src/main/java/nextstep/subway/domain/Sections.java
> +        if (sections.size() <= 1) {
좋은 의견 주셔서 감사합니다! 
제 생각에도 코드를 풀어쓴 어색한 네이밍보다는 사람이 이해하기 쉬운 함축적인 네이밍을 하는 연습이 필요할 것 같습니다 ㅎㅎ🙏

제시해주신 네이밍이 좋은 것 같습니다!
대신 다른 메서드(`checkStationRegistered`)와 네이밍 컨벤션을 맞춰서 
`checkRemovableSize` 라고 수정하겠습니다! 🙂

2022-06-06 12:42 UTC, wooobo requested changes
피드백 반영 빠르게 해주셨네요 :+1: 

추가적으로 궁금한게 있어서 코멘트남겨 두었어요!
확인부탁드려요! :pray:

2022-06-06 12:42 UTC, wooobo commented on src/main/java/nextstep/subway/domain/Sections.java
> +        final List<Section> matchedSections = findSectionsByStationId(stationId);
```suggestion
       Section targetUpSection = findUpSection(stationId);
       Section targetDownSection = findDownSection(stationId);
```
확실하게 제거할 상행 구간 과 하행구간을 찾아서 분리해보면 어떨까요?

그이유는, `removeAndMergeSections` 메서드에서 
```
final Section firstSection = matchedSections.get(0);
final Section secondSection = matchedSections.get(1);
```
같은 코드는 시간이 지나고 비지니스 로직이 추가되고 변경 될때 예측하기 힘들고 유지보수하는데에 힘듦이 있을것같아요. 
`0`번째가 상행이고, `1`번째가 하행이라는 자료구조가 지켜져야만 하니까요.
또한, 그러한 로직을 파악하려면 많은 메서드의 흐름을 이해해야하는 단점이 있을것 같아요.

만약, 꼭사용해야 한다면 일급콜렉션을 생각해볼수도 있을것같아요.
```
# 예시일뿐 현 로직상으로 그렇게 좋은 솔루션은 아닌것 같기도해요.
MatchSections matchSections = new  MatchSections();
matchSection.firstSection();
matchSection.sectionSection();
```
꼭 수정해야 하는 부분은 아니지만, 민성님의 생각이 궁금하네요 :)
이러한 부분에 대해서 어떻게 생각하시나요? :thinking:

2022-06-06 12:42 UTC, wooobo commented on src/test/java/nextstep/subway/section/SectionAcceptanceTest.java
> +        final ExtractableResponse<Response> 결과 = 지하철구간_삭제_요청(lineId, 노선에_등록되지_않은_역_ID);
:+1:

2022-06-06 15:01 UTC, kmmin78 commented on src/main/java/nextstep/subway/domain/Sections.java
> +        final List<Section> matchedSections = findSectionsByStationId(stationId);
좋은 의견 감사합니다! 🙇‍♂️
저도 처음에는 각 Section을 분리해서 가져오는 것을 고려해봤는데요!
구현을 진행하다 보니, 중요한 건 각 Section의 UpStation에 매칭된 건 지, DownStation에 매칭된 건 지가 아니라

- 지하철 역이 두 Section의 사이에 존재하는 경우 (Section이 2개 매칭된 경우)
- 지하철 역이 Section의 기점 혹은 종점에 존재하는 경우 (Section이 하나만 매칭된 경우)

위의 2가지가 키 포인트라고 생각했습니다.
그래서 각 섹션을 분리해서 가져와도, 결국엔 다시 2개의 섹션이 존재하는지 여부에 따라 로직이 분기될 것이라 생각해서 List형태로 묶어서 진행했었는데요!

예시로 주신 일급컬렉션 형태로 Sections 클래스에 존재하던 책임을 일급컬렉션으로 옮기는 게 현재 로직으로서 최선일 것 같습니다.
(제가 구조를 조금 더 잘 설계했다면 이렇게 되지 않았을 것 같네요 🥲)

다시 생각해볼 수 있는 기회를 주셔서 감사합니다! 😊

2022-06-07 00:56 UTC, wooobo approved these changes
이번 미션 또한 잘 진행해주셨습니다 💯 
피드백에 대해서 열린 마음으로 받아 주신것 같아 
기쁘게 리뷰 할 수 있었습니다!

남은 미션 성공적으로 완료하시길 응원하겠습니다!

2022-06-07 00:56 UTC, wooobo commented on src/main/java/nextstep/subway/domain/MatchedSections.java
> +public class MatchedSections {
와 정말 분리해보셨네요! 💯 💯 
해당 방법이 좋든 안좋든, 이번 pro과정을 진행하면서 다양한 방법을 시도해보시는 것이 좋다고 생각해요!(테스트 코드 까지 진행하시면 더욱좋구요~)
다양한 방식으로 구현하다 보면 보이지 않는게 보일 수 있거든요! 😄 

이번 미션은 마무리 되었으니, 시간되시면 다른 분들은 4단계에서 어떻게 하였는지 PR참고하시면 더욱 도움 될거에요!

2022-06-07 00:56 UTC, merged