Feature/delete section
next-step/atdd-subway-admin pull request #77
Opened 2021-01-03 15:03 UTC by lazy-moon

4단계 - 지하철 노선에 구간 제거 과제 제출합니다.

삭제 부분은 한번에 가져와서 처리하게 구현 해 봤는데, 추가 기능에서 이렇게 구현 했어도 나쁘지 않을 뻔 했네요

이번 미션 리뷰도 잘 부탁드립니다 :)

2021-01-04 15:36 UTC, serverwizard requested changes
지하철 노선 구간 제거 단계 잘 구현해주셨네요!! 👍

몇 가지 코멘트 남겨두었으니 확인 부탁 드릴게요

감사합니다!!

2021-01-04 15:36 UTC, serverwizard commented on src/main/java/nextstep/subway/section/ui/SectionController.java
> +    @DeleteMapping("/sections/{lineId}/{stationId}")
참고로 요구사항에 적혀있는 지하철 구간 삭제 URI는 아래와 같아요.
![image](https://user-images.githubusercontent.com/23587638/103550567-70675280-4eec-11eb-9ecb-6ba4212ed223.png)

2021-01-04 15:36 UTC, serverwizard commented on src/test/java/nextstep/subway/section/SectionAcceptanceTest.java
> +        List<SectionResponse> sections = selectedResponse.jsonPath().getList(".", SectionResponse.class);
참고로 아래와 같이 표현할 수도 있는 걸로 아는데 확인해보세요~
```
List<SectionResponse> sections = Arrays.asList(selectedResponse.as(SectionResponse[].class));
```

2021-01-04 15:36 UTC, serverwizard commented on src/test/java/nextstep/subway/section/SectionAcceptanceTest.java
> +        SectionResponse createdResponse = createRequest(new SectionRequest(line.getId(), station.getId(), lastDownStation.getId(), 3))
createdResponse는 사용하지 않는 변수인 것 같아요~

2021-01-04 15:36 UTC, serverwizard commented on src/test/java/nextstep/subway/section/SectionAcceptanceTest.java
> +        List<String> sectionNames = toSectionNames(selectedResponse);
toSectionNames( )메소드로 변환하지 않고 값 검증을 할 수 있는 방법은 없을까요?

2021-01-06 09:59 UTC, lazy-moon commented on src/main/java/nextstep/subway/section/ui/SectionController.java
> +    @DeleteMapping("/sections/{lineId}/{stationId}")
아하 URI가 정해져있었군요 반영하겠습니다

2021-01-06 10:00 UTC, lazy-moon commented on src/test/java/nextstep/subway/section/SectionAcceptanceTest.java
> +    @DisplayName("역을 삭제한다")
어라 .. 전체 테스트 진행 했었는데 .. 확인해볼게요 !

2021-01-06 10:00 UTC, lazy-moon commented on src/test/java/nextstep/subway/section/SectionAcceptanceTest.java
> +        List<SectionResponse> sections = selectedResponse.jsonPath().getList(".", SectionResponse.class);
오 확인해볼게요 감사합니다 :)

2021-01-06 10:17 UTC, lazy-moon commented on src/test/java/nextstep/subway/section/SectionAcceptanceTest.java
> +    @DisplayName("역을 삭제한다")
![image](https://user-images.githubusercontent.com/25574415/103757255-da4e3c00-5053-11eb-90a4-83425977111c.png)

2021-01-06 10:18 UTC, lazy-moon commented on src/test/java/nextstep/subway/section/SectionAcceptanceTest.java
> +    @DisplayName("역을 삭제한다")
저는 다 통과되는데 .. 어떤 차이점이 있는걸까요 ??

2021-01-07 15:12 UTC, serverwizard approved these changes
지하철 노선 마지막 미션까지 구현하시느라 고생하셨습니다. 💯

제가 드렸던 피드백들은 정답은 아니지만 많은 도움이 되었으면 좋겠네요 :)

몇 가지 코멘트 남겨뒀으니, 참고만 부탁드릴게요~

앞으로 남은 미션도 꼭 완주하셨으면 좋겠습니다 :)

그럼 남은 미션도 화이팅하세요 🥇
감사합니다. 🙇

2021-01-07 15:12 UTC, serverwizard commented on src/main/java/nextstep/subway/line/dto/LineResponse.java
> +        List<StationResponse> stations = sections.stream()
직접 sections를 통해 역 목록을 가져올 수도 있지만, Line을 통해 역 목록을 받아 올 수도 있을 것 같아요. 예를 들어, Line에게 역 목록을 달라고 요청하면  Line은 내부에서 자신이 가지고 있는 Sections를 통해 List<Station>을 만들어 리턴할 수 있을 것 같아서요

```
return LineResponse.of(savedLine, getStationResponses(savedLine));
```

```
private List<StationResponse> getStationResponses(Line savedLine) {
        return savedLine.getStations().stream()
                .map(StationResponse::of)
                .collect(Collectors.toList());
}
```

2021-01-07 15:12 UTC, serverwizard commented on src/test/java/nextstep/subway/section/SectionAcceptanceTest.java
> +    @DisplayName("역을 삭제한다")
다시 돌려봐도 저는 실패가 나네요ㅠ

일단 아래와 같이 `필드에 final 키워드 제거 및 디폴트 생성자 추가`해서 테스트 코드 통과 시켰습니다. 참고하세요~
```
public class SectionResponse {
    private Long id;
    private String lineName;
    private String upStationName;
    private String downStationName;
    private Integer distance;

    public SectionResponse() {
    }

```

2021-01-07 15:12 UTC, merged

2021-01-07 16:20 UTC, lazy-moon commented on src/main/java/nextstep/subway/section/ui/SectionController.java
> +    @PostMapping("/lines/{lineId}/sections")
아하 마침 오늘 강의 들으면서 뭔가 그런 뉘앙스로 얘기하셨던 것 같더라구요 ㅎㅎ 참고할게요 !

2021-01-07 16:25 UTC, lazy-moon commented on src/main/java/nextstep/subway/section/application/SectionService.java
> +    public SectionResponse saveSection(Long lineId, SectionRequest request) {
피드백 주신 부분들이 대부분 그런 내용이었군요, 뭔가 Section을 따로 만들었으니 따로 접근해야한다는 고정관념이 있었던 것 같아요, 이제 어떤 그림을 그리는건지 알겠네요 ㅎㅎ 피드백 감사합니다 !