Step4 : 지하철 노선에 구간 제거
next-step/atdd-subway-admin pull request #79
Opened 2021-01-03 15:19 UTC by rlapwl

안녕하세요 리뷰어님!
리뷰어님 덕분에 제가 생각지도 못한 부분들을 알고 가네요.
`@OrderColumn`에 대해 달아주신 코멘트를 보고 이번에 `@OrderColumn`을 없애고 리팩토링 해보았습니다.
그리고 지난번에 리뷰어님이 달아주신 코멘트들 다 반영하도록 노력했습니다.
이번 리뷰도 잘 부탁드립니다.😊

2021-01-04 01:24 UTC, seok-2-o requested changes
마지막 미션도 구현 정말 잘해주셨네요 💯 

새로 만든 Distance 객체의 책임이 모호한것 같아서 코멘트 남겨 놓았어요.

해당부분 수정 후에 다음 단계로 넘어가면 좋을 것 같아요 🙇

2021-01-04 01:24 UTC, seok-2-o commented on src/main/java/nextstep/subway/section/domain/Distance.java
> +    }
isEqualOrMore 메소드를 더하거나 뺄때, 혹은 디스턴스를 생성할때 진행해주는건 어떤가요 ?

2021-01-04 01:24 UTC, seok-2-o commented on src/main/java/nextstep/subway/section/domain/Distance.java
> +public class Distance {
값 객체를 [불변객체](https://galid1.tistory.com/622)로 만들면 어떤 장점이 있을까요 ?

2021-01-04 01:24 UTC, seok-2-o commented on src/main/java/nextstep/subway/section/domain/Sections.java
> +        sections.remove(nextSection);
여기도 118라인이 정상 실행되어도 추가로 실행될 것 같아요.
의도하신 동작일까요 ?

2021-01-04 01:24 UTC, seok-2-o commented on src/main/java/nextstep/subway/section/domain/Sections.java
> +    private void checkDistance(Section oldSection, Section newSection) {
minusDistance 더나아가 Distance 객체가 처리하는게 더 적합해보여요

2021-01-05 04:24 UTC, rlapwl commented on src/main/java/nextstep/subway/section/domain/Sections.java
> +        sections.remove(nextSection);
오! 제가 지운다는걸 깜박했네요!!

2021-01-05 04:30 UTC, rlapwl commented on src/main/java/nextstep/subway/section/domain/Distance.java
> +    }
네 그게 좋을것같아요!!

2021-01-05 04:59 UTC, rlapwl commented on src/main/java/nextstep/subway/section/domain/Sections.java
> +    private void checkDistance(Section oldSection, Section newSection) {
네! Distance가 책임을 가지고 있는게 좋아보이네요!

2021-01-06 00:09 UTC, seok-2-o approved these changes
피드백 반영 잘 해주셨네요 :) 

미션 내내 정말 잘해주셔서 크게 피드백 드릴 사항이 없던 것 같아요 💯 

좋은 개발자가 되는데 조금이나마 도움이 되기를 바라며,
저와의 미션은 종료되었지만 앞으로도 궁금한점이나 어려운점 있다면 편하게 연락주세요.

다음 미션도 꼭 좋은 모습으로 완주하시기라 믿습니다.🔥
감사합니다.

2021-01-06 00:09 UTC, merged