Step3 - 구간 추가 기능
next-step/atdd-subway-admin pull request #792
Opened 2022-06-09 19:51 UTC by jaesungahn91

ATDD 3단계 PR입니다. 많은 피드백 부탁드립니다!
잘하고있는지 모르겠습니다 ㅠㅠ..

2022-06-10 15:12 UTC, wooobo requested changes
잘진행해 주셨어요!

예외에 대한 테스트가 보이지 않아서 코멘트 남겨두었어요~
확인 후 재요청 부탁드릴께요 :+1:

2022-06-10 15:12 UTC, wooobo commented on src/main/java/nextstep/subway/domain/Sections.java
> +                .orElseThrow(IllegalArgumentException::new);
![image](https://user-images.githubusercontent.com/12059592/173090040-87671e74-5ec9-4af3-aa8f-34199bd76165.png)
---

`예외 케이스에 대한 검증` 테스트코드가 보이지 않아요 :thinking:

2022-06-10 15:12 UTC, wooobo commented on src/test/java/nextstep/subway/section/domain/SectionsTest.java
> +    @MethodSource("구간_등록_시_예외_케이스_3_파라미터")
`@MethodSource`를 활용해보셨네요 :+1:

2022-06-10 15:12 UTC, wooobo commented on README.md
> +- [x] 요구사항 설명에서 제공되는 요구사항을 기반으로 지하철 구간 추가 기능을 구현하세요.
정리 잘해주셨네요 :+1:

2022-06-10 15:12 UTC, wooobo commented on src/main/java/nextstep/subway/domain/Section.java
> +        this.distance = new Distance(this.distance.getValue() - distance.getValue());
```suggestion
        this.distance = this.distance.minus(distance.getValue());
```

```
# Distance.class
  public Distance minus(Integer value) {
      return new Distance(this.value - value);
  }
```

이렇게 해볼수도 있을것 같네요 :)

2022-06-10 15:12 UTC, wooobo commented on src/main/java/nextstep/subway/domain/Sections.java
> +        while (map.get(station) != null) {
```suggestion
        Station station = findFirstUpStation();

        List<Station> stations = new ArrayList<>();
        
        
        Map<Station, Station> map = sections.stream()
                .collect(Collectors.toMap(Section::getUpStation, Section::getDownStation));
        while (map.get(station) != null) {
```

`map` 
변수 선언과 사용하는곳 가깝게 놓는게 좋다고 생각해요 :)

2022-06-10 16:03 UTC, jaesungahn91 commented on src/main/java/nextstep/subway/domain/Sections.java
> +        while (map.get(station) != null) {
좋은 피드백 감사합니다!

2022-06-10 16:05 UTC, jaesungahn91 commented on src/main/java/nextstep/subway/domain/Section.java
> +        this.distance = new Distance(this.distance.getValue() - distance.getValue());
감사합니다 확실하게 의도가 더 보이는거같아요!

2022-06-11 03:05 UTC, jaesungahn91 commented on src/main/java/nextstep/subway/domain/Sections.java
> +                .orElseThrow(IllegalArgumentException::new);
테스트코드 작성했습니다! 코멘트 감사합니다!

2022-06-11 09:00 UTC, wooobo approved these changes
피드백 반영 잘 진행해주셨네요 :)

추가적으로 코멘트 남겨드렸는데
다음단계 진행전에 참고해주세요! :)

`merge` 진행하겠습니다!

2022-06-11 09:00 UTC, wooobo commented on src/main/java/nextstep/subway/domain/Distance.java
> +    public Distance minus(Integer value) {
불변객체 적용해보셨네요 :+1:

2022-06-11 09:00 UTC, wooobo commented on src/main/java/nextstep/subway/domain/Sections.java
> +        if (getSectionStream(section).count() > 1) {
매직넘버를 상수화 해보아도 좋을것 같아요
`1`은 어떠한 의미를 가지고 있을까요?

2022-06-11 09:00 UTC, wooobo commented on src/main/java/nextstep/subway/dto/LineResponse.java
> +        return line.getSections().getStationsInOrder().stream()
`line.getStationsInOrder()` 해도 되지않을까요!?

`Line 에게 Section 목록을 주세요, 그리고 정렬된 역목록을 호출할꺼에요.`
보다는  
`Line에게 정렬된 역목록을 주세요`  
어떻게 생각하시나요!?

2022-06-11 09:00 UTC, merged

2022-06-12 07:38 UTC, jaesungahn91 commented on src/main/java/nextstep/subway/dto/LineResponse.java
> +        return line.getSections().getStationsInOrder().stream()
맞습니다 고민하던 부분이였는데 단위테스드때 Sections에서 테스트하고싶어서 납뒀다가 변경하는게 좋을꺼같아요!

2022-06-12 07:39 UTC, jaesungahn91 commented on src/main/java/nextstep/subway/domain/Sections.java
> +        if (getSectionStream(section).count() > 1) {
중복의 의미를 가지고있습니다! 상수로 변경하겠습니다!