Step3 리뷰 요청 드립니다.
next-step/atdd-subway-admin pull request #801
Opened 2022-06-12 14:51 UTC by jiyeonghwang

안녕하세요, 이슬님! 
개인적인 사정으로 step3 리뷰 요청이 늦어졌습니다..ㅠ
이번에도 리뷰 잘 부탁드립니다! 😊

2022-06-13 12:57 UTC, parkeeseul requested changes
3단계 미션 잘 진행해 주셨네요! 👍 
몇 가지 코멘트 남겨두었으니 확인 부탁드립니다 ! 😄 
월요일 마무리 잘 하시고 미션 화이팅 입니다 🔥

2022-06-13 12:57 UTC, parkeeseul commented on src/test/java/nextstep/subway/section/SectionAcceptanceTest.java
> +                () -> assertThat(response.statusCode()).isEqualTo(HttpStatus.OK.value()),
지하철 노선 조회에 관한 부분도 검증을 해주시는 이유가 있으실까요? 😄

2022-06-13 12:57 UTC, parkeeseul commented on src/main/java/nextstep/subway/application/SectionService.java
> +        line.addSection(section);
line.addSection() 에서 section 을 생성하면 어떨까요?
line.addSection() 을 호출하는 측에서 Section 에 대해서 알 필요가 없어질 것 같아요 😄

2022-06-13 12:57 UTC, parkeeseul commented on src/main/java/nextstep/subway/domain/Section.java
> +    }
Section을 생성할 때 line 값을 초기화 할 수는 없을까요? 😄

2022-06-13 12:57 UTC, parkeeseul commented on src/main/java/nextstep/subway/domain/Section.java
> +    }
다음과 같이 해보면 어떨까요? 😄 
```suggestion
    public boolean isUpStationOrDownStation() {
        return this.downStation.equals(line.getUpStation())
                || this.upStation.equals(line.getDownStation());
    }
```

2022-06-13 12:57 UTC, parkeeseul commented on src/main/java/nextstep/subway/domain/Sections.java
> +    private List<Section> sectionList = new ArrayList<>();
변수명에 타입에 대해 명시해주게 되면 타입이 변경되었을 때 변수명도 함께 변경해 줘야 할 것 같아요.
sections 와 같은 네이밍은 어떨까요? 😄

2022-06-14 12:29 UTC, jiyeonghwang commented on src/test/java/nextstep/subway/section/SectionAcceptanceTest.java
> +                () -> assertThat(response.statusCode()).isEqualTo(HttpStatus.OK.value()),
조회가 잘 되었는지 테스트 하려고 넣어 놓았었는데,
질문을 보고 생각해보니 이 후 테스트도 있어서 불필요한 코드인 것 같네요.
제거하도록 하겠습니다!

2022-06-14 12:40 UTC, jiyeonghwang commented on src/main/java/nextstep/subway/domain/Section.java
> +    }
수정하였습니다!

2022-06-14 12:42 UTC, jiyeonghwang commented on src/main/java/nextstep/subway/application/SectionService.java
> +        line.addSection(section);
무의식중에 비즈니스 로직을 Service단에 넣게 되네요..ㅠ 
수정하였습니다!

2022-06-14 12:43 UTC, jiyeonghwang commented on src/main/java/nextstep/subway/domain/Section.java
> +    }
개선하였습니다!

2022-06-14 12:45 UTC, yeongever0 commented on src/main/java/nextstep/subway/domain/Sections.java
> +    private List<Section> sectionList = new ArrayList<>();
타입 변경 시 변수명 수정에 대해 생각해보지 못했는데,
유연한 코드를 위해 변수명에는 타입을 사용하지 않는 것이 좋아보입니다!
개선하였습니다.

2022-06-14 12:46 UTC, yeongever0 commented
안녕하세요, 이슬님! 이번 피드백도 넘넘 자세하게 해주셔서 감사합니다.
수정 사항에 대해 개선하였으니 확인 부탁드립니다!😊

2022-06-15 12:37 UTC, parkeeseul approved these changes
피드백 잘 반영해 주셨네요! 👍 
다음 단계 진행해 주세요! 😄 
즐거운 저녁 되시고 다음 단계도 화이팅 입니다 🔥

2022-06-15 12:37 UTC, merged