🚀 2단계 - 지하철 노선 기능 PR 리뷰 부탁드립니다.
next-step/atdd-subway-admin pull request #857
Opened 2022-11-10 15:56 UTC by sonyoon7

안녕하세요~
이번 단계에서는 1단계를 바탕으로 
인수인계 테스트를 중심으로 노선 기능 구현해 보았습니다:)

현재 노선 앞뒤로 상행선 종점, 하행선 종점 두개가 위치하고 있는데 
확장성을 고려할 때 어떤식으로 설계를 해야 편할지가 고민되었습니다. 

LineBridge 라고 이후에 노선을 이어줄 역할 혹은 맨 끝임을 알려줄 수 있게끔 
무언가를 해보려고 하다가 우선 테스트중심으로 먼저 인수테스트 작성을 한 후 PR 올려봅니다!🙇

실무에서도 그렇고 항상 어떻게 설계기초를 다져야 이후에 확장성있게 가져갈 수 있을까 고민이 많은데 
그런 부분 리뷰 많이 부탁드려요~😀

또한 아직도 JPA가 많이 서툽니다 연관관계를 어떻게 맺어야 하는게 좋을 지 부터  막막합니다 ㅠㅠ
잘 부탁드립니다!

2022-11-11 14:29 UTC, wooobo requested changes
안녕하세요! 2단계 잘 진행해주셨습니다~!

코멘트 남겨 드렸는데 확인 후 재요청 부탁드려요~
같이 고민 해보고 싶은 내용있으면 DM 주셔도 괜찮습니다~!

화이팅입니다 :smile:

2022-11-11 14:29 UTC, wooobo commented on README.md
> +- [ ] 지하철 노선 생성
완료 부분은 체크표시하면 좋겠네요~!

2022-11-11 14:29 UTC, wooobo commented on src/main/java/nextstep/subway/domain/LineBridge.java
> +class LineBridge {
[3. 필요할 일이 없다](https://www.itworld.co.kr/news/106861)

아직까지는 사용하지 않고 있네요.
물론 어떤 의도로 설계 하신부분인지는 알지만,
위 블로그 참고 해보시면 좋을것 같아요~

2022-11-11 14:29 UTC, wooobo commented on src/main/java/nextstep/subway/application/LineService.java
> +        Station upStation = stationRepository.findById((long) lineCreateRequest.getUpStationId()).get();
역이 없을 경우 대응해야 하지 않을까 고민이되네요 :thinking:

2022-11-11 14:29 UTC, wooobo commented on src/test/java/nextstep/subway/station/StationAcceptanceTest.java
>          if (RestAssured.port == RestAssured.UNDEFINED_PORT) {
`LineAcceptanceTest` 와 중복되는 코드가 있는것 같은데 클래스를 분리 시켜보는것도 좋을것 같네요!

2022-11-11 14:29 UTC, wooobo commented on src/main/java/nextstep/subway/ui/LineController.java
> +    public ResponseEntity searchLine(@PathVariable Long id) {
`ResponseEntity<Response객체>` 반환 클래스 점검 부탁드려요~

2022-11-11 14:29 UTC, wooobo commented on src/main/java/nextstep/subway/domain/Line.java
> +    public Station getUpStation() {
사용하지 않는 메서드는 제거 해주는것이 
추후 유지보수 관리 측면이나 복잡도를 낮추는데에 좋다고 생각해요~

2022-11-11 14:29 UTC, wooobo commented on src/main/java/nextstep/subway/domain/LineBridge.java
> +class LineBridge {
`LineBridge` 적용해보신 만큼 개인적인 생각으로 `Line` 도메인에 적용해보아도 좋을것 같은데요!?

`LineBridge` 도메인이 있어야 될거라고 생각하셨다면,
`LineBridge` 에게 어떤 메시지를 전달해야 될게 있어서가 아닐까요?

TDD의 장점을 좀 더 고민해보시면 좋을 것 같아요.
막연함을 테스트 코드를 활용해서 작은 단계부터 쌓아 간다면 뭔가 형태가 보이지 않을까 생각되어요! :thinking:

2022-11-11 14:29 UTC, wooobo commented on src/main/java/nextstep/subway/domain/Line.java
> +    Line (Builder builder){
개인적으로는 default 보다는 접근제어자를 챙겨주는 편입니다!

2022-11-11 14:29 UTC, wooobo commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +    public static ExtractableResponse<Response> 노선을_생성한다(LineDto.CreateRequest line) {
`특정_노선을_조회한다` 메서드와 유사한 코드가 발생하고 있는것 같은데요~

변하는 부분과 변하지 않는 부분을 적절하게 잘 분리 시키면 중복 코드를 제거 해볼수 있겠네요!

2022-11-11 16:02 UTC, sonyoon7 commented on src/main/java/nextstep/subway/domain/LineBridge.java
> +class LineBridge {
나중에 구간을 구현할 때 도움이 될까 하였는데 
아직 이단계에서 구현하기엔 필요가 없을듯하여 우선 제거해 보았습니다!😅

2022-11-11 16:02 UTC, sonyoon7 commented on src/main/java/nextstep/subway/application/LineService.java
> +        Station upStation = stationRepository.findById((long) lineCreateRequest.getUpStationId()).get();
예외처리를 구현해 보았습니다~

2022-11-12 11:05 UTC, wooobo approved these changes
잘 진행해주셨습니다!

몇가지 코멘트 남겨 드렸는데 확인 부탁드려요~ :smile: 

3단계 진행해주세요! 화이팅입니다!

2022-11-12 11:05 UTC, wooobo commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
>      }
`return HTTP.get("/lines"+lineId);`
중복되는 `RestAssured` 코드를 한곳으로 응집성 있게 모아 볼 수 있겠네요!

2022-11-12 11:05 UTC, wooobo commented on src/test/java/nextstep/subway/station/StationAcceptanceTest.java
>          if (RestAssured.port == RestAssured.UNDEFINED_PORT) {
`StationAcceptanceTest extends AcceptanceTest {`
이런 식으로 분리 시킨다면 인수테스트 공통 부분을 모을수 있겠네요!

2022-11-12 11:05 UTC, wooobo commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +                .setDistance(10);
```suggestion
        LineDto.CreateRequest 라인요청파라미터 = 라인_생성_요청파라미터(lineName...);
```

이렇게 한다면 좀 더 테스트코드에 집중하기 좋을 것 같아요

2022-11-12 11:06 UTC, merged