Step2 pr 요청드립니다.
next-step/atdd-subway-admin pull request #864
Opened 2022-11-11 14:06 UTC by velcronicity

Step2 pr 요청드립니다.

2022-11-11 14:09 UTC, velcronicity commented on src/test/java/nextstep/subway/util/PreDataUtil.java
> +        jdbcTemplate.update("delete from line", new EmptySqlParameterSource());
질문이 있습니다!
`delete from line` 을 `truncate table line` 으로 하고 싶었는데 이해할 수 없는 에러가 나와서요..ㅜㅜ
혹시 확인 좀 부탁드려도 될까요?? 왜 안되는 것일까요?

`PreparedStatementCallback; bad SQL grammar [truncate table line]; nested exception is org.h2.jdbc.JdbcSQLSyntaxErrorException: Cannot truncate "PUBLIC.LINE"; SQL statement:
truncate table line [90106-200]`

2022-11-12 10:13 UTC, seokhongkim commented on src/test/java/nextstep/subway/util/PreDataUtil.java
> +        jdbcTemplate.update("delete from line", new EmptySqlParameterSource());
몇 가지 테스트를 통해 원인을 찾았는데, 그 과정을 코멘트로 말씀드려요!
다음에는 참고하여 디버깅해보시면 학습에도 도움이 될 것 같습니다. :)

1. `delete from line` 과 `truncate table line` 은 사실상 동일한 일을 할텐데 왜 안되는지 궁금하여 공식 문서의 `truncate table` 부분을 찾아 보았습니다.
> https://www.h2database.com/html/commands.html#truncate_table
`Only regular data tables without foreign key constraints can be truncated (except if referential integrity is disabled for this database or for this table). Linked tables can't be truncated.` 이런 내용이 있네요.

2. 테이블이 생성되는 쿼리를 확인해봤습니다. hibernate 로그를 보니 아래와 같은 쿼리가 있네요. station 에서 line 에 대해 FK 제약 조건을 가지고 있었습니다. referential integrity 체크가 되어 truncate 에 실패할 것 같다는 생각이 들었네요.
```sql
    alter table station 
       add constraint FKklalypfiiahjy57wtapf4w92 
       foreign key (line_id) 
       references line
```

3. 가설을 검증하기 위해 `truncate table line` 으로 변경 후, truncate 전에 integrity check 를 disable 했습니다.
> https://www.h2database.com/html/commands.html#set_referential_integrity
```java
jdbcTemplate.update("SET REFERENTIAL_INTEGRITY FALSE", new EmptySqlParameterSource());
```

위 과정을 거친 후 truncate 가 성공하는 것을 확인했습니다. 참고 부탁드립니다. :)

2022-11-12 11:27 UTC, seokhongkim requested changes
태영님, 2단계 미션 잘 구현해주셨습니다. 👍 

남겨주신 질문에는 코멘트로 답변 남겼습니다. :)
이외에 코드에 코멘트를 추가로 조금 남겼으니 확인 부탁드립니다. 🙏

2022-11-12 11:27 UTC, seokhongkim commented on src/main/java/nextstep/subway/application/LineService.java
> +        Station upStation = stationRepository.findById(lineRequest.getUpStationId())
`findById().orElseThrow()` 가 비슷한 형식으로 반복될 것 같은데, 리팩토링해보는 건 어떨까요?

2022-11-12 11:27 UTC, seokhongkim commented on src/main/java/nextstep/subway/exception/AlreadyDeletedException.java
> +public class AlreadyDeletedException extends RuntimeException {
필요한 예외를 정의해서 사용하신 것 좋습니다. 👍

2022-11-12 11:27 UTC, seokhongkim commented on src/main/java/nextstep/subway/exception/NotFoundException.java
> +public class NotFoundException extends RuntimeException {
이 예외는 `Line` 이 없을 때 발생하는 예외일까요? `NoStationException` 처럼 명확한 사용처를 포함해서 정의하시거나, `Line` 과 `Station` 이 없는 경우 동일한 예외를 사용하는 방향으로 고민해보시면 좋을 것 같습니다. :)

2022-11-12 11:27 UTC, seokhongkim commented on src/main/java/nextstep/subway/application/LineService.java
> +    public void changeLine(Long id, LineRequest lineRequest) {
`changeLine` 에서 `LineRequest` 를 그대로 사용하니, `name`, `color` 이외의 다른 필드의 값도 사용하는것인가 싶었네요.
사용하는 필드만 가지고 있는 DTO를 추가해보는 건 어떨까요?

2022-11-12 11:27 UTC, seokhongkim commented on src/main/java/nextstep/subway/exception/NoStationException.java
> +public class NoStationException extends BadRequestException {
`NoStationException` 이 `BadRequestException` 을 상속하도록 구현하신 이유가 있을까요?

2022-11-12 11:27 UTC, seokhongkim commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +    @DisplayName("존재하지 않는 노선을 삭제한다")
예외 케이스에 대한 인수 테스트도 작성해주셨네요! 👍

2022-11-12 11:27 UTC, seokhongkim commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +        assertThat(jsonPath.getString("name")).isNotBlank();
검증을 위해서는 라인의 이름은 특정 값(e.g., 신분당선)과 같은지 검증이 필요할 것 같아요 :)

2022-11-12 11:27 UTC, seokhongkim commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +    static class LineRequestDto {
생성자 때문에 `LineRequest` 를 사용하지 않고 별도의 클래스를 추가하신 걸까요? create 요청 시 `Map` 을 사용하는 것도 방법일 것 같네요! (꼭 반영하실 필요는 없고 이게 더 쉬운 방법일 것 같아서 남긴 코멘트입니다.)

2022-11-13 00:28 UTC, velcronicity commented on src/test/java/nextstep/subway/util/PreDataUtil.java
> +        jdbcTemplate.update("delete from line", new EmptySqlParameterSource());
외래키 제약조건 때문에 안됐던거였군요
자세한 설명 감사드립니다 👍 👍

2022-11-13 00:41 UTC, velcronicity commented on src/main/java/nextstep/subway/application/LineService.java
> +        Station upStation = stationRepository.findById(lineRequest.getUpStationId())
private 메소드로 리팩토링 해보았습니다. 리뷰 감사합니다!

2022-11-13 00:47 UTC, velcronicity commented on src/main/java/nextstep/subway/exception/NotFoundException.java
> +public class NotFoundException extends RuntimeException {
`Line` 을 조회하거나 수정할 때 `query parameter` 로 요청이 오는 데 유효하지 않을때엔 `NotFoundException`을 발생시키고 `404(not found)` 응답코드를 사용했습니다.
`Line` 생성 시 `Station` id 를 body에 입력하는데 이 station id 가 없을때 `NoStationExcepion` 을 발생시키고 `400(bad request)` 로 처리했습니다.

요청 시도하려는 자원이 존재하지 않는 데이터일 때 요청 성격을 구분하지 않고 일괄적으로 응답코드를 주는게 더 좋을까요??
400 이나 404 중 어떤 응답을 하는게 더 좋을까요??

2022-11-13 00:52 UTC, velcronicity commented on src/main/java/nextstep/subway/application/LineService.java
> +    public void changeLine(Long id, LineRequest lineRequest) {
`Controller` 의 `DTO` 를 `Service` 에 바로 호출하는게 조금 아쉬웠는데 `change`의 경우 `Service` 전용 `DTO` 를 만들면 더 좋겠군요
리뷰 감사합니다!

2022-11-13 00:55 UTC, velcronicity commented on src/main/java/nextstep/subway/exception/NoStationException.java
> +public class NoStationException extends BadRequestException {
`@ExceptionHandler` 처리를 1번만 해주고싶어서 그랬습니다.
NoStationException 과 `SameStationException` 이 `BadRequestException` 을 상속하고 있습니다.
```
@ExceptionHandler
    public ResponseEntity<?> handleBadRequestException(BadRequestException e) {
        return ResponseEntity.badRequest().body(new ErrorResponse(e.getMessage()));
    }
```

2022-11-13 01:16 UTC, velcronicity commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +    static class LineRequestDto {
강의에서 테스트코드 요청 때 프로덕션의 DTO 를 사용하기보단 분리하는게 ATDD 에선 더 낫다고 말씀하셔서요!
검증 때 요청했던 값을 찾아야하는 경우가 많아서 테스트전용 DTO 를 추가했습니다.
추후 `Map` 사용에 대해 고민해보겠습니다
리뷰 감사합니다 👍 👍

2022-11-13 10:01 UTC, seokhongkim approved these changes
태영님 2단계 미션 코멘트 잘 반영해주셨습니다. 💯 
2단계 PR도 이만 머지하도록 하겠습니다.

코멘트를 조금 남겼는데, 다음 단계 미션을 진행하실 때 참고해보셔도 좋겠습니다.
3단계 미션에서 뵙겠습니다. 😀

2022-11-13 10:01 UTC, seokhongkim commented on src/main/java/nextstep/subway/application/LineService.java
> +    private Station findStationById(Long id, RuntimeException exception) {
이 메소드의 경우 `Station` 에 대한 조회이니 `StationService` 에서 제공해주는 것이 클래스의 역할에도 잘 어울리고, 다른 곳에서도 `Station` 을 조회할 때 사용하기 좋을 것 같네요!

2022-11-13 10:01 UTC, seokhongkim commented on src/main/java/nextstep/subway/application/LineService.java
> +        Line line = findLineById(id, new AlreadyDeletedException());
이미 삭제된 `Line` 이 아니라, 애초에 존재하지 않았던 `Line` 정보를 삭제 요청할 수도 있지 않을까요? :)

2022-11-13 10:01 UTC, seokhongkim commented on src/main/java/nextstep/subway/ui/LineController.java
>      public ResponseEntity<?> changeLine(@PathVariable Long id, @RequestBody LineRequest lineRequest) {
컨트롤러에서도 `LineChange` 에 대한 정보만 `@RequestBody` 로 받아와도 괜찮지 않을까요?

2022-11-13 10:01 UTC, seokhongkim commented on src/test/java/nextstep/subway/util/PreDataUtil.java
> +        jdbcTemplate.update("truncate table line", new EmptySqlParameterSource());
데이터 삭제가 완료된 후에는 `SET REFERENTIAL_INTEGRITY TRUE` 로 돌려 놓는 것이 좋을 것 같습니다 :)

2022-11-13 10:01 UTC, seokhongkim commented on src/main/java/nextstep/subway/exception/NotFoundException.java
> +public class NotFoundException extends RuntimeException {
상황에 맞춰 예외를 구분해서 전달하시는 것은 좋습니다. 상황별로 코드를 나눠서 요청하신 것도 좋습니다.
다만, 우려되는 점은 http status code 를 준수하기 위한 예외 구분이 코드의 복잡도를 너무 높이는 것은 아닐까 싶습니다. http status code 의 구분은 컨트롤러의 관심사가 되어야 하는데, 레포지토리 혹은 서비스에서 예외를 잘 구분해서 사용해야 하는 것으로 보이기도 하네요.

예를 들면, 지하철역이 존재하지 않는 경우 발생해야 하는 예외는 `NoStationException` 이 될텐데, 노선을 업데이트하는 과정에서는 400 코드를 내려줘야 하고, 지하철 역을 조회하는 API에서는 404가 내려가야하는데, 이 구분이 레포지토리 혹은 서비스에서 적절한 예외를 사용하는 방식으로 구현이 된 것 같습니다.

제 생각에는 미션으로 진행하는 프로젝트의 경우 리소스에 접근할 때 자원이 없어서 발생하는 예외는 404를 사용하도록 컨트롤러에서 제어하고, 이외 API에 대해서는 400 코드를 사용하도록 컨트롤러에서 제어해도 괜찮지 않을까 싶네요. 제 개인적인 경험으로는 상태 코드는 커스텀 코드를 하나 사용하고, 응답 내부에 별도의 코드와 메시지를 포함하는 것이 관리가 쉬웠습니다. :)

2022-11-13 10:01 UTC, merged

2022-11-14 10:51 UTC, velcronicity commented on src/main/java/nextstep/subway/application/LineService.java
> +        Line line = findLineById(id, new AlreadyDeletedException());
맞습니다 존재하지 않는 데이터를 삭제 요청했을 경우 삭제 성공과 같은 응답을 주도록 구현했습니다.
존재하지 않는 것을 삭제요청했을 땐 별도의 에러처리 응답을 해야될까요?

2022-11-20 04:34 UTC, seokhongkim reviewed
예전에 코멘트를 남겼는데, pending 상태로 남아있었네요. 😢 
지금이라도 보실 수 있을 것 같아서 코멘트 전달 드려봅니다.

2022-11-20 04:34 UTC, seokhongkim commented on src/main/java/nextstep/subway/application/LineService.java
> +        Line line = findLineById(id, new AlreadyDeletedException());
조금 고민이 되긴 하네요. 이 부분은 API 스펙에 정의가 필요할 것 같아서 정답은 없는 것 같아요.

예를 들어, 삭제를 요청했을 때 아래와 같은 케이스가 있을 것 같습니다.
1. 삭제에 성공함
2. 삭제되어 존재하지 않는 것으로 나오는 데이터 (이미 삭제됨)
3. 처음부터 존재하지 않는 데이터
4. 아이디가 잘못됨

1번은 삭제가 성공했음으로 응답이 가는 게 맞아 보입니다.
4번 케이스의 경우 bad request 로 응답이 가야 할 듯 하네요. 예를 들면 아이디 값으로 0, -1 등의 값이 오는 경우가 되겠죠.

2번과 3번을 어떻게 처리해야 하는지가 고민인데, 저는 2번과 3번의 응답이 다르게 가면 안 된다고 생각합니다. 이유는 2번을 다르게 처리하는 것은 soft delete 로 삭제가 구현되어 있을때만 가능하기 때문에, 2번과 3번의 응답이 달라지면 사용자가 구현을 알 수 있기에 좋지 않은 처리 방법이라고 생각합니다.

그렇다면 2번과 3번 케이스에 대해 삭제에 성공한 것으로 보낼지, 4번처럼 bad request 로 응답을 보낼지를 결정할텐데요. 저는 bad request 로 응답을 보낼 것 같기도 합니다. 이유는 아래와 같습니다. 
* 일반적인 사용 흐름에서 삭제는 데이터가 존재하는지를 아는 상태에서 이뤄집니다. (e.g., 노선 목록에서 삭제하기, 노선 상세 화면에서 삭제하기 등과 같은 시나리오)
* 실제로 성공하지 않은 요청에 대해 성공으로 응답이 가는 것은 혼선을 줄 수 있기에 좋지 않다고 생각합니다.

다만, 이는 제가 `삭제된 노선은 조회할 수 없다` 와 같은 전제하에 서술한 내용이므로, 요구사항이 달라지면 다른 구현이 필요하다고 생각합니다. :)