Step2 - 지하철 노선 기능 PR 요청합니다.
next-step/atdd-subway-admin pull request #868
Opened 2022-11-11 17:19 UTC by hyeongJuKim

이번 리뷰도 잘 부탁드립니다.🙇🏻‍♂️

작은 부분이라도 코멘트 해주시면 저에게 큰 도움이 됩니다 :)

감사합니다 😆

2022-11-12 08:45 UTC, minzzang requested changes
안녕하세요 형주님~!

ATDD 2단계 미션 잘 작성해주셨네요! :+1:
인수 테스트도 가독성 좋게 잘 작성해주시고 테스트 격리도 잘해주셨네요 ~ 

코멘트 남겼는데 확인 부탁드립니다. :pray:

그럼 이번 주말도 화이팅입니다. :muscle:

2022-11-12 08:45 UTC, minzzang commented on README.md
> +- [x] 지하철 노선 삭제
기능 목록 정리 👍

2022-11-12 08:45 UTC, minzzang commented on src/main/java/nextstep/subway/application/LineService.java
> +    @Transactional
읽기 작업만 있는 것 같은데 @Transactional 을 쓰신 이유가 있을까요~?

2022-11-12 08:45 UTC, minzzang commented on src/main/java/nextstep/subway/application/LineService.java
> +    public void updateLine(Long id, LineRequest lineRequest) throws NotFoundException {
RuntimeException이 아닌 Exception을 상속한 예외를 throw한 이유가 있을까요?

2022-11-12 08:45 UTC, minzzang commented on src/main/java/nextstep/subway/domain/Line.java
> +    public void setDownStation(Station downStation) {
이번 미션에서는 setter를 지양해보면 어떨까요 ~?

2022-11-12 08:45 UTC, minzzang commented on src/main/java/nextstep/subway/dto/LineRequest.java
> +    public LineRequest() {
사용되지 않는 생성자가 같은데 접근 제어자 수준을 낮춰보면 어떨까요~?

2022-11-12 08:45 UTC, minzzang commented on src/main/java/nextstep/subway/dto/LineRequest.java
> +//    public LineRequest toLine() {
사용하지 않는 주석 코드는 없애는게 좋을 것 같아요! 😄

2022-11-12 08:45 UTC, minzzang commented on src/main/java/nextstep/subway/dto/LineResponse.java
> +    public static LineResponse of(Line line) {
정적 팩토리 메소드 사용 👍

2022-11-12 08:45 UTC, minzzang commented on src/main/java/nextstep/subway/ui/LineController.java
> +@RequestMapping(PathConstant.LINE_ROOT_PATH)
저는 개인적으로 url에 사용되는 문자열을 그대로 사용하는 편인데 어떤 path를 가지고 있는지 한번에 파악할 수 있고 검색을 할 경우에 해당 컨트롤러를 쉽게 찾을 수 있는 이점있다고 생각하기 때문입니다. 형주님은 이 부분에 대해서 어떻게 생각하시고 평소에 어떻게 작성하셨나요~?

2022-11-12 08:45 UTC, minzzang commented on src/main/java/nextstep/subway/ui/LineController.java
> +    @PostMapping()
()를 없애줘도 될 것 같아요 ! 😄

2022-11-12 08:45 UTC, minzzang commented on src/main/java/nextstep/subway/ui/LineController.java
> +    @GetMapping(produces = MediaType.APPLICATION_JSON_VALUE)
produces 옵션을 사용한 이유가 있을까요~?

2022-11-12 08:45 UTC, minzzang commented on src/test/java/nextstep/subway/BaseAcceptanceTest.java
> +    public static Long getResponseId(ExtractableResponse<Response> response) {
getResponseId는 BaseAcceptanceTest와 성격이 조금 다른 것 같은데 여기에 작성하신 이유가 있나요~?

2022-11-12 08:45 UTC, minzzang commented on src/test/java/nextstep/subway/ResponseAssertTest.java
> +public class ResponseAssertTest {
assert 분리 👍

2022-11-12 08:45 UTC, minzzang commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +        ExtractableResponse<Response> lineResponse = 지하철노선_생성_요청("1호선", "bg-red-600","강남역", "역삼역", 10);
lineResponse도 한글로 표현하면 좋을 것 같아요!

2022-11-12 08:45 UTC, minzzang commented on src/test/java/nextstep/subway/utils/DatabaseCleanup.java
> +public class DatabaseCleanup implements InitializingBean {
테스트 격리도 잘하셨네요!! 혹시 여러 방법 중에 선택하신 이유가 있을까요~?

2022-11-12 09:35 UTC, hyeongJuKim commented on src/main/java/nextstep/subway/application/LineService.java
> +    @Transactional
바로 위의 코드를 복사하면서 같이 붙어들어갔습니다. 
PR 전에 코드 전체를 돌아보긴 했는데 생각하지 못했엇네요.. 🥲

2022-11-12 09:57 UTC, hyeongJuKim commented on src/main/java/nextstep/subway/application/LineService.java
> +    public void updateLine(Long id, LineRequest lineRequest) throws NotFoundException {
기존의 코드를 재사용하자는 의도에서 NotFoundException 이름을 보고 사용했지만, 지금 와서 보니 RuntimeException이 적절할 것 같네요 !!

2022-11-12 10:02 UTC, hyeongJuKim commented on src/main/java/nextstep/subway/domain/Line.java
> +    public void setDownStation(Station downStation) {
꼭 필요할 한 순간 다른 의미 있는 메서드명으로 만들어 사용하도록 하겠습니다!

2022-11-12 10:24 UTC, hyeongJuKim commented on src/main/java/nextstep/subway/ui/LineController.java
> +    @GetMapping(produces = MediaType.APPLICATION_JSON_VALUE)
뼈대코드 `StationController.showStations()`에도 기본적으로 있던 코드인데
제거해도 정상적으로 동작하네요.

검색해보니 응답 결과의 타입을 명시해주는 것으로 나옵니다.
지금 보니 굳이 필요는 없네요.
정확히 어떤 케이스에 사용해야 유의미한지 잘 모르겠네요. 😢

2022-11-12 10:26 UTC, hyeongJuKim commented on src/main/java/nextstep/subway/ui/LineController.java
> +    @PostMapping()
아하 ! 감사합니당 ㅎㅎ

2022-11-12 10:34 UTC, hyeongJuKim commented on src/main/java/nextstep/subway/ui/LineController.java
> +@RequestMapping(PathConstant.LINE_ROOT_PATH)
저도 평소에 문자열 그대로 사용합니다.

이번 교육과장에서는 TDD, ATDD를 진행하면서 리펙토링에 관점을 맞추다 보니 한번 시도하게 되었습니다.
시도하면서도  과연 적절한가에 대한 의문은 계속 있었습니다.

이야기 하신대로 한눈에 파악하거나, 문자열 검색, 호출시점에서의 이동이 불편한 부분이 있습니다.
계속 코드를 봐도 불편한 느낌은 사라지지 않네요.

문자열 그대로 사용하는 방식으로 가보겠습니다.😊

2022-11-12 10:44 UTC, hyeongJuKim commented on src/test/java/nextstep/subway/utils/DatabaseCleanup.java
> +public class DatabaseCleanup implements InitializingBean {
기존에 `@DirtiesContext`를 통해 테스트 격리를 진행했으나,
이번주 강의를 듣고 속도면에서 가장 최적회 된 방법을 적용하게 되었습니다.

`@DirtiesContext`는 매번 컨텍스트를 로드해야 하므로 속도가 느리지만,
이 방법은 데이터 베이스만 초기화 하므로 속도 면에서 더 유리한 것 같습니다.

2022-11-12 13:20 UTC, hyeongJuKim commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +        ExtractableResponse<Response> lineResponse = 지하철노선_생성_요청("1호선", "bg-red-600","강남역", "역삼역", 10);
오.. given when then에 대해서만 생각했었는데..
적용해보겠습니다 ㅎㅎ

2022-11-12 13:27 UTC, hyeongJuKim commented on src/test/java/nextstep/subway/BaseAcceptanceTest.java
> +    public static Long getResponseId(ExtractableResponse<Response> response) {
모든 entity에는 id가 존재하기 때문에 `BaseAcceptanceTest`를 상속받아 사용하도록 배치하였습니다.ㅎㅎ
이 부분에 대해서도 의견 주시면 감사하겠습니다.🙇🏻‍♂️

2022-11-13 11:02 UTC, minzzang commented on src/test/java/nextstep/subway/BaseAcceptanceTest.java
> +    public static Long getResponseId(ExtractableResponse<Response> response) {
그렇게 생각할 수도 있겠군요!! 그런 이유라면 좋은 것 같습니다 ~ 👍

2022-11-13 11:59 UTC, minzzang commented on src/main/java/nextstep/subway/ui/LineController.java
> +    @GetMapping(produces = MediaType.APPLICATION_JSON_VALUE)
사용하지 않을 경우에는 메서드 리턴 타입을 보고 반환한다와 차이점만 알고 있어도 좋을 것 같아 질문 드렸습니다 😄

2022-11-13 12:01 UTC, minzzang approved these changes
안녕하세요 형주님~!

피드백 깔끔하게 잘 반영해주셨네요! :+1:

그럼 다음 미션도 화이팅입니다. :muscle:

2022-11-13 12:01 UTC, merged