Step2
next-step/atdd-subway-admin pull request #887
Opened 2022-11-12 17:17 UTC by hyeongwon-up

2022-11-13 07:37 UTC, heowc requested changes
안녕하세요. 빠르게 2단계를 진행해주셨네요 👍 

전체적으로 잘 진행해주셨지만, 약간 아쉬운 부분이 소소한 피드백을 남겨봤습니다. 🙇 

궁금하신 점이나 의논할 것이 있다면 깃헙 코멘트나 슬랙 DM 으로 연락주세요 🙏

2022-11-13 07:37 UTC, heowc commented on src/main/java/nextstep/subway/dto/LineRequest.java
> +public class LineRequest {
저장하는 request 클래스와 갱신하는 request 클래스를 분리해보는 것은 어떨까요? 🤔

2022-11-13 07:37 UTC, heowc commented on src/main/java/nextstep/subway/domain/Sections.java
> +    private List<Section> sectionList = new ArrayList<>();
`sectionList` 보다는 `sections`는 어떨까요? 🤔 
특정 구현체에 대한 의미를 담기보다는 복수형이라는 의미로 변수명을 작성하는게 좋다고 생각합니다 👍

2022-11-13 07:37 UTC, heowc commented on src/test/java/nextstep/subway/DatabaseCleanup.java
> +public class DatabaseCleanup implements InitializingBean {
테스트간 데이터 의존성을 줄이기 위해 각 테이블 데이터를 지워주는 서비스를 만드셨네요 👍

2022-11-13 07:37 UTC, heowc commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +    @BeforeEach
위와 같은 메소드 순서로 작성하신 이유가 궁금합니다 😄  

변수 

테스트 관련 메소드

테스트 메소드

2022-11-13 07:37 UTC, heowc commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +    }
하나의 메소드로 만들고 파라미터를 추가하는건 어떨까요 ? 🤔

2022-11-13 07:37 UTC, heowc commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +            databaseCleanup.afterPropertiesSet();
해당 코드는 굳이 명시적으로 호출하지 않아도 동작하는 메소드에요~ 😄 
https://atoz-develop.tistory.com/entry/Spring-%EC%8A%A4%ED%94%84%EB%A7%81-%EB%B9%88Bean-%EC%B4%88%EA%B8%B0%ED%99%94-%EC%86%8C%EB%A9%B8-%EC%8B%9C-%ED%8A%B9%EC%A0%95-%EC%9E%91%EC%97%85%EC%9D%84-%ED%95%98%EB%8A%94-%EB%B0%A9%EB%B2%95

2022-11-13 07:37 UTC, heowc commented on src/test/java/nextstep/subway/station/StationAcceptanceTest.java
>      }
`DatabaseCleanup` 사용하는 부분이 중복코드로 보이는데요. 이를 어떻게 해결해볼 수 있을까요? 🤔

2022-11-13 07:37 UTC, heowc commented on src/main/java/nextstep/subway/ui/LineController.java
> +        System.out.println("check pint");
디버깅 코드로 보입니다 😄

2022-11-17 14:43 UTC, hyeongwon-up commented on src/main/java/nextstep/subway/dto/LineRequest.java
> +public class LineRequest {
분리해보았습니다.

2022-11-17 14:46 UTC, hyeongwon-up commented on src/main/java/nextstep/subway/domain/Sections.java
> +    private List<Section> sectionList = new ArrayList<>();
전에도 리뷰받은 사항인데, 전 회사 컨벤션이 몸에 뵈어있네요 ... ㅎㅎ
수정하였습니다.

2022-11-17 14:48 UTC, hyeongwon-up commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +    @BeforeEach
테스트 관련 메서드를 테스트 메소드 중간중간 쓰니까 코드가 보기 안좋아서, 관련 메서드끼리 모아놓으려고 하다보니 위와 같은 구조가 된 것 같습니다.

2022-11-17 14:56 UTC, hyeongwon-up commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +    }
반복되는 코드가 줄어서 좋습니다.
그런데 인수테스트를 하면서 한글 메서드 한글 변수 명과 시나리오에 대한 좀 압박?이 있는 것 같습니다.
한글로 명확하게 표현하는게 인수테스트 답지않을까 라는 고민이 들었네요.

2022-11-17 14:57 UTC, hyeongwon-up commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +            databaseCleanup.afterPropertiesSet();
넵. 참고 사이트 감사합니다. ㅎㅎ

2022-11-17 14:57 UTC, hyeongwon-up commented on src/main/java/nextstep/subway/ui/LineController.java
> +        System.out.println("check pint");
삭제하였습니다.  😢

2022-11-17 15:36 UTC, hyeongwon-up commented on src/test/java/nextstep/subway/station/StationAcceptanceTest.java
>      }
공통된 부분을 추출해서 상속해서 사용하도록 수정해보았습니다.

2022-11-18 01:40 UTC, heowc approved these changes
피드백 반영 감사합니다 👍 

다음 단계를 진행해주세요

궁금하신 점이나 의논할 것이 있다면 언제든 깃헙 코멘트나 슬랙 DM 으로 연락주세요 🙏

2022-11-18 01:40 UTC, heowc commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +    @BeforeEach
실제로 보기 위한 것은 테스트라면, 테스트 메소드가 가장 위로 가야하지 않을까란 생각을 해봤습니다. 🤔 
이건 컨벤션이라서 개인/팀에 따라 다를 순 있어요. 형원님의 기준이 있으신가 해서 여쭤봤습니다. 👍 

아래 내용은 참고만 해주세요 👍 
https://velog.io/@sojukang/public-private-%EC%9E%90%EB%B0%94-%EB%A9%94%EC%86%8C%EB%93%9C-%EC%A0%95%EB%A0%AC-%EC%88%9C%EC%84%9C%EB%8A%94-%EC%96%B4%EB%96%BB%EA%B2%8C-%ED%95%B4%EC%95%BC-%ED%95%A0%EA%B9%8C

2022-11-18 01:40 UTC, heowc commented on src/test/java/nextstep/subway/line/LineAcceptanceTest.java
> +    }
꼭 필수는 아니에요. 저도 이전에 인수테스트 작성시 영어로 작성하긴 했는데요. (이후 atdd에서는 한글로 작성하긴 했지만요)
사용자 관점에서 읽기 편하게 느껴진다면 어떤식으로든 작성할 수 있다면 상관없을 것 같아요 👍 

저는 저기서 코멘트를 드린 이유는 변수명으로도 의미를 부여할 수 있는데 따로 메소드를 다 만들 필요가 있을까싶어서 그랬습니다 ㅎ

2022-11-18 01:40 UTC, merged