[sixthou] - Step3 PR 리뷰 부탁드립니다.
next-step/atdd-subway-admin pull request #932
Opened 2022-11-16 05:45 UTC by sixthou

안녕하세요!

생각했던것 보다 과제가 훨씬 어려워서 시간이 오래걸렷네요ㅠㅠ
객체지향적으로 책임을 어디에 부여해야하는지 생각하면서 진행하려고 노력했습니다.

잘 부탁드립니다🙏

2022-11-16 13:46 UTC, wheejuni requested changes
아주 간단한 코멘트 하나만 드립니다 💯 
코드 완성도가 많이 높아지셨네요. 👍

2022-11-16 13:46 UTC, wheejuni commented on src/main/java/nextstep/subway/dto/SectionRequest.java
> +    private String upStationId;
처음부터 `Long` 으로 선언하시지 않은 이유가 있을까요?

2022-11-16 14:26 UTC, sixthou commented on src/main/java/nextstep/subway/dto/SectionRequest.java
> +    private String upStationId;
요구사항 설명에 나와 있는 명세를 기준으로 작업을 하여 `String`으로 선언하게 되었습니다. 
<img width="404" alt="스크린샷 2022-11-16 오후 11 20 49" src="https://user-images.githubusercontent.com/20774279/202205213-b0c07480-60c0-46cf-aa65-ded540ad9eb8.png">

말씀해주신 부분에 대해서 아래 두가지 json 형태로 테스트를 해보았는데요
```json
{
    "upStationId":"4",
    "downStationId":"2",
    "distance":10
}
```
```json
{
    "upStationId":4,
    "downStationId":2,
    "distance":10
}
```
String이나 Long 타입 모두 위 두 json 타입에 대해서 정상적으로 값 파싱이 되는걸 확인했습니다.!!
받아오는 값이 ID값이 만큼 String 보다 Long으로 선언을 해주는게 더 맞는것 같아 피드백 주신부분 수정했습니다.

2022-11-17 14:05 UTC, wheejuni approved these changes
👍 수고 많으셨습니다.

2022-11-17 14:05 UTC, merged