Step3 구간 추가 기능 리뷰 요청 드립니다.
next-step/atdd-subway-admin pull request #934
Opened 2022-11-16 07:54 UTC by dongha-byun

안녕하세요.

우아한 테크캠프 Pro 5기 교육생 변동하 입니다.

3주차 인수 테스트 주도 개발 step3 구간 추가 기능 미션에 대한 피드백을 요청드립니다.

감사합니다.

2022-11-16 15:34 UTC, heowc requested changes
안녕하세요. 빠르게 3단계를 진행 해주셨네요. 👍 

인수 테스트를 잘 작성해주셨지만, 바로 merge 하기엔 다소 아쉬운 부분이 있어 약간의(?) 코멘트를 남겨봤습니다. 
확인 부탁드려요! 🙏 

궁금하신 점이나 이야기 나누고 싶은 부분이 있다면 깃헙 코멘트, 슬랙 DM 편하게 남겨주세요!

2022-11-16 15:34 UTC, heowc commented on src/main/java/nextstep/subway/domain/LineStation.java
> +public class LineStation extends BaseEntity {
구간 추가하기가 `addSection`라면 엔티티로 `Section`으로 만드는건 어떨까요? 🤔

2022-11-16 15:34 UTC, heowc commented on src/main/java/nextstep/subway/domain/LineStation.java
> +        this.preStation = preStation;
생성자애는 검증 로직이 필요없을까요 ? 🤔

2022-11-16 15:34 UTC, heowc commented on src/main/java/nextstep/subway/domain/LineStations.java
> +public class LineStations {
`Embeddable`로 감싸주셨네요 👍

2022-11-16 15:34 UTC, heowc commented on src/main/java/nextstep/subway/domain/Line.java
> +        lineStations.add(preStation, station, distance);
이것도 구간 추가로 봐야한다면 `addSection`을 사용해볼 수 있지 않을까요 ? 🤔

2022-11-16 15:34 UTC, heowc commented on src/main/java/nextstep/subway/domain/LineStations.java
> +    public void addSection(Station preStation, Station station, Integer distance){
해당 비즈니스 로직 관련해서 몇가지 질문이 있어요~

1) 해당 메소드가 너무 길어요

우테코Pro 미션 진행시, 가급적이면 여러 방법을 통해 메소드를 10줄이하로 줄여보면 좋을 것 같습니다 👍 

2) 시간복잡도가 다소 비효율적이에요.

전체를 순회하면서 존재여부를 판별하고 다시 전체를 순회하면서 찾아 갱신하는 것이 비효율적이라고 느껴지는데 어떻게 개선해볼 수 있을까요? 

3) distance 계산이 없어요.

중간에 구간이 추가되는 경우는 distance가 나눠어지는(혹은 빼지는) 경우가 생길 것 같은데 관련된 내용이 누락된 것 같습니다.

2022-11-16 15:34 UTC, heowc commented on src/main/java/nextstep/subway/domain/LineStations.java
> +    public List<LineStation> getOrderStations(){
이쪽도 위와 동일하게 메소드 길이/효율성 측면에서 개선해보면 좋을 것 같습니다 :)

2022-11-16 15:34 UTC, heowc commented on src/main/java/nextstep/subway/ui/LineStationController.java
> +        LineResponse line = lineService.findLine(id);
컨트롤러에서 각기 다른 서비스를 호출하면 서로 트랜잭션이 만들어질텐데 의도하신 부분일까요 ? 🤔 
그리고 해당 부분에서 `LineResponse` 응답이 필요한 부분인가 다시 한번 확인 부탁드려요~

2022-11-16 15:34 UTC, heowc commented on src/test/java/nextstep/subway/line/LineStationAcceptanceTest.java
> +    LineResponse line;
이름을 `강남역`, `잠실역`, `2호선`으로 넣어보는건 어떨까요 ? 🤔 
이왕 한글명을 사용한다면 보다 읽기 좋을 수 있다고 생각이 드네요
(사실 이미 2호선에 대한 노선도가 머리속으로 그려지는 것도 있지만요 🤣 )

2022-11-16 15:34 UTC, heowc commented on src/test/java/nextstep/subway/line/LineStationAcceptanceTest.java
> +    @DisplayName("노선 구간 추가 시, 기존 구간거리보다 크면 추가되지 않는다.")
다양한 인수 테스트를 잘 작성해주셨습니다 👍

2022-11-17 19:19 UTC, dongha-byun commented on src/main/java/nextstep/subway/domain/LineStation.java
> +        this.preStation = preStation;
말씀주신 피드백 받고 생각해보니 같은 역으로 들어올 수 있을 것 같습니다..!ㅠㅠ 다음 리뷰요청 때 반영해 놓겠습니다!

2022-11-17 19:22 UTC, dongha-byun commented on src/main/java/nextstep/subway/domain/Line.java
> +        lineStations.add(preStation, station, distance);
처음에 Line을 생성할때는 구간 정보가 아예 없는 상태라 기존 구간이 있는 경우에 사용하는 로직/검증을 똑같이 적용시키는게 불필요하다고 생각해서 따로 빼놓은 부분입니다! 혹시 이런 경우라도 같은 로직을 태우는게 나을까요??

2022-11-17 19:24 UTC, dongha-byun commented on src/main/java/nextstep/subway/ui/LineStationController.java
> +        LineResponse line = lineService.findLine(id);
구간 정보를 추가한 후에 reponse로 해당 노선의 전체 구간(역) 정보를 return 해줄 목적으로 작성했는데, 피드백 주신 내용 보고 다시 생각해보니 성공/실패 여부 응답만 주는게 맞는거 같다고 생각되네요..!

2022-11-17 19:24 UTC, dongha-byun commented on src/test/java/nextstep/subway/line/LineStationAcceptanceTest.java
> +    LineResponse line;
오오 네네 ㅎㅎ 인수 테스트 땐 변수명도 한글명으로 사용해보도록 하겠습니다!

2022-11-17 19:25 UTC, dongha-byun commented on src/main/java/nextstep/subway/domain/LineStations.java
> +    public List<LineStation> getOrderStations(){
넵..! 개선 시도 해보겠습니다 ...!

2022-11-17 19:30 UTC, dongha-byun commented on src/main/java/nextstep/subway/domain/LineStations.java
> +    public void addSection(Station preStation, Station station, Integer distance){
1번과 2번은 더 고민해보도록 하겠습니다! 3번 내용은 LineStation 쪽에 update 하는 부분에 적용시켜놨는데... 이제보니 - 가 없네요...ㅠ 다음 요청때 적용해놓겠습니다...!ㅠㅠ

2022-11-17 19:37 UTC, dongha-byun commented on src/main/java/nextstep/subway/domain/LineStation.java
> +public class LineStation extends BaseEntity {
이 부분에 대해선 사소하지만 한 가지 질문 드리고 싶은 내용이 있습니다!

처음에 Section 이라는 이름으로 작성해놓고 개발을 하다가 여러 번 썼다지웠다를 반복하다보니 저 엔티티는 근본적으로 Line entity 와 Station entity 의 중간 entity 역할이라 독립적인 명칭을 쓰는 것 보다 Line-Station 과 연관된 entity라는걸 명시해주기 위해 이름을 수정했는데, 메서드명 같은 경우에는 "구간을 추가한다" 라는 명확한(?) 의도를 주기 위해 section 이라는 표현을 사용했습니다!

실무에서 다대다 연관관계를 풀어낼 때 저렇게 엔티티로 승격해서 사용하는 케이스가 많을 것 같은데 이 때 엔티티 네이밍은 독립적인 의미를 가져도 되는지, 아니면 다대다 연관관계를 표현하는 결합된 명칭(ex. LineStation)으로 쓰는게 일반적인(?)지 리뷰어님께서 접하시는 환경은 또 어떠신지 궁금합니당 ㅎㅎ ( 제가 실무에서 JPA 를 써본적이 없어서용...ㅠ)

2022-11-18 00:03 UTC, heowc commented on src/main/java/nextstep/subway/domain/LineStation.java
> +public class LineStation extends BaseEntity {
명확한 의도를 주기 위함이 그 엔티티(클래스) 또한 역할에 맞게 네이밍이 되어야 한다고 생각합니다. 
의도가 분명하지 않다면, 오해의 소지도 있고 이를 이해가이 어려워질 수도 있습니다. 
그렇게 되면 행위에 대한 역할이 다른 곳에 위치할 수 도 있구요. 🤔 

어떻게 생각하시나요 ? 🤔

2022-11-18 01:43 UTC, heowc commented on src/main/java/nextstep/subway/domain/Line.java
> +        lineStations.add(preStation, station, distance);
사용하는 사람 입장에서 실수에 여지가 있기도하고,
`null`을 넘기는 것보다 의미상 같은 메소드로 가져가되 안에서 효율적인 처리를 하면 좋을 것 같아요~ 어떻게 생각하시나요 ? 🤔

2022-11-18 01:52 UTC, heowc approved these changes
빠르게 피드백 반영해주신 것 같아서 감사드립니다.

소소한 피드백이 있으나 머지하기엔 충분하여 다음 단계를 진행해주시면 될 것 같습니다 👍 

궁금하신 점이나 의논할 것이 있다면 깃헙 코멘트나 슬랙 DM 으로 연락주세요 🙏

2022-11-18 01:52 UTC, heowc commented on src/test/java/nextstep/subway/line/application/LineServiceTest.java
> +    void saveExceptionBySection(){
예외 테스트 작성 👍

2022-11-18 01:52 UTC, heowc commented on src/test/java/nextstep/subway/line/LineStationAcceptanceTest.java
> +        _2호선 = 지하철_노선_1개_생성("2호선", "bg-color-060", 강남역.getId(), 잠실역.getId(), 20).as(LineResponse.class);
`_` 를 넣으신 이유가 있나요 🤔

2022-11-18 01:52 UTC, heowc commented on src/main/java/nextstep/subway/domain/Sections.java
> +        Section section1 = findFirstSection().orElse(null);
`section1`보다는 `firstSection`은 어떨까요 🤔

2022-11-18 01:52 UTC, heowc commented on src/main/java/nextstep/subway/domain/Sections.java
> +        Map<Station, Section> toMap = getSectionsToMap();
사실 이번미션에서 효율성과는 무관하지만 잘 수정해주신 것 같습니다 👍

2022-11-18 01:53 UTC, merged

2022-11-18 05:46 UTC, dongha-byun commented on src/test/java/nextstep/subway/line/LineStationAcceptanceTest.java
> +        _2호선 = 지하철_노선_1개_생성("2호선", "bg-color-060", 강남역.getId(), 잠실역.getId(), 20).as(LineResponse.class);
단순하게 "2호선"으로 하려니 맨 앞이 숫자라서 변수명으로 사용이 안돼서요...! 좋은 단어가 안떠올라서 간단하게 _ 를 붙였습니다..!

2022-11-18 05:47 UTC, dongha-byun commented on src/main/java/nextstep/subway/domain/Sections.java
> +        Section section1 = findFirstSection().orElse(null);
아... 변수 자동생성 단축키를 쓰다가 그냥 넘어갔네요ㅠㅠ 다음부터 주의하겠습니당

2022-11-18 05:48 UTC, dongha-byun commented on src/main/java/nextstep/subway/domain/Line.java
> +        lineStations.add(preStation, station, distance);
다른 개발자들의 시각을 고려하지 않았던 거 같아요 ㅠㅠ 말씀 주신 피드백 새겨듣고 시간되면 다음 PR때 이부분도 같이 고민 해보겠습니다...!

2022-11-18 05:50 UTC, dongha-byun commented on src/main/java/nextstep/subway/domain/LineStation.java
> +public class LineStation extends BaseEntity {
클래스와 메서드 간의 네이밍도 고려해야겠네요...!  다음 PR 드릴 땐 좀 더 네이밍에 시간을 투자해보겠습니다! 좋은 피드백 감사드립니다!! 👍