[Step4] 구간 제거 기능
next-step/atdd-subway-admin pull request #942
Opened 2022-11-16 14:20 UTC by ychxexn

안녕하세요.

Step4 구간 제거 기능에 대한 코드 리뷰 요청드립니다.

지난 번 PR에서 수정 제안해주신 부분 최대한 반영하려고 노력했습니다 !
하지만 도메인 테스트를 작성하려고 보니 서로 의존성이 강해서 어떻게 시작을 해야할 지 난감하더라고요 🤔
의존성이 강한 부분을 제외하고 짜다보니 생성, 비교 등 비즈니스 로직과는 거리가 먼 부분만 테스트하게 되어서 과감하게 지웠습니다.
이 부분에 대해서 가이드 받을 수 있을까요?

그 외 제안도 언제든지 환영입니다!
태경님 리뷰 덕에 저도 생각해보는 시야가 한층 넓어지는 것 같아서 재밌어요 😋

그럼, 이번 리뷰도 잘 부탁드리겠습니다 🙇🏻‍♀️

2022-11-16 17:28 UTC, ohtaeg requested changes
마지막 미션도 잘 구현 해주셨어요 👍 👍 
마지막인만큼 꼼꼼하게 리뷰를 드렸습니다 😄 
고민해보시면 좋을 포인트들이 존재하여 Request changes 하였습니다!
몇 개의 코멘트를 드렸는데 확인 후 반영하여 재요청 주시면 감사하겠습니다!
마지막까지 화이팅입니다 🔥

2022-11-16 17:28 UTC, ohtaeg commented on src/main/java/nextstep/subway/application/LineService.java
>          Station downStation = stationService.findStationById(sectionRequest.getDownStationId());
saveLine() 메서드와 addSection() 메서드에서 Station 조회를 위해 DB에 2번 접근을 하고 있는데요!
어플리케이션과 다른 곳에 위치한 DB 접근에 대한 IO 비용은 생각보다 크고 네트워크도 고려해야 되다보니
하나의 쿼리로 조회할 수 있도록 최적화해도 좋을 것 같은데 채은님은 어떻게 생각하시는지 궁금하네요 :)

2022-11-16 17:28 UTC, ohtaeg commented on src/main/java/nextstep/subway/application/LineService.java
> +        Station station = stationService.findStationById(stationId);
사소하지만 Station 엔티티의 기본 생성자 접근 제어를 최소화 하도록 해주시면 좋을 것 같아요 :D

2022-11-16 17:28 UTC, ohtaeg commented on src/main/java/nextstep/subway/application/StationService.java
> +                () -> new StationNotFoundException(String.format("존재하지 않는 지하철 역입니다. (id : %s)", id))
친절한 예외 로그 👍

2022-11-16 17:28 UTC, ohtaeg commented on src/main/java/nextstep/subway/domain/Line.java
>  package nextstep.subway.domain;
> 도메인 테스트를 작성하려고 보니 서로 의존성이 강해서 어떻게 시작을 해야할 지 난감하더라고요 🤔
의존성이 강한 부분을 제외하고 짜다보니 
생성, 비교 등 비즈니스 로직과는 거리가 먼 부분만 테스트하게 되어서 과감하게 지웠습니다.
이 부분에 대해서 가이드 받을 수 있을까요?

의존성이 강한 부분이라 하시면 연관 관계를 말씀해주시는 걸까요? 😄 
말씀해주신대로 구현도 구현이지만 현업에서도 다양한 연관관계와 많은 관계로 인해 테스트가 골치 아프죠 😭 💢 
말씀에 공감되어 마음이 찡해지네요 😌 
아쉽게도.. 도메인 없는 테스트는 속이 빈 서비스가 될 확률이 높기에 테스트 작성이 힘드실지라도
생성, 비교 등을 제외한 **상태를 변경하는 메서드는 최대한 검증해주시면 감사하겠습니다 🙏** 
ex) Line - update, deleteLineStation

2022-11-16 17:28 UTC, ohtaeg commented on src/main/java/nextstep/subway/domain/Line.java
Line 엔티티가 distance를 가지고 있지만 활용해주고 있지 않은 것 같아요!
Line 엔티티가 distance를 가지고 있는게 좋을지 고민해보시면 좋을 것 같아요 :)

2022-11-16 17:28 UTC, ohtaeg commented on src/main/java/nextstep/subway/domain/Line.java
이 부분은 같이 고민해보면 좋을 것 같아요 :)
개인적으로 봤을 때 update() 메서드를 사용하려는 다른 개발자가 보게 된다면 
LineUpdateRequest 데이터 중 어떤 값이 사용되는지 알 수 없는 것 같아요..!

파라미터가 큰 덩어리이고 메서드 이름에도 뚜렷한 정보가 없다보니 
직접 함수 내부를 보지 않는 한 어떤 값을 사용하여 업데이트하는지 알 수가 없다고 생각이 되어지는데요!
이부분에 대해서 채은님은 어떻게 생각하시는지 궁금하네요 :)

2022-11-16 17:28 UTC, ohtaeg commented on src/main/java/nextstep/subway/domain/LineStation.java
>          }
구간에 상행역, 하행역은 필수라 optional = false 를 명시적으로 선언해줘도 좋을 것 같아요 :D

2022-11-16 17:28 UTC, ohtaeg commented on src/main/java/nextstep/subway/domain/Line.java
또한 같이 고민해보면 좋을 포인트가 있어서 조심스럽게 코멘트 드려봅니다 ㅎㅎ;

도메인이 DTO를 의존하게 되었는데요!
도메인이 DTO를 의존하는 방향이 좋을지 고민해보시면 좋을 것 같아요 :D

[DTO 사용 범위에 대하여](https://tecoble.techcourse.co.kr/post/2021-04-25-dto-layer-scope/)

2022-11-16 17:28 UTC, ohtaeg commented on src/main/java/nextstep/subway/domain/LineStation.java
> +        return newLineStation.upStation == this.upStation;
👍

2022-11-16 17:28 UTC, ohtaeg commented on src/main/java/nextstep/subway/domain/LineStations.java
> +        if (lineStations.size() == 3) {
갯수로 판단하는 해당 조건이 꼭 필요한 조건인건지 궁금하네요 :) 다른 방향으로의 조건은 고려해볼 수 없을까요?

2022-11-16 17:28 UTC, ohtaeg commented on src/main/java/nextstep/subway/domain/LineStations.java
> +            return;
수정을 위한 리뷰가 아닌 같이 고민해보면 좋을 것 같아 드리는 리뷰입니다 :D
delete() 수행시 validation을 통과하여 삭제할 때 deleteLineStationIfLastLineStation() 메서드에서 삭제를 해주고 있는데요!
내부에서는 하나의 메서드에서 두가지 일을 하고 있는 것 같아요 :)
쿼리와 커맨드 메서드를 분리하면 어떨까요 :) ?

```
if (isFirstLineStation(station, prevLineStation, nextLineStation)) {
    deleteFirstLineStation();
    return;
}
```

2022-11-16 17:28 UTC, ohtaeg commented on src/main/java/nextstep/subway/exception/BadRequestForLineStationException.java
> +@ResponseStatus(HttpStatus.BAD_REQUEST)
ResponseStatus 👍

2022-11-16 17:28 UTC, ohtaeg commented on src/test/java/nextstep/subway/lineStation/LineStationAcceptanceTest.java
>          assertThat(stationNames).containsExactly("강남역", "선릉역", "삼성역");
하나의 테스트 메서드 내에 많은 검증문이 필요하다면 assertAll 활용하는 방향도 고려해보시면 좋을 것 같아요 :)

2022-11-16 17:28 UTC, ohtaeg commented on src/test/java/nextstep/subway/lineStation/LineStationAcceptanceTest.java
> +        Map<String, Object> paramMap = 지하철_구간_추가_파라미터_생성(getId(선릉역), getId(삼성역), 5);
피드백 반영 💯

2022-11-16 17:28 UTC, ohtaeg commented on src/test/java/nextstep/subway/lineStation/LineStationAcceptanceTest.java
>  @DisplayName("지하철 구간 관련 기능")
구간 삭제 인수 테스트를 잘해주셨어요 👍

2022-11-16 17:28 UTC, ohtaeg commented on src/test/java/nextstep/subway/lineStation/LineStationAcceptanceTest.java
>          paramMap.put("distance", 5);
이 부분도 작성해주신 것 처럼 아래와 같이 해볼 수 있지 않을까 합니다 :D
```suggestion
        Map<String, Object> paramMap = 지하철_구간_추가_파라미터_생성(getId(강남역), getId(역삼역), 5);
```

2022-11-16 17:28 UTC, ohtaeg commented on src/test/java/nextstep/subway/lineStation/LineStationAcceptanceTest.java
> +        paramMap.put("distance", 5);
같은 피드백입니다 :)

2022-11-16 17:29 UTC, ohtaeg commented on src/main/java/nextstep/subway/domain/Line.java
>  package nextstep.subway.domain;
**[이번 미션은 인수테스트 주도 개발인데요! 근데 이제 JPA를 곁들인]**
그렇다면 연관 관계를 최소화 해야하는데 양방향이 아닌 단방향으로도 잘 설계해주셨어요 :) 👍 
이 부분에서 개인적인 의견을 공유드려봅니다..! 수정을 위한 리뷰가 아니오니 참고만 해주세요!

개인적으론 꼭 필요한 경우가 아니면 간접 참조를 우선으로 고려합니다 :)
객체간의 관계가 단방향인 경우에는 해당 객체 참조가 반드시 필요한 것인지 고민하시어 
필요가 없다면 끊어주는 걸 추천드립니다.

현재 미션에서는 간접 참조를 고려할 만한 부분이 어디가 있을지 고민해보시면 좋을 것 같아요!
해당 미션에서 간접 참조를 적용하시는 것보다 연관 관계가 더 복잡해지는 남은 미션들에서
한번 적용해보시는 것을 추천드립니다 😄

2022-11-16 17:33 UTC, ohtaeg commented
> 태경님 리뷰 덕에 저도 생각해보는 시야가 한층 넓어지는 것 같아서 재밌어요 😋

저도 채은님 덕분에 재밌게 리뷰하고 있습니다 😊 👍

2022-11-18 05:21 UTC, ychxexn commented on src/main/java/nextstep/subway/application/LineService.java
>          Station downStation = stationService.findStationById(sectionRequest.getDownStationId());
id 파라미터만 다른 동일한 쿼리를 2번 접근하는게 비효율적이긴 하네요 🤔
in 쿼리로 한 번에 가져오도록 변경해보겠습니다!

2022-11-18 05:23 UTC, ychxexn commented on src/main/java/nextstep/subway/application/LineService.java
> +        Station station = stationService.findStationById(stationId);
앗 또 놓친 부분이네요. 😢 알려주셔서 감사합니다!

2022-11-18 05:27 UTC, ychxexn commented on src/main/java/nextstep/subway/domain/Line.java
LineStation으로 distance 계산 로직을 옮겨가면서 생각하지 못한 부분이네요!
제거하도록 하겠습니다 🙂

2022-11-18 05:29 UTC, ychxexn commented on src/main/java/nextstep/subway/domain/LineStation.java
>          }
좋은 생각입니다! 바로 수정하도록 할게요 😆

2022-11-18 05:42 UTC, ychxexn commented on src/main/java/nextstep/subway/domain/LineStation.java
>          }
구간에 상행역이 없는 경우 상행 종점, 하행역이 없는 경우 하행 종점으로 판단하고 있어서 제 로직에서는 제거가 불가하네요 🥺

2022-11-18 05:44 UTC, ychxexn commented on src/main/java/nextstep/subway/domain/LineStations.java
> +        if (lineStations.size() == 3) {
단일 구간인 경우를 판단하는 게 노선에 역이 2개뿐인 경우니까 포함된 역의 갯수로 판단하면 될까요?
갯수로 판단하는 것 말고는 좋은 방법이 떠오르질 않네요 🤔

2022-11-18 05:58 UTC, ychxexn commented on src/main/java/nextstep/subway/domain/LineStations.java
> +            return;
안 그래도 이 부분 짜면서 고민이 많았는데 ... 들켰네요
말씀해주신 부분대로 메소드를 분리하면,
역이 지워지면서 생기는 새로운 구간을 추가해주는 부분이 문제 아닌 문제가 되겠군요!
delete***Station 이라는 이름을 가지고 새 구간을 추가해주는 모양이 되니까요 🥲

if문 바깥으로 공통 처리하도록 빼기에는
조건마다 실행 후 return을 필수적으로 해줘야 하는 구조라서 애매하네요.
이 부분은 어떻게 해결하면 좋을까요?

2022-11-18 06:00 UTC, ychxexn commented on src/test/java/nextstep/subway/lineStation/LineStationAcceptanceTest.java
>          assertThat(stationNames).containsExactly("강남역", "선릉역", "삼성역");
assertAll 활용을 또 깜박했네요 😅

2022-11-18 06:10 UTC, ychxexn commented on src/test/java/nextstep/subway/lineStation/LineStationAcceptanceTest.java
>          paramMap.put("distance", 5);
만들어놓고 써먹지를 않았군요 ㅎㅎ 변경하겠습니다!

2022-11-18 06:14 UTC, ychxexn commented on src/main/java/nextstep/subway/application/LineService.java
>          Station downStation = stationService.findStationById(sectionRequest.getDownStationId());
이 경우에 1개의 역이 없으면 어떻게 검증해야 할까요?
in 조건절로 상행역, 하행역의 아이디를 던졌을 때 순서대로 가져오는게 확실한지도 의문이 듭니다 🤔
리턴되는 목록의 0번이 상행역, 1번이 하행역일거라고 보장받을 수 없는 것 같아요!

2022-11-18 06:18 UTC, ychxexn commented on src/main/java/nextstep/subway/domain/Line.java
>  package nextstep.subway.domain;
도메인 테스트는 해당 도메인에 대해서만 테스트해야 한다고 생각하는데
```
Line-LineUpdateRequest
Line-LineStation
Line-Station
```
Line안에서도 이렇게 다른 객체와 의존성을 맺고 있어서 Line을 테스트 하기 위해서는 다른 객체도 만들어주어야 하는 부분이 애매하다고 느꼈어요!

2022-11-18 06:22 UTC, ychxexn commented on src/main/java/nextstep/subway/domain/Line.java
>  package nextstep.subway.domain;
간접 참조에 대해서 좀 알아봤는데 잘 와닿지 않아서 어렵네요 ...
참고할만한 예시가 있을까요?

2022-11-18 12:11 UTC, ohtaeg commented on src/main/java/nextstep/subway/application/LineService.java
>          Station downStation = stationService.findStationById(sectionRequest.getDownStationId());
음 꼭 순서대로 갖고와야 하는 부분일까요..?
조금 코드가 길어지더라도 상행, 하행 아이디를 가져올 수 있을 것 같아요.
게다가 2개를 가져오지 못한 경우 없는 데이터이므로 예외를 발생해주면 되지 않을까해요 :)

만약 가독성 차원에서 문제라면 저는 가독성보다 비용을 좀 더 중요하게 생각하여 드린 피드백이오니 
채은님이 원하시는대로 해주시면 됩니다 😄

2022-11-18 12:18 UTC, ohtaeg commented on src/main/java/nextstep/subway/domain/Line.java
>  package nextstep.subway.domain;
> Line-LineUpdateRequest

도메인과 DTO를 꼭 의존해야하는지 고민해보시면 좋을 것 같습니다 :)

> Line안에서도 이렇게 다른 객체와 의존성을 맺고 있어서 Line을 테스트 하기 위해서는 다른 객체도 만들어주어야 하는 부분이 애매하다고 느꼈어요!

원래는 도메인 객체를 만들다보면 테스트 코드가 작성되면서 개발이 된다고 생각하였는데요..!
ATDD는 마지막 단계에서 수행하는 테스트를 의미하기도 합니다.
즉, 도메인 객체는 있는데 테스트가 없다는 것은 구현에만 신경썼다는 얘기로 들리네요 😭 
이런 경우 테스트 픽스쳐를 활용해도 좋지 않을까 합니다 😄

2022-11-18 12:23 UTC, ohtaeg commented on src/main/java/nextstep/subway/domain/LineStation.java
>          }
아 그렇군요! 이해했습니다 👍

2022-11-18 13:13 UTC, ohtaeg commented on src/main/java/nextstep/subway/domain/Line.java
>  package nextstep.subway.domain;
> 간접 참조에 대해서 좀 알아봤는데 잘 와닿지 않아서 어렵네요 ...
참고할만한 예시가 있을까요?

위에서 말씀드렸듯이 해당 미션에서는 적용하지 않으셔도 되는 부분인 점 참고 부탁드리며,
간접 참조란 말은 참조 대신 외래키를 그대로 사용하는 부분이기에 단방향 연관관계 인 부분에서 적용해볼 수 있을 것 같아요!
지금 구조라면 Station과 LineStation이 되지 않을까 하네요 😄 

참고할만한 예시라면..이전 JPA 미션에서 질문/답변과 유저간의 관계를 간접참조로 할 수 있을 것 같아요 :)

2022-11-18 13:15 UTC, ohtaeg commented on src/main/java/nextstep/subway/domain/LineStations.java
> +        if (lineStations.size() == 3) {
제가 좀 더 정확히 설명을 못드린 점 죄송합니다 🙇 

갯수로 판단하는 해당 조건이 꼭 필요한 조건 (x)

해당 갯수(3)로 판단하는 해당 조건이 꼭 필요한 조건 (o)

말씀해주신대로 3개일 경우 잘못된 구간인데 만약 4개 이상일 경우는 잘못된 경우가 아니라는 뜻이기에
꼭 3으로 해야하는지 여쭤보는 코멘트였습니다..!
혼돈을 드려서 죄송합니다 🙏

2022-11-18 13:20 UTC, ohtaeg commented on src/main/java/nextstep/subway/domain/LineStations.java
> +            return;
음 이 부분은 위에서 말씀드렸듯이 수정을 위한 리뷰가 아니며 정답이 없는 부분이라
사실 채은님이 편하신 방향이 젤 좋다고 생각하는데요!
한번 고민해보시고 그대도 가셔도 좋고, 바꿔주셔도 좋습니다!! 😄

2022-11-18 13:27 UTC, ohtaeg requested changes
피드백 반영을 잘해주셨어요 👍 
주셨던 질문들에 코멘트를 드렸는데 확인해주시면 감사하겠습니다 :)
주신 질문들이 정답이 있는 부분이 아니라 채은님이 한번 고민해보신 후 원하시는 방향으로 진행해주시면 됩니다! 마지막 PR이 될 것 같네요!! 마지막까지 화이팅입니다 🔥

2022-11-18 13:27 UTC, ohtaeg commented on src/test/java/nextstep/subway/lineStation/LineStationAcceptanceTest.java
> +        assertAll(
assertAll 활용 👍

2022-11-18 13:27 UTC, ohtaeg commented on src/test/java/nextstep/subway/lineStation/LineStationAcceptanceTest.java
> +        Map<String, Object> paramMap = 지하철_구간_추가_파라미터_생성(getId(강남역), getId(역삼역), 5);
피드백 반영 👍

2022-11-18 15:39 UTC, ychxexn commented on src/main/java/nextstep/subway/application/LineService.java
>          Station downStation = stationService.findStationById(sectionRequest.getDownStationId());
아! 어떤 말씀인지 감 잡았습니다 😋
제가 순서대로 가져오는 거에 너무 목매고 있었나봐요 ㅎㅎ

저도 비용 관점에서 생각해본 경험이 많지 않아서 태경님 의견을 좀 더 정확하게 이해하고 싶었어요!
다양하게 시도해보고 싶기도 했고요 💪🏻
도움 많이 됐습니다 감사드려요!

2022-11-20 03:43 UTC, ychxexn commented on src/main/java/nextstep/subway/domain/Line.java
도메인-DTO 의존성과, 어떤 부분이 변경되는지 알 수 없다는 부분 이해했습니다 😢
충분히 코드 수정이 필요한 부분이라고 생각이 되네요!
변경해보겠습니다. 🙂

2022-11-20 03:47 UTC, ychxexn commented on src/main/java/nextstep/subway/domain/LineStations.java
> +        if (lineStations.size() == 3) {
단일 구간인 경우가 LineStations의 size가 3일 경우라서(null-상행종점, 상행종점-하행종점, 하행종점-null) 3으로 조건을 정했어요!
혼돈을 줄 수 있는 부분이라고 생각이 들어서
노선의 역의 갯수로 수정하도록 하겠습니다 🙂

2022-11-20 11:37 UTC, ohtaeg approved these changes
수많은 피드백들을 잘 반영해주셨어요 👍 👍 
끝까지 따라와주셔서 감사드리며, 과정 내내 즐겁게 리뷰하였습니다 😄 
드렸던 피드백들이 조금이나마 채은님께 도움이 되었으면 좋겠네요 :)
이만 merge 하도록 하겠습니다!! 고생 많으셨어요 🙇

2022-11-20 11:37 UTC, ohtaeg commented on src/test/java/nextstep/subway/domain/LineStationTest.java
> +class LineStationTest {
도메인 테스트를 꼼꼼하게 잘 작성해주셨어요 💯

2022-11-20 11:39 UTC, merged