3주차 ATDD Step2 PR 요청드립니다.
next-step/atdd-subway-admin pull request #953
Opened 2022-11-17 18:40 UTC by develo-pyo

안녕하세요. 
3주차 ATDD Step2 PR 요청드립니다.

과정에서 진행하는 모든 과제와 기술들을 거의 처음 접해보는 것들이라 공부를 하면서 과제를 수행하기 버겁네요.. 😷 

jsonPath 관련하여 질문 하나 드리고 싶은데요.
노선 id 기준으로 조회한 API 결과가 null 인 경우엔 body 가 없는데, 이 경우 [Get] /lines/{id} 를 호출하여 body가 비어있는지 어떻게 확인할 수 있는걸까요?..
아래와 같이 body 에서 id 를 가져오면 body가 없기때문에 예외가 발생해서요.. 
```JAVA
RestAssured.given().log().all()
                .when()
                .delete("/lines/{id}", createdLineId)
                .then().log().all()
                .extract().body().jsonPath().getLong("id")
```
방법을 좀 찾아보긴 했지만 잘 모르겠어서 리뷰어님께 여쭈어 봅니다.
(방법을 잘 모르겠어서 목록조회 API 호출 후 반환된 body 의 List 가 비어있는지 확인하는 방향으로 구현했습니다)

행복한 금요일 보내시고, 리뷰 부탁드리겠습니다 😄

2022-11-18 09:41 UTC, joojimin requested changes
안녕하세요~ 정표님!!
미션진행 고생하셨습니다~!
몇가지 확인하고 넘어가면 좋을법만 코멘트 남겼는데요! 확인해보시고 리뷰재요청 부탁드려요~!

추가로 body부분이 비어서 nullPointException이 나는건 지금 작성하신 방법처럼 먼저 status를 검사하고 진행하는 방법으로 하는게 좋을거같아요!!
따로 예외처리하는 방법은 저도 한번 찾아보겠습니다!

2022-11-18 09:41 UTC, joojimin commented on src/main/java/nextstep/subway/application/LineService.java
> +        Line line = lineRepository.findById(id).orElseThrow(() -> new NoSuchElementException(""));
엇 여기 메시지는 일부러 비워두신걸까요~?

2022-11-18 09:41 UTC, joojimin commented on src/main/java/nextstep/subway/domain/Line.java
> +    @ManyToOne(fetch = FetchType.LAZY)
외래키를 명시할 수 있는 `@JoinColumn` 이 생략되었는데요!
생략되도 동작은 똑같으나 명시적으로 조인될 키를 지정해주는게 좋을거같아요~! 어떻게생각하실까요~?

2022-11-18 09:41 UTC, joojimin commented on src/main/java/nextstep/subway/domain/Line.java
> +    public Line(String name, String color, Station upStation, Station downStation, int distance) {
3개이상의 컬럼을 생성자에 두는건 타입이 같을 경우 자칫 위험한 코드가 나올 수 있을 것 같아요!
다른 생성패턴은 어떤게 있을까요~?

2022-11-18 09:41 UTC, joojimin commented on src/main/java/nextstep/subway/ui/GlobalExceptionHandler.java
> +public class GlobalExceptionHandler {
Exception handler 💯

2022-11-18 09:41 UTC, joojimin commented on src/main/java/nextstep/subway/ui/LineController.java
> +    public ResponseEntity updateStation(@PathVariable Long id, @RequestBody LineUpdateRequest lineUpdateRequest) {
```suggestion
    public ResponseEntity<Void> updateStation(@PathVariable Long id, @RequestBody LineUpdateRequest lineUpdateRequest) {
```
제네릭 타입은 형을 명시하는 것이 좋습니다!

2022-11-18 14:36 UTC, develo-pyo commented on src/main/java/nextstep/subway/application/LineService.java
> +        Line line = lineRepository.findById(id).orElseThrow(() -> new NoSuchElementException(""));
앗...아닙니다.. 수정하겠습니다. 감사합니다..

2022-11-18 16:24 UTC, develo-pyo commented on src/main/java/nextstep/subway/ui/LineController.java
> +    public ResponseEntity updateStation(@PathVariable Long id, @RequestBody LineUpdateRequest lineUpdateRequest) {
여지껏 이렇게 살아왔습니다.. 죄송합니다. 감사합니다...!

2022-11-18 17:56 UTC, develo-pyo commented on src/main/java/nextstep/subway/domain/Line.java
> +    public Line(String name, String color, Station upStation, Station downStation, int distance) {
빌더패턴을 사용하여 인자 갯수를 줄일 수 있겠지만 노선의 모든 인스턴스가 null 허용을 하면 안된다고 생각하여, 일부 인스턴스변수를 실수로 set하지 않을 수 있는 빌더패턴은 적합하지 않다고 판단했습니다. 😢 
원시타입을 래핑하면 말씀하신 문제는 해결이 될 것 같아 원시타입을 래핑하는 방향으로 개선하겠습니다!

2022-11-18 18:01 UTC, develo-pyo commented on src/main/java/nextstep/subway/domain/Line.java
> +    @ManyToOne(fetch = FetchType.LAZY)
넵 명시적으로 조인 키 및 fk제약조건 명명하겠습니다!

2022-11-18 18:26 UTC, develo-pyo commented on src/main/java/nextstep/subway/domain/Line.java
> +    public Line(String name, String color, Station upStation, Station downStation, int distance) {
원시타입으로 래핑을 하게되면서 궁금한게 있어 여쭤봅니다!
Response DTO 의 경우 인스턴스변수의 자료형은 원시타입을 사용함이 일반적인지, 래핑된 객체를 사용하는게 일반적인지 여쭤보고 싶습니다. 🙏

2022-11-19 07:10 UTC, joojimin commented on src/main/java/nextstep/subway/domain/Line.java
> +    public Line(String name, String color, Station upStation, Station downStation, int distance) {
`빌더패턴을 사용하여 인자 갯수를 줄일 수 있겠지만 노선의 모든 인스턴스가 null 허용을 하면 안된다고 생각하여, 일부 인스턴스변수를 실수로 set하지 않을 수 있는 빌더패턴은 적합하지 않다고 판단했습니다. 😢
원시타입을 래핑하면 말씀하신 문제는 해결이 될 것 같아 원시타입을 래핑하는 방향으로 개선하겠습니다!`
=> 말씀하신대로 빌더패턴 적용이 힘들면 필요한 속성들을 DTO로 옮기는 것도 좋을 것 같아요!

2022-11-19 07:13 UTC, joojimin commented on src/main/java/nextstep/subway/domain/Line.java
> +    public Line(String name, String color, Station upStation, Station downStation, int distance) {
`원시타입으로 래핑을 하게되면서 궁금한게 있어 여쭤봅니다!
Response DTO 의 경우 인스턴스변수의 자료형은 원시타입을 사용함이 일반적인지, 래핑된 객체를 사용하는게 일반적인지 여쭤보고 싶습니다. 🙏`
=> 엇 저같은경우 Controller에서 내려주는 Response DTO는 원시타입을 사용하고 있습니다! 래핑된 객체를 사용하면 때에 따라 deserialize를 구현해야할 수 도 있어서.. 조금 번거롭더라구요!

2022-11-19 07:14 UTC, joojimin requested changes
안녕하세요~ 정표님!
수정한 커밋이 안올라온거 같아요! 확인한번부탁드려요~!

2022-11-20 02:41 UTC, joojimin approved these changes
안녕하세요~ 정표님!
피드백 반영 고생하셨습니다!!
다음미션도 화이팅입니다!

2022-11-20 02:41 UTC, merged