Step4 지하철 노선에 구간 제거
next-step/atdd-subway-admin pull request #96
Opened 2021-01-06 16:30 UTC by baekss

안녕하세요. 이전 피드백을 반영하여 단계를 진행해 보았습니다.

코드 리뷰 부탁드립니다.
감사합니다.

2021-01-07 07:34 UTC, seok-2-o requested changes
제가 이전 미션에서 발견하지 못한 이슈가 있는것 같아 코멘트로 남겨 놓았습니다.
리펙토링 혹은 답변 남겨주세요

2021-01-07 07:34 UTC, seok-2-o commented on src/main/java/nextstep/subway/line/domain/PositionStatus.java
> +public enum PositionStatus {
해당 상태가 나타내는 의미나 동작을 설명해주실 수 있을까요 ? 🤔

2021-01-07 07:34 UTC, seok-2-o commented on src/main/java/nextstep/subway/line/domain/LineStation.java
> +    }
제가 지난번 과정에서 캐치를 잘못했던것 같은데 현재 LineStation 이 구현하고 있는부분을 설명해주실 수 있나요?

삼성역 ---- 역삼역 ---- 종합운동장역

위와 같이 구현한다면 가운데 `----` 의 정보가 라인스테이션으로 생각한다면 거리가 0인 섹션은 존재할 수 없을 것 같아요.

2021-01-07 07:34 UTC, seok-2-o commented on src/main/java/nextstep/subway/section/domain/Distance.java
>  public class Distance {
역이 추가되거나 빠질때 거리변화가 필요할 것 같은데 해당 로직은 어디서 이뤄지고 있나요?

2021-01-07 10:29 UTC, baekss commented on src/main/java/nextstep/subway/section/domain/Distance.java
>  public class Distance {
각 구간을 나타내는 LineStation 엔티티의 이전역, 다음역, 거리 등의 상태는 각 구간을 연결시키거나 해제시키는 LineStations 도메인 안에서 행해집니다.

2021-01-07 10:36 UTC, baekss commented on src/main/java/nextstep/subway/line/domain/LineStation.java
> +    }
LineStation은 다음과 같이 (---해당역---) 구조를 나타내는 엔티티이며 각각의 독립된 LineStation은 LineStations 도메인을 통해 구간이 연결되거나 해제 됩니다. 이때 LineStations 안에서 각 구간의 포지션 상태를 할당해주며 이를 통해 이전역 다음역 거리 등이 자연스럽게 설정됩니다. 본 어플에서 (----)은 다음역까지의 거리를 나타내는 DistanceForNextStation 입니다.

2021-01-07 11:27 UTC, baekss commented on src/main/java/nextstep/subway/line/domain/PositionStatus.java
> +public enum PositionStatus {
FIRST는 해당 LineStation이 구간안에서 기점역임을 의미합니다.
MIDDLE은 해당 LineStation이 구간에서 사이에 존재하는 역을 의미합니다.
LAST는 해당 LineStation이 구간안에서 종점역임을 의미합니다.

해당 상태는 LineStations 도메인이 나열된 LineStation 엔티티의 입장에 맞게 할당하고 해당 엔티티는 자연스럽게 알맞은 방향성으로 상태변화를 행합니다.

2021-01-08 06:28 UTC, seok-2-o approved these changes
답변 잘 받아보았습니다 :)  

다음미션에서도 동일한 주제로 많은 고민을 할 수 있기에,
이번 미션은 여기서 종료되어도 괜찮을 것 같아요.

좋은 개발자가 되는데 조금이나마 도움이 되기를 바라며,
저와의 미션은 종료되었지만, 궁금한점이나 어려운점 있으면 편하게 연락주세요.

감사합니다.

다음 미션도 화이팅입니다. 🔥

2021-01-08 06:29 UTC, merged