Step3 리뷰 부탁드립니다
next-step/atdd-subway-admin pull request #963
Opened 2022-11-19 05:14 UTC by happy-dev-travel

어렵네용....+_+  보이는건 뭐든 리뷰 부탁드려요!! 감사합니다!!

2022-11-19 13:06 UTC, mskangg requested changes
3단계 미션 잘수행해주셨습니다 !!!! 🚀 👍 
다양한 예시로 인수테스트 작성해주시고 예외 테스트까지 해주신 부분 💯 
그리고 단위테스트 까지 잘해주셨습니다!
몇가지 소소한 피드백 드렸어요~~
확인해 주시고 반영 부탁드립니다 🙏

2022-11-19 13:06 UTC, mskangg commented on src/main/java/nextstep/subway/domain/Section.java
> +    private Long distance;
거리 원시값을 포장하여 불변객체로 만든 후 캡슐화하는게 좋아보입니다 :)

2022-11-19 13:06 UTC, mskangg commented on src/main/java/nextstep/subway/domain/Line.java
> +    }
사용하지 않는 코드는 삭제해주세요 :)

2022-11-19 13:06 UTC, mskangg commented on src/main/java/nextstep/subway/application/SectionService.java
> +    public static final String MESSAGE_CAN_NOT_ADD_SECTION = "구간을 등록하지 못했습니다";
상수메세지는 여기서만 쓰이니 private으로 바꿔주세요 :)

2022-11-19 13:06 UTC, mskangg commented on src/main/java/nextstep/subway/domain/Line.java
> +    private List<Section> sections = new ArrayList<>();
Line과 Section을 양방향으로 만드셨네요!
어떠한 이유로 단방향이 아닌 양방향으로 하셨는지 궁금합니다 🤔

2022-11-19 13:06 UTC, mskangg commented on src/main/java/nextstep/subway/domain/Sections.java
> +    private Line line;
구간들의 컬렉션에 Line을 상태로 갖게 하셨네요.
어떤 이점이 있어 이렇게 구현하셨을까요?

2022-11-19 13:06 UTC, mskangg commented on src/main/java/nextstep/subway/dto/SectionListResponse.java
> +    public boolean hasSection(Long sectionId) {
어디서 사용하고 있는 메서드인가요??

2022-11-19 13:06 UTC, mskangg commented on src/main/java/nextstep/subway/dto/StationResponse.java
> +    public boolean hasId(Long stationId) {
이 부분도 어디서 사용되는부분 인가요?

2022-11-19 13:06 UTC, mskangg commented on src/test/java/nextstep/subway/domain/SectionsTest.java
> +    @DisplayName("상행역에서 시작하고, 거리가 100이내이면 구간이 추가되고, 2개의 구간을 갖게 됨")
단위테스트 💯

2022-11-19 16:14 UTC, happy-dev-travel reviewed
질문해 주신 부분에 설명을 하다보니 문제점이 발견되어서 리팩토링에 반영하였습니다
Sections 클래스가 굳이 Line밖에 나와 있을 이유가 없더라고요
Distance는 Embedded로 반영해 보았는데.. 맞는 방법인가요? Entity에는 Long으로 반영할까 했지만
Entity 레벨에서도 도메인 관련된 표현이 더 드러나면 좋겠단 생각이 들었습니다.
한편으론 Distance에 Column 어노테이션도 있어서.. 서비스 레이어에서 자유롭게 쓰기엔 뭔가 부담스러울 것 같다는 우려도 드네요.. 의견 부탁드립니다

2022-11-19 16:14 UTC, happy-dev-travel commented on src/main/java/nextstep/subway/domain/Line.java
> +    private List<Section> sections = new ArrayList<>();
이 부분은 저의 사고의 편의를 위해서 그랬습니다. 구간들을 노선이 관리하는 하위 개념으로 생각해서, 구간 관련 조작을 할 때 노선에 대해서 추가/삭제를 편하게 하기 위해 양방향으로 설정을 했습니다

2022-11-19 16:14 UTC, happy-dev-travel commented on src/main/java/nextstep/subway/dto/StationResponse.java
> +    public boolean hasId(Long stationId) {
삭제했습니다ㅠㅠ

2022-11-19 16:14 UTC, happy-dev-travel commented on src/main/java/nextstep/subway/dto/SectionListResponse.java
> +    public boolean hasSection(Long sectionId) {
삭제했습니다ㅠㅠ

2022-11-19 16:15 UTC, happy-dev-travel commented on src/main/java/nextstep/subway/domain/Sections.java
> +    private Line line;
이점이라고 생각했던 부분이 있었는데.. 개발하던 중에 사라졌네요ㅎㅎ 리팩토링을 많이 했습니다 :)

2022-11-19 16:16 UTC, happy-dev-travel commented on src/main/java/nextstep/subway/domain/Section.java
> +    private Long distance;
반영하였습니다~ 👍 👍

2022-11-20 16:22 UTC, mskangg approved these changes
> 한편으론 Distance에 Column 어노테이션도 있어서.. 서비스 레이어에서 자유롭게 쓰기엔 뭔가 부담스러울 것 같다는 우려도 드네요.. 의견 부탁드립니다

서비스레이어에서 쓰기에 부담스럽다는 말씀이 어떤부분일까요??
제가 이해한대로 설명을 드리겠습니다~! 🙏

불변객체를 만듦으로 인해 오히려 `자유롭게 쓴다` 를 더 마음놓고 사용할 수 있지 않을까요?
일반적인 원시값이라면 해당 값이 변할 수 있고 변함으로 인해 항상 validation을 해야하는 수고로움이 발생하기도 합니다.
반면에, 불변객체로 이뤄진다면 어느 레이어에 가던 validation을 신경쓰지 않아도 되니 더 자유롭게 사용할 수 있지 않을까? 생각해요~

피드백 반영하시느라 고생하셨습니다~! 🙇‍♂️
그럼 마지막 단계 진행해주세요!
화이팅!! 🔥

2022-11-20 16:22 UTC, merged