Step4 구간삭제기능 PR요청드립니다.
next-step/atdd-subway-admin pull request #964
Opened 2022-11-19 06:38 UTC by chunhodong

2022-11-20 08:05 UTC, chae-yh requested changes
동기님 안녕하세요. 벌써 마지막 step 이네요...! 이것저것 다양한 방법을 시도해주셔서 저도 많이 배우고 있습니다 ㅎㅎ
마지막 step 코드도 전체적으로 잘 작성이 된 것 같아요 👍 다만 조금씩 고민해주시면 좋을 것 같은 포인트가 있어 코멘트 드리니 확인 부탁드립니다.

감사합니다 : )

2022-11-20 08:05 UTC, chae-yh commented on src/main/java/nextstep/subway/application/LineService.java
> +    public void deleteSection(Long lineId,Long stationId) {
신규로 기능이 추가되는데, 기능 작성 목록을 작성해도 좋을 것 같습니다...!

2022-11-20 08:05 UTC, chae-yh commented on src/main/java/nextstep/subway/application/LineService.java
> +        Station station = stationRepository.findById(stationId)
이것도 이미 존재하는 메서드를 쓸 수 있을 것 같습니다..!

2022-11-20 08:05 UTC, chae-yh commented on src/main/java/nextstep/subway/application/LineService.java
> +        Line line = lineRepository.findById(lineId)
이 부분도 반복적으로 나오는데 메서드 추출해보면 어떨까요...?

2022-11-20 08:05 UTC, chae-yh commented on src/main/java/nextstep/subway/domain/Line.java
> +    public void deleteSection(Line line, Station deleteStation) {
이미 Line에서 삭제를 해주고 있는데, 또 Line을 매개변수로 받아야 할까요...?

2022-11-20 08:05 UTC, chae-yh commented on src/main/java/nextstep/subway/domain/Line.java
> +        if (Objects.isNull(color) || color.isEmpty()) {
피드백 반영 👍

2022-11-20 08:05 UTC, chae-yh commented on src/main/java/nextstep/subway/domain/Sections.java
> +    private void validateMultiSection(List<Section> findSections) {
오.. 이런 방어 코딩 좋네요 👍 숫자는 상수 추출해도 좋을 것 같아요..!

2022-11-20 08:05 UTC, chae-yh commented on src/main/java/nextstep/subway/domain/Sections.java
> +    private void validateEmptySection(List<Section> sections) {
이 부분도 validateSections에 넣을 수 있지 않을까요...?

2022-11-20 08:05 UTC, chae-yh commented on src/main/java/nextstep/subway/domain/Sections.java
> +        if (isSingleSection(findSections)) {
이 경우는 삭제하려는 Station이 상행 종점 혹은 하행 종점일 경우 일 것 같아요..! method extract해서 해당 내용을 표현해줄 수 있지 않을까요...?

2022-11-20 08:05 UTC, chae-yh commented on src/main/java/nextstep/subway/domain/Sections.java
> +        if (isSingleSection(sections) && isSingleSection(findSections)) {
이 부분은 의견 여쭤보고 싶습니다..! sections의 길이가 1이면 무조건 삭제할 수 없는 경우 아닐까요...?

2022-11-20 08:05 UTC, chae-yh commented on src/main/java/nextstep/subway/domain/Sections.java
> +        return findSections.size() == 1;
여기도 상수를 추출해줄 수 있을 것 같아요..!

2022-11-20 08:05 UTC, chae-yh commented on src/main/java/nextstep/subway/ui/LineController.java
> +    @ExceptionHandler({DataIntegrityViolationException.class, LineException.class, SectionsException.class})
중요한 부분은 아니지만, 이렇게 Exception을 모아서 처리하려면, @RestControllerAdvice을 이용해서 클래스로 분리해줄 수도 있을 것 같아요..!

2022-11-20 08:05 UTC, chae-yh commented on src/test/java/nextstep/subway/acceptance/section/SectionAcceptanceCommon.java
> +                .when().delete("/lines/{id}/sections?stationId={stationId}",lineId,stationId)
stationId의 경우에는 .queryParam 메서드를 쓸 수도 있을 것 같아요..!

2022-11-20 08:05 UTC, chae-yh commented on src/test/java/nextstep/subway/acceptance/section/SectionAcceptanceTest.java
> +        assertThat(response.statusCode()).isEqualTo(HttpStatus.OK.value());
단지 OK 확인을 받는 것으로 끝내기보다는, 실제로 역의 리스트를 체크해보면 어떨까요..?

2022-11-20 08:05 UTC, chae-yh commented on src/test/java/nextstep/subway/acceptance/section/SectionAcceptanceTest.java
> +    void removeSectionWithNoneExistsStation() {
현재도 정확히 같은 형태는 아닙니다만, 인수테스트 작성 시 given -> when -> then -> given -> when -> then 이 반복되며 테스트를 해야할 수 있습니다. 이 때는 [다이나믹 테스트](https://tecoble.techcourse.co.kr/post/2020-07-31-dynamic-test/)를 써볼 수 있을 것 같아요..!
참고차 전달 드립니다 : )

2022-11-20 08:05 UTC, chae-yh commented on src/test/java/nextstep/subway/domain/line/LineTest.java
> +    class DescribeDeleteSection {
단위테스트 👍

2022-11-20 11:28 UTC, chunhodong commented on src/main/java/nextstep/subway/domain/Sections.java
> +        if (isSingleSection(sections) && isSingleSection(findSections)) {
맞습니다 착각했네요 감사합니다!! :)

2022-11-21 10:49 UTC, chae-yh approved these changes
동기님 안녕하세요. 피드백 잘 반영해주셨습니다 👍 소소하게 코멘트 드린 부분이 있는데, 중요한 부분은 아니라 참고만 부탁드립니다...!

그리고 이렇게 제 리뷰는 마지막인 것 같습니다. 학습에 대한 열정이 높으시고, 새로운 것에도 관심이 많으셔서 저도 리뷰 드리면서 많이 배울 수 있었기에, 감사드립니다 ㅎㅎ 나름대로는 열심히 리뷰 드린다고 드렸는데, 도움이 되었을지 모르겠네요.
남은 미션에서도 지금처럼 열정과 호기심을 가지고, 저보다 훌륭하신 리뷰어님들께 많이 배워가시길 바랍니다.

그 동안 고생많으셨습니다. 감사합니다 : )

2022-11-21 10:49 UTC, chae-yh commented on src/main/java/nextstep/subway/domain/Sections.java
> +    private boolean removeEdgeSection(List<Section> findSections){
이 메서드는 두가지 역할이 혼재되어 있는 것 같아요(종점인지 판단 / 종점일 경우 삭제)
각각 분리해줄 수도 있을 것 같습니다...!

2022-11-21 10:49 UTC, merged