3단계 - 구간 추가 기능
next-step/atdd-subway-admin pull request #966
Opened 2022-11-19 09:11 UTC by baeksoo

2022-11-20 08:22 UTC, chae-yh requested changes
규범님 안녕하세요. 세번째 step 코드도 전체적으로 잘 작성해주셨습니다 👍 다만 조금더 고민해주시면 좋을만한 내용이 있어 코멘트 드리니 확인 부탁드립니다.

감사합니다 : )

2022-11-20 08:22 UTC, chae-yh commented on README-Requires.md
> +# Step3 기능 요구사항
기능 요구 사항 작성 👍

2022-11-20 08:22 UTC, chae-yh commented on src/main/java/nextstep/subway/domain/Distance.java
> +public class Distance {
오.. Distance VO를 따로 분리해주셨군요 👍

2022-11-20 08:22 UTC, chae-yh commented on src/main/java/nextstep/subway/domain/Distance.java
> +    protected Distance() {
```suggestion
    protected Distance() {}
```
이 부분은 [컨벤션](https://naver.github.io/hackday-conventions-java/#permit-concise-empty-block)에 따르면 이렇게 써도 될 것 같아요...!

2022-11-20 08:22 UTC, chae-yh commented on src/main/java/nextstep/subway/domain/Distance.java
> +    public Distance(Long distance) {
distance에 대한 validation이 추가될 수도 있을 것 같아요..! (음수일 수 없다 등...)

2022-11-20 08:22 UTC, chae-yh commented on src/main/java/nextstep/subway/domain/Distance.java
> +    public void sub(Distance distance) {
distance를 빼주는 메서드를 만들어주신 것 같아요 👍 
다만 sub같은 축약어보다는 의미를 명화하게 전체로 작성해보면 어떨까요..? (substract 등...)

2022-11-20 08:22 UTC, chae-yh commented on src/main/java/nextstep/subway/domain/Section.java
> +public class Section {
Section과 Sections는 복잡한 로직이 들어간 도메인입니다. 단위테스트를 작성해보면 어떨까요...?

2022-11-20 08:22 UTC, chae-yh commented on src/main/java/nextstep/subway/domain/Sections.java
> +public class Sections {
1급 컬렉션 👍

2022-11-20 08:22 UTC, chae-yh commented on src/main/java/nextstep/subway/domain/Sections.java
> +        if (sections.isEmpty()) {
이 부분은 결국 아무동작도 아닌데, 코드를 작성해줄 필요가 있을까요...?

2022-11-20 08:22 UTC, chae-yh commented on src/main/java/nextstep/subway/domain/Sections.java
> +                    .filter(it -> it.getUpStation() == pre.getDownStation())
it / pre 와 같은 축약어보다는 의미를 명확하게 알려줄 수 있는 변수명 작성을 해도 좋을 것 같습니다..!

2022-11-20 08:22 UTC, chae-yh commented on src/main/java/nextstep/subway/domain/Section.java
> +    public void rebase(Section section) {
이 방법도 재밌군요 ㅎㅎ 👍

2022-11-20 08:22 UTC, chae-yh commented on src/main/java/nextstep/subway/domain/Sections.java
> +                .filter(it -> it.getUpStation() == station)
이 부분은 equals를 써주어야 하지 않을까요...?

2022-11-20 08:22 UTC, chae-yh commented on src/main/java/nextstep/subway/domain/Sections.java
> +        Set<Station> result = new LinkedHashSet<>();
순서를 위해서 사용해주신 것 같군요 👍 혹시 단순 ArrayList를 쓸 수 도 있지 않을까요..?

2022-11-20 08:22 UTC, chae-yh commented on src/main/java/nextstep/subway/domain/Sections.java
> +        return new ArrayList<>(result);
방어적 복사를 해주려고 하신 것 같군요 👍

2022-11-20 08:22 UTC, chae-yh commented on src/main/java/nextstep/subway/ui/LineController.java
> +        if (request.getUpStationId() == null) {
```suggestion
        if (Objects.isNull(request.getUpStationId())) {
```
도 좋을 것 같습니다..!

2022-11-20 08:22 UTC, chae-yh commented on src/main/java/nextstep/subway/ui/LineController.java
> +    private void validateSectionRequest(SectionRequest request) {
request의 값 validation인데 SectionRequest에서 해줄 수도 있지 않을까요...?
혹은 `@NotNull 과 같은 BeanValidation을 사용해도 좋을 것 같습니다..!

2022-11-20 08:22 UTC, chae-yh commented on src/test/java/nextstep/subway/line/LineSectionAcceptanceTest.java
> +        // 지하철_노선_구간_등록_요청
메서드 명에서 이미 충분히 잘 설명해주고 있어서, 이런 주석은 없어도 되지 않을까요...?

2022-11-20 08:22 UTC, chae-yh commented on src/test/java/nextstep/subway/line/LineSectionAcceptanceTest.java
> +public class LineSectionAcceptanceTest extends AcceptanceTest {
오.. 인수테스트 정말 꼼꼼하게 잘 작성해주셨습니다 👍

2022-11-20 08:22 UTC, chae-yh commented on src/main/java/nextstep/subway/domain/Line.java
>      private Station lastUpStation;
종점의 경우 역을 순서대로 추출하기 위해 필요한 것 같습니다. 로직을 통해서도 추출해줄 수 있는데, 컬럼으로 가지고 있어야 할까요...?

2022-11-20 08:22 UTC, chae-yh commented on src/main/java/nextstep/subway/domain/Sections.java
> +    @OneToMany(mappedBy = "line", cascade = CascadeType.ALL)
적절한 연관관계와 영속성 전파도 좋네요 👍 영속성 지연도 주면 어떨까요..?

2022-11-20 13:22 UTC, baeksoo commented on src/main/java/nextstep/subway/domain/Sections.java
> +        Set<Station> result = new LinkedHashSet<>();
result.addAll(pre.getStations());
을 통해서 중복을 제거하고 있습니다.
ArrayList를 사용하게 되면, UpStation만 저장하다가, 마지막 구간에서 DownStation을 같이 저장하면 되는데..
Set을 쓰면 신경쓸 필요 없이 그냥 넣기만 하면 되므로 위와 같이 작성되었습니다.

2022-11-20 13:22 UTC, baeksoo commented on src/main/java/nextstep/subway/ui/LineController.java
> +        if (request.getUpStationId() == null) {
좋습니다.

2022-11-20 13:49 UTC, baeksoo commented on src/main/java/nextstep/subway/domain/Sections.java
> +        if (sections.isEmpty()) {
노선 생성하면서 구간을 생성할 때에 한하여 validate 를 하지 않기 위한 라인입니다.

2022-11-20 13:49 UTC, baeksoo commented on src/main/java/nextstep/subway/domain/Sections.java
> +                    .filter(it -> it.getUpStation() == pre.getDownStation())
좋습니다.

2022-11-20 13:49 UTC, baeksoo commented on src/main/java/nextstep/subway/domain/Sections.java
> +                .filter(it -> it.getUpStation() == station)
좋습니다

2022-11-20 13:51 UTC, baeksoo commented on src/main/java/nextstep/subway/domain/Distance.java
> +    protected Distance() {
오 감사합니다.

2022-11-20 14:04 UTC, baeksoo commented on src/main/java/nextstep/subway/domain/Distance.java
> +    public void sub(Distance distance) {
좋습니다!

2022-11-20 14:04 UTC, baeksoo commented on src/main/java/nextstep/subway/domain/Distance.java
> +    public Distance(Long distance) {
반영하겠습니다

2022-11-20 14:52 UTC, baeksoo commented on src/main/java/nextstep/subway/ui/LineController.java
> +    private void validateSectionRequest(SectionRequest request) {
NotNull은 validation 의존성을 추가해야되니, SectionRequest에서 하는식으로 변경하도록 할게요~

2022-11-20 14:52 UTC, baeksoo commented on src/test/java/nextstep/subway/line/LineSectionAcceptanceTest.java
> +        // 지하철_노선_구간_등록_요청
주석 삭제 해야겠네요

2022-11-20 14:53 UTC, baeksoo commented on src/main/java/nextstep/subway/domain/Line.java
>      private Station lastUpStation;
컬럼을 하나 더 추가해서, 추가 로직을 없앨 것인지,
추가 로직을 더 추가해서 컬럼을 없앨것인지에 대한 고민이 좀 있었습니다.
로직 추가하는 방식으로 다시 푸시 하겠습니다

2022-11-20 14:56 UTC, baeksoo commented on src/main/java/nextstep/subway/domain/Sections.java
> +    @OneToMany(mappedBy = "line", cascade = CascadeType.ALL)
OneToMany default 타입이 Lazy라 별도로 주진 않았는데 명시적으로 표현할게요.

2022-11-21 11:50 UTC, chae-yh approved these changes
규범님 안녕하세요. 피드백 잘 반영해주셨습니다 💯 소소하게 코멘트 드린부분이 있긴한데, 다음 step 진행 시에 참고만 부탁드립니다 ㅎㅎ

이제 마지막 step만 남았네요. 파이팅 입니다 : )

2022-11-21 11:50 UTC, chae-yh commented on src/main/java/nextstep/subway/domain/Distance.java
> +        if (distance <= 0) {
0은 상수로 추출해도 좋을 것 같아요...!

2022-11-21 11:50 UTC, chae-yh commented on src/main/java/nextstep/subway/domain/Distance.java
> +        this.distance -= distance.distance;
이 부분은 제가 바로 전 리뷰에서 놓친 부분입니다만...ㅎ.ㅎ;;; VO는 [보통 불변객체로 만들어줍니다](https://tecoble.techcourse.co.kr/post/2020-06-11-value-object/).
그래서 이 부분도 이렇게 변경해줄 수 있을 것 같아요...!
```suggestion
        return Distance.from(this.distance - distance.distance)
```

2022-11-21 11:50 UTC, chae-yh commented on src/test/java/nextstep/subway/domain/SectionTest.java
> +class SectionTest {
도메인에 대한 단위 테스트 👍

2022-11-21 11:50 UTC, chae-yh commented on src/main/java/nextstep/subway/domain/Sections.java
> +        if (sections.isEmpty()) {
그러면, 해당 validation 체크 전에, sections가 비어있다면 바로 section을 add 하는 방법도 있을 것 같습니다...!

2022-11-21 11:50 UTC, chae-yh commented on src/main/java/nextstep/subway/domain/Sections.java
> +                .filter(station -> section.getStations().contains(station))
[디미터 법칙 위반](https://tecoble.techcourse.co.kr/post/2020-06-02-law-of-demeter/)으로 보이네요..!
section에 station이 있는지 물어볼 수 있지 않을까요...?

2022-11-21 11:50 UTC, merged