Step4 - 구간 제거 기능 PR 요청드립니다
next-step/atdd-subway-admin pull request #968
Opened 2022-11-19 12:18 UTC by paki1019

Step4 - 구간 제거 기능 PR 요청드립니다!

과제를 진행하면서 몇가지 궁금한 사항 및 이슈가 확인되어 아래에 같이 정리하였습니다. 이에 대한 의견 부탁드립니다..!

1. entity를 response로 변환하는 로직에서 getter 메서드들을 사용하게 되는데요, 객체지향 생활 체조의 규칙에 따라서 이 경우에도 getter를 지양해야할까요..? response 객체 생성을 도메인 객체에서 한다면 가능은 할것 같지만, 의존성의 방향이 적절할지가 의문입니다.(Response의 변경에 domain이 영향)
2. Entity 객체의 equals를 오버라이딩함에 따라 Id이외의 값은 equals로 비교가 불가능합니다. 이에 따라 테스트 코드에서 객체의 상태값 변경을 getter로 확인하게 되는데요, 이 경우에도 getter 대신의 대안이 있을까요?
3. Entity 객체와 Entity 객체가 상속된 Hibernate Proxy 객체간의 equals 비교시 제대로 동등성 비교가 안되는 이슈가 있었습니다. 트러블 슈팅을 해보니 Hibernate Proxy 객체의 경우는 getter 메서드로 호출을 해야 Lazy Fetch가 이뤄져 제대로 된 비교가 가능한 이슈가 있었습니다. 따라서 equals의 부분을 아래와 같이 유지하게 되었는데요.. 이부분에도 혹시 다른 방안이 있을까요..?
    ```
    Objects.equals(getId(), section.getId());
    ```

2022-11-20 05:33 UTC, wooobo requested changes
4단계도 잘 진행해주셨네요!

꼼꼼한 테스트 작성이 인상적이네요 :+1: 

질문주신에 대한 답변과 코멘트 남겨드렸는데 
확인 후 재요청 부탁드려요~ :pray:

2022-11-20 05:33 UTC, wooobo commented on README.md
>    - [X] 상행역과 하행역이 이미 노선에 모두 등록되있는 경우 추가 불가
> entity를 response로 변환하는 로직에서 getter 메서드들을 사용하게 되는데요, 객체지향 생활 체조의 규칙에 따라서 이 경우에도 getter를 지양해야할까요..? response 객체 생성을 도메인 객체에서 한다면 가능은 할것 같지만, 의존성의 방향이 적절할지가 의문입니다.(Response의 변경에 domain이 영향)

A. 맞아요. `entity`를 `ui`레이어에서 사용하게 될때 `getter`를 사용해야 될 부분이 있습니다.
그러한 문제를 나누기 위해서 `Layer`를 좀 더 구조화 해야하는 부분이 필요한것 같아요.
[주문 프로젝트](https://github.com/gregshiny/example-order) 예전에 학습에 참고 했던 프로젝트인데요.
해당 프로젝트는 [mapstruct](https://mapstruct.org/) 라이브러리를 통한 구조화가 인상깊었어요. `layer`별로 추상화하고 중간 단계에 `mapper`를 사용함으로써 의존성을 덜려고 했다는 생각을 했습니다.
많은 방법이 있겠지만, 답변이 도움이 되었으면 좋겠습니다!




> Entity 객체의 equals를 오버라이딩함에 따라 Id이외의 값은 equals로 비교가 불가능합니다. 이에 따라 테스트 코드에서 객체의 상태값 변경을 getter로 확인하게 되는데요, 이 경우에도 getter 대신의 대안이 있을까요?

A. 위 질문에서 `객체지향 생활 체조의 규칙` 에 대해서 이야기 하셨는데요!
그렇다면, 제 생각에는 `getter`,`setter` 개념을 좀 더 생각해볼것 같아요.
- `getter` 무엇을 왜 가져와야하는가? 
말씀하신대로라면 값을 비교해야하는 부분입니다. 왜 가져와서 비교를 해야할까요?
`객체지향`으로 생각한다면 묻지말고 시켜야하지 않을까요? [Tell, don't ask 원칙(TDA 원칙)](https://effectiveprogramming.tistory.com/entry/Tell-dont-ask)

```
Price price = new Price(1000);

검증(price.getValue(), 1000);
```
위의 검증이 필요할까요? 다르게 생각해보면 어떨까요? 객체에게 시킨다는 관점으로요.

```
Price 천원 = new Price(1000);

assertTrue(천원.isSamePrice(1000));
```

가져온다는건(`getter`) 가져와서 추가적인 행동을 바깥에서 한다는것이라 생각해본다면 객체를 능동적으로 사용하는것이 아닌 수동적으로 사용하고 있다 생각이 듭니다.
객체를 능동적으로 고려해본다면 `지시`를 내리게 됩니다. `isSamePrice` 비교하도록 시켰던것 처럼요.
**_데이터 보다는 객체에게 보낼 메시지를 생각해보면 좋을것같아요_**

`setter` 또한 비슷한 관점으로 생각해보시면 좋을것 같아요 :thinking: 

> Entity 객체와 Entity 객체가 상속된 Hibernate Proxy 객체간의 equals 비교시 제대로 동등성 비교가 안되는 이슈가 있었습니다. 트러블 슈팅을 해보니 Hibernate Proxy 객체의 경우는 getter 메서드로 호출을 해야 Lazy Fetch가 이뤄져 제대로 된 비교가 가능한 이슈가 있었습니다. 따라서 equals의 부분을 아래와 같이 유지하게 되었는데요.. 이부분에도 혹시 다른 방안이 있을까요..?
Objects.equals(getId(), section.getId());

A.  [JPA Entity의 equals와 hashCode](https://velog.io/@park2348190/JPA-Entity%EC%9D%98-equals%EC%99%80-hashCode)
해당 블로그 내용이 도움이 되지않을까 싶습니다!

2022-11-20 05:33 UTC, wooobo commented on src/main/java/nextstep/subway/domain/Distance.java
> +        return new Distance(this.distance + distance.distance);
불변객체 좋은것 생각이네요!

2022-11-20 05:33 UTC, wooobo commented on src/test/java/nextstep/subway/section/RemoveSectionAcceptanceTest.java
> +        assertThat(response.statusCode()).isEqualTo(HttpStatus.BAD_REQUEST.value());
실패에 대한 테스트도 꼼꼼하게 잘 작성해주셨네요 :+1:

2022-11-20 05:33 UTC, wooobo commented on src/main/java/nextstep/subway/domain/Sections.java
> +        Optional<Section> removedUpSection = removeUpSection(station);
[Optional 제대로 활용하기](https://www.latera.kr/blog/2019-07-02-effective-optional/)
참고해보시면 좋을것 같아요~

2022-11-21 13:11 UTC, paki1019 commented on README.md
>    - [X] 상행역과 하행역이 이미 노선에 모두 등록되있는 경우 추가 불가
메시지로 값 비교를 요청하는 방법도 있었군요, 이부분은 생각을 못했었던것 같습니다ㅎ

JPA equals는 제공해주신 블로그 내용을 확인해보고, 인터넷에서 다른 글도 확인해보았는데요.. 아쉽지만 equals에서 getId()를 사용하는게 최선인듯 합니다.. Lazy Loading 되고있는 프록시 객체를 fetch 하기 위해서는 get으로 시작하는 메서드를 사용해야만 하는것 같습니다.

2022-11-21 13:30 UTC, paki1019 commented on src/main/java/nextstep/subway/domain/Sections.java
> +        Optional<Section> removedUpSection = removeUpSection(station);
공유해주신 내용 잘 보았습니다! Optional은 반환값으로 사용해야한다는 것이 핵심이었던것 같습니다. Optional을 분기문으로 사용하는 대신, null로 치환해서 처리하는 로직으로 수정하였습니다..!

2022-11-22 01:09 UTC, wooobo approved these changes
안녕하세요 진호님 4단계 까지 진행하느라 수고 많으셨습니다~
 테스트 꼼꼼하게 잘 진행해주시면 부분이 인상적이었습니다 👍 

이만 `merge` 진행하겠습니다.

남은 미션도 화이팅입니다~ 😄

2022-11-22 01:09 UTC, wooobo commented on src/test/java/nextstep/subway/section/RemoveSectionAcceptanceTest.java
> +    private Integer WANGSIPLI_ID;
`인수테스트 주도개발` 미션에 맞게 꼼꼼하게 잘 작성해주셨네요 👍

2022-11-22 01:09 UTC, merged