[yeojiin(임정연)] - 4단계 구간 제거 기능
next-step/atdd-subway-admin pull request #980
Opened 2022-11-21 07:35 UTC by yeojiin

안녕하세요 민수님~ 
JPA 양방향 매핑이 익숙하지 않아서 이번 미션을 진행하면서 애를 먹었네요.😂
delete를 sections에서 뿐 아니라 Line에서도 해주지 않으면 지웠던 구간 정보가 제대로 반영되지 않아 해결하는데 어려웠던 거 같아요!
그리고 stream을 좀 더 능숙히 사용해 코드를 깔끔히 정리하고 싶은데 
if와 return으로 처리하는 상황에 스스로 좀 아쉬움이 크게 느껴지네요.🥲

지하철 노선도 미션이 여지껏 진행했던 미션 중 가장 시간도 많이 걸리고, 
뒤엎기도 여러번 뒤엎었던 미션같아요.
그만큼 많이 배웠지만 멘탈 관리하기 쉽지 않았던 거 같네요.
그때마다 꼼꼼하게 리뷰해주신 덕분에 제가 어느 부분을 놓치고 있는지 찾알 수 있어서 정말 감사합니다!🙏
리뷰 받고 생각이 리프레쉬 돼서 여러번 코드를 뒤엎었던 거 같아요! 
답답하게 느껴지셨을 수도 있는데 꼼꼼히 체크해주셔서 정말 감사했습니다.🙇‍♀️
벌써 마지막 미션인데 이번 미션도 잘 부탁드립니다~
날이 쌀쌀해진다고 하니 건강 조심하세요!😀

2022-11-22 08:47 UTC, mskangg requested changes
> 지하철 노선도 미션이 여지껏 진행했던 미션 중 가장 시간도 많이 걸리고,
뒤엎기도 여러번 뒤엎었던 미션같아요.

ATDD 지하철 노선 구간 미션이 요구사항도 복잡하고 바꿀게 많고 그런 미션입니다!!
자신감 잃지 않으셔도 되는게 모든 사람들이 어려워하는 미션이에요 😁

걱정하신부분과 달리 미션 요구사항 잘 구현하셨습니다!
다만, 이전 피드백 드린 부분 중 누락된 커밋이 있어보여요~
확인 부탁드립니다.

그리고 도메인의 책임(기능)이 추가되었는데, 테스트코드가 없어 리뷰하기가 조금(?) 힘들었습니다.
나름 복잡한 요구사항이니 유닛테스트코드 추가해주시면 훨씬 좋은 코드가 될 것 같아요!!
그럼 피드백 반영 기다리곘습니다 🔥

2022-11-22 08:47 UTC, mskangg commented on README.md
> +  * 제거할 수 없음
요구사항 정의 👍

2022-11-22 08:47 UTC, mskangg commented on src/test/java/nextstep/subway/section/LineSectionStep.java
> +        assertThat(response.statusCode()).isEqualTo(HttpStatus.INTERNAL_SERVER_ERROR.value());
상태코드를 500으로 두셨는데, 어떤 이유로 두셨을까요?? 🤔
IllegalException으로 예외를 지정해주셨다면, 알수없는 에러코드는 아닐 것 같습니다!

그리고 구간 삭제시 예외로 설정하신 메세지를 확인하고 있지 않네요!
NOT_VALID_REMOVE_ONLY_ONE_SECTION <- 이부분 검증추가해주시면 될것 같습니다 :)

2022-11-22 08:47 UTC, mskangg commented on src/main/java/nextstep/subway/application/LineService.java
> +        Station downStation = findStationById(Long.valueOf(lineRequest.getDownLastStationId()));
음.. 아직 박싱하는 부분 바뀌지 않았네요 😭

2022-11-22 08:47 UTC, mskangg commented on src/main/java/nextstep/subway/constant/Message.java
> +    public final static String NOT_CONTAIN_STATION_IN_LINE = "해당 구간에 포함된 역이 아닙니다.";
에러 메세지를 정의하고 추가했으니 예외 테스트도 있으면 좋을것 같습니다 🤔

2022-11-22 08:47 UTC, mskangg commented on src/main/java/nextstep/subway/dto/LineResponse.java
> +    }
피드백 반영하신 부분 중 누락된 커밋이 있나보네요.
확인 부탁드립니다 :)

2022-11-22 13:57 UTC, yeojiin commented on src/main/java/nextstep/subway/application/LineService.java
> +        Station downStation = findStationById(Long.valueOf(lineRequest.getDownLastStationId()));
해당 부분은 request를 Long 변경했습니다!😭

2022-11-22 14:00 UTC, yeojiin commented on src/main/java/nextstep/subway/dto/LineResponse.java
> +    }
PR하면서 충돌이 나는 부분을 수정했더니 소스가 원복된 부분이 있는 거 같네요.😭 죄송합니다!

2022-11-23 00:41 UTC, yeojiin commented on src/test/java/nextstep/subway/section/LineSectionStep.java
> +        assertThat(response.statusCode()).isEqualTo(HttpStatus.INTERNAL_SERVER_ERROR.value());
해당 부분을 `ControllerExceptionHandler`을 만들어서 400 에러로 변경 후 메세지 검증도 추가했습니다~

2022-11-23 00:47 UTC, yeojiin commented on src/main/java/nextstep/subway/constant/Message.java
> +    public final static String NOT_CONTAIN_STATION_IN_LINE = "해당 구간에 포함된 역이 아닙니다.";
NOT_VALID_REMOVE_ONLY_ONE_SECTION 에러는 메세지를 확인해 명시적으로 변경했고, NOT_CONTAIN_STATION_IN_LINE 에러부분은 새로 추가했습니다!👍

2022-11-23 12:12 UTC, mskangg approved these changes
정연님!
정말정말정말 고생 많이하셨습니다 🔥
얼마나 열심히하셨는지, 커밋을 보면 알수 있을정도로 열정있는 모습 보기 좋았어요 👍 
덕분에 저도 좋은 기운 받아 좋았습니다 🙇‍♂️

> 지하철 노선도 미션이 여지껏 진행했던 미션 중 가장 시간도 많이 걸리고,
뒤엎기도 여러번 뒤엎었던 미션같아요.
그만큼 많이 배웠지만 멘탈 관리하기 쉽지 않았던 거 같네요.

멘탈관리는 잘 되고 계시죠?
전혀 걱정하지 않으셔도 됩니다!
과정시작하기 전 간절했던 마음 잊지 마시고 끝까지 미션 완주하셨으면 좋겠어요!

그럼 다음 미션도 화이팅이에요!! 🔥

2022-11-23 12:12 UTC, mskangg commented on src/test/java/nextstep/subway/section/LineSectionStep.java
> +                () -> assertThat(saveErrorMessages).contains(response.body().jsonPath().getString("message"))
검증 추가해주셨군요 👍

2022-11-23 12:12 UTC, mskangg commented on src/test/java/nextstep/subway/utils/CommonMethodFixture.java
> +public class CommonMethodFixture {
Fixture 제네릭으로 추가해주셨군요 👍

2022-11-23 12:12 UTC, mskangg commented on src/main/java/nextstep/subway/exception/ControllerExceptionHandler.java
> +@ControllerAdvice
에러핸들링 👍

2022-11-23 12:12 UTC, merged